### ISSUE TITLE
Ability to disable "Espanso is running!" notification

### ISSUE THREAD

**Issue by hmnd** [federico-terzi/espanso#1002]
**Is your feature request related to a problem? Please describe.**
Every time Espanso v2 starts on Windows, a notification appears from PowerShell saying "Espanso is running!". When my computer starts up, I don't care to know when Espanso has started, and I have no way to disable this notification since it's coming from PowerShell and not Espanso itself.

**Describe the solution you'd like**
Remove this notification or provide the ability to disable it on the user's end.

**Describe alternatives you've considered**
The notification could possibly be made to appear to come from Espanso and not PowerShell, allowing the user to disable notifications through Windows.

**Additional context**
![image](https://user-images.githubusercontent.com/12853597/155426439-8bc1bd94-b2aa-4327-b01c-a54d1403e5cf.png)

**Comment by jvlianodorneles** [comment]
Have you tried the `show_notifications` flag?

`show_notifications: false`

**Comment by mrjoecastellon** [comment]
> **Is your feature request related to a problem? Please describe.** Every time Espanso v2 starts on Windows, a notification appears from PowerShell saying "Espanso is running!". When my computer starts up, I don't care to know when Espanso has started, and I have no way to disable this notification since it's coming from PowerShell and not Espanso itself.
> 
> **Describe the solution you'd like** Remove this notification or provide the ability to disable it on the user's end.
> 
> **Describe alternatives you've considered** The notification could possibly be made to appear to come from Espanso and not PowerShell, allowing the user to disable notifications through Windows.
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/12853597/155426439-8bc1bd94-b2aa-4327-b01c-a54d1403e5cf.png)

Looking at that image though, it seems there are 2 different notifications, one for PowerShell and one for Espanso. Notice the two 'X's 🧐

**Comment by hmnd** [comment]
@jvlianodorneles Ahh I hadn't and that fixes it! Should have checked the docs before opening this issue. Thanks ;)

**Comment by hmnd** [comment]
ps @mrjoecastellon the two Xs is just because Windows groups notifications by source app and you can either dismiss the group or the individual notifs.

**Comment by kkard2** [comment]
> Have you tried the `show_notifications` flag?
> 
> `show_notifications: false`

this also disables the notification about reloading the configuration; it would be nice to have the ability to disable only the startup one

**Comment by gravelld** [comment]
@kkard2 See #1116
