### ISSUE TITLE
Outlook on Mac 12.0, duplication in Outlook

### ISSUE THREAD

**Issue by schilzy** [federico-terzi/espanso#1003]
**Describe the bug**
I keep getting double ups from a match i have set up. other programs like text edit are totally fine

**Screenshots**
Image of what i get in Outlook app
![Screen Shot 2022-02-25 at 6 05 38 pm](https://user-images.githubusercontent.com/21233221/155670282-f5622b6a-055f-47b3-b318-0789a0a7d312.png)

What i have written in the default.yml file
![Screen Shot 2022-02-25 at 6 05 52 pm](https://user-images.githubusercontent.com/21233221/155670364-02acc4ca-f9d7-4596-b160-36b7804eca00.png)

**Setup information**
- OS: Mac OS 12.0
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @schilzy,

I'm sorry you experienced this problem! That's interesting, you might try the `force_clipboard: true` option, sometimes that helps:

```yaml
  - trigger: "hello"
    replace: "world"
    force_clipboard: true
```

Cheers :)

**Comment by schilzy** [comment]
Hey @federico-terzi 

Thanks for the quick response.

Sadly that doesn't work for me in Outlook. I use 1Clipboard as my clipboard manager and it just activates that instead of pasting into outlook. If I then choose the option from the clipboard and paste it in it's fine, but at that point i could have just typed it in lol.

**Comment by schilzy** [comment]
I have tested in a bunch of other programs and it works like a dream, it just seems Outlook is being painful. 

For reference my outlook version is 16.58
It the one where they have forced everyone over to the "new Outlook" on macs. at least that's what they called it before this update.

**Comment by mrjoecastellon** [comment]
Check your keyboard settings in MacOS and see if there's a "text replace" for "Cheers".

I've noticed that on MacOS, Espanso may sometimes struggle when I use a trigger that is also set up as text replace in the keyboard settings in my iPhone. It sometimes wants to output double the replace value.

For example, in my iPhone I set the text "zxd" to replace to the emoji 😆. I use the same trigger in Espanso and in some apps, like Whatsapp desktop, I get "😆😆". It doesn't happen everytime, but I know it's basically a conflict between Espanso and the text replace feature of iOS (it syncs to MacOS).

**Comment by schilzy** [comment]
Hey @mrjoecastellon 

Thanks for the tips. I tried digging into the outlook auto-correct and macs text replace and the new shortcuts app and sadly nothing :(

**Comment by federico-terzi** [comment]
@schilzy That's interesting... I'll investigate and get back to you when I find out something :)

**Comment by schilzy** [comment]
@federico-terzi i found it!!!!!!!!!

So turns out Outlook doesn't like me using ctrl C as my trigger,I changed it to //c and it works like a dream in outlook as well now. 

Not sure what it's issue was with Ctrl C but at least i found out what it's issue is. 

Thanks for all your help I really appreciate it.

**Comment by federico-terzi** [comment]
@schilzy Thanks for sharing! What do you mean by "using ctrl C as trigger"? :) I'd love to see the problematic YAML match, if possible (even just the trigger part)
