### ISSUE TITLE
Search shortcut/trigger not working on Windows

### ISSUE THREAD

**Issue by TheChilliPL** [federico-terzi/espanso#1006]
**Describe the bug**
Neither the search shortcut nor trigger work on Windows

**To Reproduce**
1. Set the search shortcut or trigger in the configuration file on Windows (%appdata%/espanso/default.yml)

**Expected behavior**
Search bar should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/18823939/155861508-83c3fc9a-66b0-4af4-b52d-90cc71b1bf44.png)

**Logs**
Nothing interesting in logs

**Setup information**
- OS: Windows 11 22543.1000
- Version: 0.7.3

**Comment by branislavbudzak** [comment]
I have the exact problem. I have Flow Launcher on ALT+SPACE shortcut, so I what to change it to CTRL+SPACE shortcut. I put everything to default.yml file and nothing worked.
![image](https://user-images.githubusercontent.com/52125274/156607008-108fa7b6-d576-44de-a4d6-a55f2020190c.png)

**Comment by federico-terzi** [comment]
Hey @TheChilliPL,

I'm sorry you experienced this problem! For the searchbar, you'll need to upgrade to version 2, see: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)
