### ISSUE TITLE
Espanso is not recognized as an internal or external command (Windows 11)

### ISSUE THREAD

**Issue by kaylamillerdev** [federico-terzi/espanso#1009]
BUG: Going through setup and decided to install the basic emojis package to my espanso app. Opened a terminal and typed in

`espanso install basic-emojis`

And it gives back: 'espanso' is not recognized as an internal or external command.

I have espanso installed and it works fine in other areas of my computer, but apparently not in the the command prompt. I have already checked the path / environment variable and it did load it into the path. I've restarted the terminal multiple times and it just doesn't recognize the espanso keyword.

**Comment by kaylamillerdev** [comment]
Interesting. I redownloaded the install file and ran it. Then I opened an elevated CMD prompt and the install command worked.

**Comment by federico-terzi** [comment]
Hey @kaylamillerdev,

Thanks for reporting this issue! What version of Espanso are you using? (you can find out by running `espanso --version`)

Cheers :)

**Comment by kaylamillerdev** [comment]
It says version 0.7.3

**Comment by federico-terzi** [comment]
@kaylamillerdev I see, thanks! When/If you have the chance, I'd suggest downloading the new v2 release, which shouldn't suffer from this problem :) (see: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339)

Cheers :)

**Comment by jubair-gh** [comment]
in my pc i installed version 2.3 but it also saying the same thing "espanso' is not recognized as an internal or external command"
