### ISSUE TITLE
No reaction for --config_dir on Windows / v2.1.3-alpha

### ISSUE THREAD

**Issue by KarolPiechoczek** [federico-terzi/espanso#1010]
>  --config_dir <config_dir>
>             Specify a custom path from which espanso should read the configuration

espanso (or espansod) --config_dir "some_dir"
Also I tried run cmd as administrator.

**Expected behavior**
Change default config dir to own. I know the solution with symlink.

**Screenshots**
![cmd_2022-03-03_11-12-16](https://user-images.githubusercontent.com/45637112/156543742-20e6eceb-c06b-4b3b-b28e-2923df1a94a5.gif)

**Logs**
Log was not registred for this action.

**Setup information**
- OS: Windows 10 21H2 / 19044.1526
- Version: 2.1.3-alpha

**Comment by federico-terzi** [comment]
Hey @KarolPiechoczek,

I'm sorry you experienced this problem! The `--config_dir` option is problematic in many ways and it's unlikely to be fixed anytime soon... If you want to override the config directory, your best bet is to redefine the `ESPANSO_CONFIG_DIR` environment variable with your desired path

Cheers :)

**Comment by KarolPiechoczek** [comment]
`ESPANSO_CONFIG_DIR` environment sounds good and works perfectly :)

**Comment by yuexl** [comment]
I have set the ESPANSO_CONFIG_DIR, espanso edit locate the right file, but did not parse this dir, still load the default config '.config/espanso'
