### ISSUE TITLE
[Bug] [Question] Due to my bank company's policy, `AppUserModelID` should be registered in Command Prompt and not in PowerShell

### ISSUE THREAD

**Issue by gusbemacbe** [federico-terzi/espanso#1011]
- Please read https://github.com/cmderdev/cmder/issues/2640 before
- I work as a software engineer in a bank company. 
- We demanded Espanso to be included in the bank company's its software central. 
- Espanso has been deployed successfully to the software central.
- It has been successfully installed from the software central without failures or problems.
- It is important to observe that the bank company does not allow us to use PowerShell. PowerShell is blocked. But Command Prompt, Git Bash and WSL are allowed. 

**Describe the bug**

- Espanso is not automatically started. As it was not started automatically, I had to use the terminal to enter the `Program Files` folders to run the command `espanso.cmd start`. 
- Log: 
   
   ```
   [ERROR] unable to determine if AppUserModelID was registered: Este programa está bloqueado pela política de grupo. Para obter mais informações, contacte o administrador de sistema. (os error 1260)
   [WARN] unable to find espanso AppUserModelID in the list of registered ones, failling back to PowerShell. 
  ```

- The sentence `Este programa está bloqueado pela política de grupo. Para obter mais informações, contacte o administrador de sistema` is in Portuguese. Let me translate: “This program is blocked due to the group policy. To get further details, contact the system administrator.”

You can see it cannot be added in PowerShell due to bank company's restrictions. The `AppUserModelID` should be registered in user mode and not in administrator mode. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the terminal with Git Bash;
2. Run `cd "/c/Program Files/Espanso"`;
3. Run `espanso.cmd start`;
4. It will open Espanso dialogue. At the startup question dialogue, you mark that option. When you proceed, it gives the `AppUserModelID` error. But I clicked OK and proceeded. Espanso worked fully. Unfortunately, it is not started automatically, has to be run manually on the terminal. 

**Expected behaviour**
Startup option cannot be enabled due to `AppUserModelId` error. It failed. But even, Espanso still worked. 

**Logs**

```
[...]
[ERROR] unable to determine if AppUserModelID was registered: Este programa está bloqueado pela política de grupo. Para obter mais informações, contacte o administrador de sistema. (os error 1260)
[WARN] unable to find espanso AppUserModelID in the list of registered ones, failling back to PowerShell. 
```

**Setup information**
- OS: Windows 10 64 bits
- Version: 2.1.2

**Comment by federico-terzi** [comment]
Hey @gusbemacbe,

I'm sorry you experienced this problem! Please try adding the following line to your default.yml config and see if that helps:

```yaml
show_notifications: false
```

Cheers :)

**Comment by gusbemacbe** [comment]
@federico-terzi 

Espanso is not started automatically. I am unable to trigger `:espanso`.

**Comment by gusbemacbe** [comment]
@federico-terzi 

It has been solved. The support analyst updated the deployment. The Espanso icon has been added to the desktop area. I open with `shell:startup` to create Espanso icon shortcut there in the startup folder. I restarted the computer and I saw that Espanso is automatically started. 

Please update the documentation for company engineers. Include that option and get this small tutorial.

**Comment by federico-terzi** [comment]
@gusbemacbe Thanks for sharing! Glad you got it working
