### ISSUE TITLE
Text is inserted at beginning of document instead of current location

### ISSUE THREAD

**Issue by shbach** [federico-terzi/espanso#1013]
**Describe the bug**
When using [Joplin](https://github.com/laurent22/joplin), Expanso often inserts text at beginning of the note instead of the current location. I've only noticed this happening with Joplin so far. I think this is an Espanso bug but if it is something that needs to be fixed on Joplin's side let me know and I'll post an issue there instead.

**To Reproduce**
1. Create a note in Joplin. 
2. Use Espanso somewhere in the note. This bug isn't consistent. Sometimes it works fine but a few minutes later it doesn't.

**Expected behavior**
Espanso shouldn't jump to the beginning of the note and insert there

**Screenshots**
![espanso joplin](https://user-images.githubusercontent.com/5298745/157769883-ec4dff2f-2503-485f-b4fa-6fac9d5afc2d.gif)

**Setup information**
- OS: Tried on both Windows and Linux
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @shbach,

Thanks for reporting this issue! If it happens only inside Joplin, it's likely not Espanso fault :)
That said, you might be able to mitigate the issue by using:
* The `force_clipboard: true` option, as explained here: https://github.com/federico-terzi/espanso/issues/1003#issuecomment-1052475670
* Slowing down the injection by adding the following to your default.yml file (increase the values as necessary)
```
backspace_delay: 10
inject_delay: 10
```

Let me know if that helps

Cheers :)

**Comment by shbach** [comment]
@federico-terzi 

`force_clipboard: true` didn't work but slowing down the injection did!

I was able to get it to reliably work with: 
```
backspace_delay: 25
inject_delay: 25
```

Does seem like it may be a Joplin bug. I'll try to submit an issue on Joplin's side but would you happen to have any thoughts on how Espanso works that may result in Joplin not handling it properly?

**Comment by shbach** [comment]
So I tried slowing down the injection on my Windows machine and it doesn't work. Not sure why it works on my Linux laptop but not my Windows desktop.

**Comment by federico-terzi** [comment]
@shbach That's interesting, thanks for sharing! I don't have other workarounds at the moment, if something comes up I'll let you know :)

**Comment by federico-terzi** [comment]
@shbach Interesting

> Maybe it's something to do with the amount of system resources used? From what I gathered, Espanso basically does backspaces and then enters the replacement text. 

Yes, that might be related. If the system load is high, the current application might not be able to process the input data fast enough. That said, I'm not sure whether we can consider it a bug on the Joplin side :)

**Comment by shbach** [comment]
> That said, I'm not sure whether we can consider it a bug on the Joplin side :)

@federico-terzi I figured out that this is definitely occurring due to a [bug with Joplin's spellchecker](https://github.com/laurent22/joplin/issues/5969#issuecomment-1078510949). I'm going to close this issue since it's not an Espanso bug.

Thanks for all the help and the backspace/injection delay tip which fixes it somewhat!
