### ISSUE TITLE
How to disable jkj shortcut

### ISSUE THREAD

**Issue by johannesCmayer** [federico-terzi/espanso#1018]
When I press `jkj`, I get a popup for selecting shortcuts. I find this extremely annoying. How can I disable that? I am using the Dvorak keyboard layout, so maybe the shortcut keys are normally on `cvc`. 

I am using espanso 2.1.0-alpha.

**Comment by federico-terzi** [comment]
Hey,

I'm sorry you experienced this problem! You can add the following line to your `$CONFIG/config/default.yml` file:

```
search_trigger: off
```

Cheers :)
