### ISSUE TITLE
Do not work with terminator on Linux

### ISSUE THREAD

**Issue by profy12** [federico-terzi/espanso#102]
Espanso do not work with terminator (tested with Ubuntu 18.04). 

It's matching but replace with nothink and return a blank line.

**Comment by federico-terzi** [comment]
Hi @profy12,

Thanks for the feedback, could you please run `espanso detect` on terminator and post the output here?

Thank you

**Comment by profy12** [comment]
```
profy@nuc:~$ espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'profy@nuc: ~'
==> Class: 'Terminator'
==> Executable: '/usr/bin/python2.7'
```

**Comment by federico-terzi** [comment]
Thank you @profy12, I should be able to publish a fix in the next release ( it will be available this weekend )

**Comment by profy12** [comment]
Great ! so reactive :smile: 
If it can help, it seems to work switching the backend to inject :
```
profy@nuc:~/.config/espanso/user$ cat terminator.yml 
filter_class: "Terminator"
backend: "Inject"
```

**Comment by federico-terzi** [comment]
> Great ! so reactive 

Well, I was right in front of my inbox, that's why :)

> If it can help, it seems to work switching the backend to inject :
> 
> ```
> profy@nuc:~/.config/espanso/user$ cat terminator.yml 
> filter_class: "Terminator"
> backend: "Inject"
> ```

Indeed the `Inject` backend does not suffer from this problem, though it has its own.
In the next version, Terminator should work also with the default `Clipboard` backend.

Thanks for your help
