### ISSUE TITLE
Package didn't work

### ISSUE THREAD

**Issue by WooHooDai** [federico-terzi/espanso#1024]
Package didn't work after installed

What I do:
1. I install  the package by `espanso install lorem`
2.  `espanso restart`
3. and trigger like `>lorem` didn't work

Info output:
![image](https://user-images.githubusercontent.com/16878459/159172681-8d9c0c2f-ffeb-4222-8c3e-df7e44fd11ad.png)

**Comment by federico-terzi** [comment]
Hey @WooHooDai,

I'm sorry you experienced this problem! Could you please type `#acfg#` inside an application and post the output here?
In the meantime, you could also work around that issue by removing the `C:\Users\woohodai\AppData\Local\espanso\packages` folder and then reinstalling all your packages

Cheers :)

**Comment by WooHooDai** [comment]
> Hey @WooHooDai,
> 
> I'm sorry you experienced this problem! Could you please type `#acfg#` inside an application and post the output here? In the meantime, you could also work around that issue by removing the `C:\Users\woohodai\AppData\Local\espanso\packages` folder and then reinstalling all your packages
> 
> Cheers :)


Remove the folder works.Thanks
and ‘#acfg#’ output as follows

[espanso config: "C:\\Users\\woohoodai\\AppData\\Roaming\\espanso\\config\\default.yml"]

backend: Auto
enable: true
paste_shortcut: None
inject_delay: None
key_delay: None
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
post_form_delay: 200 
post_search_delay: 200 
backspace_limit: 5
search_trigger: None
search_shortcut: Some("ALT+SHIFT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "C:\\Users\\woohoodai\\AppData\\Roaming\\espanso\\match\\base.yml",
]

**Comment by federico-terzi** [comment]
@WooHooDai Thanks! We'll investigate on a separate issue :)
