### ISSUE TITLE
right_word option doesn't work anymore after upgrade from 0.7.3

### ISSUE THREAD

**Issue by freeform99** [federico-terzi/espanso#1032]
Hi there,

I use the `right_word` option for all my expansions to trigger immediatly when the trigger is typed and not when the next word delimiter is typed. 

After upgrading and using the migrate tool the `right_word` option is still present in the config file but it appears to be ignored by espanso: my trigger triggers only if I enter another key (for example, space or comma) afterwards. 

Thank you for making this great piece of software!

**Comment by federico-terzi** [comment]
Hey @freeform99,

Thanks for reporting this issue! Could you please provide an example match I can use to test this behavior? :)

Cheers :)

**Comment by freeform99** [comment]
Hi @federico-terzi,

thanks for repsonding. 

On a fresh installation, try this in `base.yml`:
```matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: "e#"
    replace: "espanso"
    right_word: true 
```

The first one will be expanded when one types the "o", the second one only after typing an additional word delimiter such as `space` or `,`

**Comment by freeform99** [comment]
Uh. 

If I change the config like this it works:

```
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: "e#"
    replace: "espanso"
```

So I have to remove all the `right_word` config options I guess. No big deal. I probably misunderstood something along the way - sorry!

**Comment by federico-terzi** [comment]
@freeform99 Glad you figured it out :)

> The first one will be expanded when one types the "o", the second one only after typing an additional word delimiter such as space or ,

That's the expected behavior :D It means "have a word delimiter on the right side"
