### ISSUE TITLE
Unable to install espanso-latex package on Powershell

### ISSUE THREAD

**Issue by shawnkoh** [federico-terzi/espanso#1034]
**Describe the bug**
Unable to install espanso-latex package on Powershell.

**To Reproduce**
1. In Powershell, run ```espanso install espanso-latex --external```

**Expected behavior**
Espanso-latex should be installed.
Instead
```
Allowing external repositories
Updating package index
Index updated!
Unable to parse Package.info from README.md
```

**Setup information**
Windows 11 Home
10.0.22000 Build 22000

- Version: which version of Espanso are you running?
0.7.3

**Comment by federico-terzi** [comment]
Hey @shawnkoh,

I'm sorry you experienced this problem! When you have the chance, could you please try upgrading to the v2? It's the new stable version and there's a good chance it might solve this problem. Here's the migration guide for when you're ready: https://espanso.org/docs/migration/overview/

Feel free to reopen if that doesn't solve your issue :)

**Comment by zoenglinghou** [comment]
Hi, I am the author of the package.

I am trying to migrate `espanso-latex` to `espanso` v2.x as well, as you can see in the repo: https://github.com/zoenglinghou/espanso-latex/

Maybe we can continue the conversation there? I am trying to debug some of the issues

**Comment by federico-terzi** [comment]
@zoenglinghou Awesome, thank you for the help :) Feel free to open a PR to the new Espanso Hub if you want to integrate the latest changes without `--external` :)

**Comment by zoenglinghou** [comment]
https://github.com/espanso/hub/pull/16
