### ISSUE TITLE
Espanso detects legacy process/can't fully uninstall

### ISSUE THREAD

**Issue by spacekaila** [federico-terzi/espanso#1048]
I had the old 0.7.3 version of espanso on my Ubuntu 18.04 machine.  I don't have sudo access on this computer, so I originally installed it by downloading the .tar.gz file and putting it in ~/.local/bin. Today i wanted to upgrade it, so i followed the instructions to run `espanso stop` and `espanso unregister`. I deleted the `espanso` file from ~/.local/bin. Then I downloaded the new AppImage and originally placed it in a new folder and made it executable. I couldn't do the `env-path register` step because I don't have sudo access, and I would just get a `~/.local/bin/espanso file or folder not found` error if I tried `espanso` in the terminal, so I moved the AppImage to ~/.local/bin. I was able to register it with `espanso service register`. Now I can start espanso and I get the GUI for the startup manager, but it tells me that a legacy espanso process has been detected and I need to terminate and uninstall it before I can use the new espanso. I've restarted my computer and I still get the message. I'm not sure what it is detecting, because running `espanso status` tells me that it's not running and I've deleted the old file.

**Logs**
```
14:12:57 [service(10064)] [INFO] reading configs from: "~/.config/espanso"
14:12:57 [service(10064)] [INFO] reading packages from: "~/.local/share/espanso/packages"
14:12:57 [service(10064)] [INFO] using runtime dir: "~/.local/share/espanso"
14:13:03 [service(10064)] [ERROR] unable to start service: timed out
```

**Comment by federico-terzi** [comment]
Hey @spacekaila,

I'm sorry you experienced this problem! Could you please run the following command in a terminal after you see a "legacy version is running" dialog and post the output here?

```
ps aux | grep espanso
```

Cheers :)

**Comment by spacekaila** [comment]
Hi @federico-terzi ,

I tried to start espanso and ran the `ps aux | grep espanso` command after getting the legacy message. Here's the output:

```
username  9293  1.6  1.2 646864 47244 ?        Ssl  15:38   0:00 /users/username/.local/bin/espanso launcher
username  9296  1.8  0.0  22596  2356 ?        Ssl  15:38   0:00 /users/username/.local/bin/espanso launcher
username  9348  0.0  0.0  14792  1096 pts/0    S+   15:38   0:00 grep espanso
```

**Comment by federico-terzi** [comment]
@spacekaila Thanks! What happens if you run `killall espanso` and then start he AppImage?

**Comment by spacekaila** [comment]
I ran `killall espanso` and got the message that no process called espanso could be found, but then was able to successfully run `espanso start` and go through the migration wizard and now it's working!

**Comment by federico-terzi** [comment]
@spacekaila Awesome, thanks!
