### ISSUE TITLE
Espanso and krunner on kde

### ISSUE THREAD

**Issue by vroger11** [federico-terzi/espanso#1055]
**Is your feature request related to a problem? Please describe.**
I am using the last espanso version (2.1.5) under kde. I love using both espanso and krunner. But since last update of espanso (2.1.5) when I trigger the shortcut Alt+space it triggers espanso instead of krunner.

**Describe the solution you'd like**
Maybe their should be a specific behavior (like a popup when espanso launch to warn you about this and propose a solution) when krunner is installed on the system (or the system is KDE)

**Describe alternatives you've considered**
Change the default shortcut for espanso when on kde (like meta+space)

**Comment by federico-terzi** [comment]
Hey @vroger11,

I'm sorry you experienced this problem! You can customize the search shortcut, see: https://espanso.org/docs/configuration/options/#customizing-the-search-shortcut
Feel free to reopen if that doesn't solve your issue :)

Cheers :)
