### ISSUE TITLE
Launch search bar from command line

### ISSUE THREAD

**Issue by clyra** [federico-terzi/espanso#1066]
**Is your feature request related to a problem? Please describe.**

Espanso has support for "global" hotkeys but it needs to be setup on espanso itself. It would be very nice and more flexible if it could be called from another "keyboard daemon" like  Karabiner or skhd. Is there a way to create a command line option for espanso that shows the search bar? For instance:

```
$ espanso  searchbar
```

And the search bar is displayed.

**Comment by federico-terzi** [comment]
Hey @clyra,

```
espanso cmd search
```

Should do the trick :)

Cheers :)

**Comment by clyra** [comment]
thx! I missed that!
