### ISSUE TITLE
Espanso and OSX sleep

### ISSUE THREAD

**Issue by clyra** [federico-terzi/espanso#1069]
**Describe the bug**
I usually sleep my Mac mini M1 running Big Sur (11.6.5) with a hotkey that runs the command "osascript -e 'tell application "Finder" to sleep'". With Espanso running, when I hit the hotkey the screen blanks for a second like it's going to sleep and lit again as nothing had happened. If I close/end Espanso I got the usual behavior and my Mac sleeps.

**To Reproduce**
1. I'm using karabiner to map caps-lock to the "hyper-key" (command+option+shift+control) and skhd as the keyboard daemon.
2. hyper+z is configured to run the command "osascript -e 'tell application "Finder" to sleep'"
3. hit the hyper+z hotkey. system was supposed to sleep but only got the screen to blink 

**Expected behavior**
system should sleep.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
```
23:24:35 [worker(2711)] [WARN] detected inconsistent modifier state for keys [(Meta, 55), (Control, 59), (Shift, 56), (Alt, 58)], sending compensating events...
```

**Setup information**
- OS: OS X big sur
- Version: espanso 2.1.5-beta

**Comment by clyra** [comment]
hm... the log suggests that Espanso is sending some kind of key press and this wakes the system. I modified my skhd config so instead of just calling the sleeping command, it waits 2 seconds before calling the script, and this seems to solve the problem. So my new config is "sleep 2 && osascript -e 'tell application "Finder" to sleep'", so Espanso sends the "compensating events" before the osascript runs.

**Comment by federico-terzi** [comment]
Hey @clyra,

Thanks for reporting this issue! I think we can safely close this issue given that you found a workaround, but feel free to reopen if you encounter any other problems or have some feedback! :)

The compensating events were needed to fix this issue: https://github.com/federico-terzi/espanso/issues/825

Cheers :)
