### ISSUE TITLE
unable to load match group

### ISSUE THREAD

**Issue by Kmfernan5** [federico-terzi/espanso#1079]
**Describe the bug**
unable to load match group. Its synced to google drive.  available offline. 

**To Reproduce**
1. I dont know

**Expected behavior**
expand text

**Screenshots**
NOthing happens when I type match trigger

**Logs**
16:17:41 [daemon(18104)] [INFO] reading configs from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso"
16:17:41 [daemon(18104)] [INFO] reading packages from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso\\match\\packages"
16:17:41 [daemon(18104)] [INFO] using runtime dir: "C:\\Users\\djtlm\\AppData\\Local\\espanso"
16:17:41 [daemon(18104)] [INFO] watching for changes in path: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso"
16:17:42 [daemon(18104)] [WARN] ------- detected some errors in the configuration: -------
16:17:42 [daemon(18104)] [WARN] >>> H:\My Drive\backup\espanso\match\djtl.yml
16:17:42 [daemon(18104)] [ERROR] unable to load match group "H:\\My Drive\\backup\\espanso\\match\\djtl.yml"

Caused by:
    0: failed to parse YAML match group
    1: while parsing a quoted scalar, found unknown escape character at line 475 column 14
    2: while parsing a quoted scalar, found unknown escape character at line 475 column 14
16:17:42 [daemon(18104)] [WARN] -----------------------------------------------------------
16:17:42 [daemon(18104)] [INFO] espanso version: 2.1.5-beta
16:17:42 [daemon(18104)] [INFO] spawning the worker process...
16:17:42 [daemon(18104)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
16:17:42 [worker(39192)] [INFO] reading configs from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso"
16:17:42 [worker(39192)] [INFO] reading packages from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso\\match\\packages"
16:17:42 [worker(39192)] [INFO] using runtime dir: "C:\\Users\\djtlm\\AppData\\Local\\espanso"
16:17:42 [worker(39192)] [WARN] ------- detected some errors in the configuration: -------
16:17:42 [worker(39192)] [WARN] >>> H:\My Drive\backup\espanso\match\djtl.yml
16:17:42 [worker(39192)] [ERROR] unable to load match group "H:\\My Drive\\backup\\espanso\\match\\djtl.yml"

Caused by:
    0: failed to parse YAML match group
    1: while parsing a quoted scalar, found unknown escape character at line 475 column 14
    2: while parsing a quoted scalar, found unknown escape character at line 475 column 14
16:17:42 [worker(39192)] [WARN] -----------------------------------------------------------
16:17:42 [worker(39192)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
16:17:42 [worker(39192)] [INFO] using Win32AppInfoProvider
16:17:42 [worker(39192)] [INFO] monitoring the status of the daemon process
16:17:42 [worker(39192)] [INFO] using Win32Source
16:17:42 [worker(39192)] [INFO] using Win32Injector
16:17:42 [worker(39192)] [INFO] using Win32Clipboard
16:19:15 [worker(39192)] [INFO] engine eventloop has terminated, propagating exit event...
16:19:15 [worker(39192)] [INFO] waiting for engine exit mode...
16:19:15 [worker(39192)] [INFO] exiting worker (to be restarted)
16:19:15 [daemon(18104)] [INFO] worker requested a restart, spawning a new one...
16:19:15 [daemon(18104)] [INFO] spawning the worker process...
16:19:15 [worker(17700)] [INFO] reading configs from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso"
16:19:15 [worker(17700)] [INFO] reading packages from: "C:\\Users\\djtlm\\AppData\\Roaming\\espanso\\match\\packages"
16:19:15 [worker(17700)] [INFO] using runtime dir: "C:\\Users\\djtlm\\AppData\\Local\\espanso"
16:19:15 [worker(17700)] [WARN] ------- detected some errors in the configuration: -------
16:19:15 [worker(17700)] [WARN] >>> H:\My Drive\backup\espanso\match\djtl.yml
16:19:15 [worker(17700)] [ERROR] unable to load match group "H:\\My Drive\\backup\\espanso\\match\\djtl.yml"

Caused by:
    0: failed to parse YAML match group
    1: while parsing a quoted scalar, found unknown escape character at line 475 column 14
    2: while parsing a quoted scalar, found unknown escape character at line 475 column 14
16:19:15 [worker(17700)] [WARN] -----------------------------------------------------------
16:19:15 [worker(17700)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
16:19:15 [worker(17700)] [INFO] using Win32AppInfoProvider
16:19:15 [worker(17700)] [INFO] monitoring the status of the daemon process
16:19:15 [worker(17700)] [INFO] using Win32Source
16:19:15 [worker(17700)] [INFO] using Win32Injector
16:19:15 [worker(17700)] [INFO] using Win32Clipboard

**Setup information**
- OS: What OS are you using? Windows 11
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)espanso 2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @Kmfernan5,

I'm sorry you experienced this problem! This usually happens when you have a YAML syntax error in your config (it seems to be at line 475).
You can use tools like http://www.yamllint.com/ to debug this further

Cheers :)
