### ISSUE TITLE
Ubuntu 22.04: Depends: libssl1.1 (>= 1.1.0) but it is not installable

### ISSUE THREAD

**Issue by chipotledonut** [federico-terzi/espanso#1083]
As the title says.

I followed the install steps on the website and I get that error:

espanso : Depends: libssl1.1 (>= 1.1.0) but it is not installable.

**Comment by idcrook** [comment]
Dup of #1056

**Comment by federico-terzi** [comment]
I'm sorry you experienced this problem! Closing in favor of #1056
