### ISSUE TITLE
Install v0.7.3 on Linux Solus

### ISSUE THREAD

**Issue by DutchPete** [federico-terzi/espanso#1085]
I had installed v0.2.1.5-beta on my Linux machine, but did not realize there was also v0.7.3 until I wanted to use my existing default.yml file. When I checked the Espanso version on the machine I had that file on, it turned out to be v0.7.3.

Now, I know 0.2.1.5 is more advanced with more features, but I don't need more than beyond my current use. So, I would like to install 0.7.3. I stopped espanso running, then unregistered it and deleted the files that remained.

I could not find instructions about installing 0.7.3 since there is only Ubuntu/Debian, and Manjaro/Arch; I have Solus. I downloaded the Linux tar.gz file from [here](https://github.com/federico-terzi/espanso/releases?page=2), extracted it but don't know how to proceed.

Any chance to give me a hint?

**Comment by federico-terzi** [comment]
Hey @DutchPete,

Your best bet would be to compile espanso manually :) I'm not familiar with the packages required on Solus, but you might be able to figure out the steps by:

* Cloning the repo and heading to the "legacy" branch (which is for 0.7.3)
* Install the required libraries, these are the ones for Debian: https://github.com/federico-terzi/espanso/blob/legacy/Cargo.toml#L53

Then run `cargo build --release`, you will find the executable in the /target/release folder

Copy it into `/usr/local/bin` and you should be good to go :)
