### ISSUE TITLE
Shift/Ctrl key input not recognized in kitty terminal

### ISSUE THREAD

**Issue by wescox** [federico-terzi/espanso#1101]
**Describe the bug**
Expansions which include characters such as * or ! do not work in kitty terminal.  They will just produce the number instead, such as 8 or 1.  When backend is changed to Clipboard, the expansion doesn't work at all.  The trigger gets "expanded" to the letter v.  I'm assuming this is due to espanso replicating the ctrl+shift+v command and ctrl is also lost so I just end up with v.  Also, my triggers start with : (shift+;).  When I backspace an expansion, : becomes ;.  

**To Reproduce**
1. Create an expansion using a shift character such as ! (* [ ] is my specific example)
2. type trigger in kitty terminal
3. the result will be 8 [ ]

**Expected behavior**
The result in my example should have the asterisk rather than the number -> * [ ]

**Screenshots**
https://user-images.githubusercontent.com/24943022/166754891-80f45093-8e39-4205-8e36-fef1911f6805.mp4

**Logs**
❯ espanso log
11:38:42 [daemon(583621)] [INFO] reading configs from: "/home/wally/.config/espanso"
11:38:42 [daemon(583621)] [INFO] reading packages from: "/home/wally/.config/espanso/match/packages"
11:38:42 [daemon(583621)] [INFO] using runtime dir: "/home/wally/.cache/espanso"
11:38:42 [daemon(583621)] [INFO] watching for changes in path: "/home/wally/.config/espanso"
11:38:42 [daemon(583621)] [INFO] espanso version: 2.1.5-beta
11:38:42 [daemon(583621)] [INFO] spawning the worker process...
11:38:42 [daemon(583621)] [INFO] binded to IPC unix socket: /home/wally/.cache/espanso/espansodaemonv2.sock
11:38:42 [worker(583629)] [INFO] reading configs from: "/home/wally/.config/espanso"
11:38:42 [worker(583629)] [INFO] reading packages from: "/home/wally/.config/espanso/match/packages"
11:38:42 [worker(583629)] [INFO] using runtime dir: "/home/wally/.cache/espanso"
11:38:42 [worker(583629)] [INFO] using X11AppInfoProvider
11:38:42 [worker(583629)] [INFO] binded to IPC unix socket: /home/wally/.cache/espanso/espansoworkerv2.sock
11:38:42 [worker(583629)] [INFO] using X11Source
11:38:42 [worker(583629)] [INFO] monitoring the status of the daemon process
11:38:42 [worker(583629)] [INFO] using X11Injector
11:38:42 [worker(583629)] [INFO] using X11Clipboard
11:49:09 [worker(583629)] [WARN] Received malformed char: data provided contains an interior nul byte at byte pos 0

**Setup information**
- OS: Fedora 35 Workstation
- Terminal: kitty
- Shell: fish (maybe this matters)
- Prompt: starship (maybe this matters)
- Version: 2.1.5-beta (this is the AppImage version downloaded using the install instructions)

**Comment by wescox** [comment]
Fixed this with an app specific config of:
filter_class: kitty
disable_x11_fast_inject: true

**Comment by mrrcollins** [comment]
BTW, be sure you use `filter_class: kitty` and not `filter_exe`. I just lost 30 minutes of my life because nothing seemed to work to fix my problem... That is, until I saw this issue and my mistake. 

Just a random comment to share my pain. 😎
