### ISSUE TITLE
Packages triggers are not working

### ISSUE THREAD

**Issue by welcoMattic** [federico-terzi/espanso#1109]
**Describe the bug**
After a clean install of 2.1.5-beta, and some packages (shruggie, lorem, and table-flip) I tried to type `:shrug` and nothing happens. However, when I type some of *my* own triggers (like `:mail` to expand my email) it works.

**To Reproduce**
1. Install espanso 2.1.5-beta, and install shruggie package

**Expected behavior**
Packages triggers must work

**Logs**
nothing in log after typing a package trigger

**Setup information**
- OS: Manjaro i3 community edition
- Version: 2.1.5-beta

**Comment by federico-terzi** [comment]
Hey @welcoMattic,

I'm sorry you experienced this problem! Some users experienced the same problems, and it seems deleting the package directory helps sometimes, so you could run the following commands:

```
espanso stop
rm -Rf $(espanso path packages)
espanso start
```

Then reinstall all your packages and see if that helps :)

Cheers :)

**Comment by welcoMattic** [comment]
@federico-terzi it works, thanks for the tip!
