### ISSUE TITLE
Package Install Error on Win11

### ISSUE THREAD

**Issue by cbellini** [federico-terzi/espanso#1113]
**Describe the bug**
On a fresh Espanso install on Windows 11, I'm unable to install any packages via the `espanso install <package_name>` command.

**To Reproduce**

1. Install Espanso on Windows 11 via [the installer](https://espanso.org/docs/install/win/).
2. Open a Powershell or Cmd prompt.
3. Enter the install command to install any package (e.g. `espanso install all-emojis`).

**Expected behavior**
The package provided in the install command should be installed and available to Espanso wtih no error messages indicated to the user.

**Actual behavior**
The package is not installed and the following error message is returned:

> Updating package index...
> expected value at line 1 column 1

**Logs**
14:02:31 [ INFO] espanso version 0.7.3
14:02:31 [ INFO] using config path: C:\Users\chris\AppData\Roaming\espanso
14:02:31 [ INFO] using package path: C:\Users\chris\AppData\Local\espanso\packages
14:02:31 [ INFO] spawning worker process...
14:02:31 [ INFO] Binding to named pipe: \\.\pipe\espansodaemon
14:02:31 [ INFO] initializing worker process...
14:02:31 [ INFO] Initializing Espanso resources in C:\Users\chris\AppData\Local\espanso
14:02:31 [ INFO] BMP already initialized, skipping.
14:02:31 [ INFO] ICO already initialized, skipping.
14:02:31 [ INFO] red ICO already initialized, skipping.
14:02:31 [ INFO] Binding to named pipe: \\.\pipe\espansoworker
14:02:31 [ INFO] watching for changes in path: C:\Users\chris\AppData\Roaming\espanso
14:02:32 [ INFO] Using modulo at "C:\\Users\\chris\\AppData\\Local\\Programs\\espanso\\modulo"
14:02:32 [ INFO] worker is running!

**Setup information**
- OS: Windows 11  (21H2 OS Build 22000.675)
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @cbellini,

I'm sorry you experienced this problem! We recently deprecated the old espanso hub, so that might be causing this issue. Any chance you could upgrade to the latest Espanso version (v2)?

Cheers :)

**Comment by cbellini** [comment]
I installed v2 and I'm now able to install packages - thank you! And thanks for this project!
