### ISSUE TITLE
Espanso's license is faulty

### ISSUE THREAD

**Issue by AlmightyLks** [federico-terzi/espanso#1114]
It's a quick fix, but take a look at https://github.com/federico-terzi/espanso/blob/master/LICENSE#L655
>\<program\>  Copyright (C) \<year\>  \<name of author\>

It is pretty clear what is missing

![image](https://user-images.githubusercontent.com/54688434/169499787-ec942cbd-b9d8-451a-8060-8ed71bd526e9.png)

**Comment by federico-terzi** [comment]
Hey @AlmightyLks,

Thanks for reporting this issue! I never noticed, my bad! I'll make sure to update it soon

Cheers :)
