### ISSUE TITLE
Package not installing Windows 10

### ISSUE THREAD

**Issue by DfultonCube** [federico-terzi/espanso#1119]
**Describe the bug**
Running a command line prompt to install an external package returns a parsing error

**To Reproduce**
1. Running command prompt " espanso install cube-notes --git https://github.com/DfultonCube/Cube-Notes.git --external"

**Expected behavior**
Package should install

**Screenshots**
![image](https://user-images.githubusercontent.com/106206111/170173260-abe1aa21-20ee-4c14-800d-c59d3c2240aa.png)

**Logs**
12:17:11 [package(11588)] [INFO] using runtime dir: "C:\\Users\\dfulton\\AppData\\Local\\espanso"
12:17:11 [package(11588)] [INFO] installing package: cube-notes - version: latest
12:17:12 [package(11588)] [INFO] using package provider: github
12:17:12 [package(11588)] [ERROR] unable to install package: manifest YAML parsing error

Caused by:
    0: while parsing a block mapping, did not find expected key at line 5 column 24
    1: while parsing a block mapping, did not find expected key at line 5 column 24
12:54:53 [worker(21712)] [WARN] detected outdated modifier records for Meta, releasing the state

**Setup information**
- OS: Windows 10
- Version: 2.1.5

**Comment by DfultonCube** [comment]
Update: tested this on Mac too, also doesn't work. Text inside manifest folder is as follows, but I have tested multiple variants:

name: "cube-notes"
title: "Cube Notes"
description: A dummy package for testing
version: 0.1.0
author: Drew Fulton

**Comment by federico-terzi** [comment]
Hey @DfultonCube,

I'm sorry you experienced this problem! Please try to remove the `.github` folder from your repository, then it should work :)

Long explanation: the `.github` directory contains some test packages which are interfering with the Espanso resolution system.
I've just pushed a commit which should make troubleshooting these problems easier in the future

Cheers :)
