### ISSUE TITLE
Manjaro KDE - not working in the terminal

### ISSUE THREAD

**Issue by xircon** [federico-terzi/espanso#112]
Installed the espanso-bin and then the git version from aur.

Tried konsole and st, typed `:espanso` all it does is backspace, nothing is typed.  It appears to be working in Firefox.

Same for both versions.

**Comment by federico-terzi** [comment]
Hi @xircon,
Thanks for the feedback, could you please run espanso detect on the terminal and post the output here?

Thank you

**Comment by xircon** [comment]
st:
```
 espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'steve-pc ❐ 0 ● 1 zsh'
==> Class: 'St'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'steve-pc ❐ 0 ● 1 espanso'
==> Class: 'St'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'steve-pc ❐ 0 ● 1 [tmux]'
==> Class: 'St'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'steve-pc ❐ 0 ● 1 espanso'
==> Class: 'St'
==> Executable: ''
```
konsole (no tmux):
```
espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'steve : zsh — Konsole'
==> Class: 'konsole'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'steve : espanso — Konsole'
==> Class: 'konsole'
==> Executable: ''
```

**Comment by federico-terzi** [comment]
@xircon thank you very much, I should roll out a fix for this bug in the next release ( scheduled for this weekend ).

Thanks for your help

**Comment by xircon** [comment]
Thankyou, glad to help.  Will install over the weekend (aur git version)

**Comment by xircon** [comment]
Thankyou, glad to help.  Will install over the weekend (aur git version)

**Comment by xircon** [comment]
Thankyou, glad to help.  Will install over the weekend (aur git version)

**Comment by federico-terzi** [comment]
Glad to hear that, I'll reopen the issue so that I can close it properly with a pull request this weekend.
Thanks for your help

**Comment by xircon** [comment]
Seems to be working in Konsole, but not in yakuake, st, kitty or alacritty.  It just backspaces with no replacement.

**Comment by federico-terzi** [comment]
Thanks for your feedback @xircon , I'll take a look as soon as possible.

**Comment by xircon** [comment]
Now working in alacritty, not in st or kitty, many thanks.

**Comment by federico-terzi** [comment]
Hi @xircon, glad to hear that. I'm still working on a fix for the other two, but I don't know how long it could take.

Thanks

**Comment by federico-terzi** [comment]
Hey @xircon,

I shipped an update (version 0.4.1) that should fix these problems. Let me know if you experience any other bug.

Thanks for your help!

**Comment by s7dhansh** [comment]
@federico-terzi Still not working in yakuake :(

**Comment by federico-terzi** [comment]
Hey @s7dhansh, thank you for the feedback, I'll try to improve support for `yakuake` as well in the next version :)
Check out the status of this issue #153

**Comment by shmuhammad2004** [comment]
Hi Installed espanso on Mac OS Catalina and using iterm-3. But, expanso is not working on terminal 👍. After running `espanso detect`:


Detected change, current window has properties:
==> Title: 'com.googlecode.iterm2'
==> Class: 'com.googlecode.iterm2'
==> Executable: '/Applications/iTerm-3.app'

Detected change, current window has properties:
==> Title: 'com.apple.Safari'
==> Class: 'com.apple.Safari'
==> Executable: '/Applications/Safari.app'

**Comment by federico-terzi** [comment]
Hey @shmuhammad2004,

Thanks for reporting this issue! Could you please open a separate issue for this one?

Cheers :)

**Comment by mprincipe** [comment]
Hi @federico-terzi. Thank for your amazing work. I need help!

espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error

**Comment by federico-terzi** [comment]
Hey @mprincipe,

If you used the `espanso-bin` package from the AUR, please try with the `espanso` one.

Cheers :)

**Comment by bsahane** [comment]
Hello @federico-terzi 

I'm getting error while using `espanso` in **GNOME TERMINAL**
```bash
$ espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
```
Also `$ espanso edit` is working fine but not from `~/.config/espanso/default.yml`

---
`espanso` Installed using 
```bash
$ sudo snap install espanso --classic
espanso 0.7.3 from Federico Terzi (federicoterzi) installed
```
System Details
```bash
Operating System: Fedora Linux 35 (Workstation Edition)
Kernel: Linux 5.14.17-301.fc35.x86_64
Architecture: x86-64
GNOME TERMINAL: Version 3.42.1 for GNOME 41
```

**Comment by federico-terzi** [comment]
@bsahane I'm sorry you experienced this problem! Your best bet is to install the new alpha v2, or wait until it becomes stable :) More info here: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

**Comment by bsahane** [comment]
Thank You @federico-terzi

**Comment by woshichuanqilz** [comment]
> alacritty

Same manjaro, not when use espanso in alacritty and nvim the output will be disordered. 
For example: 
if you the right output is abc, the output may be: cba, some time may add some spaces into it. 


a wierd thing is that when I use nvim it got something wrong, but if I use lunarvim, it worked well...

How to solve my problem?

# espanso detect
```
~ $ espanso detect                                                                                                                       21:34:55
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'FightForYourDream'
==> Class: 'Alacritty'
==> Executable: ''
```

# Some system info: 
```
 lizhe@ori
 OS: Manjaro 21.2.5 Qonos
 Kernel: x86_64 Linux 5.15.28-1-MANJARO
 Uptime: 5h 1m
 Packages: 1611
 Shell: python
 Resolution: 1920x1080
 DE: KDE 5.91.0 / Plasma 5.24.3
 WM: KWin
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: breeze-dark
 Disk: 69G / 236G (31%)
 CPU: Intel Core i7-7700K @ 8x 4.5GHz [41.0°C]
 GPU: Mesa Intel(R) HD Graphics 630 (KBL GT2)
 RAM: 5956MiB / 15866MiB

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

alacritty 0.10.1 (2844606d)


```

**Comment by federico-terzi** [comment]
@woshichuanqilz I'm sorry you experienced this problem! When you have the chance, could you please try upgrading to the v2? It's the new stable version and there's a good chance it might solve this problem. Here's the migration guide for when you're ready: https://espanso.org/docs/migration/overview/

**Comment by woshichuanqilz** [comment]
> @woshichuanqilz I'm sorry you experienced this problem! When you have the chance, could you please try upgrading to the v2? It's the new stable version and there's a good chance it might solve this problem. Here's the migration guide for when you're ready: https://espanso.org/docs/migration/overview/

I follow the instruction here: https://espanso.org/docs/migration/uninstalling_legacy/#uninstalling-on-linux

And get errors like this: 
```
~ $ espanso stop                                                      23:42:13
    espanso unregister
Error parsing YAML file '/home/lizhe/.config/espanso/default.yml', invalid syn
tax: while parsing a block mapping, did not find expected key at line 451 colu
mn 29
Error parsing YAML file '/home/lizhe/.config/espanso/default.yml', invalid syn
tax: while parsing a block mapping, did not find expected key at line 451 colu
mn 29

~ $ sudo pacman -R espanso                                            23:44:09
error: target not found: espanso
```
I get error when I install v2, how to solve it?

![image](https://user-images.githubusercontent.com/11295355/162476947-75387f60-0505-4245-8c4f-ede14db5c69a.png)

![image](https://user-images.githubusercontent.com/11295355/162477042-1a9e6ad1-a437-438d-9002-b795cc6f2133.png)
![image](https://user-images.githubusercontent.com/11295355/162477103-96a374f1-ee5d-4a2e-9191-ade0a93a9b1f.png)
![image](https://user-images.githubusercontent.com/11295355/162477137-5960c1c3-9082-4bce-a360-e9e301a41051.png)
