### ISSUE TITLE
current calendar week

### ISSUE THREAD

**Issue by Photographix** [federico-terzi/espanso#1128]
**Is your feature request related to a problem? Please describe.**
Hello and thank you for this great tool!

Is there any way to output the current calendar week? I can't find a solution for this in the date options.

Thanks

**Describe the solution you'd like**
A variable to configure

**Comment by ssotoen** [comment]
There are 3 options:

- `%U`: Week 1 starts with the first Sunday in the year. It is possible to have week 0 for days before the first Sunday.
- `%W`: Same as `%U`, but week 1 starts with the first Monday in that year instead.
- `%V`: Week 1 is the first week with at least 4 days in the year.
