### ISSUE TITLE
Bitdefender "disinfecting" espanso

### ISSUE THREAD

**Issue by s14230** [federico-terzi/espanso#1139]
After installing Espanso on Windows 11, Bitdefender immediately disinfects and dsiables the product. I've reported it as a false positive to Bitdefender but they haven't changed the rating. Please find below the notificiation they provide. I'd be grateful if you could fix this with them please.

![image](https://user-images.githubusercontent.com/48768717/173330433-2e54ee00-1095-4da1-babc-b632f1cd2f34.png)

**Comment by federico-terzi** [comment]
Hey @s14230,

Thanks for reporting this issue! Unfortunately, for reasons unknown to me Bitfender never played well with Espanso, and we received countless reports over the years... Things might improve once we set up digital signatures (which are likely coming in the upcoming months), but in the meantime, I can't offer you much of a solution...

Cheers :)

**Comment by Dlakoms** [comment]
Happened to me as well with Bitdefender on Windows 10 Pro 21H2 19044.2006. Haven't been able to make a "clean" uninstall of Espanso (some files/folder were locked and windows keep telling me I need rights I already have to do so), so I switched to the portable version after then.
