### ISSUE TITLE
espanso Selection dialog has unicode issue

### ISSUE THREAD

**Issue by Initnum13** [federico-terzi/espanso#1144]
**Describe the bug**
While using the selection dialog feature, i cannot read the text on the screen which shows all blocks. 

**Screenshots**
![Jun-19-2022_unicode](https://user-images.githubusercontent.com/88510122/174468838-160da0a4-4a1f-4a2f-932a-509b6b7fdeff.jpeg)

screenshot of the display attached. 

**Setup information**
- OS: Fedora 34
- Version: espanso 2.1.4-beta

**Comment by federico-terzi** [comment]
I'm sorry you experienced this problem! Please see: https://github.com/federico-terzi/espanso/issues/877

Cheers :)
