### ISSUE TITLE
Windows installer force a restart of the system without asking the user

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#115]

**Comment by wadbr** [comment]
This just happened to me. It was not great. I was able to press cancel (on closing unsaved work) and saved some of my open windows (including the installer). I noticed the installer had the options to restart or delay so this happened before the the restart was selected. 

Using Win10x64 and latest espanso installer from github 0.3.4.

**Comment by federico-terzi** [comment]
Hi @wadbr, thank you very much for the feedback. I'll definitely look into it in the next few days.

Thanks for your help

**Comment by wadbr** [comment]
No problem at all, if you need any more help to debug (I don't know if the installer leaves a log somewhere?) let me know.

**Comment by federico-terzi** [comment]
@wadbr thank you. I'll try to reproduce the issue by myself and let you know if I need more info :)
