### ISSUE TITLE
all hypens are removed in linux (worked on windows 11)

### ISSUE THREAD

**Issue by alexn-s** [federico-terzi/espanso#1152]
**Describe the bug**
I have multiple snippets that i use in markdown files which worked on win 11.
The same snippets dont work on my current os.

Even the simplified example from below does not work for me.

**Code**

snippets.yml
```
matches:
  - trigger: ":frontmatter"
    label: "frontmatter"
    replace: "---"
```

Even other replacements such as: `lorem-ipsum-a-b-c`
all hyphens are removed.

**Expected behavior**
use the string which is actual inside of the brackets

**Setup information**
```
    `osssssssssssssssssssso`           alex@alex-zorin 
       .osssssssssssssssssssssso.          ---------------                                                                                  
      .+oooooooooooooooooooooooo+.         OS: Zorin OS 16.1 x86_64                                                                         
                                           Host: HVY-WXX9 M1060                                                                             
                                           Kernel: 5.13.0-30-generic                                                                        
  `::::::::::::::::::::::.         .:`     Uptime: 10 hours, 46 mins                                                                        
 `+ssssssssssssssssss+:.`     `.:+ssso`    Packages: 2451 (dpkg), 23 (flatpak), 9 (snap)                                                    
.ossssssssssssssso/.       `-+ossssssso.   Shell: zsh 5.8                                                                                   
ssssssssssssso/-`      `-/osssssssssssss   Resolution: 1920x1080                                                                            
.ossssssso/-`      .-/ossssssssssssssso.   DE: GNOME                                                                                        
 `+sss+:.      `.:+ssssssssssssssssss+`    WM: Mutter                                                                                       
  `:.         .::::::::::::::::::::::`     WM Theme: ZorinRed-Dark                                                                          
                                           Theme: ZorinRed-Dark [GTK2/3]                                                                    
                                           Icons: ZorinRed-Dark [GTK2/3]                                                                    
      .+oooooooooooooooooooooooo+.         Terminal: cool-retro-term                                                                        
       -osssssssssssssssssssssso-          CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz                                      
        `osssssssssssssssssssso`           GPU: AMD ATI 03:00.0 Renoir                                                                      
                                           Memory: 8613MiB / 15365MiB 

```
`espanso 2.1.5-beta`

**Comment by alexn-s** [comment]
remembered to try the backend key in the config.
set it to
`backend: clipboard`
and now everything works

**Comment by dtap001** [comment]
I have the same problem. However setting the backend to clipboard solves it, but after this settings the replacement only works in text editors, not in any terminal (gnome default, termius, tabby) Can anyone help me please?

**Comment by morgan-dgk** [comment]
This match triggers as expected under 6.8.1-arch1-1 / Wayland. 

What is the output of `loginctl show-session <your-session-number-here> | grep Type`?

**Comment by dtap001** [comment]
Thanks for the prompt reply! 

```
❯ loginctl show-session 2 | grep Type
Type=x11
```

**Comment by smeech** [comment]
> I have the same problem. However setting the backend to clipboard solves it, but after this settings the replacement only works in text editors, not in any terminal (gnome default, termius, tabby) Can anyone help me please?

You may need different `backend:` for different apps (hence app-specific configurations). I too, use `clipboard` globally, but need `auto` in terminal and `inject` in LO Calc.

**Comment by dtap001** [comment]
But my problem is that it works with clipboard everywhere but the hyphen is stripped out from matches. With inject it is not working in terminal. Is there any other option there?

**Comment by smeech** [comment]
> But my problem is that it works with clipboard everywhere but the hyphen is stripped out from matches. With inject it is not working in terminal. Is there any other option there?

I'm not sure what you mean by "the hyphen is stripped out from matches".

If `force_mode:` in your expansion indicates you need different injection mechanisms (`backend: clipboard`/`inject`) in different programs, you may need to set up one or more app-specific configurations to select what works best in those that aren't happy with your default.

**Comment by dtap001** [comment]
For example this is my match:

```
matches:
  - trigger: ":cback"
    replace: "cd -"
    label: "move/cd/back"
```

This match will insert this at my computers:
```
cd
```

instead of the expected

```
cd -
```

**Comment by smeech** [comment]
> I have the same problem. However setting the backend to clipboard solves it, but after this settings the replacement only works in text editors, not in any terminal (gnome default, termius, tabby) Can anyone help me please?

It's still likely to be an [injection mechanism](https://espanso.org/docs/matches/basics/#injection-mechanism) issue. However, you may need different mechanisms in different programs (as you have found). Consequently, you will probably need one or more [app-specific configuration](https://espanso.org/docs/configuration/app-specific-configurations/) for your terminals. 

For example, I use `backend: clipboard` _globally_ (in `default.yml`), but need:
```yml
filter_class: terminal
backend: auto
```
for my Xfce4-terminal. You may need several app-specific configurations for your different terminals, unless they have a common class. Check them out by typing `#detect#` in each.

**Comment by dtap001** [comment]
But I have tried with both of the possible injection modes.  :(

With auto -> the missing hyphen problem is present
With clipboard -> not wokring at all

**Comment by smeech** [comment]
Hmm... I'm running out of suggestions!
You can type `#acfg#` in your terminals to check which backend is in use, just in case there's a conflict somewhere.
The `force_mode:` option for Inject is `keys` (unfortunately - `inject` would have been more consistent).

Otherwise, bring your problem to [Discord](https://discord.gg/4QARseMS6k). Someone else there may be able to help.

**Comment by dtap001** [comment]
Hello just a fast followup:

I was able to solve this to make it work everywhere as it supposed to:
```
backend: auto
force_mode: keys
disable_x11_fast_inject: false
inject_delay: 0
x11_use_xclip_backend: false
x11_use_xdotool_backend: true
```

**Comment by smeech** [comment]
Excellent! I've not found a program in which `x11_use_xdotool_backend: true` was useful, but that's a useful tip for others. Thank you very much for reporting back.
