### ISSUE TITLE
[Package] all-emojis

### ISSUE THREAD

**Issue by FoxxMD** [federico-terzi/espanso#116]
Hi love this application! I made a package to include all emojis. https://github.com/FoxxMD/espanso-all-emojis

**Comment by federico-terzi** [comment]
Hi @FoxxMD, 
Very nice work! I published it on the hub: https://hub.espanso.org/packages/all-emojis/
By the way, thanks to this package I also solved a bug in espanso, it has been very useful :)

Thanks for your help

**Comment by FoxxMD** [comment]
Glad to contribute 👍 P.S. Something I forgot to put in the description -- I replaced all underscores in names (`_`) with spaces to make them easier to type. EX `:neutral_face:` is `:neutral face:` in the package.

**Comment by federico-terzi** [comment]
> Glad to contribute 👍 P.S. Something I forgot to put in the description -- I replaced all underscores in triggers with spaces to make them easier to type. EX `:neutral_face:` is `:neutral face:` in the package.

Thank you, I'll add it to the readme as soon as I have some time :)

**Comment by federico-terzi** [comment]
@FoxxMD  this should have been fixed now :)
