### ISSUE TITLE
Allow more specific toggle_key settings

### ISSUE THREAD

**Issue by lkrms** [federico-terzi/espanso#117]
I've been able to change espanso's toggle shortcut key from ALT to CTRL by adding the undocumented `toggle_key: CTRL` setting to my `default.yml`. This works around the problem I was having with espanso toggling whenever I used an sxhkd + xdotool hotkey that temporarily clears modifiers via KeyRelease (Alt) and KeyPress (Alt).

It would be great to have, say, Right Alt or Right Shift operate as the espanso toggle shortcut key. At the moment there's only META, SHIFT, ALT, CTRL, and BACKSPACE.

Something for the distant future, perhaps :smile: 

Thanks so much for this outstanding software. As a former TextExpander on macOS + AutoKey on Linux user, it's a dream come true.

**Comment by federico-terzi** [comment]
Hi @lkrms,
Thank you for the kind words and valuable feedback. I'll take a look at the problem and let you know once I've investigated further.

Thanks for your help

**Comment by federico-terzi** [comment]
Hey @lkrms,

Sorry for the long wait, this feature is finally here!
If you want to try it out, update to version 0.5.2 of espanso.

Thanks for your help :)

**Comment by lkrms** [comment]
That's fantastic! Thanks for working so actively on this project :)

**Comment by federico-terzi** [comment]
You're welcome :)
