### ISSUE TITLE
not working in emacs

### ISSUE THREAD

**Issue by muralikodali** [federico-terzi/espanso#122]
Application is not working in emacs . My emacs version is 26.3
It is working well in vim and geany editors.

**Comment by federico-terzi** [comment]
Hi @muralikodali,
Thanks for the feedback, I would need to know a few other things:

* What operating system are you using?
* Are you using emacs inside the terminal?
* Which terminal are you using?

Thanks

**Comment by muralikodali** [comment]
On 17 November 2019 10:30:39 PM IST, Federico Terzi <notifications@github.com> wrote:
>Hi @muralikodali,
>Thanks for the feedback, I would need to know a few other things:
>
>* What operating system are you using?
>* Are you using emacs inside the terminal?
>* Which terminal are you using?
>
>Thanks

My operating system is Ubuntu Mate 18.04.3

I am not running emacs inside terminal. Running emacs with evil mode. I have tried espanso without evil mode also. I have got the same result.

My terminal is mate-terminal .
-- 
Regards,
Murali Kodali

**Comment by federico-terzi** [comment]
All right, thanks for the feedback. I'll look into it in the next few days.

Thanks

**Comment by federico-terzi** [comment]
Hi @muralikodali,
I'm currently in the process of developing a feature that could solve this problem.
When using emacs, which keyboard shortcut do you use to paste content?

Thanks for your help

**Comment by muralikodali** [comment]
I use p (evil mode) or shift+insert to paste content in emacs

**Comment by o175** [comment]
Hi there!
I have the same issue.
Is it possible to re-type expansion text letter by letter instead of pasting it? Will it be slow?

**Comment by federico-terzi** [comment]
Hi @o175,
I'm glad you were able to solve your problem with the `backend` option. Keep in mind that on Linux, that option may be unable to correctly type non-ascii characters in some editors.

For this reason, I would personally limit the `Inject` backend to emacs only, so that other applications can work with the default one. You can achieve this with App-specific configuration: https://espanso.org/docs/configuration/#application-specific-configurations

Cheers

**Comment by federico-terzi** [comment]
Hi @muralikodali,
This bug should be fixed in version 0.4.1. Let me know if you experience any other error.

Thanks for your help :)
