### ISSUE TITLE
Disable toggle key?

### ISSUE THREAD

**Issue by NickSeagull** [federico-terzi/espanso#126]
Hey, thanks a lot for this! ❤🙏

Is there a way to disable the toggle key, and if not, how could I contribute in order to add this feature?

Thanks in advance!!

**Comment by federico-terzi** [comment]
Hi @NickSeagull,
Thanks for your kind words! At the moment it's not possible to disable the toggle key, but you can change it by adding:

```
toggle_key: CTRL
```

You can choose between CTRL, ALT and META ( which is equivalent to WIN key on Windows and CMD on macOS ).

I'll try to add the feature to the next release of espanso, thanks for your help

**Comment by NickSeagull** [comment]
Thanks @federico-terzi 😄 , I saw that there's quite a log on your backlog, and I'd really like to help, this project is awesome!

I saw that `toggle_key` is being handled [here](https://github.com/federico-terzi/espanso/blob/ff41090bb1cb0bd438ce179129132ff74c4c3888/src/matcher/scrolling.rs#L196). Would you accept a PR that adds a `KeyModifier` called `Off` that gets ignored on that `if`?

**Comment by federico-terzi** [comment]
Sure @NickSeagull, thank you very much for your help :)

**Comment by NickSeagull** [comment]
This is merged in `dev` now, closing...
