### ISSUE TITLE
Espanso does not work to log into apps

### ISSUE THREAD

**Issue by DutchPete** [federico-terzi/espanso#132]
I use an Espanso snippet to log into the SpiderOak GUI window that pops up when I launch SO on my Mac. I think this a security feature of the Mac, but is there a way to bypass this?

**Comment by federico-terzi** [comment]
Hi @DutchPete,
Do you mean using espanso on password fields? If that's the case, it's not possible to bypass on macOS as the operating system blocks every operation on those for security purposes.

Cheers

**Comment by DutchPete** [comment]
@federico-terzi : yes, that's what I mean.
So, OK, I'll have to accept. Thanks for the reply, I'll close this issue.
