### ISSUE TITLE
Unable to start espanso - Result::unwrap() panicked

### ISSUE THREAD

**Issue by m4mum** [federico-terzi/espanso#134]
$ espanso start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

$ export RUST_BACKTRACE=1

$ espanso start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: espanso::start_main
  12: espanso::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by federico-terzi** [comment]
Hi @m4mum,

Thanks for your feedback, I'm sorry you experienced this issue. I'll need a few more info to help you, in  particular:

* What operating system are you using?
* Can you post here the output of `espanso path`? (if it doesn't crash)

Thanks for your help

**Comment by m4mum** [comment]
Hi Federico

Similar error I found on net related to rust... but I am totally noob with
Rust.
Here is requested details

raxitsheth@raxits-Lenovo-G570:~$ espanso path
Config: /home/raxitsheth/.config/espanso
Packages: /home/raxitsheth/.local/share/espanso/packages
Data: /home/raxitsheth/.local/share/espanso

raxitsheth@raxits-Lenovo-G570:~$ uname -a
Linux raxits-Lenovo-G570 3.13.0-170-generic #220-Ubuntu SMP Thu May 9
12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

raxitsheth@raxits-Lenovo-G570:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.6 LTS
Release: 14.04
Codename: trusty
raxitsheth@raxits-Lenovo-G570:~$

**Comment by federico-terzi** [comment]
All right, thank you @m4mum. Could you please run these commands and post here the output?

```
ls -R /home/raxitsheth/.config/espanso
ls -R /home/raxitsheth/.local/share/espanso
```

Judging from the error, a file is probably missing.

Thanks for your help :)

**Comment by m4mum** [comment]
Hi @federico-terzi/espanso <espanso@noreply.github.com>

Here you go :)

raxitsheth@raxits-Lenovo-G570:~$ ls -R /home/raxitsheth/.config/espanso
/home/raxitsheth/.config/espanso:
default.yml  user

/home/raxitsheth/.config/espanso/user:
raxitsheth@raxits-Lenovo-G570:~$ ls -R /home/raxitsheth/.local/share/espanso
/home/raxitsheth/.local/share/espanso:
espanso.lock  packages

/home/raxitsheth/.local/share/espanso/packages:

you are welcome :)

**Comment by federico-terzi** [comment]
Hey @m4mum, 

I think I found the culprit. You are using Ubuntu 14.04 which uses Upstart instead of Systemd to manage background processes. For this reason, when espanso tried to communicate with Systemd using the `systemctl` command, it failed.

In the next release I'll try to add a check to make this error more clear in the future.

At this point, you have two options:
* If you are willing to update your system, any newer version of Ubuntu supports Systemd out of the box.
* Use the *unmanaged mode* of espanso, which does not communicate with the system daemon manager (I have to warn you that it is not super tested though)

If you choose the latter, you should add this line to the `default.yml` file found in the config directory:
```yaml
use_system_agent: false
```

After this step, espanso should work correctly, but you have to manage it by yourself. That means calling `espanso start` when your system boots up, so that it's always running.

Thanks for your help :)

**Comment by m4mum** [comment]
👍👍👍👍  @federico-terzi/espanso
<reply@reply.github.com>
(typed using espanso!)

Thanks

**Comment by federico-terzi** [comment]
Glat to know that :)
