### ISSUE TITLE
Suggestion: Adopt rustfmt formatting for the project.

### ISSUE THREAD

**Issue by matt-h** [federico-terzi/espanso#137]
`cargo fmt` currently makes a many changes throughout the project.

A suggestion would be to adopt using the [rustfmt](https://github.com/rust-lang/rustfmt) style auto-formatter to make the project consistent with other rust projects.

**Comment by federico-terzi** [comment]
Hi @matt-h,

That's surely a great suggestion. Considering the number of resulting changes, it would be better to ship it in a major release probably.

What do you think about it?

Thanks for your help

**Comment by matt-h** [comment]
That is fine to wait for that.

Although it is pretty much just whitespace changes of the code so shouldn't result it any feature changes. Tests all passed still after I tried it.

I mostly just noticed because I had to turn off the rust auto formatter in my editor when making a change otherwise it was changing a lot of code.

**Comment by federico-terzi** [comment]
Glad to hear that, I'll keep you updated.

Cheers
