### ISSUE TITLE
Does not run on Windows 7

### ISSUE THREAD

**Issue by Banbury** [federico-terzi/espanso#141]
The website should state clearly, that espanso is only running on Windows 10.
Also the installer shouldn't install espanso on anything but Windows 10.

Or you could make a version, that runs on older versions of Windows. I'm not the only person, who doesn't like Windows 10.

**Comment by federico-terzi** [comment]
Hi @Banbury,

You are right, I'm sorry you experienced this issue. I tested espanso on Windows 8 and it wasn't working as expected, though I may get it working on Windows 7. What kind of errors are you getting?

Nevertheless, I'll try updating the description on the website to make the situation more clear.

Thanks for your help :)

**Comment by Banbury** [comment]
You're using several functions, that are only available on Windows 10.
The first was SetThreadDpiAwarenessContext.

I can't remember the rest, and I've uninstalled espanso already.

**Comment by federico-terzi** [comment]
No problem, I'm sorry about that. 

Honestly, I didn't pay much attention to older versions of Windows, as Windows 7 is going to get discontinued soon: https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020

Supporting 3 platforms is already pretty demanding for me, I had to make some compromises.

Thanks for your help anyway, I'll update the website so that this incompatibility is not a surprise.

**Comment by cser** [comment]
Hello! I have this problem on Windows 7 too:
---------------------------
espanso.exe - Точка входа не найдена
---------------------------
Точка входа в процедуру SetThreadDpiAwarenessContext не найдена в библиотеке DLL USER32.dll. 
---------------------------
ОК   
---------------------------
But I can't change OS on my work :(
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext
> Important  
> In general, it is recommended to not use SetProcessDpiAwarenessContext to set the DPI awareness for your application. If possible, you should declare the DPI awareness for your application in the application manifest. For more information, see Setting the default DPI awareness for a process.
Is there possible to do something with this problem?

**Comment by federico-terzi** [comment]
@cser Unfortunately, as far as my testing goes, espanso will need a few other tweaks to work on older Windows versions, and at the moment, I only have limited resources, so I must prioritize other tasks :(

**Comment by GlassGruber** [comment]
Hei there sorry to bump, I've been bitten by same problem, too bad but I understand!

I'm just reporting that Win 10 only support should be mentioned also on installation page https://espanso.org/install/, currently it is not clear like in docs page https://espanso.org/docs/install/win/. Maybe something like below
![image](https://user-images.githubusercontent.com/1172428/168765150-564bc730-0f34-41b5-953a-0e6467d4f46a.png)

Hopefully I'll have the chance to test your app on Linux, thank you anyway for your program!

**Comment by cser** [comment]
Yes, the circumstance is unpleasant.
By the way, Windows 10 was installed at my work after all 😄

**Comment by HydraOrc** [comment]
What you can do is download user32.dll and then put it next to the executable file, so it takes the priority over the file in windows/system32, this worked for me for another application (Radeon Software particullary)
