### ISSUE TITLE
Support multiple triggers for the same expansion

### ISSUE THREAD

**Issue by muhlinux** [federico-terzi/espanso#144]
Could just use yaml lists for this e.g.
```
  - trigger: 
    - ":lol"
    - ":xd"
    - ":laugh"
    replace: ":laughing:"
```

And a short form:

```
  - trigger: [":lol", ":xd", ":laugh"]
    replace: ":laughing:"
```

I realize you could make a new expansion with a different trigger, but i think this would be nice to see, and keep the config file cleaner...

**Comment by federico-terzi** [comment]
Hey @muhlinux,

Thanks for the feedback, this could be a good feature to have. I'll add it to the roadmap.

Cheers :)

**Comment by ndmax** [comment]
I attempted to configure a multi-trigger expansion, but upon save/reload I received the following error:

[ERROR] unable to load match group "/home/{{USER||/Cloud/Tech/System/Espanso/match/communication.yml"

Caused by:
    0: failed to parse YAML match group
    1: matches[5].trigger: invalid type: sequence, **expected a string** at line 18 column 14

I'm on Lubuntu 22.04

**Comment by kschellercrowley** [comment]
> I attempted to configure a multi-trigger expansion, but upon save/reload I received the following error:
> 
> [ERROR] unable to load match group "/path/to/match/communication.yml"
> 
> Caused by: 0: failed to parse YAML match group 1: matches[5].trigger: invalid type: sequence, **expected a string** at line 18 column 14
> 
> I'm on Lubuntu 22.04

@ndmax - Make sure you are updating your yaml to "triggers:" instead of "trigger:"
