### ISSUE TITLE
[Documentation] Clarify matches

### ISSUE THREAD

**Issue by muhlinux** [federico-terzi/espanso#145]
## Valid YAML doesn't require quotes
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

This is one of the current examples of the syntax

```
- trigger: "hello"
  replace: "world"
```

To replace the original text with a multi-line expansion, we can use the \n line terminator character, such as:

```
- trigger: "hello"
  replace: "line1\nline2"

```
---

I tested this and It works

```
- trigger: hello
  replace: world
```

To replace the original text with a multi-line expansion, we can either use the \n line terminator character, such as:

```
- trigger: hello
  replace: "line1\nline2"

```
> Notice using  `\n` as the line terminator character quotes are needed

Or values can span multiple lines using  `|` or `>`. Spanning multiple lines using a “Literal Block Scalar” `|` will include the newlines and any trailing spaces. Using a “Folded Block Scalar” `>` will fold newlines to spaces; it’s used to make what would otherwise be a very long line easier to read and edit. In either case the indentation will be ignored. Examples are:

```
- trigger: include newlines
  replace: |
            exactly as you see
            will appear these three
            lines of poetry
```
```
- trigger: fold newlines
  replace: >
            this is really a
            single line of text
            despite appearances
```
> Notice how no quotes are needed

There are a number of characters that are special (or reserved) and cannot be used as the first character of an unquoted scalar: ``' "  [] {} > | * & ! % # ` @ ``  (Haven't actually tested these with espanso maybe there is more/less)

I think the default configuration should reflect this as well :)

**Comment by federico-terzi** [comment]
Hey @muhlinux,

First of all, thank you for helping me improve the documentation :)

I like this part and I'll definitely add it to the documentation:
> To replace the original text with a multi-line expansion, we can either use the \n line terminator character, such as:
> 
> ```
> - trigger: hello
>   replace: "line1\nline2"
> ```
> 
> > Notice using  `\n` as the line terminator character quotes are needed
> 
> Or values can span multiple lines using `|` or `>`. Spanning multiple lines using a “Literal Block Scalar” `|` will include the newlines and any trailing spaces. Using a “Folded Block Scalar” `>` will fold newlines to spaces; it’s used to make what would otherwise be a very long line easier to read and edit. In either case the indentation will be ignored. Examples are:
> 
> ```
> - trigger: include newlines
>   replace: |
>             exactly as you see
>             will appear these three
>             lines of poetry
> ```
> 
> ```
> - trigger: fold newlines
>   replace: >
>             this is really a
>             single line of text
>             despite appearances
> ```
> 
> > Notice how no quotes are needed
> 
> There are a number of characters that are special (or reserved) and cannot be used as the first character of an unquoted scalar: `` ' " [] {} > | * & ! % # ` @ `` (Haven't actually tested these with espanso maybe there is more/less)

On the other hand, I'm not sure about suggesting users to avoid using `"` at all. From my perspective, it's better to show a single, opinionated, way to do things in order to keep them simple.
If we tell users to go ahead and use triggers without quotes, they will do so. This is totally fine until one not-so-experienced developer decides to use multi-word strings or some special characters without reading the full documentation in which we state that, in those cases, he should use the quotes. As a result, he will receive an error and spend a good amount of time trying to fix it.

What do you think?

Thank you for the help :)

**Comment by SantoshSrinivas79** [comment]
@muhlinux many thanks for this explanation.

Is there a way to create a trigger for the below snippet. I tried as follows:

```yaml
  - trigger: ";sc"
    replace: >
              // Select the required elements. The selector will need to be modified depending on the use case

              var notes = document.getElementsByClassName("s-tag");

              var text = "";

              for (var i = 0; i < notes.length; i++) {
                  var note = notes[i].innerText;

                  // concantenate the text
                  text = text + "\n\n" + note;
              }

              // https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f
              const copyToClipboard = str => {
                  const el = document.createElement('textarea');
                  el.value = str;
                  el.setAttribute('readonly', '');
                  el.style.position = 'absolute';
                  el.style.left = '-9999px';
                  document.body.appendChild(el);
                  el.select();
                  document.execCommand('copy');
                  document.body.removeChild(el);
              };

              console.log(text);

              // copy to clipboard
```

However, the quotes get replaced in a different character in `TextEdit` application on Mac.
If I try to trigger in devtools, it doesn't simply output to the console.

**Comment by federico-terzi** [comment]
Hey @SantoshSrinivas79,
Could you please make a screenshot of the output?
Thanks for your help

**Comment by SantoshSrinivas79** [comment]
@federico-terzi here is the animated gif (both using espanso and copy and paste later)

My exact config in `default.yml` is:

```sh
  # Otter copy
  - trigger: ";sc"
    replace: >
              // Select the required elements. The selector will need to be modified depending on the use case

              var notes = document.getElementsByClassName("s-tag");

              var text = "";

              for (var i = 0; i < notes.length; i++) {
                  var note = notes[i].innerText;

                  // concantenate the text
                  text = text + "\n\n" + note;
              }

              // https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f
              const copyToClipboard = str => {
                  const el = document.createElement('textarea');
                  el.value = str;
                  el.setAttribute('readonly', '');
                  el.style.position = 'absolute';
                  el.style.left = '-9999px';
                  document.body.appendChild(el);
                  el.select();
                  document.execCommand('copy');
                  document.body.removeChild(el);
              };

              console.log(text);

              // copy to clipboard
```

![espanso-dev-tools-bug](https://user-images.githubusercontent.com/1036163/71654593-892cad80-2d58-11ea-985f-81e4ce3555d4.gif)

**Comment by federico-terzi** [comment]
Hey @SantoshSrinivas79,
you can try switching espanso to `Clipboard` mode by adding this line in your `default.yml` file:

```yaml
backend: Clipboard
```

and then restart espanso. This should work correctly in your case.
You could even make an [application specific](https://espanso.org/docs/configuration/#application-specific-configurations) configuration just for chrome, to avoid using the clipboard backend on all applications.

Cheers

**Comment by SantoshSrinivas79** [comment]
Hi @federico-terzi,

Thank you! That works! :-)

I had to add a line after `// https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f`

Else, it was getting merged into the next line.

Below version works:

```sh
  # Otter copy
  - trigger: ";sc"
    replace: >
              // Select the required elements. The selector will need to be modified depending on the use case

              var notes = document.getElementsByClassName("s-tag");

              var text = "";

              for (var i = 0; i < notes.length; i++) {
                  var note = notes[i].innerText;

                  // concantenate the text
                  text = text + "\n\n" + note;
              }

              // https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f
              
              const copyToClipboard = str => {
                  const el = document.createElement('textarea');
                  el.value = str;
                  el.setAttribute('readonly', '');
                  el.style.position = 'absolute';
                  el.style.left = '-9999px';
                  document.body.appendChild(el);
                  el.select();
                  document.execCommand('copy');
                  document.body.removeChild(el);
              };

              console.log(text);

              // copy to clipboard
```

**Comment by federico-terzi** [comment]
Glad to hear that @SantoshSrinivas79 :)

**Comment by federico-terzi** [comment]
[Added to the documentation](https://espanso.org/docs/matches/#multi-line-expansions) @muhlinux, thanks for your help :)

**Comment by smeech** [comment]
For information only, I added a documentation section on [quoting](https://espanso.org/docs/matches/quotes/) a while ago.
