### ISSUE TITLE
[Documentation] Mention libnotify-bin in the installation instructions

### ISSUE THREAD

**Issue by siddbudd** [federico-terzi/espanso#149]
I just installed espanso on Pop!_OS according to the instructions for Ubuntu and was told after attempting to start espanso that 

> 'notify-send' command is needed for espanso to work correctly

So I did some research and found that the required package is called 'libnotify-bin'. It would be ideal if you could include that in the line
`sudo apt install libxtst6 libxdo3 xclip`
and change it to
`sudo apt install libxtst6 libxdo3 xclip libnotify-bin`
Anyway, nothing happens if the user already has that installed, but it is good to have it in the instructions considering it is a prerequisite for your program to function correctly.

**Comment by federico-terzi** [comment]
Hey @siddbudd,
This is a great suggestion! Thank you very much for your help, I'll update the documentation soon.
Merry Christmas :)

**Comment by Scrumplex** [comment]
I already updated the AUR package to add libnotify as a dependency.

**Comment by federico-terzi** [comment]
Thank you very much as always @Scrumplex :)

**Comment by federico-terzi** [comment]
Added to the documentation @siddbudd, thanks for your help :)
