### ISSUE TITLE
issue with replacing trigger

### ISSUE THREAD

**Issue by siddbudd** [federico-terzi/espanso#150]
I have been playing around with espanso on Pop!_OS for a couple hours now, trying to use it as a replacement for trusty AHK (I am coming from Windows). I am experiencing an issue with the trigger not always being fully replaced. Sometimes the first 1 character, very rarely the first 2 characters remain. On other occasions a space is introduced before the replacement.

E.g. my trigger is "/essr" and the replacement is "Entschuldigen Sie bitte die späte Rückmeldung." then I get following results:

- [x] "Entschuldigen Sie bitte die späte Rückmeldung."

- [ ] " Entschuldigen Sie bitte die späte Rückmeldung."

- [ ] "/Entschuldigen Sie bitte die späte Rückmeldung."

- [ ] "/eEntschuldigen Sie bitte die späte Rückmeldung." (very rare)

To demonstrate, I will now trigger it several times in a row (added code tags to better highlight the lines starting with spaces):

```
/Entschuldigen Sie bitte die späte Rückmeldung. 
/Entschuldigen Sie bitte die späte Rückmeldung.
/Entschuldigen Sie bitte die späte Rückmeldung. 
 Entschuldigen Sie bitte die späte Rückmeldung. 
Entschuldigen Sie bitte die späte Rückmeldung. 
/Entschuldigen Sie bitte die späte Rückmeldung. 
Entschuldigen Sie bitte die späte Rückmeldung.  
/Entschuldigen Sie bitte die späte Rückmeldung. 
/Entschuldigen Sie bitte die späte Rückmeldung. 
/Entschuldigen Sie bitte die späte Rückmeldung. 
Entschuldigen Sie bitte die späte Rückmeldung. 
Entschuldigen Sie bitte die späte Rückmeldung. 
 Entschuldigen Sie bitte die späte Rückmeldung. 
/Entschuldigen Sie bitte die späte Rückmeldung. 
```

**Comment by federico-terzi** [comment]
Hi @siddbudd,
This is strange indeed. It only happened to me a few times on a particular software, in which applications are you experiencing this phenomenon?

Thanks for your help :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up. I suggest you to take a look at #248 for a possible solution.
Let me know if you have other questions.
Cheers :)
