### ISSUE TITLE
Archlinux and DWM

### ISSUE THREAD

**Issue by a-baghdadi** [federico-terzi/espanso#151]
Hi

[ali@nuc ~]$ espanso start
Daemon started correctly!
[ali@nuc ~]$ espanso status
espanso is not running

Does not working after says started correctly!!
Thanks

**Comment by federico-terzi** [comment]
Hey @a-baghdadi,

Thanks for the feedback, this is strange indeed! Could you please run `espanso log` and post the output here?

Cheers

**Comment by a-baghdadi** [comment]
Thank you dear federico-terzi for your fast reply

I am using DWM on Arch
Here you are :

[ali@nuc ~]$ espanso log
09:41:44 [ INFO] espanso version 0.4.1
09:41:44 [ INFO] using config path: /home/ali/.config/espanso
09:41:44 [ INFO] using package path: /home/ali/.local/share/espanso/packages
09:41:44 [ INFO] starting daemon...
09:41:44 [ERROR] Error, can't connect to X11 context

**Comment by federico-terzi** [comment]
It seems like espanso is unable to connect to X11. 
Are you using Wayland? Otherwise, it may be due to something going on with DWM.
You could also try executing `espanso -v daemon` and see if you still see `Error, can't connect to X11 context`.

Let me know :)

**Comment by a-baghdadi** [comment]
espanso -v daemon works without problem (a few errors) like this :
[ERROR] Unable to receive char: invalid utf-8 sequence of 1 bytes from index 1

I am using X11 (not wayland)

Thank you very much

**Comment by a-baghdadi** [comment]
Switched to Xfce4 and still the same with espanso start and espanso is not running
like DWM.

**Comment by Scrumplex** [comment]
Is there a `$DISPLAY` environment variable present when starting espanso? Where are you running `espanso start`? That error appears when you have no `$DISPLAY` at all or just an invalid value for the variable.

**Comment by a-baghdadi** [comment]
[ali@nuc ~]$ echo $DISPLAY
:0

I run espanso from ST terminal in Archlinux and DWM

**Comment by a-baghdadi** [comment]
The problem is solved.
I copied xinitrc again from its default location to home folder and everything works fine.

thank you federico-terzi and Scrumplex.

**Comment by federico-terzi** [comment]
Glad to hear that  @a-baghdadi :)

**Comment by banan314** [comment]
> The problem is solved.
> I copied xinitrc again from its default location to home folder and everything works fine.
> 
> thank you federico-terzi and Scrumplex.

You mean `cp /etc/X11/xinit/xinitrc ~` ?

**Comment by a-baghdadi** [comment]
> > The problem is solved.
> > I copied xinitrc again from its default location to home folder and everything works fine.
> > thank you federico-terzi and Scrumplex.
> 
> You mean `cp /etc/X11/xinit/xinitrc ~` ?

Hi, yes exactly, and then add _exec dwm_ to the end of _.xinitrc_ for my window manager. the main command is : `cp /etc/X11/xinit/xinitrc ~/.xinitrc`

**Comment by hisbaan** [comment]
I have the same issue and tried resetting my xinitrrc. Nothing was resolved... Anyone have any solutions? My display variable is :0 as well so I don't know why it can't connect to the X11 server

**Comment by federico-terzi** [comment]
Hey @hisbaan,
Could you please try to follow these steps and see if that helps: #243
Cheers :)

**Comment by hisbaan** [comment]
@federico-terzi That worked, thanks so much! I looked over that thread but I must have missed it. Thanks for writing such a useful piece of software!

**Comment by federico-terzi** [comment]
@hisbaan you're welcome :)
