### ISSUE TITLE
Case affects expansion

### ISSUE THREAD

**Issue by muhlinux** [federico-terzi/espanso#152]
This is a feature I'm missing from AutoKey.
To me it makes sense to add it to the word feature, it could get its own key of course.
```
  - trigger: foo
    replace: bar
    word: true
```
foo = bar
Foo = Bar
FOO = BAR

**Comment by federico-terzi** [comment]
Hey @muhlinux,
This is definitely a good feature to have, I'll add it to the project roadmap.

Thanks for your help :)
