### ISSUE TITLE
Support multiple replaces with the same trigger

### ISSUE THREAD

**Issue by MarihFiba** [federico-terzi/espanso#154]
Hi @federico-terzi,

Thanks for your hard work on espanso. I think it has huge potential.

I have a sophisticated setup on PhraseExpress with hundreds of terms. As a translator I have to use many words regularly and the easiest way to remember all the triggers is to apply a logic.

For me, this logic has to be:
- short to justify using a text expansion solution
- consistent to help remember every defined term easily

So my logic was to use first and last letters of each word.
```
"kr"

for:
kaldır (which means "remove")
kadar (which means "up to")
kriter (which means "criteria")
kurtar (which means "recover")
and many more
```

Now when I use this trigger, PhraseExpress show me a dropdown menu to chose any of the entries associated to it. But espanso just replaces the trigger with one of them.

It would be great to find a solution to solve this issue. I really like how espanso is designed and I'm looking forward to migrate to it as soon as I can find all the functuonality in it.

Thanks man!

**Comment by federico-terzi** [comment]
Hey @MarihFiba,
Thank you very much for the great feedback!
At the moment implementing a dropdown would be problematic due to the number of supported platforms. That said, I don't exclude the possibility as many users already requested a similar feature.

In your opinion, is really worth it to have a dropdown menu to select a word such as "kadar"? Because for 5 characters it would probably be faster by typing it directly. Am I wrong?

Thanks for your help :)

**Comment by MarihFiba** [comment]
Thanks for getting back!

As for your question, when you're on my field, that changes everything. :)

In my case, we have to use thousands of words every day and quality for every one of them is very important.

Abbreviating even short words provides two advangtages:
- You need to think less about typing, you can focus on what to type
- Most importantly this allows us to spend much less time for spelling issues

So yes, five characters are very easy to type. But using less mental energy to repetitively type thousands of characters is a game changer. Saving time and again energy in quality control gives you a critical edge.

Looking forward to see what future versions will bring.

**Comment by federico-terzi** [comment]
That sounds defintely reasonable, thanks again for the great feedback!
Stay tuned :)

**Comment by federico-terzi** [comment]
Hey @MarihFiba,

I know it's been a while, but the new alpha version v2 supports this use case :)

You can also assign the same trigger to multiple matches, and the search bar will automatically open to "disambiguate" between them. For example, I have the `:sig` trigger  associated with multiple signatures

```yaml
  - trigger: ":sig"
    replace: "Best regards, Federico"
  - trigger: ":sig"
    replace: "All the best, Federico"
```

and when I type it, Espanso shows me the search bar to select the right one:

![image](https://user-images.githubusercontent.com/20475953/136691705-d5c8184c-e484-40e0-b25a-7f8bbd47dc9c.png)

Cheers :)

**Comment by MarihFiba** [comment]
Hey @federico-terzi 

You're truly wonderful. I'll definitely try espanso again!

Thanks!

**Comment by federico-terzi** [comment]
@MarihFiba Thanks :pray: Let us know if you have any feedback :)
