### ISSUE TITLE
Popos - notify-send is not installed by default

### ISSUE THREAD

**Issue by sidouglas** [federico-terzi/espanso#155]
http://vaskovsky.net/notify-send/linux.html
Please update your docs - because I wasn't able to start espanso without it.

```
Pop!_OS 19.10
Gnome: 3.34.1
64-bit
```

**Comment by federico-terzi** [comment]
Hey @sidouglas,
Thanks for reporting this, it's problably the same problem as #149.
I'll definitely update the docs as soon as I have some time, the last few weeks have been crazy busy for me :)
Thanks for your help

**Comment by federico-terzi** [comment]
Added to the documentation! Thanks for your help :)
