### ISSUE TITLE
Word triggers on start of line behaviour?

### ISSUE THREAD

**Issue by tiktuk** [federico-terzi/espanso#157]
Hi,

I just set up a word trigger and found out it works differently in different contexts:

    - trigger: ":mymail"
      replace: mail@example.org
      word: true

In Telegram and the Safari address bar I need to type a space before and after for it to trigger.

In TextMate and TextEdit it's enough to end with a space.

I prefer the last behaviour so I don't end up with an extraneous space in front if it's the first word.

Thanks for your great work, as always!

**Comment by federico-terzi** [comment]
Hey @tiktuk,
Thanks for your feedback! Unfortunately, this is a known problem. I'm still trying to figure out the best way to solve it. Follow this issue to stay updated: #127 

Cheers :)
