### ISSUE TITLE
Top keyboard number keys stop working. 

### ISSUE THREAD

**Issue by pifiuk** [federico-terzi/espanso#158]
Im using Espanso on Windows 64 bit. In what seems to be random intervals my number keys at the top of my keyboard seem to stop working. It is a software issue as I can change keyboards and even use the laptop keyboard itself and it still occurs.

Fortunately I found espanso because I had this issue with previous text expanders but I would love to get to the bottom of it. What method does Espanso use to expand text, maybe if I had a small understanding of what is happening I could start to troubleshoot my issue.

**Comment by federico-terzi** [comment]
Hey @pifiuk,
Thank you very much for the feedback. I'll ask you a couple of questions to better understand the problem:

> Im using Espanso on Windows 64 bit. In what seems to be random intervals my number keys at the top of my keyboard seem to stop working. It is a software issue as I can change keyboards and even use the laptop keyboard itself and it still occurs.

Do matches without numbers still work?

> Fortunately I found espanso because I had this issue with previous text expanders but I would love to get to the bottom of it. What method does Espanso use to expand text, maybe if I had a small understanding of what is happening I could start to troubleshoot my issue.

Espanso uses [Raw Input API](https://docs.microsoft.com/en-us/windows/win32/inputdev/raw-input) on WIndows to detect keypresses.

Are you sure you aren't accidentaly disabling espanso with double ALT presses?

Thanks for your help :)

**Comment by pifiuk** [comment]
Hi, 

Thanks for the reply. Yes matches still work and even the ones with numbers still work as long as I use the numbers on the keypad on the right hand side of the keyboard.

**Comment by federico-terzi** [comment]
That's pretty strange indeed! What keyboard layout are you using?

**Comment by pifiuk** [comment]
I am using the standard British UK layout.

**Comment by pifiuk** [comment]
Hello @federico-terzi I found the problem and the solution to my issue. 

Thankfully it has nothing to do with espanso. It is caused by PowerToys - https://github.com/microsoft/PowerToys/issues/410 

Sorry for the time wasting but it all seemed linked.

**Comment by federico-terzi** [comment]
Hey @pifiuk,
Thank you very much for clearing this out! It will be surely helpful to future users.

Cheers :)
