### ISSUE TITLE
Adobe Creative Cloud 2020 conflict on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by jkmgme** [federico-terzi/espanso#159]
I've been dealing with this issue for about a month now. I had Catalina, and have reverted to Mojave due to Catalina's many issues. The one issue that I was facing on Catalina that has resurfaced on Mojave is presented as a particular tool (specifically the "Hand" tool used to grab the artwork and move it around) shows stuck/frozen. This also disables any other tool access specifically in Photoshop. Other Adobe software is effected by this as well. I spend a majority of my time in Photoshop, but have used other Adobe applications (After Effects, Illustrator) during the issue and certain functionalities in the other Adobe applications show the same disrupted behavior, just in a different way. Once this occurs, I have to either restart my system or logout and login. This is to reset the state of my applications on my system in any way to temporarily fix the issue to allow me the option to work on my projects. I've spent many hours having multiple different applications running all while stopping others to target a suspected application causing the issue. I have recently determined that when I don't have espanso running, the issue does not occur. I would like to look into this further as I love using espanso and would like to continue using espanso. Although, if a solution to this problem is not possible, then I can always work on building my own or finding an alternative. I wanted to bring this to the surface to assist the possibility of others having the same issue. I would love to be able to use espanso and Adobe applications simultaneously.

**Comment by federico-terzi** [comment]
Hey @jkmgme,
Thank you very much for your feedback, it's definitely a problem. In fact, when using macOS I experienced the exact same issue with Photoshop related to the stuck Hand tool. If I recall correctly, what I did was removing **Photoshop** from the applications with accessibility permissions, though I may be wrong.

Could you please check if is there "Photoshop" in the list of Accessibility-enabled applications in the Settings and, if there is, trying to disable it and see if that helps?

Thanks for your help :)

**Comment by jkmgme** [comment]
Hey @federico-terzi !
Thank you for your prompt reply. 
I don't currently have and have not had Photoshop as an included application with accessibility permissions via System Preference > Security & Privacy > Privacy > Accessibility. So, that rules that possibility out. :/

**Comment by federico-terzi** [comment]
All right, thank you for your help @jkmgme.
Does quitting espanso solve the issue immediately? I mean, if you are currently using Photoshop and you find your hand tool stuck, does quitting espanso make Photoshop behave normally again?

**Comment by jkmgme** [comment]
No. I have to restart the computer or log out and log back in, or restart the user system before Photoshop starts working normally again. And espanso doesn’t effect Photoshop right away, it’s after a certain amount of time or some use from espanso that it starts to effect Photoshop.

**Comment by federico-terzi** [comment]
That is pretty strange indeed! In fact, I don't really know how to tackle this issue, but I'll take a look at it in the next few days and let you know if I find out something :)

Thanks for your help :)

**Comment by massimo-cassandro** [comment]
Same problem, the issue affects all adobe CC 2020 apps on OSX Catalina. None of them has accessibility permission 

Thanks for help

**Comment by federico-terzi** [comment]
Hey guys,
Yesterday I ran into the same problem on my machine, running Mojave and Photoshop CS6. This is a clear indication that the issue spans across all versions of MacOS and Photoshop, and not just the latest ones.

That said, I tried searching online for possible solutions or mitigations but I couldn't find one that worked. I suspect that Adobe stuffed some hacks inside Photoshop to achieve some functionality, which in turns breaks support for accessibility software. 
In fact, espanso doesn't do anything to block or change events in the system, it just *intercept* keypresses to detect when a trigger has been pressed, using the [addGlobalMonitorForEventsMatchingMask](https://developer.apple.com/documentation/appkit/nsevent/1535472-addglobalmonitorforeventsmatchin?language=objc) method which, according to the documentation, doesn't interfere with apps.

The best way to tackle this issue would be finding a similar accessibility tool for macOS that doesn't suffer from this problem, and see how it does it. If any of you know any Accessibility tool that doesn't cause this issue with Photoshop, please let me know.

Thanks for your help :)

**Comment by massimo-cassandro** [comment]
I have been using Typinator on Mojave for a long time, without problems. 
https://www.ergonis.com/products/typinator/

**Comment by federico-terzi** [comment]
Guys I've got wonderful news! I've tracked down the problem and a fix will be rolled out with the next version of espanso (v0.5.0) in the next few days.

If you are curious, espanso uses a particular macOS API to inject text into applications when expanding a match that basically works like this: I send a keyboard event to the application, usually a space, and in the event itself I can bundle a string of 20 characters that will be the ones effectively printed. In 99% of the applications, space is ignored (as it should), but Photoshop actually registered the press, thus triggering the Hand tool. With this fix, espanso sends an explicit `SPACE RELEASE` event later on, releasing the Hand tool and making photoshop behave like normal. This is the actual commit: https://github.com/federico-terzi/espanso/commit/d8392b4e48e106711d92ca94098ff527e4879702

Your reports helped a lot to track down the issue, thanks again :)

**Comment by jkmgme** [comment]
@federico-terzi Genius!! Thank you!!! Also, a kind-a sort-a related question: How do you properly update espanso after an update like this? I must be blind, but I can't seem to find any information on updating espanso...

**Comment by federico-terzi** [comment]
Hey @jkmgme, although I'm not super experienced with Homebrew, it should be pretty easy. You can try with:

```
brew upgrade espanso
```

If for some reasons that doesn't work, you could try removing it first:

```
brew remove espanso
brew install espanso
```

By the way, the new version should be released pretty soon :)
