### ISSUE TITLE
Under MacOS 10.15.2, Espanso is not deleting the "trigger" text when expanding

### ISSUE THREAD

**Issue by jrop** [federico-terzi/espanso#160]
Espanso replaces `:espanso` => `:espansHi there!`, and `:date` => `:dat01/23/2020`.

I am on macOS 10.15.2.

BTW, this looks like an awesome app, and I was pleasantly surprised to see that it is written in Rust!

![espanso-bug](https://user-images.githubusercontent.com/1404053/73028126-1f9d3d80-3df2-11ea-9fb2-b67fc5c27adf.gif)

**Comment by jrop** [comment]
For anybody else who sees this issue, I had to remove accessibility privileges for [`debounce`](https://github.com/toothbrush/debounce-mac).  I ended up uninstalling `debounce` as I do not need it anymore, anyway.

**Comment by federico-terzi** [comment]
Thank you for your report @jrop, I'm sure it will be useful to someone :)
