### ISSUE TITLE
[macOS] Packages fail to install

### ISSUE THREAD

**Issue by johnrichardrinehart** [federico-terzi/espanso#164]
I have followed the [shruggie package installation instructions](https://hub.espanso.org/packages/shruggie/) after following the [espanso package installation instructions for macOS](https://espanso.org/install/mac) and experienced the following behavior:

```shell
➜  ~ espanso install shruggie
Updating package index...
Index updated!
authentication required but no callback set; class=Ssh (23)
➜  ~ espanso restart
Daemon started correctly!
➜  ~ espanso package list
➜  ~
```
I figured this authentication issue was related to SSH. So, I figured maybe I needed an SSH key loaded (my SSH keys are password-protected). But, `ssh-add -l` confirmed that my keys were already loaded by the agent. Also, the `espanso` hub only provides publicly-accessible code, so this shouldn't be an issue, it seems.

Note that I have repeated this for other packages, also. It's common across all packages that I tried.

**Comment by federico-terzi** [comment]
Hey @johnrichardrinehart.

Thank you very much for your report. It seems like the library espanso currently uses to clone packages ( [libgit2](https://github.com/rust-lang/git2-rs)) , does not deal well with encrypted credentials.

I'll look at the problem as soon as I can and get back to you when I find something.

Thanks for your help :)

**Comment by federico-terzi** [comment]
Hey @johnrichardrinehart,
Unfortunately, I tried to reproduce your issue many times without success, it always works fine on my machine, even with encrypted ssh credentials.
Could it be that perhaps you encountered a temporary error not due to espanso?

Cheers :)

**Comment by johnrichardrinehart** [comment]
Let me check in ~12 hours.

**Comment by johnrichardrinehart** [comment]
@federico-terzi Please leave this open for a bit (if it's been more than a week since I can return to this then feel free to close it). I'm in the middle of a big sprint at work.

**Comment by federico-terzi** [comment]
No problem @johnrichardrinehart, take all the time you need :)

**Comment by unn** [comment]
Ran into this myself. Following along.

**Comment by johnrichardrinehart** [comment]
@unn @federico-terzi I'm awful at making time for this. I'll do some tests within the next 30 hours.

**Comment by federico-terzi** [comment]
I'm sorry you both experienced issues guys. If we can't come up with a solution, I'll implement an alternative channel to install packages that doesn't depend on git, so that you can still install the packages.

Cheers :)

**Comment by unn** [comment]
No stress about timing from me, but thanks for being so on top of it.

**Comment by federico-terzi** [comment]
Hey guys,

I'm currently pushing version 0.5.3 out with an alternative package provider which should work in your case. You can now download a package with the `--no-git` option:

```
espanso install <package_name> --no-git
```

Let me know if it works for you.

Cheers :)

**Comment by unn** [comment]
Works as expected!

**Comment by federico-terzi** [comment]
> Works as expected!

Great! :) I'll keep the issue open as it shouldn't happen with the default provider and someone may come up with a solution in the future. At least now we have a backup plan.

Cheers :)

**Comment by johnrichardrinehart** [comment]
@federico-terzi I forgot to post the results of my tests. I created a password-less RSA key, but `0.5.2` still failed to install packages with the same error code and message.

I've installed 0.5.3 and can confirm that `--no-git` works. Failure to use `--no-git` fails, though, still with the same error code and message
```
>  espanso install shruggie
Updating package index...
Index updated!
authentication required but no callback set; class=Ssh (23)
```

**Comment by federico-terzi** [comment]
Hey  @johnrichardrinehart ,

Thank you for experimenting this further, at this point I can say quite confidently that password-protected RSA keys are not the cause of the issue (as it should be).

Cheers :)

**Comment by johnrichardrinehart** [comment]
@federico-terzi That seems true. Thanks for issuing this new flag.

Do you know the cause of the problem?

**Comment by federico-terzi** [comment]
@johnrichardrinehart Unfortunately, I don't. I tried in many ways to reproduce the issue without any success...

**Comment by johnrichardrinehart** [comment]
In the grand scheme of things that's just fine with me.

Thanks @federico-terzi .
