### ISSUE TITLE
Not working: how can I troubleshoot?

### ISSUE THREAD

**Issue by dan-peterson** [federico-terzi/espanso#165]
I’ve installed espanso using brew on Catalina. Everything seems to be running fine and I’ve enabled the required security settings. 

Unfortunately the expansions aren’t being triggered.

Any suggestions on how I can troubleshoot, and specifically what should I expect to see in the log when running `espanso log`?

**Comment by federico-terzi** [comment]
Hey @dan-peterson,
I'm sorry you are experiencing problems. Firstly, could you please post the output of `espanso log` here?
Secondly, are you sure you didn't accidentaly disabled espanso (try double pressing the Option ALT key)?

Cheers

**Comment by dan-peterson** [comment]
> I'm sorry you are experiencing problems. 

No problem! I was hoping to recreate the problem, but I haven't had issues since. Perhaps it was as simple as an accidental disable, but I'm pretty sure I did check that. :)

Anyways, case closed for now. If it comes up again I'll post the logs.

Great project btw.

**Comment by federico-terzi** [comment]
Great to hear that! Let me know if you have other problems.

Cheers :)
