### ISSUE TITLE
Wrong paste shortcut for urxvt

### ISSUE THREAD

**Issue by maximelouet** [federico-terzi/espanso#166]
Hello,

First of all thank you very much for this wonderful tool!

I'm using `urxvt` and it seems `espanso` cannot correctly paste expansions because the default paste shortcut for `urxvt` is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd>, not <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd>. I saw there were some special conditions here: https://github.com/federico-terzi/espanso/blob/master/src/keyboard/linux.rs#L47, maybe we could add one for `urxvt`?

I just tested to change my `urxvt` paste keyboard shortcut to the more standard <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> and `espanso` was able to expand text, so this is definitely a shortcut issue :slightly_smiling_face:

Thank you for your time!

**Comment by federico-terzi** [comment]
Hey @maximelouet,
Thank you very much for the report! That's strange indeed, I'll definitely take a look at it in the next few days.

Cheers :)

**Comment by federico-terzi** [comment]
Hey @maximelouet,
I examined the problem and it seems like `urxvt` uses Ctrl+Alt+V as the default shortcut. The funny thing was, when I tested it on a VM a couple of months ago it used the standard Ctrl+Shift+V. Turns out the distro I was using (Manjaro i3) redefined the shortcut for the terminal. 

Which distro are you using?

At this point, I'm not sure how to proceed. I could change it to CTRL+ALT+V on urxvt, but that would break espanso for people that remapped the paste shortcut to CTRL+SHIFT+V. What do you think?

Cheers

**Comment by maximelouet** [comment]
Hi @federico-terzi,
I'm using Arch Linux with i3. It's quite strange that Manjaro would redefine the shortcut for `urxvt`.

According to what I found on the Internet (ArchWiki + manjaro forums), the default shortcut is always <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd> for `urxvt`. Maybe Manjaro added the more standard one in addition to this one?

I believe users would not unmap the original <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd> shortcut but rather just add the more standard one (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd>). Removing the original shortcut takes two explicit lines in the `.Xresources` config file.

So I believe the best way to go is to use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>v</kbd> for `urxvt`. This isn't a perfect solution as some users may unmap this keyboard shortcut — but that's not really specific to `urxvt` because `espanso` relies on keyboard shortcuts and users may change them in any case.

Thanks again for your help!

**Comment by federico-terzi** [comment]
Your suggestion sounds absolutely reasonable, I'll make the change in the next release.

Thanks for your help :)
