### ISSUE TITLE
Diacritics and other nonascii entry as HTML converted to UTF-8

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#167]
Well, inputting characters like "áë™§" are a nightmake on many keyboards or OSes.

So, entering e.g. an á can be done by

` - trigger:  :aacute`
`    replace: "&auml;"`
`    htmlentities: yes`

would replace :aacute by á (:aacute is a bit long, but it is just an example).
This prevents nonascii characters in the yaml file.

**Comment by federico-terzi** [comment]
Hey @freebrowser1,
This could be useful indeed. Have you considered trying Unicode escape sequences? I never tried myself, but espanso might support them out of the box. Something like `\u56`.

What do you think?
Cheers

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
