### ISSUE TITLE
macOS install : wrong library

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#168]
I installed Espanso on my Mac running Catalina 15.2 and Homebrew and used the install instructions on the site. But when invoking espanso I got this:

`~/homebrew % espanso --version                                     `
`dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib`
`  Referenced from: /Users/me/homebrew/bin/espanso`
`  Reason: image not found`
`zsh: abort      espanso --version`

The problem is probably that Espanso assumes Homebrew is installed in /usr/local/opt, which is not in my case, it is in my home folder /Users/me .
I had a workaround by symlinking the libssl.1.1.dylib to the correct folder by issuing these two symlink commands (the first as root):

`sudo ln -s  /Users/mehomebrew/Cellar /usr/local/opt`
`ln -s  /Users/me/homebrew/Cellar/openssl@1.1/1.1.1d/lib /Users/me/homebrew/Cellar/openssl@1.1/lib`

Then the problem was fixed.

**Comment by federico-terzi** [comment]
Hey @freebrowser1,
Thanks for your report, I'll definitely take a look at it in the next few days.
The strange thing is that espanso does not assume anything about Homebrew, I just used the default formula. This edge case might need to be handled as well.

Cheers :)

**Comment by federico-terzi** [comment]
Hey @freebrowser1,

In the last version espanso removed its dependency on openssl, so this issue should be solved.
I'm going to close this issue, let me know if you have other questions.

Cheers :)
