### ISSUE TITLE
Native Notification on Windows

### ISSUE THREAD

**Issue by LiHRaM** [federico-terzi/espanso#169]
Hi,

The current notification looks a little out of place on Windows:
![image](https://user-images.githubusercontent.com/25297553/73547785-eee78480-443f-11ea-9e81-c5bae87fd354.png)

It would be nice to get a toast notification instead, which is possible using [winrt](https://github.com/contextfree/winrt-rust/blob/master/examples/toast_notify.rs), for example.

If this is a lower priority for you, I'd love to try setting it up with some guidance.

Great project!

**Comment by federico-terzi** [comment]
Hey @LiHRaM,
Thank you for your interest! Yes I totally agree with you, the current notification doesn't look great. In fact, I initially tried implementing the native one myself, but I couldn't find a way to effectively call the Windows 10 API from Rust, so I focused on other issues.

If you have some suggestions, I would be more than happy to include them :)

If you are willing to try implementing it yourself, you can fork the project and modify the "notify" method here:

https://github.com/federico-terzi/espanso/blob/master/src/ui/windows.rs

Thanks for your help :)

**Comment by federico-terzi** [comment]
Hey,

As I said in the PR, I think we should close this issue now that the new alpha version ships with native Windows notifications out of the box.

Again, thank you for the help!

Cheers :)
