### ISSUE TITLE
Feature request: Edit default.yml with system editor

### ISSUE THREAD

**Issue by GJKrupa** [federico-terzi/espanso#171]
I'd like to request the following feature that goes a step beyond `espanso path`.  Something along the lines of `espanso edit` that opens the default.yml file in the system editor (as defined by $EDITOR/$VISUAL on *nix systems or vi/Notepad as a default) and then automatically reloads the daemon on exit.  Something a bit like `visudo` in effect.

**Comment by federico-terzi** [comment]
Hey @GJKrupa, 

thank you for the suggestion! I was thinking about the same exact thing last week, I'll definitely add it to the roadmap.

Cheers :)
