### ISSUE TITLE
Linux: Autostart Instuctions

### ISSUE THREAD

**Issue by vexillia** [federico-terzi/espanso#176]
Do I need to set this up on Xubuntu?  If so how?  Thanks.

**Comment by vexillia** [comment]
Just rebooted and it seems it's already set up to autostart.  Would appreciate confirmation before closing issue.  Thanks.

**Comment by federico-terzi** [comment]
Hey, 
If your system supports Systemd (and ubuntu generally does), the first time you call "espanso start", you register it as a service and it gets automatically started at system startup. If you want to avoid this behavior, you can call `espanso unregister`.

Cheers

**Comment by vexillia** [comment]
Thanks.  Much appreciated.

**Comment by federico-terzi** [comment]
You're welcome :)

**Comment by owzim** [comment]
@federico-terzi this should be in the docs

**Comment by federico-terzi** [comment]
Hey @owzim,
Do you mean the fact that it automatically setup Systemd to get started at startup?
Cheers

**Comment by owzim** [comment]
Yes. To minimize guess work.

**Comment by federico-terzi** [comment]
All right! I will :)
