### ISSUE TITLE
Failing to compile espanso Package 'dbus-1', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by xplosionmind** [federico-terzi/espanso#1791]
**Describe the bug**
I run into an error while compiling espanso

**To Reproduce**
1. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. `sudo dnf install @development-tools gcc-c++ wl-clipboard libxkbcommon-devel dbus-devel wxGTK-devel.x86_64`
3. `sudo dnf groupinstall "Development Tools"`
4. `cargo install --force cargo-make`
5. `git clone https://github.com/federico-terzi/espanso ~/dev/espanso`
6. `cargo make --profile release --env NO_X11=true build-binary`

**Expected behavior**
The build should be successful

**Logs**
```
cargo make --profile release --env NO_X11=true build-binary 
[cargo-make] INFO - cargo make 0.37.5
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: build-binary
[cargo-make] INFO - Profile: release
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: build-binary
[cargo-make] INFO - Execute Command: "rust-script" "/home/tommi/dev/espanso/target/_cargo_make_temp/persisted_scripts/AE24A9C9DA1530FD32A6A950627773A335A7E66D0F0BC1C10905E91DB7CA6072.rs"
Using profile: Release
Using Wayland feature
Calling with args: ["build", "--release", "--manifest-path", "espanso/Cargo.toml", "-p", "espanso", "--no-default-features", "--features", "wayland modulo vendored-tls"]
   Compiling num_cpus v1.13.0
   Compiling getrandom v0.1.16
   Compiling time v0.1.44
   Compiling mio v0.8.6
   Compiling socket2 v0.4.9
   Compiling ring v0.16.20
   Compiling nix v0.24.2
   Compiling getrandom v0.2.2
   Compiling string_cache v0.8.1
   Compiling wayland-sys v0.29.5
   Compiling wayland-client v0.29.5
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling serde_json v1.0.62
   Compiling libdbus-sys v0.2.1
   Compiling flate2 v1.0.20
   Compiling toml v0.5.8
error: failed to run custom build command for `libdbus-sys v0.2.1`

Caused by:
  process didn't exit successfully: `/home/tommi/dev/espanso/target/release/build/libdbus-sys-b4a1ba7ee2078c01/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DBUS_1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=DBUS_1_STATIC
  cargo:rerun-if-env-changed=DBUS_1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/tommi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libdbus-sys-0.2.1/build.rs:6:70:
  called `Result::unwrap()` on an `Err` value: Failure { command: "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=\"1\" PKG_CONFIG_ALLOW_SYSTEM_LIBS=\"1\" \"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'dbus-1', required by 'virtual:world', not found\nPackage 'dbus-1', required by 'virtual:world', not found\n" } }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at /home/tommi/dev/espanso/target/_cargo_make_temp/persisted_scripts/AE24A9C9DA1530FD32A6A950627773A335A7E66D0F0BC1C10905E91DB7CA6072.rs:101:5:
cargo build failed
stack backtrace:
   0:     0x560bb37ac8dc - <unknown>
   1:     0x560bb37cf89c - <unknown>
   2:     0x560bb37aa50e - <unknown>
   3:     0x560bb37ac6c4 - <unknown>
   4:     0x560bb37ae2b3 - <unknown>
   5:     0x560bb37adfd4 - <unknown>
   6:     0x560bb37ae835 - <unknown>
   7:     0x560bb37ae6e6 - <unknown>
   8:     0x560bb37ace06 - <unknown>
   9:     0x560bb37ae482 - <unknown>
  10:     0x560bb3787355 - <unknown>
  11:     0x560bb3789267 - <unknown>
  12:     0x560bb3787b43 - <unknown>
  13:     0x560bb3787b59 - <unknown>
  14:     0x560bb37a70eb - <unknown>
  15:     0x560bb37893d5 - <unknown>
  16:     0x7f4bafbee14a - __libc_start_call_main
  17:     0x7f4bafbee20b - __libc_start_main_impl
  18:     0x560bb3787a75 - <unknown>
  19:                0x0 - <unknown>
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.
```

**Setup information**
- OS: Fedora 39
- Version: trying to build from master branch

**Comment by AucaCoyan** [comment]
Hi! Thanks for submitting the issue.
there is an open PR #1695 that updates the doc for Fedora. Can you try it and tell me if it works?

I use windows and Federico too, I believe another dev uses Debian, so we are missing people for the hat-distro here 😢

**Comment by xplosionmind** [comment]
Thanks for your reply, @AucaCoyan! Unfortunately, as you can see there is very little difference between the steps I followed and the one indicated in the PR you mentioned.

The compilation still fails… Maybe @eclipseo could help?

**Comment by cives** [comment]
I am having the same problem once and again, also in Fedora 39, with Wayland. My issue is the same as the one described by @xplosionmind.
Everything goes smooth until the very last moment:

warning: be sure to add `/home/antoniosp/.cargo/bin` to your PATH to be able to run the installed binaries
[cargo-make] INFO - Execute Command: Command {
    program: "rust-script",
    args: [
        "rust-script",
        "/tmp/antoniosp/fsio/ZpjEeTKgwE.rs",
    ],
    stdin: Some(
        Inherit,
    ),
    stdout: Some(
        Inherit,
    ),
    stderr: Some(
        Inherit,
    ),
    create_pidfd: false,
}
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.

**Comment by AucaCoyan** [comment]
Mmmm, this is a wild guess but...
Since I saw `rust-script` failed, maybe the script it's executing is failing. I don't know where rust-scipt executes that, or where in the codebase is rust-script relevant, but I lookup in the documentation of rust-script and found [that maybe we need to add a shebang to the script in case it's running on linux](https://github.com/fornwall/rust-script/issues/57).
Again, this doesn't explain why it compiles on Ubuntu but not on Fedora, but it's something to look up

**Comment by cives** [comment]
I solved the problem with the compilation of espanso in Fedora 39, both with X11 as with Wayland.
It seems that the executable of .cargo/bin was not being added to the $PATH route, no matter how many times I had tried.
Once I realized what the problem was, I retried adding it to the $PATH until I checked that the cargo executable had been correctly added, checking with echo $PATH.
Then, the compilation was smooth.
I don't know why it wasn't added, because I copypasted the same instructions (export PATH=/home/myusername/.cargo/bin:$PATH) once and again until it remained in the $PATH. Otherwise, I am not sure if I did something else wrong. But, definitely, it's now working.

**Comment by AucaCoyan** [comment]
Horray!
That is weird. Do you see anything we can do from the source code to prevent it from happening?

**Comment by cives** [comment]
I am not very savvy regarding this subject, and I probably made some
mistake somewhere I am not aware of. So I cannot really tell you.
But I do appreciate your readiness to help.
I wanted mostly to leave track of my experience, because I have seen some
more people with exactly my same problem. Maybe this could be the reason.
Just in case.
Thank you and best regards.
Antonio

**Comment by AucaCoyan** [comment]
> `cargo install --force cargo-make`

On Windows, I had trouble by installing the latest cargo-make (0.37.8), but version 0.34 compiled correctly.
Maybe that?

**Comment by cives** [comment]
No idea.  I don't use Windows long ago.

**Comment by AucaCoyan** [comment]
> No idea.  I don't use Windows long ago.

No, sorry. I meant that @xplosionmind ran:

> cargo install --force cargo-make

which personally caused me problems in another OS (Windows). I was wondering if we lock down the version is any improvement seen

**Comment by AucaCoyan** [comment]
I'm currently in a VM with Debian and trying to compile espanso in wayland throws the same error. I don't think it is a problem of fedora, but a dependencies problem
running `cargo make build-binary --env NO_X11=true --profile release` throws and error of `pkg-config`. In which you can manually test it on the shell with
```bash
PKG_CONFIG_ALLOW_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 pkg-config --libs --cflags dbus-1 dbus-1 >=1.6
```

This first fails trying to find `dbus`, so according to [this stackoverflow](https://stackoverflow.com/questions/15239560/d-bus-linking-issue) I installed the dependency with
```bash
sudo apt install libdbus-glib-1-dev
```
You can check the stackoverflow link to find instructions for fedora

After I did that, `cargo make ...` works! ... aaaaaand it fails again with
```
cargo:warning=src/evdev/native.cpp:49:10: fatal error: xkbcommon/xkbcommon.h: No such file or directory
  cargo:warning=   49 | #include "xkbcommon/xkbcommon.h"
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1
```

**Comment by AucaCoyan** [comment]
I was the dependencies again 🤣 
I don't know why, but we need to install X11 deps to compile in Wayland 🤔 . After I ran 
```
sudo apt install libx11-dev libxtst-dev libxkbcommon-dev libdbus-1-dev libwxgtk3.2-dev
```
(ubuntu 22.04 or later, tested in Debian 12)
It compiled sucesfully 🎉 !
Can you try it? If this works, we can update the readme

**Comment by cives** [comment]
Thank you. I finally decided to go back to X11 by now, and I compiled it
properly.
Wayland already works quite well, except for some issues, such as nVidia
graphic cards and, as in this case, compiling cargo for espanso.

**Comment by cives** [comment]
I will be out of home for a few days, in hospital. I can try after that.

**Comment by AucaCoyan** [comment]
> I will be out of home for a few days, in hospital. I can try after that.
> 

I hope everything is going well!

**Comment by cives** [comment]
Thank you!

**Comment by AucaCoyan** [comment]
Hello @xplosionmind , did you tried to compile it again recently? had the same error?

**Comment by xplosionmind** [comment]
Hi @AucaCoyan, thanks for the ping!

Hoorray! I managed to compile espanso with the current state of the repository, following the exact steps in the docs! 🚀

Now I’d like to figure out how to create a `.rpm` package, but at least this issue can be closed, now.

**Comment by AucaCoyan** [comment]
Excellent!
