### ISSUE TITLE
Have to type each trigger twice

### ISSUE THREAD

**Issue by januz** [federico-terzi/espanso#1799]
**Describe the bug**
When I type a trigger once (e.g., `:espanso`), the entered text get deleted and not replaced. If I type the sequence again, it is successfully replaced.

**To Reproduce**
1. see "Describe the bug"

**Expected behavior**
replacement should work when I type the sequence once.

**Screenshots**
N/A

**Logs**
```
15:36:24 [daemon(16138)] [INFO] reading configs from: "/Users/januz/.config/espanso"
15:36:24 [daemon(16138)] [INFO] reading packages from: "/Users/januz/.config/espanso/match/packages"
15:36:24 [daemon(16138)] [INFO] using runtime dir: "/Users/januz/Library/Caches/espanso"
15:36:24 [daemon(16138)] [INFO] system info: Darwin v14.2.1 - kernel: 23.2.0
15:36:24 [daemon(16138)] [INFO] espanso version: 2.2.1
15:36:24 [daemon(16138)] [INFO] watching for changes in path: "/Users/januz/.config/espanso"
15:36:24 [daemon(16138)] [INFO] spawning the worker process...
15:36:24 [daemon(16138)] [INFO] binded to IPC unix socket: /Users/januz/Library/Caches/espanso/espansodaemonv2.sock
15:36:24 [worker(16139)] [INFO] reading configs from: "/Users/januz/.config/espanso"
15:36:24 [worker(16139)] [INFO] reading packages from: "/Users/januz/.config/espanso/match/packages"
15:36:24 [worker(16139)] [INFO] using runtime dir: "/Users/januz/Library/Caches/espanso"
15:36:24 [worker(16139)] [INFO] system info: Darwin v14.2.1 - kernel: 23.2.0
15:36:24 [worker(16139)] [INFO] using CocoaAppInfoProvider
15:36:24 [worker(16139)] [INFO] binded to IPC unix socket: /Users/januz/Library/Caches/espanso/espansoworkerv2.sock
15:36:24 [worker(16139)] [INFO] using CocoaSource
15:36:24 [worker(16139)] [INFO] monitoring the status of secure input
15:36:24 [worker(16139)] [INFO] monitoring the status of the daemon process
15:36:24 [worker(16139)] [INFO] using MacInjector
15:36:24 [worker(16139)] [INFO] using CocoaClipboard
```

**Setup information**
- OS: Mac OS X 14.2.1
- Version: 2.2.1

**Comment by januz** [comment]
I found this [Reddit thread](https://www.reddit.com/r/espanso/comments/11jbpri/replacement_only_works_from_the_2nd_time/) describing the same issue but without a solution. The difference for me is that it happens every single time, not only after not using the app for a while.

**Comment by smeech** [comment]
Is this the same in all editors/shell etc.?
Have you tried different methods for replacing (i.e. `force_mode: clipboard|keys` in the trigger, or different `backend` [setting](https://espanso.org/docs/configuration/options/) in $CONFIG/config/default.yml), or a different `_delay` setting?

**Comment by januz** [comment]
@smeech Thanks for your suggestions! Setting

```yaml
backend: Clipboard
```

seems to work! 

```yaml
backend: Inject
```

causes issue.

Sorry, I should have played with the options before asking. Are there any specific reasons that the `Inject` method wouldn't work?

**Comment by smeech** [comment]
Not that I'm aware of. I mostly have to use `Clipboard` and `x11_use_xclip_backend`, except for my terminal (`Inject`, reverting to `Clipboard` for very long expansions).
