### ISSUE TITLE
Replacement doesn't work correctly on Kate ``` python  

### ISSUE THREAD

**Issue by moshpirit** [federico-terzi/espanso#1800]
In my base.yml file I added:

``` yaml
  - trigger: ";P"
    replace: "``` python  \n$|$\n ```"
```
But it replaces it with `;P```` python` in some editor like Kate or Micro on Archlinux with KDE/Plasma (X11). Using Espanso 2.1.8.

LOG:

``` 
17:58:25 [daemon(82055)] [INFO] reading configs from: "/home/username/.config/espanso"
17:58:25 [daemon(82055)] [INFO] reading packages from: "/home/username/.config/espanso/match/packages"
17:58:25 [daemon(82055)] [INFO] using runtime dir: "/home/username/.cache/espanso"
17:58:25 [daemon(82055)] [INFO] system info: Arch Linux v - kernel: 6.6.8-arch1-1
17:58:25 [daemon(82055)] [INFO] watching for changes in path: "/home/username/.config/espanso"
17:58:25 [daemon(82055)] [INFO] espanso version: 2.1.8
17:58:25 [daemon(82055)] [INFO] spawning the worker process...
17:58:25 [daemon(82055)] [INFO] binded to IPC unix socket: /home/username/.cache/espanso/espansodaemonv2.sock
17:58:25 [worker(82063)] [INFO] reading configs from: "/home/username/.config/espanso"
17:58:25 [worker(82063)] [INFO] reading packages from: "/home/username/.config/espanso/match/packages"
17:58:25 [worker(82063)] [INFO] using runtime dir: "/home/username/.cache/espanso"
17:58:25 [worker(82063)] [INFO] system info: Arch Linux v - kernel: 6.6.8-arch1-1
17:58:25 [worker(82063)] [INFO] binded to IPC unix socket: /home/username/.cache/espanso/espansoworkerv2.sock
17:58:25 [worker(82063)] [INFO] using X11AppInfoProvider
17:58:25 [worker(82063)] [INFO] monitoring the status of the daemon process
17:58:25 [worker(82063)] [INFO] using X11Source
17:58:25 [worker(82063)] [INFO] using X11ProxyInjector
17:58:26 [worker(82063)] [INFO] using X11Clipboard
```

**Comment by smeech** [comment]
Can you try adding the line: `force_mode: clipboard` to your code, please? I.e.:
```
  - trigger: ";P"
    replace: "``` python  \n$|$\n ```"
    force_mode: clipboard
```

**Comment by moshpirit** [comment]
It does solve it! thanks!! Is there any reason why isn't this a default option? I think I'd like to have it as a default for at least the `$|$` commands

**Comment by smeech** [comment]
You can set it as the default for everything with the [line](https://espanso.org/docs/configuration/options/#options-reference) in your `default.yml` file, which is what I do, as the only place where it's not so useful for me is my terminal emulator for which I have an [app-specific file](https://espanso.org/docs/configuration/app-specific-configurations/) specifying `backend: Inject`. Even there, `force_mode: clipboard` works better for very long individual expansions.

**Comment by moshpirit** [comment]
It does solve it! thanks!! Is there any reason why isn't this a default option? I think I'd like to have it as a default for at least the `$|$` commands

**Comment by smeech** [comment]
I don't know. The [docs](https://espanso.org/docs/configuration/options/#options-reference) indicates there are pros and cons of both mechanisms, but doesn't explain what they are.

**Comment by moshpirit** [comment]
Oops! Sorry, I really shouldn't have sent this last comment. It was by mistake, I already sent that. Thank you so much for replying every time, and sorry for the bother!! :pray:

**Comment by smeech** [comment]
No worry - I've closed the issue anyway.
