### ISSUE TITLE
MacOS brew installation docs should be updated

### ISSUE THREAD

**Issue by jborbik** [federico-terzi/espanso#1804]
According to the instructions here: https://espanso.org/docs/install/mac the set up over brew should be done over a custom tap. In meantime espanso became available over [brew cask](https://github.com/Homebrew/homebrew-cask/blob/287f1f338d503afc206c4a24fbf4e00aae06d327/Casks/e/espanso.rb) so the custom tap is not needed anymore.

Docs should be updated to reflect that.

**Comment by smeech** [comment]
Done. Thank you.

**Comment by flniu** [comment]
Does brew installation only support Mac Intel, not support Mac M1?

**Comment by jborbik** [comment]
M1 supports any Intel binaries through the Rosetta translation layer. Rosetta is used automatically if needed.

**Comment by dcchambers** [comment]
@flniu Espanso has native builds for both intel and arm (M-series) macs.
