### ISSUE TITLE
Cinnamon Icon

### ISSUE THREAD

**Issue by antonellosalis** [federico-terzi/espanso#1808]
**Describe the bug**
Just installed in Debian stable with Cinnamon, using the deb package and following your instructions. 
Unfortunately, it seems that the icon is not in the bar.
Also tried to restart the DE.

**To Reproduce**
1.
espanso start

**Expected behavior**
Icon appears in the bar together with other apps correctly running

**Logs**
12:52:00 [daemon(60933)] [INFO] reading configs from: "/home/antonello/.config/espanso"
12:52:00 [daemon(60933)] [INFO] reading packages from: "/home/antonello/.config/espanso/match/packages"
12:52:00 [daemon(60933)] [INFO] using runtime dir: "/home/antonello/.cache/espanso"
12:52:00 [daemon(60933)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.10.0-27-amd64
12:52:00 [daemon(60933)] [INFO] espanso version: 2.2.1
12:52:00 [daemon(60933)] [INFO] spawning the worker process...
12:52:00 [daemon(60933)] [INFO] binded to IPC unix socket: /home/antonello/.cache/espanso/espansodaemonv2.sock
12:52:00 [daemon(60933)] [INFO] watching for changes in path: "/home/antonello/.config/espanso"
12:52:00 [worker(60953)] [INFO] reading configs from: "/home/antonello/.config/espanso"
12:52:00 [worker(60953)] [INFO] reading packages from: "/home/antonello/.config/espanso/match/packages"
12:52:00 [worker(60953)] [INFO] using runtime dir: "/home/antonello/.cache/espanso"
12:52:00 [worker(60953)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.10.0-27-amd64
12:52:00 [worker(60953)] [INFO] binded to IPC unix socket: /home/antonello/.cache/espanso/espansoworkerv2.sock
12:52:00 [worker(60953)] [INFO] monitoring the status of the daemon process
12:52:00 [worker(60953)] [INFO] using X11AppInfoProvider
12:52:00 [worker(60953)] [INFO] using X11Source
12:52:00 [worker(60953)] [INFO] using X11ProxyInjector
12:52:02 [worker(60953)] [INFO] using X11Clipboard
12:52:02 [worker(60953)] [ERROR] Unable to show notification: No such interface “org.freedesktop.Notifications” on object at path /org/freedesktop/Notifications
12:52:42 [service(62201)] [INFO] reading configs from: "/home/antonello/.config/espanso"
12:52:42 [service(62201)] [INFO] reading packages from: "/home/antonello/.config/espanso/match/packages"
12:52:42 [service(62201)] [INFO] using runtime dir: "/home/antonello/.cache/espanso"
12:52:42 [service(62201)] [INFO] system info: Debian GNU/Linux v11 - kernel: 5.10.0-27-amd64
12:52:42 [service(62201)] [INFO] espanso is running

**Setup information**
- OS: Deabian stable
- Version: espanso 2.2.1

**Comment by smeech** [comment]
The Linux version of Espanso has never had an icon. See [here](https://espanso.org/docs/configuration/options/#hiding-the-icon), [here](https://espanso.org/docs/configuration/options/#customizing-the-search-bar) and the text associated with `show_icon` below it in [Options reference](https://espanso.org/docs/configuration/options/#options-reference).
I agree, it would be nice to have one, to access the settings, and perhaps show the current status.
Duplicate of #1512

**Comment by antonellosalis** [comment]
Thank you!
