### ISSUE TITLE
Add a SECURITY.md file to the repo

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#182]
A few users suggested me to add a documentation page about security, describing the espanso security model, as well as an official way to report me security disclosures.
I'll do my best to add the file in one of the next releases.

**Comment by d1koder** [comment]
hello

**Comment by federico-terzi** [comment]
Hey guys,
The overview is now available here: [https://github.com/federico-terzi/espanso/blob/master/SECURITY.md](https://github.com/federico-terzi/espanso/blob/master/SECURITY.md)

Let me know if you need other clarifications.

Cheers :)
