### ISSUE TITLE
Having trouble compiling espanso on my laptop

### ISSUE THREAD

**Issue by mansmohaali** [federico-terzi/espanso#1820]
Hello, there i am having issue compiling the espanso project,
This is my hardware and software:
     Host: Inspiron 15 7000 Gaming
     Kernel: 6.6.12-1-lts
     Shell: bash 5.2.26
     DE: Plasma 5.27.10

Here is the terminal output i am getting:
error: failed to run custom build command for `espanso-modulo v0.1.0 (/home/mansarchy/Downloads/espanso/espanso-modulo)`

Caused by:
  process didn't exit successfully: `/home/mansarchy/Downloads/espanso/target/release/build/espanso-modulo-4a821170bfeaeec1/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at espanso-modulo/build.rs:462:5:
  wxWidgets is not installed, as `wx-config` cannot be executed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at /tmp/mansoor/fsio/ifF3V98d8e.rs:101:5:
cargo build failed
stack backtrace:
 0:     0x63e41af02cfc - <unknown>
   1:     0x63e41af26090 - <unknown>
   2:     0x63e41af00fdf - <unknown>
   3:     0x63e41af02ae4 - <unknown>
   4:     0x63e41af04617 - <unknown>
   5:     0x63e41af0437f - <unknown>
   6:     0x63e41af04a98 - <unknown>
   7:     0x63e41af04949 - <unknown>
   8:     0x63e41af031c6 - <unknown>
   9:     0x63e41af046e2 - <unknown>
  10:     0x63e41aedf385 - <unknown>
  11:     0x63e41aee12c3 - <unknown>
  12:     0x63e41aedfb83 - <unknown>
  13:     0x63e41aedfbb9 - <unknown>
  14:     0x63e41aefdb57 - <unknown>
  15:     0x63e41aedfbae - <unknown>
  16:     0x750fffb37cd0 - <unknown>
  17:     0x750fffb37d8a - __libc_start_main
  18:     0x63e41aedfaa5 - <unknown>
  19:                0x0 - <unknown>
[cargo-make] ERROR - Unable to execute rust code.
[cargo-make] WARN - Build Failed.

Thank you for helping me.

**Comment by mansmohaali** [comment]
I am using Wayland btw.

**Comment by morgan-dgk** [comment]
Do you have the relevant version of wxwidgets-gtk3 installed as per the [docs](https://espanso.org/docs/install/linux/#wayland-compile)?

**Comment by AucaCoyan** [comment]
On windows, it gave me the same error by using `cargo-make` version 0.37.8 instead of 0.34
Can you double check the correct version of cargo-make?

**Comment by mansmohaali** [comment]
Hello @AucaCoyan , thank you for the response.
I checked the version of cargo-make and it is the 0.34 i am using and install on my system. I am pretty sure/confident of my previous statement, explanation below.

I could find a direct way to check the version of cargo-make, but when i typed cargo-make in my terminal emulator is got this:
cargo-make
thread 'main' panicked at /home/mansarchy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-make-0.34.0/src/lib/cli.rs:156:21:
cargo-make not invoked via cargo command.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I concluded from the path line ".../cargo-make-0.34/..." that is have the correct version.

**Comment by mansmohaali** [comment]
Hello @morgan-dgk, I read the installation wiki but there is nothing for arch user except having:
1. rust and its tools
2. cargo-make-0.34

The list of dependencies to install are for Debian/Ubuntu and fedora users.
However i am using arch. 

Unless there are steps missing for arch user or i couldn't find, i am stuck here.

**Comment by morgan-dgk** [comment]
@mansmohaali I am also on arch, and from memory I did have to install wxwidgets-gtk3. There is no arch specific build target, so I would assume the same dependency need to be satisfied when building on arch. See also the dependencies included with the [AUR package](https://aur.archlinux.org/packages/espanso-wayland), which include wxwidgets-gtk3. 

Hope this helps!

**Comment by mansmohaali** [comment]
Thank you so mush @morgan-dgk, it works now. I am able  to make my own matches and so with all the app i have try the espanso tool work accordingly.
I have add a lot of warning during compilation, such as:
-  warning to get the latest version of cargo-make instead of the 0.34 espanso want us to use
-  warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0, html5ever v0.25.1, nom v6.1.2, xml5ever v0.16.1
- note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
- and a lot of warning;
The output of the compilation is attached below it contains all the warnings.
I tried to make sense of them, i am stuck, still new to rust and compiling from source.

The first line is the command to compile.

Thank you again.

[espanso_compilation_output_01_29_2024.txt](https://github.com/espanso/espanso/files/14080121/espanso_compilation_output_01_29_2024.txt)

**Comment by AucaCoyan** [comment]
Hi! Yes, all of that output is expected. Obviously is not there by design, but we are currently updating dependencies and build tools as we go.
- I have a cargo-make PR on the way, still on the works.
- I tried to update the deprecated packages yesterday and updated correctly, I only need to update the changes into a PR
- The rest of the warnings are all coming from C++ code, in which I'm a complete noob, so that I cannot help yet.

Some things are taken care of, but we still have loads of work to do. Don't worry if you are new to the language! We have contributors of all coding knowledge. I also read a couple of chapters of the rust book (not even half!) and started to hack in another open project. I learned much in the way!

Tag me if you need any help with anything 😄 
Only one question remaining: I assume the issue can be closed successfully, right?

**Comment by mansmohaali** [comment]
Thank you so much with all the help @morgan-dgk, @smeech, @mattn and @AucaCoyan.

Definitely @AucaCoyan, will do.

The issue is currently close.

**Comment by mansmohaali** [comment]
Amazing people :superhero:.
