### ISSUE TITLE
Espanso doesn't run on Windows 10 (Antivirus issue?)

### ISSUE THREAD

**Issue by sleerash** [federico-terzi/espanso#183]
Hi,

First things first: I love Espanso. I use it for about a month. Two days ago, I changed my antivirus software from Kaspersky to Bitdefender, and... to my dissapointment, Espanso does not run. 
It installs without problems, but when I run it it simply doesn't start.
The strange thing is that I do tried to uninstall Bidefender and reinstall Espanso, but then Espanso didn't run either.
 What can I do?

Best regards from Spain,
JMB

**Comment by federico-terzi** [comment]
Hey @sleerash,
Thanks for the kind words! Yep, that's probabily Bitdefender trying to stop espanso from working. I'm not experienced with that Antivirus, but you could try adding espanso to the list of exceptions: https://www.bitdefender.com/consumer/support/answer/13427/

Notice that espanso is located in `C:\Users\Freddy\AppData\Local\Programs\espanso\espanso.exe`
(remember to replace Freddy with your name)

Let me know if that helps

Cheers

**Comment by sleerash** [comment]
Hey, Federico,
Thanks for your kind and fast reply, but... alas, it is not working. I don't even think that Bitdefender it's blocking Espanso, but something is definitively doing it, and I have no idea what it is.
:(
Thanks anyway.

**Comment by sleerash** [comment]
Hi again...
Don't ask me how, but I managed to run the program. I created a ".espanso" directory, and run the espanso.exe in the original folder.
I just don't know how it worked, but it did.

I copy the log, by the way:

22:37:55 [ INFO] espanso version 0.5.0
22:37:55 [ INFO] using config path: C:\Users\jose_\AppData\Local\Programs\espanso\.espanso
22:37:55 [ INFO] using package path: C:\Users\jose_\AppData\Local\espanso\packages
22:37:55 [ INFO] starting daemon...
22:37:55 [ INFO] Initializing Espanso resources in C:\Users\jose_\AppData\Local\espanso
22:37:55 [ INFO] BMP already initialized, skipping.
22:37:55 [ INFO] ICO already initialized, skipping.
22:37:55 [ INFO] espanso is running!
22:37:55 [ INFO] Binded to IPC tcp socket: 127.0.0.1:34982

WTF?

**Comment by sleerash** [comment]
And finally, although Espanso appears as active, substitutions do not work :(. Sorry for the trouble, btw.

**Comment by sleerash** [comment]
Hi, @federico-terzi,

Thank you I really appreciate your effort!

**Comment by federico-terzi** [comment]
Hey,
Unfortunately, I wasn't able to find anything useful to solve this issue... If someone discovers a new way to mitigate the problem, please reopen the issue
