### ISSUE TITLE
Compile error on aarch64-darwin

### ISSUE THREAD

**Issue by n8henrie** [federico-terzi/espanso#1832]
**Describe the bug**

Espanso isn't compiling from source on my M1 Mac anymore. Have compiled espanso a number of times previously. It seems to be having difficulty compiling 2.1.8 as well now (fails the first attempt and successfully compiles only on a subsequent attempt -- race condition?) which previously compiled without a hitch, so I wonder if one of the macOS point upgrades changed something?

Would love input from others on aarch64-darwin.

```console
$ sw_vers
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
$ rustc --version
rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)
$ cargo make --version
cargo-make 0.34.0
$ rust-script --version
rust-script 0.7.0
```

**To Reproduce**

1. `cargo make build-macos-arm-binary`

Build log: https://gist.github.com/n8henrie/ea694c27a278ca4872a44242af0580ad 

**Expected behavior**

Build should succeed.

I've disabled sccache and removed my `.cargo/config.toml` to minimize confounding variables.

I am using a nix-derived toolchain, but the same toolchain was previously compiling espanso without issues.

```console
$ type -p cargo rustc gcc g++
/run/current-system/sw/bin/cargo
/run/current-system/sw/bin/rustc
/usr/bin/gcc
/usr/bin/g++
```

**Setup information**
- OS: What OS are you using? aarch64-darwin as per above
- Version: which version of Espanso are you running? current master:

```
$ git rev-parse HEAD
b421bcf73fa13506938d62425459d6c16c6a8d0a
```

**Comment by n8henrie** [comment]
I'm back to suspecting some kind of race condition.

If I run the compilation in a loop, it eventually succeeds:

```
$ cargo clean
$ until cargo make build-macos-arm-binary; do sleep 1; done
...
fails several times
...
  Compiling espanso v2.2.1 (/Users/n8henrie/git/espanso/espanso)
    Finished dev [unoptimized + debuginfo] target(s) in 23.78s
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0, html5ever v0.25.1, xml5ever v0.16.1
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
[cargo-make] INFO - Build Done in 30.10 seconds.
```

Also, as of yesterday GitHub has (free) Apple Silicon runners for open source applications, perhaps I can help adapt the GitHub Actions to use them (and thereby remove some of the "workarounds" referenced in the `build.rs` files).

**Comment by AucaCoyan** [comment]
Hello! Sorry for the late response, this is a very weird build issue. Sadly, I don't have a mac to help you.
If it's not too much to ask, can you try to compile it with the latest rust version 1.77?
Currently I'm having issues with clippy at #1917 . Work in progress!

**Comment by n8henrie** [comment]
Seems to be working now, thanks for checking in!

**Comment by AucaCoyan** [comment]
Amazing!
