### ISSUE TITLE
Espanso Wayland Turkish F keyboard problem

### ISSUE THREAD

**Issue by snsrkn** [federico-terzi/espanso#1835]
Espanso Wayland doesn't replace with Turkish F keyborad.

It works when I change keyboard to US. 

I cannot find the right layout for the Turkish F keyboard. I tried: 

layout: tr
variant: trf, tr_f, crh_f, f, F, Turkish F 

but none of them worked.

**Setup information**
- OS: Arch Linux
- Version: 2.2.1

**Comment by snsrkn** [comment]
Sorry, I'm an idiot.
It wal all about the indentation of the yaml. There should be two spaces before "variant" row. I've tried without space, with tab but I did not think to try with two spaces. 

I apologize very much. 
Problem solved. Actually there was no such a problem.

**Comment by morgan-dgk** [comment]
@smeech this looks good to close.

**Comment by smeech** [comment]
No problem!
