### ISSUE TITLE
Operation not permitted by the OS (application error code: 100001).

### ISSUE THREAD

**Issue by acanton77** [federico-terzi/espanso#1839]
**Describe the bug**
Espanso will not load on macOS Sonoma 14.3 on a 2 year old Mac Air laptop

**To Reproduce**
1.

**Expected behavior**
It used to work... but now it does not since upgrade to 14.3.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

I can open the YAML file but have no idea what to change!

**Comment by smeech** [comment]
Any error message?
Anything in the log?

**Comment by acanton77** [comment]
I'm pretty sure it had to do with iCloud which is where I had the Espanso yaml file. I took the Espanso stuff off of iCloud and moved it to Microsoft OneDrive, changed the symbolic link... and now it works just fine on all my computers. There is some issue with Apple M1 on MacAir, Sonoma, iCloud, and Espanso and I'm sure it on the iCloud side... because compared to OneDrive (and maybe Dropbox) iCloud sucks!!!   - Al

**Comment by smeech** [comment]
That's odd - this is the first Issue where iCloud has been a problem. Not that OneDrive is always better!
I'll close this for now, as I don't think it can be fixed in Espanso, but will be happy to reopen it if necessary.
I'm glad to hear you found a solution.

**Comment by acanton77** [comment]
iCloud has a lot of issues with 3rd party apps that want to 'connect' to it. I know several programs, like BBEdit strongly suggests that you use Dropbox and not iCloud for sharing of settings although I still use iCloud because I don't trust the security/privacy of DropBox.  To bad I can't put the Espanso stuff on my web server and 'share' it from there!
