### ISSUE TITLE
user/*.yml loaded, parsed but not applied

### ISSUE THREAD

**Issue by owzim** [federico-terzi/espanso#184]
Hi,

outstanding software. One can feel the passion, dedication and attention to detail in the way espanso works, is presented on its website and so on ... Thank you!

I want to categorize my expansions in multiple files. For example I created a `user/mail.yml` with the same structure as the `default.yml`, but the containing replacements do not work.

I can verify the the file is loaded by deliberately placing faulty yaml syntax into it. Then espanso complains when executing `espanso restart`

Is there something I am missing? All custom replacements in `default.yml` work just fine.

I am on Pop!_OS 19.10 and installed it with the ubuntu/debian deb-file instructions.

Thanks in advance!

Cheers!

**Comment by federico-terzi** [comment]
Hey @owzim,

Thank you for the kind words! I totally understand your point, as I split my matches on multiple files as well to organize them better. 

The first step is to create your additional config files in the `user/*` directory as you did. The important thing to keep in mind is to add the `parent: default` parameter, which tells espanso to merge the current matches in the `default.yml` ones.

Here's an example of my `user/emails.yml` file:

```yaml
name: emails
parent: default

matches:
  - trigger: ":reg"
    replace: |
        Best Regards,
        Federico Terzi
```

Let me know if you have other dubts.

Cheers :)

**Comment by owzim** [comment]
Thanks! That works like a charm. Is this mentioned in the docs somewhere? Can't find it. Additionally, why is the `parent: default' declaration necessary? Does not seems intuitive to me. Since it does not depend on or inherits from the `default.yml` at all. It's separate.

**Comment by federico-terzi** [comment]
Hey @owzim,
Now that you've pointed it out, I realized I never wrote anything about it in the docs!
I'll try to add a few instructions as soon as I have some time.

> Additionally, why is the `parent: default` declaration necessary? Does not seems intuitive to me. Since it does not depend on or inherits from the `default.yml` at all. 

I understand that without any explanation it could look strange. In a nutshell, espanso merges all children matches into their parent at startup, and declaring `parent: default` indicates that the following matches should be merged into the `default.yml` file.

It doesn't set `parent: default`by default as configs in the `user/*` directory can also be used for app-specific configurations, which must be separate to the default one.

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm closing the issue as I added a [section](https://espanso.org/docs/configuration/#organizing-matches) to the docs.
Cheers :)

**Comment by atika** [comment]
I was going to create an issue about this as I encountered the same problem. It's not explicit that we have to insert this option and the other usage other than `parent: default` is not documented.

I haven't tried it but I think that's it:

```shell
# ./user/telegram.yml
filter_title: "Telegram"

matches:
  - trigger: ":ok"
    replace: "👍"

# ./user/another.yml
parent: telegram

matches:
  - trigger: ":lol"
    replace: "😂"
```
It could be great to add an additional example, even small.

**Comment by federico-terzi** [comment]
> I was going to create an issue about this as I encountered the same problem. It's not explicit that we have to insert this option and the other usage other than `parent: default` is not documented.
> 
> I haven't tried it but I think that's it:
> 
> ```shell
> # ./user/telegram.yml
> filter_title: "Telegram"
> 
> matches:
>   - trigger: ":ok"
>     replace: "👍"
> 
> # ./user/another.yml
> parent: telegram
> 
> matches:
>   - trigger: ":lol"
>     replace: "😂"
> ```
> 
> It could be great to add an additional example, even small.

There is a [small example](https://espanso.org/docs/configuration/#organizing-matches) in the docs, but not for this particular case. 

I'll make sure to document it #274 :)
