### ISSUE TITLE
Multiline Strings Missing Lines

### ISSUE THREAD

**Issue by finnito** [federico-terzi/espanso#185]
Hi!

This tool is amazing, thank you for all your work Federico!

I am having issues with multi-line strings. Espanso expands my trigger but doesn't give me the full replacement. Here is some info:

MacOS Catalina 10.15.2

```
espanso --version
espanso 0.5.0
```

My replacement:

```yaml
  - trigger: ":student"
    replace: |
              Hi,

              I have put you down for transport this week. See you at the flag pole by 2.45pm on Wednesday!

              Thanks,
              Finn
```

But when I do my trigger I get the following:

```
Hi,

eek. See you at the 

Thanks,
```

I have tried using a normal double quoted string with `\n`s instead of the scalar as suggested, was getting the same thing.

Any pointers to my user error would be most appreciated!

**Comment by federico-terzi** [comment]
Hey @finnito,
This is definitely a bug, thanks for reporting it!
A couple of questions:
* Does it happen on every application?
* Could you please try this match without any newline `\n` and see if that expands correctly?

Thanks for your help :)

**Comment by finnito** [comment]
Hi Federico, thanks for your response!

I have changed the trigger to look like this:
```yaml
  - trigger: ".student"
    replace: "Hi,I have put you down for transport this week. See you at the flag pole by 2.45pm on Wednesday!Thanks,Mr LeSueur"
```

And get this output:
```
Hi,I have put you dopm on Wednesday!Than
```

__However, I think I have solved it:__ I use a tool called [Unshaky](https://unshaky.nestederror.com/) which removes double key presses that are prevalent in the new butterfly keyboard on the Macbook Pros. I believe that injection gets caught by Unshaky and therefore doesn't paste properly!

I noticed this after reading more docs and finding that I could use `backend: Clipboard` which seems to solve the problem. This does pollute my clipboard history but it's not a big deal!

**Comment by federico-terzi** [comment]
Hey @finnito,

I think that's it! :) Because I also heard some complaints about other debouncing tools for macOS which interacted negatively with espanso.
Using the `Clipboard` backend should partially solve the problem. You may also want to enable:

```
preserve_clipboard: true
```

in your `default.yml` file for a better experience.

Cheers :)

**Comment by finnito** [comment]
That'll be it - I'll enable `preserve_clipboard` and we can close this :)

Thanks for your friendly and great help @federico-terzi!

**Comment by federico-terzi** [comment]
You're welcome :) Let me know if you have other issues.

Cheers
