### ISSUE TITLE
Close this repository's wiki

### ISSUE THREAD

**Issue by AucaCoyan** [federico-terzi/espanso#1850]
We already have a `README.md` and a website, we don't need yet another source of truth

**Comment by smeech** [comment]
At least the Wiki merely directs people to the sources of truth, and it's arguably a quick route to them.
Are there any downsides to keeping it? If not, we could add the Discord server to the list!

**Comment by AucaCoyan** [comment]
There are no downsides at all, but it's yer another place to check if it's updated. We don't change the homepage often, but if we do (or any other link that  is there) the wiki will be obsolete. If we already have a Readme, who is going to look at the wiki?
In my opinion we should delete what we don't want to actively maintain

**Comment by smeech** [comment]
I suppose Wikis are most useful for repos that don't have a website of their own.

**Comment by AucaCoyan** [comment]
I agree on that!

**Comment by mandarvaze** [comment]
Looking at the wiki, it is just a bunch of links, none of them are likely to change.
So I see no problem leaving it as-is

It does **not** require maintenance IMO

**Comment by AucaCoyan** [comment]
Yeah, I may be a bit harsh on the wiki, it has a clear purpose and it's done basically forever

> If not, we could add the Discord server to the list!

Added! Closing this issue as not interested
