### ISSUE TITLE
Detect module not working

### ISSUE THREAD

**Issue by JoseRuedaRueda** [federico-terzi/espanso#1871]
**Describe the bug**
I tried to run `espanso detect` as described [here](https://espanso.org/docs/legacy/configuration/#application-specific-configurations), to find the right filter configuration, but it gives me the error: `Found argument 'detect' which wasn't expected, or isn't valid in this context`

**To Reproduce**
1. Install espanso in PopOs 22 via deb package
2. Try to run `espanso detect`

**Expected behavior**
I was expecting something like the results said in the espanso guide:
```
Detected change, current window has properties:
==> Title: 'Telegram (1828)'
==> Class: 'TelegramDesktop'
==> Executable: '/snap/telegram-desktop/953/bin/Telegram'
```

**Screenshots**
![image](https://github.com/espanso/espanso/assets/100191586/00dac30a-640f-40e6-a15b-eda87d438bbf)

**Logs**
```
09:11:27 [daemon(8353)] [INFO] reading configs from: "/home/jrr/.config/espanso"
09:11:27 [daemon(8353)] [INFO] reading packages from: "/home/jrr/.config/espanso/match/packages"
09:11:27 [daemon(8353)] [INFO] using runtime dir: "/home/jrr/.cache/espanso"
09:11:27 [daemon(8353)] [INFO] system info: Pop!_OS v22.04 - kernel: 6.6.10-76060610-generic
09:11:27 [daemon(8353)] [INFO] watching for changes in path: "/home/jrr/.config/espanso"
09:11:27 [daemon(8353)] [INFO] espanso version: 2.2.1
09:11:27 [daemon(8353)] [INFO] spawning the worker process...
09:11:27 [daemon(8353)] [INFO] binded to IPC unix socket: /home/jrr/.cache/espanso/espansodaemonv2.sock
09:11:27 [worker(8361)] [INFO] reading configs from: "/home/jrr/.config/espanso"
09:11:27 [worker(8361)] [INFO] reading packages from: "/home/jrr/.config/espanso/match/packages"
09:11:27 [worker(8361)] [INFO] using runtime dir: "/home/jrr/.cache/espanso"
09:11:27 [worker(8361)] [INFO] system info: Pop!_OS v22.04 - kernel: 6.6.10-76060610-generic
09:11:27 [worker(8361)] [INFO] binded to IPC unix socket: /home/jrr/.cache/espanso/espansoworkerv2.sock
09:11:27 [worker(8361)] [INFO] using X11AppInfoProvider
09:11:27 [worker(8361)] [INFO] monitoring the status of the daemon process
09:11:27 [worker(8361)] [INFO] using X11Source
09:11:27 [worker(8361)] [INFO] using X11ProxyInjector
09:11:28 [worker(8361)] [INFO] using X11Clipboard
```

**Setup information**
- OS: Pop_OS 22.04 (Linux)
- Version: which version of Espanso are you running? 2.2.1 (latest installable via deb in Pop_OS)

**Comment by joh6nn** [comment]
Somehow you wound up looking at the documentation for a much older version of espanso (0.7.3)

The documentation for the current version is here: https://espanso.org/docs/configuration/app-specific-configurations/#finding-the-right-filters

**Comment by JoseRuedaRueda** [comment]
My bad
I did not know how I arrived to that old documentation
All solved now
