### ISSUE TITLE
Error after creating yaml files

### ISSUE THREAD

**Issue by katastrophe92** [federico-terzi/espanso#1879]
Hello espanso team and community!
Please let me know what i set wrong. I had all my triggers in a single yaml file and it was a chaos. Then I've done some cleaning and split the 1 yaml file into multiple yml files. After saving everything, I got this error. Besides copy the text from one file to the next file, I did nothing else. Before everything was working as it should. [Screenshots](https://photos.app.goo.gl/QkswU9hMtcmZMPpe8)
Hope some will understand what I mean and help me. Thanks!

![24 February 22024 ⁓ 11⁚18⁚09 ⁓ 827  ⁄1012](https://github.com/espanso/espanso/assets/103950507/ae2c657c-ab45-460c-bd0b-df146ad5ac17)
![24 February 22024 ⁓ 11⁚13⁚03 ⁓ 656  ⁄454](https://github.com/espanso/espanso/assets/103950507/bc9fbd45-faa5-431e-b5ae-9fc26af39d30)
![24 February 22024 ⁓ 11⁚14⁚55 ⁓ 504  ⁄478](https://github.com/espanso/espanso/assets/103950507/8b16fe34-76c1-463e-bb1f-526c06395aac)
![24 February 22024 ⁓ 11⁚15⁚26 ⁓ 603  ⁄605](https://github.com/espanso/espanso/assets/103950507/36f07e59-ff40-441b-a135-4e86e9a80797)
![24 February 22024 ⁓ 11⁚17⁚25 ⁓ 490  ⁄490](https://github.com/espanso/espanso/assets/103950507/ff5508db-5535-4709-9b08-8b088e6e966f)

**Comment by smeech** [comment]
Please see our responses on [Discord](https://discord.com/channels/884163483409731584/1013918746471039067/1212886688154779728). We think you need to check the formatting of your `.yml` files.

**Comment by smeech** [comment]
Resolved.
