### ISSUE TITLE
Multline expansions are not workong 

### ISSUE THREAD

**Issue by Philipp0205** [federico-terzi/espanso#188]
First: Thank you for this great tool!

I use Ubuntu 19.10 and multiline expansions are not working atm. This is the section in the default.yml: 

```
- trigger: "include newlines"
  replace: |
            exactly as you see
            will appear these three
            lines of poetry
```

Output: 
```
 exactly as you see will appear these three lines of poetry
``

Thanks!

**Comment by federico-terzi** [comment]
Hey @Philipp0205,
Thanks for the kind words! Unfortunately, I couldn't reproduce your issue as it is working correctly for me on Ubuntu 18.04.

Does it happen on every application or just a few ones?

Cheers

**Comment by Philipp0205** [comment]
Sorry for my late reply. 
I can't reproduce the error anymore. For some reason it is resolved. 

Maybe a restart did it 🙃

Thanks again!
