### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by txtsd** [federico-terzi/espanso#1889]
Please clarify whether espanso is licensed as `GPL-3.0-or-later` or `GPL-3.0-only`.

Packaging on the AUR now prefers SPDX license identifiers so this information would help a lot!

**Comment by AucaCoyan** [comment]
Hi! Thank you for submitting an issue, we will discuss this shortly on the upcoming meeting (details in the espanso discord!)

**Comment by federico-terzi** [comment]
Hey folks :)

> Please clarify whether espanso is licensed as GPL-3.0-or-later or GPL-3.0-only.

GPL-3.0 or later, as seen in the source files: https://github.com/espanso/espanso/blob/dev/espanso-detect/src/event.rs#L6-L9

Hope that helps!

**Comment by AucaCoyan** [comment]
Great! Closing the issue

**Comment by txtsd** [comment]
Thank you!
