### ISSUE TITLE
Espanso doesn't start despite no other process running

### ISSUE THREAD

**Issue by archie-was-taken** [federico-terzi/espanso#1890]
**Describe the bug**
Espanso refuses to start with `espanso start` even when `espanso status` says espanso is not running.

**To Reproduce**
1. Close espanso
2. Start espanso with `espanso start`
> The output will be as follows:
>
> ```
> unable to start service: timed out
> Hint: sometimes this happens because another Espanso process is left running for some reason.
>      Please try running 'espanso restart' or manually killing all Espanso processes, then try again.
> ```
4. Do `espanso restart`, and observe this:
> ```
> espanso is not running!
> unable to start service: timed out
> Hint: sometimes this happens because another Espanso process is left running for some reason.
>      Please try running 'espanso restart' or manually killing all Espanso processes, then try again.
> ```

**Expected behavior**
espanso will run when I type `espanso start` and hit `Return ⮐`

**Screenshots**
![image](https://github.com/espanso/espanso/assets/113207560/fe3cd7e6-905c-4c60-97f0-827216292dbc)

**Logs**
https://app.warp.dev/block/1KJGQBiwxaWhsFkFbgzQut

**Setup information**
- OS: Fedora Linux 39 (Workstation Edition)
- Version: 2.2.1

**Comment by morgan-dgk** [comment]
Thanks for this report and the logs.

Based on the error seen in your logs, it looks like compilation of the XKB keymap is failing for some reason.

**Comment by morgan-dgk** [comment]
Does `localectl list-x11-keymap-layouts` list `en-in` as an available layout?

**Comment by morgan-dgk** [comment]
Assuming you want the English (India, with rupee) keyboard, try setting the below in your espanso config:

```
keyboard_layout: 
  layout: "in"
  variant: "eng"
```

**Comment by archie-was-taken** [comment]
> Assuming you want the English (India, with rupee) keyboard, try setting the below in your espanso config:
> 
> ```
> keyboard_layout: 
>   layout: "in"
>   variant: "eng"
> ```

This solved my problem. Thanks for the help! I'm closing the issue.
