### ISSUE TITLE
A white blob appears on starting Espanso

### ISSUE THREAD

**Issue by archie-was-taken** [federico-terzi/espanso#1899]
**Describe the bug**
A white rectangular unresponsive box appears on the top left of the screen whenever espanso is running. Additionally, an entry titled __unknown__ appears in the dock.

**To Reproduce**
1. Open a Terminal and run `espanso start`.

**Expected behavior**
There should be no such boxes.

**Screenshots**
![image](https://github.com/espanso/espanso/assets/113207560/cf9831ff-202a-4d84-bb61-97ec72dfe61f)

**Logs**
```
21:07:39 [daemon(206289)] [INFO] reading configs from: "/home/arch/.config/espanso"
21:07:39 [daemon(206289)] [INFO] reading packages from: "/home/arch/.config/espanso/match/packages"
21:07:39 [daemon(206289)] [INFO] using runtime dir: "/home/arch/.cache/espanso"
21:07:39 [daemon(206289)] [INFO] system info: Fedora Linux v39 - kernel: 6.7.5-200.fc39.x86_64
21:07:39 [daemon(206289)] [INFO] watching for changes in path: "/home/arch/.config/espanso"
21:07:39 [daemon(206289)] [INFO] espanso version: 2.2.1
21:07:39 [daemon(206289)] [INFO] spawning the worker process...
21:07:39 [daemon(206289)] [INFO] binded to IPC unix socket: /home/arch/.cache/espanso/espansodaemonv2.sock
21:07:39 [daemon(206289)] [WARN] keyboard layout watcher couldn't determine active layout.
21:07:39 [worker(206299)] [INFO] reading configs from: "/home/arch/.config/espanso"
21:07:39 [worker(206299)] [INFO] reading packages from: "/home/arch/.config/espanso/match/packages"
21:07:39 [worker(206299)] [INFO] using runtime dir: "/home/arch/.cache/espanso"
21:07:39 [worker(206299)] [INFO] system info: Fedora Linux v39 - kernel: 6.7.5-200.fc39.x86_64
21:07:39 [worker(206299)] [INFO] binded to IPC unix socket: /home/arch/.cache/espanso/espansoworkerv2.sock
21:07:39 [worker(206299)] [INFO] using WaylandAppInfoProvider
21:07:39 [worker(206299)] [INFO] detection module will use this keyboard layout: [R=, M=, L=in, V=eng, O=]
21:07:39 [worker(206299)] [INFO] monitoring the status of the daemon process
21:07:39 [worker(206299)] [INFO] using EVDEVSource
21:07:39 [worker(206299)] [INFO] Querying modifier status...
21:07:40 [worker(206299)] [INFO] inject module will use this keyboard layout: [R=, M=, L=in, V=eng, O=]
21:07:40 [worker(206299)] [INFO] using EVDEVInjector
21:07:40 [worker(206299)] [INFO] using WaylandFallbackClipboard
```

**Setup information**
- OS: Fedora Workstation 39
- Version: 2.2.1

**Comment by archie-was-taken** [comment]
![image](https://github.com/espanso/espanso/assets/113207560/14e22fc0-9b5e-4bc5-87e9-687a21efcb0a)

Here's the entry in the dock

**Comment by smeech** [comment]
This is a well-documented Wayland issue.
#1826, #1722, #1619

**Comment by AucaCoyan** [comment]
Hello! #1901 got merged, can we re-test if this keeps happening in the latest version? ❤️

**Comment by archie-was-taken** [comment]
No, it doesn't any longer. Thanks for the fix!

**Comment by AucaCoyan** [comment]
kudos to @morgan-dgk !

**Comment by qwertychouskie** [comment]
Are there any packages that include this fix, or would I need to compile Espanso myself?

**Comment by AucaCoyan** [comment]
Yeah, it's still on dev branch. Sadly it isn't packaged into a release.

**Comment by smeech** [comment]
Compilation for Fedora 39 went pretty smoothly for me (and I'm not familiar with Fedora *or* compiling), with a minor problem for which I updated the docs.
The alternative some people choose is to move the errant window to another Workspace.
