### ISSUE TITLE
install manually on macOS

### ISSUE THREAD

**Issue by trolologuy** [federico-terzi/espanso#190]
The official espanso [installation documentation for macOS](https://espanso.org/install/mac/) lacks clarity regarding a manual installation: "_but you can also do it manually_." 
Sorry if i'm probably missing the obvious... but looking at the source code i couldn't figure out where to start.

Installing through Homebrew is **not** an option in my case.

Any clarification would be greatly appreciated, at least to get a starting point.
From there if needed i'd be happy to help documenting all the steps :)

**Comment by federico-terzi** [comment]
Hey @trolologuy,
You're totally right, the documentation is not very clear about that!

The first step is to download the "espanso-mac.tar.gz" archive from the [Releases](https://github.com/federico-terzi/espanso/releases) page.

Then you can extract it and place the binary "espanso" in your chosen folder, For example `/usr/local/bin` (which has the advantage of automatically add espanso to the PATH variable).

Then you should be able to proceed with the [Enabling Accessbility](https://espanso.org/install/mac/#enabling-accessibility) part of the guide.

There is only one thing that could go wrong with this steps, which is the OpenSSL 1.1 dependency (Homebrew automatically takes care of this). Therefore, you may need to install it as well manually.

Let me know if it works for you!

Cheers :)

**Comment by trolologuy** [comment]
Hey @federico-terzi,
Thanks a lot for the really fast response !

I ran into some issues trying to manually compile OpenSSL, it seems that **maybe** espanso is looking for libssl on a specific path?
After successfully compiling OpenSSL here's what i get when trying to start espanso:
`dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib`
The openssl version installed:
`openssl version
OpenSSL 1.1.1d  10 Sep 2019`
When i run `which openssl` it indeeds points to my local installation.
My guess is that i would need to compile espanso manually as well (?)

Here's the steps i followed:
**OpenSSL Manual installation**
1. Download and unzip the latest version of [openssl](https://github.com/openssl/openssl/releases)
2. Open a terminal in the directory where you unzipped the file
3. run `./Configure darwin64-x86_64-cc no-ssl3 no-ssl3-method no-zlib --prefix=$SOME_PATH_TO_FOLDER --openssldir=$SOME_PATH_TO_FOLDER`, $SOME_PATH_TO_FOLDER should be a folder the current can access and has the rights (for e.g on your desktop), to be able to run the `make install` command without root rights.
4. `make`, `make test` and `make install`
5. add an alias in your `.zshrc` / `.bashrc` file to use the version you compiled. for e.g: `alias openssl="$SOME_PATH_TO_FOLDER/bin/openssl"`
6. add an alias for espanso (_following the same logic as step 5_.)
7. run `openssl version` to check that the version is indeed the one you compiled.

**Comment by trolologuy** [comment]
Okey i found a workaround.
Here's what i did. I tried to override the library with dyld.
`man dyld` gave:
> DYLD_LIBRARY_PATH
> 
> This is a colon separated list of directories that contain libraries. The dynamic linker searches these directories before it searches the default locations for libraries. It allows you to test new versions of existing libraries.
> 
> For each library that a program uses, the dynamic linker looks for it in each directory in DYLD_LIBRARY_PATH in turn. If it still can't find the library, it then searches DYLD_FALLBACK_FRAMEWORK_PATH and DYLD_FALLBACK_LIBRARY_PATH in turn.
> 
> Use the -L option to otool(1). to discover the frameworks and shared libraries that the executable is linked against.

So i tried to export the library to force the usage of the locally compiled openssl version using:
`export DYLD_LIBRARY_PATH=$PATH_TO_FOLDER/lib`

But due to a security in macOS is wasn't working, more information can be found [here](https://gitlab.haskell.org/ghc/ghc/issues/11617)

So i created a wrapper to be able to override the library path and start espanso, here are all the steps to make it work:
1. go to a folder where you have read/write access
2. `mkdir espanso`
3.  `cd espanso` -> The path to the "espanso" folder will be referred as $PATH_TO_ESPANSO
4. copy the espanso executable into this folder
5. copy sh into this folder: `cp /bin/sh .`
6. `touch launcher.sh` and  copy paste the following into it
```
#!./sh
export DYLD_LIBRARY_PATH=$PATH_TO_FOLDER/lib
./espanso
```
7. `mkdir openssl` -> The path to the folder "openssl" will be referred as $PATH_TO_FOLDER
8. Download and unzip the latest version of [openssl](https://github.com/openssl/openssl/releases)
9. in the same folder run `./Configure darwin64-x86_64-cc no-ssl3 no-ssl3-method no-zlib --prefix=$PATH_TO_FOLDER --openssldir=$PATH_TO_FOLDER`
10. run `make`, `make test` and `make install`
11. change the $PATH `.zshrc` / `.bashrc` file to add the path to the version you compiled. for e.g: `export path="$PATH_TO_FOLDER/bin/:$PATH"` 
11. add an alias for espanso (`alias espanso="$PATH_TO_ESPANSO/launcher.sh"`)
12. run `openssl version` to check that the version is indeed the one you compiled.
13. `chmod +x launcher.sh`
14. run the wrapper using `./launcher.sh`

**Comment by federico-terzi** [comment]
Hey @trolologuy,
Thanks for your detailed explanation! I'm not particularly practical of macOS libraries, could the error be solved creating a link to the correct directory?

For example, on my machine espanso loads the shared libraries in these paths:
![image](https://user-images.githubusercontent.com/20475953/75477982-6952e800-599d-11ea-92f9-9df11f10a675.png)

What about creating a link from your openssl location to these paths? Such as:

```
ln -s /your/path/to/dylib /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
```

and the same with `libcrypto.1.1.dylib`.

Let me know what you think

Cheers :)

**Comment by trolologuy** [comment]
Hello Federico, 
Apologies for the delay :) Sadly i'm not root on the machine, i already tried to manually link the shared libraries (it was indeed one the first things i tried, should have been more precise about it, sorry for that). But yeah i guess it would be a working workaround for anyone with root rights (even though i doubt they would run it the same issues in the first place).

Since i have no root rights, i'm also not able to do the "espanso register" step.
I tried the following as well:
![Screenshot 2020-03-02 at 13 58 48](https://user-images.githubusercontent.com/16886290/75678860-d660c900-5c8e-11ea-82b4-705e8a66dfb1.png)

So i guess espanso won't be usable without root rights 😢 

I think you can close the issue, since there won't be possibilities to fix it for my use case (use espanso on a machine where you are not root) i imagine. Nevertheless i have to admit i'm impressed by your blog + your projects. Keep on the good work ! 😉

**Comment by federico-terzi** [comment]
Hey @trolologuy,

Thank you for the kind words :)

> So i guess espanso won't be usable without root rights 😢

Unfortunately, without enabling espanso in the Accessibility settings (which requires admin rights), the OS will block it from working correctly. I'm sorry I didn't realized it earlier.

Stay tuned, maybe we'll find a solution one day :)
