### ISSUE TITLE
Hello guys,

### ISSUE THREAD

**Issue by gthelotparthondevon** [federico-terzi/espanso#1909]
Hello guys,
I have MacOS 14.3 Sonoma and now Espesanso won't even start.
When I click on the icon from the doc it starts but after less than 1 sec it stops. 
So it's not even in the Activity monitor.

I deleted the app and add again and still not working.

I have another laptop with same OS and same issue.

Anybody has this issue?

**Comment by morgan-dgk** [comment]
Please run espanso -vvvvv worker or espanso log and share the output.

-------- Message d'origine --------

**Comment by gthelotparthondevon** [comment]
Thanks the quick follow up :)

20:28:08 [worker(32113)] [INFO] creating config directory in "/Users/TheThelotsPdeVon/Library/Application Support/espanso"
20:28:08 [worker(32113)] [ERROR] thread 'main' panicked at 'unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }': espanso-path/src/lib.rs:48
Gs-MacBook-Pro:~ TheThelotsPdeVon$ 

(I am not developer so looks very foreign to me). Is that what you are looking for?

**Comment by morgan-dgk** [comment]
Yes, this is useful thank you. Espanso is failing to find the existing config directory for some reason.

**Comment by morgan-dgk** [comment]
Is this the whole log? It would be useful to see any additional debug messages that `espanso -vvvvv worker` or `espanso log` show.

**Comment by gthelotparthondevon** [comment]
Here it is :)

Gs-MacBook-Pro:~ TheThelotsPdeVon$  espanso log
thread 'main' panicked at espanso-path/src/lib.rs:48:33:
unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Gs-MacBook-Pro:~ TheThelotsPdeVon$ espanso -vvvvv worker 
06:05:52 [worker(54303)] [INFO] creating config directory in "/Users/TheThelotsPdeVon/Library/Application Support/espanso"
06:05:52 [worker(54303)] [ERROR] thread 'main' panicked at 'unable to create config directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }': espanso-path/src/lib.rs:48

Thanks a lot :)

**Comment by morgan-dgk** [comment]
I am not yet sure why this is occuring. Did this occur issue immediately after a fresh install or was Espanso previously working?

While I investigate, can you try to move the existing Espanso config folder at `/Users/TheThelotsPdeVon/Library/Application Support/espanso` outside of the Application Support folder? Before doing so, please run `espanso stop` to ensure Espanso is not running.

Espanso should then be able to create the necessary config folder.

**Comment by gthelotparthondevon** [comment]
@morgan-dgk  thanks so much !!!! Thanks to your help I found. 
when I went to Application support I noticed that the symbolic work was broken since my espanso folder is on google drive. I was able to fix by creating a new symbolic link!!

I would never had been able to fix without you, you rock !!
