### ISSUE TITLE
Add ClipboardExtension to insert clipboard content into matches

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#192]
A user requested the feature on Reddit, with the following use case:

> In a very simple example, I often copy a key value from the database, then expand an SQL query that includes the key value:
> - Copy A12345 from the database
> - Expand a query: select * from mytable where mycol = '%Clip%'
> - This results in: select * from mytable where mycol = 'A12345'
> I also include the clipboard into many email templates I have for customers.

**Comment by johnmbaughman** [comment]
Glad this has been started! This is one of the only things I could think of that was missing... 

I started with TextExpander, moved to Breevy, tried the very limited and expensive PhraseExpress, found espanso and I think I'm in love... Thank you for this! Getting used to the syntax of the yml file is a small learning curve, but this will be a great tool!

**Comment by federico-terzi** [comment]
Hey @johnmbaughman,
Thank you for the kind words! I'm glad you liked the new feature, it should ship in the next version of espanso which I plan to release very soon :)

> Getting used to the syntax of the yml file is a small learning curve, but this will be a great tool!

Yaml based configuration has many advantages, but honestly I find it a bit cumbersome too sometimes. I'm still looking for the best way to implement it, but I'm planning to add an (optional) GUI to customize them. 

Stay tuned :)
