### ISSUE TITLE
Add HTTP Request extension

### ISSUE THREAD

**Issue by AucaCoyan** [federico-terzi/espanso#1935]
### Discussed in https://github.com/espanso/espanso/discussions/1204

<div type='discussions-op-text'>

<sup>Originally posted by **federico-terzi** January  3, 2021</sup>
I've noticed a lot of packages rely on `curl` to execute HTTP requests and obtain the expansion text.
It might be a good idea to introduce a "request" extension so that use-case is solved without the use of an external command</div>

**Comment by joh6nn** [comment]
I'm actually strongly opposed to this, not because I don't think it would be useful, but because it drastically changes the security profile of Espanso. To me, it's important that Espanso doesn't directly connect to the internet.

**Comment by AucaCoyan** [comment]
Mmmmm... it does to download packages from the hub, but you are correct that security might be a concern. 
What scenarios are desired or undesired to happen?

**Comment by smeech** [comment]
This takes us back to the discussions about `script` and `shell` extensions. I tend to agree with @joh6nn - it's essential to be able to identify code that "*extends*" Espanso into more risky areas, and leaving `curl` to shell commands helps. If it's not inbuilt, as a `request` extension would be, I feel less responsible!

**Comment by AucaCoyan** [comment]
Mmmm, yeah, now that you say that we currently do have a way to call a url, I don't see a reason to have yet another way to do the same.
Let's close this as unplanned and in the future we may choose to open it, but it's not necessary as of today. Thanks to both!
