### ISSUE TITLE
Espanso not working, window not rendering + "Unknown" app in dock (Ubuntu/Wayland)

### ISSUE THREAD

**Issue by Arche151** [federico-terzi/espanso#1949]
### Description

I installed espanso 2.2.1 on my Ubuntu 22.04 PC, following the documentation, and it seemed to start successfully. 

I got a notification saying "Espanso is running" and `espanso status` says, that it's running as well.

But typing `:espanso` did nothing. There is a generic active app icon in my dock now (nothing in the tray) and when I click on it, a horribly deformed and broken window (more like a strip) appears. 

It seems to be espanso, since it disappears and reappears when I restart espanso.

![image](https://github.com/espanso/espanso/assets/124050126/5113be9d-2ea8-4cca-a579-10605c5e63a1)

My logs are not indicating, what is wrong: 

```
snake@Framework-Laptop:~$ espanso log
18:48:15 [daemon(202718)] [INFO] reading configs from: "/home/snake/.config/espanso"
18:48:15 [daemon(202718)] [INFO] reading packages from: "/home/snake/.config/espanso/match/packages"
18:48:15 [daemon(202718)] [INFO] using runtime dir: "/home/snake/.cache/espanso"
18:48:15 [daemon(202718)] [INFO] system info: Ubuntu v22.04 - kernel: 6.5.0-1019-oem
18:48:15 [daemon(202718)] [INFO] espanso version: 2.2.1
18:48:15 [daemon(202718)] [INFO] watching for changes in path: "/home/snake/.config/espanso"
18:48:15 [daemon(202718)] [INFO] spawning the worker process...
18:48:15 [daemon(202718)] [INFO] binded to IPC unix socket: /home/snake/.cache/espanso/espansodaemonv2.sock
18:48:15 [daemon(202718)] [WARN] keyboard layout watcher couldn't determine active layout.
18:48:15 [worker(202725)] [INFO] reading configs from: "/home/snake/.config/espanso"
18:48:15 [worker(202725)] [INFO] reading packages from: "/home/snake/.config/espanso/match/packages"
18:48:15 [worker(202725)] [INFO] using runtime dir: "/home/snake/.cache/espanso"
18:48:15 [worker(202725)] [INFO] system info: Ubuntu v22.04 - kernel: 6.5.0-1019-oem
18:48:15 [worker(202725)] [INFO] using WaylandAppInfoProvider
18:48:15 [worker(202725)] [INFO] binded to IPC unix socket: /home/snake/.cache/espanso/espansoworkerv2.sock
18:48:15 [worker(202725)] [INFO] monitoring the status of the daemon process
18:48:15 [worker(202725)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
18:48:15 [worker(202725)] [INFO] using EVDEVSource
18:48:15 [worker(202725)] [INFO] Querying modifier status...
18:48:15 [worker(202725)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
18:48:15 [worker(202725)] [INFO] using EVDEVInjector
18:48:15 [worker(202725)] [INFO] using WaylandFallbackClipboard
18:48:27 [service(202793)] [INFO] reading configs from: "/home/snake/.config/espanso"
18:48:27 [service(202793)] [INFO] reading packages from: "/home/snake/.config/espanso/match/packages"
18:48:27 [service(202793)] [INFO] using runtime dir: "/home/snake/.cache/espanso"
18:48:27 [service(202793)] [INFO] system info: Ubuntu v22.04 - kernel: 6.5.0-1019-oem
18:48:27 [service(202793)] [INFO] espanso is running
snake@Framework-Laptop:~$

```
Reinstalling espanso didn't help, unfortunately.

**Comment by asdrubale88** [comment]
Can confirm the bug, I have the same behaviour building from the source on Arch via the AUR repository (https://aur.archlinux.org/packages/espanso-wayland). Running Plasma 6.0.4 on Wayland. Tried starting/stopping/restarting the service but the bug remains. Probably Wayland related.

![image](https://github.com/espanso/espanso/assets/16238902/83052f60-6c8b-4f79-88b0-66fc21d30e0d)

Logs:
22:33:04 [daemon(73533)] [INFO] reading configs from: "/home/romeo/.config/espanso"
22:33:04 [daemon(73533)] [INFO] reading packages from: "/home/romeo/.config/espanso/match/packages"
22:33:04 [daemon(73533)] [INFO] using runtime dir: "/home/romeo/.cache/espanso"
22:33:04 [daemon(73533)] [INFO] system info: EndeavourOS vrolling - kernel: 6.8.5-arch1-1
22:33:04 [daemon(73533)] [WARN] keyboard layout watcher couldn't determine active layout.
22:33:04 [daemon(73533)] [INFO] watching for changes in path: "/home/romeo/.config/espanso"
22:33:04 [daemon(73533)] [INFO] espanso version: 2.2.1
22:33:04 [daemon(73533)] [INFO] spawning the worker process...
22:33:04 [daemon(73533)] [INFO] binded to IPC unix socket: /home/romeo/.cache/espanso/espansodaemonv2.sock
22:33:04 [worker(73539)] [INFO] reading configs from: "/home/romeo/.config/espanso"
22:33:04 [worker(73539)] [INFO] reading packages from: "/home/romeo/.config/espanso/match/packages"
22:33:04 [worker(73539)] [INFO] using runtime dir: "/home/romeo/.cache/espanso"
22:33:04 [worker(73539)] [INFO] system info: EndeavourOS vrolling - kernel: 6.8.5-arch1-1
22:33:04 [worker(73539)] [INFO] binded to IPC unix socket: /home/romeo/.cache/espanso/espansoworkerv2.sock
22:33:04 [worker(73539)] [INFO] using WaylandAppInfoProvider
22:33:04 [worker(73539)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
22:33:04 [worker(73539)] [INFO] monitoring the status of the daemon process
22:33:04 [worker(73539)] [INFO] using EVDEVSource
22:33:05 [worker(73539)] [INFO] Querying modifier status...
22:33:05 [worker(73539)] [WARN] unable to determine keyboard layout automatically, please explicitly specify it in the configuration.
22:33:05 [worker(73539)] [INFO] using EVDEVInjector
22:33:05 [worker(73539)] [INFO] using WaylandFallbackClipboard

**Comment by morgan-dgk** [comment]
@asdrubale88 compiling from source _should_ fix this, fix in #1901 which is not yet in release.

**Comment by philister** [comment]
same here. Just not working. status is running. log without errors. :espanso does nothing. ubuntu 22.04 wayland

**Comment by Midou1966** [comment]
Same ... just not working, the same unknown app in the dock and the line on the screen.

**Comment by MS1034** [comment]
![image](https://github.com/user-attachments/assets/3d276d74-6599-443f-a0b7-b971be56eb6c)

same issue ubuntu noble numbat wayland

**Comment by Arche151** [comment]
Esapanso now works for me!

I had to install it via snap (the 10th of july version) by running `sudo snap install espanso --edge --classic`

Then I had to run `espanso service register` and finally `espanso start` and now it works flawlessly.

Thanks a lot to everyone at Espanso :)
