### ISSUE TITLE
Slow on linux but instant on mac

### ISSUE THREAD

**Issue by owzim** [federico-terzi/espanso#195]
## Specs

* **OS:** Pop!_OS 19.10
* *on macOS this works as expected*

It seems like it takes about half a second before an expansion is executed. On the one hand this feels sluggish on the other hand it results in borked sentences when using misspelling expansions.

I for example use an expansion to correct my perpetual misspelling of `const`

```yaml
- { trigger: "cosnt", replace: "const" }
```
Depending on the speed I am typing:

`cosnt foo = 'bar'`

results in:

`  constfoo = 'bar'` *<- the has a space in the beginning which is not displaying correctly*

or

`cconstfoo = 'bar'`

or something similar

I guess it injects the text where ever the cursor currently is, and because of the delay, this happens in places where is should not.

**Comment by federico-terzi** [comment]
Hey @owzim,

You're definitely a fast typer! :)
Jokes aside, espanso is much snappier on Windows and macOS due to the fact that those OS allow an efficient text injection, whereas (up to know) I wasn't able to get reliable results on Linux. Therefore, on Linux it uses the Clipboard backend by default, which is a bit slower.

That said, I'll look into ways to improve the performances on Linux and get back to you once I know something!

Cheers :)

**Comment by federico-terzi** [comment]
Hey @owzim,
I just finished a set of general improvements for the Linux backend that should improve the responsiveness a lot. I plan to publish the release (0.5.2) in a few days, I'll let you know when it's ready so you can try it out :)

Cheers

**Comment by federico-terzi** [comment]
Hey @owzim,
Espanso 0.5.2 has been released, please set the `Auto` backend (you can find the info in the releases page) and let me know if that helps :)

Cheers

**Comment by owzim** [comment]
The speed in crease is definitely noticeable, especially in KDE apps like Telegram. Thanks!

**Comment by v217** [comment]
The [latex extension](https://github.com/zoenglinghou/espanso-latex) is very slow on linux, otherwise the espanso is fast.
Is there a way to speed up the lookup of the math symbols?
Thanks!

**Comment by federico-terzi** [comment]
@v217 I'm sorry you experienced this problem! Could you please try to temporarily add `backend: Clipboard` to your default.yml and see if that helps with speed? Also, is it slow on every application on Linux?

Cheers :)

**Comment by v217** [comment]
Hi @federico-terzi, no the welcome message works instantaneously. I will try the clipboard option. Do you think espanso works faster under wayland?
Thanks!

**Comment by federico-terzi** [comment]
@v217 Thanks! 

> Do you think espanso works faster under wayland?

Hard to tell at this point. It will use a completely different engine, so that could be either faster or slower :)

**Comment by kankaristo** [comment]
> @v217 I'm sorry you experienced this problem! Could you please try to temporarily add `backend: Clipboard` to your default.yml and see if that helps with speed? Also, is it slow on every application on Linux?

`backend: Clipboard` is definitely much faster. Still a bit slow, but without this, Espanso is unusably slow on Linux.

For example, I have a 4-line text expansion, and:
- without `backend: Clipboard`, it takes 4-5 seconds to run
- with `backend: Clipboard`, it takes about 1 second

1 second is usable, but still a bit slow. It's not that long, but I still have to wait for it to finish before continuing to type.

**Comment by federico-terzi** [comment]
@kankaristo I'm sorry you experienced this problem! Are you using Gnome? If that's the case, the next major version might significantly improve the speed!

> are there any caveats to using backend: Clipboard, is it "safe" to use? Any reason why it isn't the default, since it seems to be faster (at least on Linux)?

The only downside is that it overwrites the current clipboard content and that is sometimes inconvenient (although with text content espanso tries to recover the previous content, but that doesn't work with images)

**Comment by RaulDurand** [comment]
I am having the same issue on Ubuntu with i3-wm. I tried the clipboard backend even though it is slow. There is a delay before the replacing characters are injected,  so the next typed characters appear before the injection. I set pre_paste_delay to 10 and now is working a bit better.

**Comment by owzim** [comment]
@RaulDurand I am also still having issues every now and then on Linux Mint 22. Logging out and in again works around it. That makes me wonder if restarting the espanso service might fix that as well. Will try next time it happens.
