### ISSUE TITLE
Matches don't work in password fields

### ISSUE THREAD

**Issue by AdamSPi** [federico-terzi/espanso#196]
Typing an abbreviation into a password field does not trigger the match, however it works fine in any normal field. I'm not sure if this is by design or not, but I was wondering if there's any way to get around this in the configuration files.

I've tested this in Chrome, Mozilla, and Safari on OSX and they all behave the same way. The same happens on Windows 10.

**Comment by federico-terzi** [comment]
Hey @AdamSPi,
Most operating systems enforce some kind of restriction when typing on password fields (SecureInput on macOS) and unfortunately, there is nothing we can do about it.

Cheers :)

**Comment by franz101** [comment]
Certainly there is something people can do. Fe this works for passwords:
https://www.ergonis.com/products/typinator/
