### ISSUE TITLE
link to config file/match folder in the taskbar right click menu

### ISSUE THREAD

**Issue by andrearicci** [federico-terzi/espanso#1965]
### Description

I always have difficulties to remember where's the config file - I also wrote some triggers but I never remember them (I have more config files, a local specific for the pc and a common on the cloud for different pcs).
I would find very helpful to have a link to the config file (or match folder) in the taskbar right click menu.
Thank you

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

![immagine](https://github.com/espanso/espanso/assets/1193266/14302250-9ef2-4023-939a-4be6c474d68f)

**Comment by smeech** [comment]
I don't have the luxury of a taskbar icon as I'm on Linux, but this sounds like a good idea.

In the meantime, the command lines: 
- `espanso edit` will open your `base.yml` file for editing 
- `espanso edit default` will open your config file 
- `espanso edit foo` will open your `foo.yml` file
- `espanso path` will show you where your files are.

**Comment by andrearicci** [comment]
@smeech thank you

**Comment by stewcam** [comment]
@andrearicci In response to your issue of tracking key Espanso files and folders, you may find the freeware Windows app [EspansoEdit ](https://ee.qqv.com.au/)helpful.

**Comment by doggy8088** [comment]
I'd like to recommend add the following three items to the context menu of the system tray icon.

1. Edit base.yml
2. Open match folder

@smeech What do you think?

**Comment by smeech** [comment]
I'm not a good person to opine! I only occasionally use Windows (as a VM), so I'm not accustomed to having an icon, I never touch `base.yml`, preferring to keep my expansions in a smattering of different files, and my editors are configured to take me directly to the `espanso/match` folder.

That having been said, a link to open the `espanso/match` folder sounds like a good idea.

**Comment by doggy8088** [comment]
I see. I'm totally agree with you. I tend to just add `Open match folder` menu item for now.

**Comment by doggy8088** [comment]
Wait, after I can build this project on my Windows with the latest `dev` branch. I just realized there is [already a commit](https://github.com/espanso/espanso/commit/6a3ee2ce9416e68d4cb52a0a54566e7db0267538) that is already implemented **Open config folder** context menu item.

![image](https://github.com/espanso/espanso/assets/88981/c3cc7300-ed49-43bd-8583-d6d3c1de80cb)

I think this issue might be able to closed.

When will espanso release new version?

**Comment by AucaCoyan** [comment]
Hi! I didn't follow this issue and it got lost in the history.

> I think this issue might be able to closed.

Yes, I believe so. I don't think we can add a line for _each_ config file, given some people have many different files (and packages!). But we did merged a `Open config folder`. Do you think that is enough or should we add `Edit base.yml` too?

> When will espanso release new version?

Not soon sadly, we [have an issue explaining why](https://github.com/espanso/espanso/issues/2126)

cc @smeech penny for your thoughts too!

**Comment by smeech** [comment]
I think opening the config folder (by that I mean the Espanso folder that contains `/config`, and `/match`), or the `/match` folder is sufficient. There's a good argument for including a link to `base.yml` for _new_ users' benefit, however, although I too never touch it.

**Comment by AucaCoyan** [comment]
Great! Then we can close this issue and open a new one with a `low priority` tag with that feature (if anyone is feeling strong enough to take it)
