### ISSUE TITLE
Espanso not triggering on Windows 11

### ISSUE THREAD

**Issue by HossBigft** [federico-terzi/espanso#1978]
### Description

I can't get espanso to work on my win11 machine and I can't find anything related. Legacy version is working, for some reason. I tried to change backends to no avail.

### Steps to reproduce

1. Install espanso 2.2.1/2.2
2. Type any trigger
3. Nothing happens

### Expected behavior

Espanso triggers and expands text

### Logs

```
09:29:58 [daemon(8932)] [INFO] reading configs from: "C:\\Users\\COMPUTER406_1\\AppData\\Roaming\\espanso"
09:29:58 [daemon(8932)] [INFO] reading packages from: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso\\packages"
09:29:58 [daemon(8932)] [INFO] using runtime dir: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso"
09:29:58 [daemon(8932)] [INFO] system info: Windows v11 (22621) - kernel: 22621
09:29:58 [daemon(8932)] [INFO] watching for changes in path: "C:\\Users\\COMPUTER406_1\\AppData\\Roaming\\espanso"
09:29:58 [daemon(8932)] [INFO] espanso version: 2.2.1
09:29:58 [daemon(8932)] [INFO] spawning the worker process...
09:29:58 [daemon(8932)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
09:29:58 [worker(11688)] [INFO] reading configs from: "C:\\Users\\COMPUTER406_1\\AppData\\Roaming\\espanso"
09:29:58 [worker(11688)] [INFO] reading packages from: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso\\packages"
09:29:58 [worker(11688)] [INFO] using runtime dir: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso"
09:29:58 [worker(11688)] [INFO] system info: Windows v11 (22621) - kernel: 22621
09:29:58 [worker(11688)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
09:29:58 [worker(11688)] [INFO] using Win32AppInfoProvider
09:29:58 [worker(11688)] [INFO] monitoring the status of the daemon process
09:29:58 [worker(11688)] [INFO] using Win32Source
09:29:58 [worker(11688)] [ERROR] unable to register hotkey: ALT+SPACE
09:29:58 [worker(11688)] [INFO] using Win32Injector
09:29:58 [worker(11688)] [INFO] using Win32Clipboard
09:30:45 [daemon(8932)] [INFO] configuration change detected, restarting worker process...
09:30:45 [worker(11688)] [INFO] engine eventloop has terminated, propagating exit event...
09:30:45 [worker(11688)] [INFO] waiting for engine exit mode...
09:30:45 [worker(11688)] [INFO] exiting worker process...
09:30:45 [daemon(8932)] [INFO] spawning the worker process...
09:30:45 [worker(5292)] [INFO] reading configs from: "C:\\Users\\COMPUTER406_1\\AppData\\Roaming\\espanso"
09:30:45 [worker(5292)] [INFO] reading packages from: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso\\packages"
09:30:45 [worker(5292)] [INFO] using runtime dir: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso"
09:30:45 [worker(5292)] [INFO] system info: Windows v11 (22621) - kernel: 22621
09:30:45 [worker(5292)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
09:30:45 [worker(5292)] [INFO] using Win32AppInfoProvider
09:30:45 [worker(5292)] [INFO] monitoring the status of the daemon process
09:30:45 [worker(5292)] [INFO] using Win32Source
09:30:45 [worker(5292)] [ERROR] unable to register hotkey: ALT+SPACE
09:30:45 [worker(5292)] [INFO] using Win32Injector
09:30:45 [worker(5292)] [INFO] using Win32Clipboard
09:30:48 [worker(5292)] [INFO] engine eventloop has terminated, propagating exit event...
09:30:48 [worker(5292)] [INFO] waiting for engine exit mode...
09:30:48 [worker(5292)] [INFO] exiting worker (to be restarted)
09:30:48 [daemon(8932)] [INFO] worker requested a restart, spawning a new one...
09:30:48 [daemon(8932)] [INFO] spawning the worker process...
09:30:48 [worker(6808)] [INFO] reading configs from: "C:\\Users\\COMPUTER406_1\\AppData\\Roaming\\espanso"
09:30:48 [worker(6808)] [INFO] reading packages from: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso\\packages"
09:30:48 [worker(6808)] [INFO] using runtime dir: "C:\\Users\\COMPUTER406_1\\AppData\\Local\\espanso"
09:30:48 [worker(6808)] [INFO] system info: Windows v11 (22621) - kernel: 22621
09:30:48 [worker(6808)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
09:30:48 [worker(6808)] [INFO] monitoring the status of the daemon process
09:30:48 [worker(6808)] [INFO] using Win32AppInfoProvider
09:30:48 [worker(6808)] [INFO] using Win32Source
09:30:48 [worker(6808)] [ERROR] unable to register hotkey: ALT+SPACE
09:30:48 [worker(6808)] [INFO] using Win32Injector
09:30:48 [worker(6808)] [INFO] using Win32Clipboard
```

### Your environment

- Public source code: Didn't found where to get it
- Environment name and version (e.g., Rust 1.59.0): Didn't found where to get it
- Operating system and version : Windows 11 Pro 22621.3593
- Espanso version: 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by stewcam** [comment]
Your config is under `%appdata%` but your packages are under `%localappdata%`. With a standard Espanso v2 installation you would expected both config and packages to be under `%appdata%`. Suggest you uninstall both legacy version and v2 and then reinstall v2. After that Espanso should pick up your matches from `%appdata%\espanso\match`.

**Comment by HossBigft** [comment]
> Your config is under `%appdata%` but your packages are under `%localappdata%`. With a standard Espanso v2 installation you would expected both config and packages to be under `%appdata%`. Suggest you uninstall both legacy version and v2 and then reinstall v2. After that Espanso should pick up your matches from `%appdata%\espanso\match`.

I initially installed last version, then rebooted the pc.  Then tried different versions but only legacy would work. After your reply I deleted folders espanso in Appdata/Local and Appdata/Roaming, then reinstalled last version. It didn't help.

**Comment by stewcam** [comment]
@HossBigft From your last comment I am not sure that you uninstalled the legacy version before reinstalling v2. However, *if* you did/do so and v2 does not work, there is an alternative approach you could try:
1. Close any running version of Espanso
2. Extract portable Espanso to a folder on your hard drive.
3. Open a Powershell window in your portable Espanso folder and enter the following command:
```
.\espanso.cmd start
```
You must use this command instead of  `START_ESPANSO.bat`.
4. Portable Espanso should start with your matches under the portable Espanso folder in subfolder `.espanso\match`.

**Comment by HossBigft** [comment]
> @HossBigft From your last comment I am not sure that you uninstalled the legacy version before reinstalling v2. However, _if_ you did/do so and v2 does not work, there is an alternative approach you could try:
> 
> 1. Close any running version of Espanso
> 2. Extract portable Espanso to a folder on your hard drive.
> 3. Open a Powershell window in your portable Espanso folder and enter the following command:
> 
> ```
> .\espanso.cmd start
> ```
> 
> You must use this command instead of `START_ESPANSO.bat`. 4. Portable Espanso should start with your matches under the portable Espanso folder in subfolder `.espanso\match`.

Yes, I uninstalled legacy version. I just wanted to point out that it wasn't installed to begin with.  I ran portable version as you told to no avail, no new things in the logs either.

**Comment by stewcam** [comment]
Like yourself I am running under Windows 11 Pro 23H2. I use both installed and portable Espanso v2.2.1 and both are generally very stable. Sometimes Espanso triggers will stop working, which in my case is invariably due to an issue with parsing part of a match file. Hope you can work it out - sorry I could not be more helpful.

**Comment by HossBigft** [comment]
I'm using it on my win 10 home pc and it works fine but on my work pc it just doesn't. Thank you for help!

**Comment by HossBigft** [comment]
The problem was that I was using Moonlight/Sunshine to type. Autohotkey was working though.

**Comment by stewcam** [comment]
Thanks for the update - good that you worked it out!
