### ISSUE TITLE
Getting mixed up output on Windows using 'portet' app

### ISSUE THREAD

**Issue by mmoole** [federico-terzi/espanso#1983]
### Description

When using espanso for text replacement on some other apps like Creo Parametric (xtop.exe), then the output is mixed up when using the inject back-end. The clipboard back-end seems to work fine. (This app is a proprietary application that is kind of 'portet' from the unix world or at least contains some stuff working like this, whatever that might mean.)
At the same time, text replacement in MS Remote Desktop is 'a bit' mixed, but less than in this app.

### Steps to reproduce

1. Use this config as trigger
```
   # Datum
  - trigger: ":dd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
```

1. change to a window of Creo Parametric (xtop.exe) and press `:dd`
2. observe what happens:
  - when using clipboard back-end: it works as configured using clipboard
  - when using inject back-end, the trigger that was entered is removed with the delays as configured and the replaced text appears at one point in time (not certain if that should happen when `key_delay: 100` and `inject_delay: 100` are set (Changing inject_delay to smaller numbers doesn't change anything).

Since this is a proprietary app I am not certain if this counts a reproducible. Increasing `inject_delay` and `key_delay` did seemingly solve the problems I had in MS Remote Desktop (connected from Windows to Windows).

### Expected behavior

Espanso should replace the trigger with the correct date, e.g. `2024-06-06`

### Screenshots

![image](https://github.com/espanso/espanso/assets/678765/8dee2d59-ff78-441d-8ca7-275b595d67e8)
![image](https://github.com/espanso/espanso/assets/678765/b477014b-64f8-421b-9bd3-25b8d903e521)
![image](https://github.com/espanso/espanso/assets/678765/67f5fef1-9415-4399-b601-aa096abc6559)
![image](https://github.com/espanso/espanso/assets/678765/0ccd2fa3-e556-484f-a8df-7b74a7d85c96)

### Logs

```
12:45:20 [worker(20060)] [INFO] system info: Windows v10 (19045) - kernel: 19045
12:45:20 [worker(20060)] [INFO] using Win32AppInfoProvider
12:45:20 [worker(20060)] [INFO] using Win32Source
12:45:20 [worker(20060)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
12:45:20 [worker(20060)] [INFO] monitoring the status of the daemon process
12:45:20 [worker(20060)] [INFO] using Win32Injector
12:45:20 [worker(20060)] [INFO] using Win32Clipboard
12:45:22 [worker(20060)] [WARN] unable to find espanso AppUserModelID in the list of registered ones, falling back to Powershell
```

### Your environment

- Public source code: ?
- Environment name and version (e.g., Rust 1.59.0): ?
- Operating system and version: Windows 10 22H2 (Build 19045.4412)
- Espanso version: espanso 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
The answer is to use the `clipboard` backend. Not all programs are happy with both, which is why we need them.

Either use `backend: clipboard` globally in your `default.yml` file, or set up an app-specific configuration, specifying the same, for Creo Parametric

**Comment by smeech** [comment]
I'll close this for now, but will see any replies and can reopen if necessary.

**Comment by mmoole** [comment]
Just a small addition: setting instead `clipboard_threshold` to `1` is also great since it uses the clipboard only for strings longer than one character, and when inserting unicode symbols and the like that is more handy than having all those symbols in clipboard history.
