### ISSUE TITLE
Espanso as App Launcher

### ISSUE THREAD

**Issue by boncuk10** [federico-terzi/espanso#1985]
### Description

is there a easy way that Espanso can search for installed app at windows and start it? 

I want to replace https://www.flowlauncher.com/ on my computer 👍

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by boncuk10** [comment]
![IMG_0628](https://github.com/espanso/espanso/assets/54523503/5a942989-0568-4dfe-8e05-fcd6ea35f99f)

**Comment by joh6nn** [comment]
sorry, no, Espanso doesn't have any features for that right now, and it wouldn't be easy to add

**Comment by smeech** [comment]
I agree. I would require extensive scripting or use of another utility, to which Espanso would have little to add.
I'll close this, if that's OK.

**Comment by cubimon** [comment]
I  am just wondering why this was closed, if empty replace expression is possible it should be enough to work as app launcher

**Comment by smeech** [comment]
Launching is fine, and fairly easily scripted, but @boncuk10 was requesting something that would search for installed programs and present them for selection. That would be difficult for Espanso, particularly across platforms, and there are already tools available that can do this.

**Comment by cubimon** [comment]
Actually my main problem is that espanso 2 doesn't allow empty replace and if a variable is unused the cmd isn't execute.

But shouldn't the search shortcut prove a way to show all programs for selection?
