### ISSUE TITLE
espanso does not work on ubuntu 24.04 (noble)

### ISSUE THREAD

**Issue by valia0906** [federico-terzi/espanso#1986]
### Description

When try to run espanso it gives error: espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory

### Steps to reproduce

espanso service start

### Expected behavior

espanso started successfully

### Logs

espanso: error while loading shared libraries: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory

### Your environment

- Operating system and version (e.g., Ubuntu 24.04 LTS):
- Espanso version 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
Please see the discussion at #1793. There may be a solution there.
I'll close this as duplicate, but will happy to reopen if it's not!

**Comment by McThump** [comment]
I am having the same problem. Espanso broke after upgrading from Ubunto 22.04.4 to 24.04.1. Tried various possible solutions from the discussion at #1793 but didn't work.

**Comment by stpp2** [comment]
> I am having the same problem. Espanso broke after upgrading from Ubunto 22.04.4 to 24.04.1. Tried various possible solutions from the discussion at #1793 but didn't work.

Same

**Comment by smeech** [comment]
@davidvv's [method](https://github.com/espanso/espanso/issues/1793#issuecomment-1919055522) worked for me in my fresh Ubuntu 24.04 Wayland VM.
Probably best to watch the discussion in #1793. It certainly needs to be fixed.
