### ISSUE TITLE
In-app UI for configuration

### ISSUE THREAD

**Issue by lduperval** [federico-terzi/espanso#1993]
### Description

I've used a few other tools like espanso and they all have a UI to enter the expansions directly. It would be great if espanso could do that also.

### Motivation

As a new user, dealing with the YAML configuration is a bit daunting. Having a UI that makes it easier would be very welcome.

### Alternatives

If that's too complicated, maybe a menu in the tray to open the config folder or the config files.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
There's a GUI in development at https://github.com/Pebkac03/espanso_gui.

Alternatively, there's a dedicated editor for Windows at https://ee.qqv.com.au/. It works quite well in Linux Wine.

**Comment by lduperval** [comment]
Sorry about that, I was coming t delete my comment. I just noticed the big banner in the docs… I found it weird that it wasn<t proposed as an enhancement already!
