### ISSUE TITLE
Multiline replacement doesn't get replaced correctly sometimes and instead letter 'v' is the output

### ISSUE THREAD

**Issue by typoman** [federico-terzi/espanso#2005]
### Description

Output of the following trigger works as expected:
```
  - trigger: "pdfo==" # pdf outlines using the current selected file in the finder
    replace: |
      cmd1
      cmd2
```

But here the output is only 'v'
```
  - trigger: "pdfo==" # pdf outlines using the current selected file in the finder
    replace: |
      filePath=$(osascript -e 'tell application "Finder" to get the POSIX path of (the selection as alias)')
      fileName=$(basename "$filePath" .pdf)
      outFileName="${fileName}-outlines.pdf"
      gs -dNoOutputFonts -sDEVICE=pdfwrite -o "$outFileName" "$filePath"
```

### Your environment
- Environment name and version (e.g., Rust 1.59.0): Anywhere in the OS
- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Mac OSX 12.7.5
- Espanso version (e.g., 2.1.4-beta): 2.1.8

**Comment by smeech** [comment]
The output of `v` in response to a trigger is usually a `clipboard` injection method problem.

If you're using `backend: auto` in your `default.yml` or app-specific configuration, Espanso switches from `inject` to `clipboard` at the threshold set by your `clipboard_threshold:` setting (default 100) for long expansions like these.

Options:
- Update to the current release of Espanso - I'm not sure if this will fix the problem, however.
- In Linux, toggling `disable_x11_fast_inject:` `true`/`false` can help, but probably won't make a difference for macOS. 
- Use `backend: inject` for the relevant program.
- If this is the only expansion causing problems, you could add `force_mode: keys` to the trigger.
- Increase your `clipboard_threshold:` setting to 250 or so.

**Comment by typoman** [comment]
Thank you very much, updating to the [latest version](https://github.com/espanso/espanso/releases/tag/v2.2.1) fixed the issue.
