### ISSUE TITLE
Incorrect cursor placement

### ISSUE THREAD

**Issue by yaz008** [federico-terzi/espanso#2010]
### Description

# Incorrect Cursor Placement

The `$|$` snippet interacts with triple backticks (```) incorrectly 

For example, this match:
```yml
  - trigger: :lang
    replace: |
      ```$|$
      {{clip}}
      ```
    vars:
      - name: clip
        type: clipboard
```

Is exactly equivalent to this one:
```yml
  - trigger: :lang
    replace: |
      $|$```
      {{clip}}
      ```
    vars:
      - name: clip
        type: clipboard
```

### Steps to reproduce

1. Define any match with triple backticks at the beginning
2. Place `$|$` near the backticks

### Expected behavior

I expect the following matches to differ:

```yml
  - trigger: :lang
    replace: |
      ```$|$
      {{clip}}
      ```
    vars:
      - name: clip
        type: clipboard
```

And

```yml
  - trigger: :lang
    replace: |
      $|$```
      {{clip}}
      ```
    vars:
      - name: clip
        type: clipboard
```

### Screenshots

_No response_

### Logs

The bug has no effects in the logs

### Your environment

- Operating system and version: **Windows 10**
- Espanso version: **2.2.1**


### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by stewcam** [comment]
I tried this on Windows 11 with Espanso 2.2.1 and found that the cursor placement was as expected for both matches. That is, I could not replicate the issue.

**Comment by smeech** [comment]
It works as expected here (Linux Mint Xfce X11), too.

It's likely to be an injection method problem. Would you try adding the methods `force_mode: clipboard`|`keys` to the trigger, i.e.:
```yml
  - trigger: :lang
    replace: |
      ```$|$
      {{clip}}
      ```
    vars:
      - name: clip
        type: clipboard
    force_mode: clipboard
```
and see if that makes a difference, and we can take it from there.

**Comment by yaz008** [comment]
> It works as expected here (Linux Mint Xfce X11), too.
> 
> It's likely to be an injection method problem. Would you try adding the methods `force_mode: clipboard`|`keys` to the trigger, i.e.:
> 
> ```yaml
>   - trigger: :lang
>     replace: |
>       ```$|$
>       {{clip}}
>       ```
>     vars:
>       - name: clip
>         type: clipboard
>     force_mode: clipboard
> ```
> 
> and see if that makes a difference, and we can take it from there.

Switching to keys was indeed helpful, thank you!
I didn't think of it

**Comment by smeech** [comment]
> Switching to keys was indeed helpful, thank you!

Excellent.

Have a look at the [`docs`](https://espanso.org/docs/matches/basics/#injection-mechanism). You may need an [app-specific](https://espanso.org/docs/configuration/app-specific-configurations/) [backend setting](https://espanso.org/docs/configuration/options/#options-reference) for that particular program.
