### ISSUE TITLE
Won't start saying that it's not in the Applications folder, but it is

### ISSUE THREAD

**Issue by alltiagocom** [federico-terzi/espanso#2012]
### Description

I can't run Espanso, because I get this message
![image](https://github.com/espanso/espanso/assets/96640778/9341de82-178a-437c-821d-57ea2fe7f189)

### Steps to reproduce

I downloaded the ZIP file to a folder on my Mac called "Inbox". Unzipped it and moved it to the Applications folder.
Espanso keeps saying it's not there when it is.

I thought that maybe unzipping it in a different folder would be the issue (which I don't think it would, but I always check things that probably don't make sense, just in case...), so I deleted the app from the Applications folder, moved the ZIP file to the Applications folder and unzipped it there. Same result

I'm on the latest version of Espanso 2.2.1 on macOS Catalina 10.15.7

### Screenshots

![SCR-20240711-iafp](https://github.com/espanso/espanso/assets/96640778/17eb16a3-f332-433e-9af6-ec4d2b8f95e0)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by AucaCoyan** [comment]
Hi! thanks for submitting an issue. The strange thing is that this window is coming from [wizard_gui.cpp](https://github.com/espanso/espanso/blob/a80be447640496cc10d9b52aaf84c2ee03d2ee47/espanso-modulo/src/sys/wizard/wizard_gui.cpp#L84). Now, I'm have no idea of C++, but I don't see any `if`s or `switch`es there. It's strange that this line is out there without being surrounded by a boolean

**Comment by alltiagocom** [comment]
> Hi! thanks for submitting an issue. The strange thing is that this window is coming from [wizard_gui.cpp](https://github.com/espanso/espanso/blob/a80be447640496cc10d9b52aaf84c2ee03d2ee47/espanso-modulo/src/sys/wizard/wizard_gui.cpp#L84). Now, I'm have no idea of C++, but I don't see any `if`s or `switch`es there. It's strange that this line is out there without being surrounded by a boolean

I'm no developer myself, so that's too technical for me, I'm sorry...
Do you know if it's possible to start the app without going through the wizard?

**Comment by alltiagocom** [comment]
@AucaCoyan 
Just by accident, I thought of moving the app to the user's Applications folder (~/Applications) instead of the system's Applications folder (/Applications) and now I can see a different panel:

![image](https://github.com/user-attachments/assets/45ed53ae-264f-4bc0-a4b4-071334409b19)

It's weird that this behaves like this, because by default all applications go to the main applications folder, not the user's. I have no application on that folder. This is the first time I have to have an application there.

Unless there's a very good reason to do this (which is weird, because that's the only app that behaves like this), then I would say that this is a bug that should be fixed.

Hope this detail helps.

**Comment by AucaCoyan** [comment]
Oh, I didn't expect to be actually 2 applications folders.
The bare minimum is make a clarification of which folder to use, but it should also work on both, or at least we should know why not in one of them.
Thanks for the test!

**Comment by AucaCoyan** [comment]
Sadly, it's a macOS feature we are dealing with (and it's a good one!)

From a similar issue, we have this line [right here](https://github.com/espanso/espanso/blob/a80be447640496cc10d9b52aaf84c2ee03d2ee47/espanso/src/cli/service/macos.rs#L40) that tells us about #844 `App Translocation`. 

Explained here on [apple.stackexchange](https://apple.stackexchange.com/questions/462468/how-does-apple-manage-apps-in-downloads-and-applications-differently)
