### ISSUE TITLE
espanso not workin when kinto is running

### ISSUE THREAD

**Issue by owzim** [federico-terzi/espanso#202]
I know it is maybe not an issue on your side, but [kinto](https://github.com/rbreaves/kinto) prevents [espanso](https://github.com/federico-terzi/espanso) from expanding text, so I am creating an issue in both repos. If kinto is not running espanso works like expected.

I don't know on which side the issue can be fixed and I really don't expect either of you to fix it, but perhaps one of you can look into it.

* [espanso issue](https://github.com/federico-terzi/espanso/issues/202)
* [kinto issue](https://github.com/rbreaves/kinto/issues/61)

Thanks

**Comment by federico-terzi** [comment]
Hey @owzim,

Does espanso completely stop working when kinto is activated?
Does the toggle shortcut work?
Could you please post the output of `espanso log` when kinto is running?

Cheers :)

**Comment by rbreaves** [comment]
@federico-terzi 

I'm the author of Kinto and you're app looks to be pretty impressive, so I've installed it on one of my VMs. I am not sure what it is that Kinto would be doing that causes espanso to fail, it applies custom keymaps though via xkbcomp.

```
@pop-os:~/Documents/git-projects$ espanso log
17:01:44 [ INFO] espanso version 0.5.2
17:01:44 [ INFO] using config path: /home/ryanreaves/.config/espanso
17:01:44 [ INFO] using package path: /home/ryanreaves/.local/share/espanso/packages
17:01:44 [ INFO] starting daemon...
17:01:44 [ WARN] Unable to delete Unix socket: No such file or directory (os error 2)
17:01:44 [ INFO] Binded to IPC unix socket: /home/ryanreaves/.local/share/espanso/espanso.sock
17:01:44 [ INFO] Creating espanso icon in '/home/ryanreaves/.local/share/espanso/icon.png'
17:01:44 [ INFO] espanso is running!
```

An example of a custom keymap file that is applied for gui apps.
```
setxkbmap -option;xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.mac.gui $DISPLAY
```
~/.xkb/keymap/kbd.mac.gui
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete+mac_gui(addmac_levels)"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+us:2+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(mac_levelssym)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

**Comment by rbreaves** [comment]
@owzim @federico-terzi 

I think I figured it out, just needed to restart the espanso service after the kinto keyswap service. That appears to work for me, I guess the default setxkbmap mapping is sufficiently different from the custom one that espanso has difficulty working with it. My guess is that espanso does not monitor or watch for any xkb keymap changes - and in most cases why would it, keymaps don't change that often so a single load would usually be fine.

```
systemctl --user restart espanso
```

**Comment by federico-terzi** [comment]
Hey @rbreaves ,
Thanks a lot for your help!

> I think I figured it out, just needed to restart the espanso service after the kinto keyswap service. That appears to work for me, I guess the default setxkbmap mapping is sufficiently different from the custom one that espanso has difficulty working with it

I definitely think it could be it, though under the hood espanso uses `libxdo` to inject text, so it could be a problem related to the library. 

> My guess is that espanso does not monitor or watch for any xkb keymap changes - and in most cases why would it, keymaps don't change that often so a single load would usually be fine.

I'm not super experienced with layouts remapping on Linux. The only thing espanso does is refreshing the keyboard mapping when it detects a `MappingNotify` event:

```c
if (event.type == MappingNotify) {
    XMappingEvent *e = (XMappingEvent *) &event;
    if (e->request == MappingKeyboard) {
        XRefreshKeyboardMapping(e);
    }
}
```

I'm not sure though if that accounts for xkb keymap changes, do you have any tip about it? :)

By the way, I like kinto a lot, and seems like a wonderful tool for those switching from macOS and Linux frequently. I often mistype some keys myself after switching OSes.

Cheers :)

**Comment by rbreaves** [comment]
Hmmm it would make sense to assume that applying a keymap via xkbcomp would trigger the MappingNotify event, but I honestly don't know. Kinto uses the xlib library in C and I had a heck of a time debugging it so that resizing or moving a Window wouldn't attempt to trigger a keymap change lol. My code would throw it out regardless, but I had to add write a function just to prevent the XNextEvent from triggering when it did not need to and go through the documentation on all the possible event types and their related integer id values.

Originally I believe I wanted to apply my custom keymaps via setxkbmap, but I couldn't ever figure out how to make that work and some people suggested xkbcomp and that was simply what worked for me.

And thanks, it's taken some time and false starts to get Kinto where it is at lol.

**Comment by owzim** [comment]
@rbreaves @federico-terzi thanks a lot you guys for looking into it. For the time being the @rbreaves' suggestion to restart both services with kinto first, works for me.

@federico-terzi 
The expansion is triggered but empty

**Comment by federico-terzi** [comment]
Hey @rbreaves,
Sorry for the late reply, I've gone through some busy days!

> Hmmm it would make sense to assume that applying a keymap via xkbcomp would trigger the MappingNotify event, but I honestly don't know. Kinto uses the xlib library in C and I had a heck of a time debugging it so that resizing or moving a Window wouldn't attempt to trigger a keymap change lol. My code would throw it out regardless, but I had to add write a function just to prevent the XNextEvent from triggering when it did not need to and go through the documentation on all the possible event types and their related integer id values.
> 
> Originally I believe I wanted to apply my custom keymaps via setxkbmap, but I couldn't ever figure out how to make that work and some people suggested xkbcomp and that was simply what worked for me.
> 
> And thanks, it's taken some time and false starts to get Kinto where it is at lol.

Thank you very much your help, it's a great starting point and I'll definitely look into it as soon as I can!

> The expansion is triggered but empty

@owzim it definitely seems like espanso is struggling with the new keymap. That said, at least the "deletion" of the trigger happens and this is good news.

Cheers :)

**Comment by rbreaves** [comment]
No problem @federico-terzi and for now I have suggested that @owzim just adds a startup delay to the espanso service file as I think something like this would be sufficient in delaying it beyond the first custom keymap that Kinto will apply.

```
[Service]
ExecStartPre=/bin/sleep 30
```

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue, thank you @rbreaves for your help :)
Let me know if you have other questions.
Cheers :)

**Comment by bigplayer-ai** [comment]
I have a similar issue on windows 11 23H2...
I don't know on which side the issue can be fixed and I really don't expect either of you to fix it, but perhaps one of you can look into it.

[kinto issue](https://github.com/rbreaves/kinto/issues/876) :[https://github.com/rbreaves/kinto/issues/876](https://github.com/rbreaves/kinto/issues/876)
[espanso issue](https://github.com/espanso/espanso/issues/2061): [https://github.com/espanso/espanso/issues/2061](https://github.com/espanso/espanso/issues/2061)
Thanks
