### ISSUE TITLE
Some symbols that indicate the end of a word don't trigger whole-word matches

### ISSUE THREAD

**Issue by michaelmarch84** [federico-terzi/espanso#2023]
### Description

Seems like only period (.), comma (,), question mark (?), and exclamation mark (!) can trigger whole-word matches. Seems like at least parentheses (()), brackets ([]), quotation marks, (',")semicolons (;), and colons (:) should, too. If there's some reason why this is not always desirable, could it be configurable?

### Steps to reproduce

define a match, e.g., 
```
  - trigger: "t"
    replace: "the"
    propagate_case: true
    word: true
```

### Expected behavior

t)
t]
t;
t:

should all trigger replacements

### Your environment

Latest MacOS
espanso 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
The `word_separators` [option](https://espanso.org/docs/configuration/options/#options-reference) documentation is ahead of the release, I'm afraid. If you add the sequence to your `default.yml` they will. I.e.
```yml
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\t", "'", "\"", "\x0c", "(", ")", "[", "]", "{", "}", "<", ">", ":", ";"]
```
