### ISSUE TITLE
`espanso package update --all` command

### ISSUE THREAD

**Issue by AucaCoyan** [federico-terzi/espanso#2024]
### Description

It's written as a `TODO` element in the code, so I'm writing an issue for that.

### Motivation

I don't want to type every single package to update. I want a command to write so it updates all the packages at once.

### Have you tried building it? Or would you like it?

- [X] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
[`espanso package update all`](https://espanso.org/docs/packages/basics/#updating-all-packages) is a thing already.

**Comment by AucaCoyan** [comment]
Whoops! Then the `TODO` it's done!
That was fast 🤣
