### ISSUE TITLE
[FEATURE REQUEST] Expanding Espanso functionality with AutoHotKey (AHK) functionality

### ISSUE THREAD

**Issue by mercifulboss** [federico-terzi/espanso#2037]
### Description

Since Linux (wayland) and MacOS do not have AHK or alternatives (as far as I am aware), it would be nice to have the ability to do basic things with Espanso like moving the mouse in seperate places on the screen, simulating key presses, etc similar to what you can do on AHK. In many ways, Espanso already does this, so I can't imagine this would be too difficult

### Motivation

Linux on Wayland in particular, seems to lack alot of scripting functionality and it would be nice to add it - particularly with the unique way that Espanso manages to do this.  Since Wayland is the future on Linux, it would be nice to be able to implement various mouse movements, mouse clicks and keyboard presses and automate certain tasks (like on video editing for example)

### Alternatives

I tried doing some of this on Espanso with existing functionality, but I found that I was having trouble getting hotkeys registered and I couldn't find a documented api for mouse movements.

I have limited coding knowledge, otherwise I'd be willing to help expand this functionality myself.

Please let me know if this is out of scope of this project

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
Although much requested, I think mouse movement and window management are beyond the scope of Espanso.

I'd achieve these in Linux Mint using tools like `xdotool` and `wmctrl`, and the system hotkeys, but the Wayland alternatives don't appear mature. There might be a version of the former for macOS.

**Comment by mercifulboss** [comment]
> Although much requested, I think mouse movement and window management are beyond the scope of Espanso.
> 
> I'd achieve these in Linux Mint using tools like `xdotool` and `wmctrl`, and the system hotkeys, but the Wayland alternatives don't appear mature. There might be a version of the former for macOS.

Yes I understand, thank you for your response. I just thought that its a logical expansion of espanso, since AHK has a similar feature of expanding typed text. I was hoping it could be added nonetheless but I understand it would be a great deal of extra work :)

**Comment by knl** [comment]
@mercifulboss on macOS you can use [Hammerspoon](https://www.hammerspoon.org/) for most of these tasks.

**Comment by AucaCoyan** [comment]
> basic things with Espanso like moving the mouse in seperate places on the screen, simulating key presses, etc similar to what you can do on AHK. In many ways, Espanso already does this, so I can't imagine this would be too difficult

Yeah, no, it's not that easy. It's clearly out of scope for a text expander
