### ISSUE TITLE
Can't use § (section sign) in a trigger

### ISSUE THREAD

**Issue by psu** [federico-terzi/espanso#2039]
### Description

Creating triggers with "§" (section sign) instead of for example ":" (colon) doesn't work.

Is there a documentation for what limitations there are for triggers? I cannot get the § char to work with regex either, btw.

### Steps to reproduce

Create a simple match:
```matches:
  - trigger: '§hello'
    replace: 'world'
```

### Expected behavior

"§hello" to be replaced with "world"

### Your environment

- Public source code: Brew install
- Operating system and version: MacOS Sonoma 14.5 (Intel)
- Espanso version: 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
It's fine here (`§` = \<Shift>\<AltGr>+s), so may depend on your keyboard and locale.
Mine's `"gb"` layout, `LANG=en_GB.UTF-8`.

**Comment by psu** [comment]
Interesting! I'm on Mac and have tried both Swedish and US input source without any luck.
On Swedish keyboard layout you input "§" by pressing the key above TAB without any modifier at all, that's why it is useful (the screenshot from MacOS settings shows the wrong character "<").

<img width="827" alt="Screenshot 2024-08-16 at 14 21 21" src="https://github.com/user-attachments/assets/2f04dacd-1563-4cb9-ada7-8835ecd68a81">

**Comment by smeech** [comment]
That would be the backtick \` for me, which works fine - I wonder if that might work for you - perhaps try "  - trigger: '\`hello'" 
![image](https://github.com/user-attachments/assets/5a5a0362-7ee1-4c2a-bebe-27462183cb76)
and see if that responds to `§`, the same key on your keyboard:

![image](https://github.com/user-attachments/assets/331b4e63-9647-4490-b14a-091c62594b45)

Mind you, one of the problems with using the backtick prefix at the beginning of YAML values is that you then have to enclose them in quotes. Not necessary with `§`.

**Comment by psu** [comment]
Yeah, backtick works fine, but when I type the backtick character. Still no luck with the § section character.
Most characters of course work perfectly fine: /%#! etc. 
When tested some random, euro char € doesn't work either (less of a surprise, though).

**Comment by mthies-unibi** [comment]
This is a macOS-specific bug that has already been fixed in the `dev` branch: [native.mm](https://github.com/espanso/espanso/blob/fd9a7dd4f2afccaeb61623286b1230c0df0c7033/espanso-detect/src/mac/native.mm#L77)

The bug affects all characters outside the 7-bit ASCII range, so `§` is affected but not the backtick.

**Comment by psu** [comment]
Duplicate of bug fixed here: #1967
