### ISSUE TITLE
Replace quotes

### ISSUE THREAD

**Issue by shaund** [federico-terzi/espanso#204]
With this in my default.yml file

```
  - trigger: ".\" a"
    replace: ".\" A"
```
I get this as output`.' A`

If I use `".' a"` I get `. "A`

Also in anything with auto brackets, I get `.' A'`, I guess because it's typing rather than pasting?

**Comment by shaund** [comment]
You can disregard the first part, it was interference from autohotkey. I switched to clipboard mode and everything works (though losing copied images is a minor annoyance).

**Comment by federico-terzi** [comment]
Hey @shaund ,

Thanks for the feedback, in which ways did AutoHotKey interfere with espanso?

Cheers :)
