### ISSUE TITLE
[FEATURE REQUEST] Network Based Include / Exclude Rules

### ISSUE THREAD

**Issue by IsaacD277** [federico-terzi/espanso#2042]
### Description

I work at a company and have placed some of my espanso files on a shared server so that others on the team can access them. I would like to have a local copy on my machine in the case I am not on the company network.
It would be cool to have essentially App-specific configurations but based on the network I am connected to, so that espanso can fall back on my local backup copy if I'm not connected to the server.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by joh6nn** [comment]
If you're trying to share some of your expansions with co-workers, you're likely better served by using a privately hosted package: https://espanso.org/docs/packages/external-packages/#private-alternatives

**Comment by smeech** [comment]
Having the Espanso files on a shared network location means minor changes are automatically rolled out to others - that's how I used to configure AutoHotKey at work, although I guess my own machine used my local files, which I copied across to the network when I was happy with them.

I guess we're back to the issue of [enabling or disabling](https://discord.com/channels/884163483409731584/1013915939156275210/1275690216396685357) files programmatically for now. An alternative is to sync the files locally from the network at boot so they're always available locally.

**Comment by IsaacD277** [comment]
If I create an external package, would everybody in the company have to manually pull the latest changes?

**Comment by smeech** [comment]
@joh6nn's suggestion would require an `espanso package install` command on each machine.

**Comment by IsaacD277** [comment]
Using packages works as the solution!
