### ISSUE TITLE
Inject mode does not work with Windows PowerShell on ConEmu/Cmder

### ISSUE THREAD

**Issue by virginviolet** [federico-terzi/espanso#2046]
### Description

Unless I set backend to Clipboard, whenever I try to expand text in Windows PowerShell with [Cmder](https://github.com/cmderdev/cmder/), it removes the trigger text, but nothing is inserted. It works fine with cmd in Cmder, and it also works in Microsoft's Windows PowerShell app. 

EDIT: It works with Cmder in Windows Terminal, so presumably, it's an issue with [ConEmu](https://github.com/Maximus5/ConEmu) that Cmder by default relies on.

### Steps to reproduce

1. Open PowerShell in Cmder, either by typing powershell in a cmd console, or create a new console with a PowerShell task.
2. Type out a trigger.

### Expected behavior

`replace` text gets inserted.

### Logs

Nothing gets logged.

### Your environment

- Operating system and version: Windows 11
- Espanso version: 2.2.1
- PowerShell version: Windows PowerShell 5.1
- Cmder version: 1.3.25.328

**Comment by smeech** [comment]
That's why we have alternative backends. 

I would suggest you create an [app-specific configuration](https://espanso.org/docs/configuration/app-specific-configurations/) for Cmder, to use the Clipboard backend there. Or have I misunderstood the problem?

**Comment by virginviolet** [comment]
Yes! That would solve the problem.
