### ISSUE TITLE
Multiple trigger not working -- Error on save of config file

### ISSUE THREAD

**Issue by rpnfan** [federico-terzi/espanso#2050]
### Description

The following works

```
  - trigger: "nbhqq" # no-breaking hyphen -
    replace: "‑"
```
while

```
  - trigger: [nbhqq, nb-qq] # no-breaking hyphen - 
    replace: "‑"
```

gives an error. 

### Steps to reproduce

Try saving the yml file with the second definition.

### Expected behavior

Both triggers `nbhqq `and `nb-qq`  work as a single trigger, but give an error when combined. Seems like a bug to me.

### Logs

(ERROR) unable to Ioad match group "C:\\_ohnelnst\\espanso-portable\\.espanso\\match\\base.yml"
Caused by:
O: failed to parse YAML match group
1: matches[2J.trigger: invalid type: sequencet expected a string at line 21 column 14

### Your environment

Windows 11, 
- Espanso version 1.02 (jtroo fork), which is is based on version 2.1.8

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
You're missing the `s` on the end of [`triggers:`](https://espanso.org/docs/matches/basics/#multiple-triggers). :smile:

**Comment by rpnfan** [comment]
Oh, thanks. I overlooked that indeed! IMO a strange decision to use a different name here, because the list already tells that one is wanting to use multiple triggers. :-) But my fault, sorry for not catching that myself and thanks for the help!

**Comment by smeech** [comment]
I agree - it would make sense for `trigger:` to be followed by a single item, or a sequence.
