### ISSUE TITLE
error while loading shared libraries: libwx_baseu-3.0.so.0

### ISSUE THREAD

**Issue by ghost** [federico-terzi/espanso#2054]
### Description

When running the **espanso service register** command on **Ubuntu 24.04.1 LTS** operating system, the following error is issued:

espanso: error while loading shared libraries: **libwx_baseu-3.0.so.0**: cannot open shared object file: No such file or directory

And it is not found when installing **libwx_baseu-3.0.so.0** in ubuntu.

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS):
- Espanso version (e.g., 2.1.4-beta):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by SkepticMystic** [comment]
Just ran into this issue myself, did you find a solution?
