### ISSUE TITLE
Multi-line expansion breaks on "lorum ipsum" paragraph

### ISSUE THREAD

**Issue by eccentricon** [federico-terzi/espanso#2064]
### Description

Using either `|` or `>` to produce a "lorum ipsum" paragraph doesn't seem to work. I'm new to Espanso, so I may be doing something wrong. I have no packages installed, just Espanso 2.2.1.

### Steps to reproduce

The following works:

```
  - trigger: ":test"
    replace: |
      test
      multiline
```

The following **does not** work:

```
  - trigger: ";;lorum"
    replace: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
```

The following doesn't work either:

```
  - trigger: ";;lorum"
    replace: >
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
```

### Logs

16:31:18 [daemon(2146)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
16:31:18 [daemon(2146)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
16:31:18 [daemon(2146)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
16:31:18 [daemon(2146)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
16:31:19 [daemon(2146)] [INFO] espanso version: 2.2.1
16:31:19 [daemon(2146)] [INFO] spawning the worker process...
16:31:19 [daemon(2146)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansodaemonv2.sock
16:31:19 [daemon(2146)] [INFO] watching for changes in path: "/Users/my_username_redacted/Library/Application Support/espanso"
16:31:19 [worker(2150)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
16:31:19 [worker(2150)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
16:31:19 [worker(2150)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
16:31:19 [worker(2150)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
16:31:19 [worker(2150)] [INFO] using CocoaAppInfoProvider
16:31:19 [worker(2150)] [INFO] using CocoaSource
16:31:19 [worker(2150)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
16:31:19 [worker(2150)] [INFO] using MacInjector
16:31:19 [worker(2150)] [INFO] using CocoaClipboard
16:31:19 [worker(2150)] [INFO] monitoring the status of secure input
16:31:19 [worker(2150)] [INFO] monitoring the status of the daemon process
16:31:19 [worker(2150)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
16:31:36 [worker(2150)] [INFO] secure input has been disabled
16:38:15 [worker(2150)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
16:38:23 [worker(2150)] [INFO] secure input has been disabled
17:07:26 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
17:07:26 [worker(2150)] [INFO] engine eventloop has terminated, propagating exit event...
17:07:26 [worker(2150)] [INFO] waiting for engine exit mode...
17:07:26 [worker(2150)] [INFO] exiting worker process...
17:07:26 [daemon(2146)] [INFO] spawning the worker process...
17:07:26 [worker(7129)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
17:07:26 [worker(7129)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
17:07:26 [worker(7129)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
17:07:26 [worker(7129)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
17:07:26 [worker(7129)] [INFO] using CocoaAppInfoProvider
17:07:26 [worker(7129)] [INFO] using CocoaSource
17:07:26 [worker(7129)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
17:07:26 [worker(7129)] [INFO] using MacInjector
17:07:26 [worker(7129)] [INFO] monitoring the status of secure input
17:07:26 [worker(7129)] [INFO] monitoring the status of the daemon process
17:07:26 [worker(7129)] [INFO] using CocoaClipboard
17:10:13 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
17:10:13 [worker(7129)] [INFO] engine eventloop has terminated, propagating exit event...
17:10:13 [worker(7129)] [INFO] waiting for engine exit mode...
17:10:13 [worker(7129)] [INFO] exiting worker process...
17:10:13 [daemon(2146)] [INFO] spawning the worker process...
17:10:13 [worker(7420)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
17:10:13 [worker(7420)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
17:10:13 [worker(7420)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
17:10:13 [worker(7420)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
17:10:14 [worker(7420)] [INFO] using CocoaAppInfoProvider
17:10:14 [worker(7420)] [INFO] using CocoaSource
17:10:14 [worker(7420)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
17:10:14 [worker(7420)] [INFO] using MacInjector
17:10:14 [worker(7420)] [INFO] monitoring the status of the daemon process
17:10:14 [worker(7420)] [INFO] monitoring the status of secure input
17:10:14 [worker(7420)] [INFO] using CocoaClipboard
17:14:48 [worker(7420)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'loginwindow', but there are cases in which the detection is unreliable. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
10:06:23 [worker(7420)] [INFO] secure input has been disabled
10:06:29 [worker(7420)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'Google Chrome', but there are cases in which the detection is unreliable. Full path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
10:06:34 [worker(7420)] [INFO] secure input has been disabled
10:10:29 [worker(7420)] [INFO] secure input has been acquired, preventing espanso from working correctly. Our guess is that this is caused by 'iTerm', but there are cases in which the detection is unreliable. Full path: /Applications/iTerm.app/Contents/MacOS/iTerm2
10:10:36 [worker(7420)] [INFO] secure input has been disabled
10:23:33 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:23:33 [worker(7420)] [INFO] engine eventloop has terminated, propagating exit event...
10:23:33 [worker(7420)] [INFO] waiting for engine exit mode...
10:23:33 [worker(7420)] [INFO] exiting worker process...
10:23:33 [daemon(2146)] [INFO] spawning the worker process...
10:23:33 [worker(37783)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:23:33 [worker(37783)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:23:33 [worker(37783)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:23:33 [worker(37783)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:23:33 [worker(37783)] [INFO] using CocoaAppInfoProvider
10:23:33 [worker(37783)] [INFO] using CocoaSource
10:23:33 [worker(37783)] [INFO] using MacInjector
10:23:33 [worker(37783)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:23:33 [worker(37783)] [INFO] using CocoaClipboard
10:23:33 [worker(37783)] [INFO] monitoring the status of the daemon process
10:23:33 [worker(37783)] [INFO] monitoring the status of secure input
10:26:06 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:26:06 [worker(37783)] [INFO] engine eventloop has terminated, propagating exit event...
10:26:06 [worker(37783)] [INFO] waiting for engine exit mode...
10:26:06 [worker(37783)] [INFO] exiting worker process...
10:26:06 [daemon(2146)] [INFO] spawning the worker process...
10:26:06 [worker(38156)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:26:06 [worker(38156)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:26:06 [worker(38156)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:26:06 [worker(38156)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:26:06 [worker(38156)] [INFO] using CocoaAppInfoProvider
10:26:06 [worker(38156)] [INFO] using CocoaSource
10:26:06 [worker(38156)] [INFO] using MacInjector
10:26:06 [worker(38156)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:26:06 [worker(38156)] [INFO] using CocoaClipboard
10:26:06 [worker(38156)] [INFO] monitoring the status of the daemon process
10:26:06 [worker(38156)] [INFO] monitoring the status of secure input
10:28:09 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:28:09 [worker(38156)] [INFO] engine eventloop has terminated, propagating exit event...
10:28:09 [worker(38156)] [INFO] waiting for engine exit mode...
10:28:09 [worker(38156)] [INFO] exiting worker process...
10:28:09 [daemon(2146)] [INFO] spawning the worker process...
10:28:09 [worker(38417)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:28:09 [worker(38417)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:28:09 [worker(38417)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:28:09 [worker(38417)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:28:09 [worker(38417)] [INFO] using CocoaAppInfoProvider
10:28:09 [worker(38417)] [INFO] using CocoaSource
10:28:09 [worker(38417)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:28:09 [worker(38417)] [INFO] using MacInjector
10:28:09 [worker(38417)] [INFO] monitoring the status of the daemon process
10:28:09 [worker(38417)] [INFO] monitoring the status of secure input
10:28:09 [worker(38417)] [INFO] using CocoaClipboard
10:29:18 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:29:18 [worker(38417)] [INFO] engine eventloop has terminated, propagating exit event...
10:29:18 [worker(38417)] [INFO] waiting for engine exit mode...
10:29:18 [worker(38417)] [INFO] exiting worker process...
10:29:18 [daemon(2146)] [INFO] spawning the worker process...
10:29:18 [worker(38600)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:29:18 [worker(38600)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:29:18 [worker(38600)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:29:18 [worker(38600)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:29:18 [worker(38600)] [INFO] using CocoaAppInfoProvider
10:29:18 [worker(38600)] [INFO] using CocoaSource
10:29:18 [worker(38600)] [INFO] using MacInjector
10:29:18 [worker(38600)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:29:18 [worker(38600)] [INFO] using CocoaClipboard
10:29:18 [worker(38600)] [INFO] monitoring the status of secure input
10:29:18 [worker(38600)] [INFO] monitoring the status of the daemon process
10:29:56 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:29:56 [worker(38600)] [INFO] engine eventloop has terminated, propagating exit event...
10:29:56 [worker(38600)] [INFO] waiting for engine exit mode...
10:29:56 [worker(38600)] [INFO] exiting worker process...
10:29:56 [daemon(2146)] [INFO] spawning the worker process...
10:29:56 [worker(38682)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:29:56 [worker(38682)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:29:56 [worker(38682)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:29:56 [worker(38682)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:29:56 [worker(38682)] [INFO] using CocoaAppInfoProvider
10:29:56 [worker(38682)] [INFO] using CocoaSource
10:29:56 [worker(38682)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:29:56 [worker(38682)] [INFO] using MacInjector
10:29:56 [worker(38682)] [INFO] monitoring the status of the daemon process
10:29:56 [worker(38682)] [INFO] monitoring the status of secure input
10:29:56 [worker(38682)] [INFO] using CocoaClipboard
10:33:08 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:33:08 [worker(38682)] [INFO] engine eventloop has terminated, propagating exit event...
10:33:08 [worker(38682)] [INFO] waiting for engine exit mode...
10:33:08 [worker(38682)] [INFO] exiting worker process...
10:33:08 [daemon(2146)] [INFO] spawning the worker process...
10:33:08 [worker(39024)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:33:08 [worker(39024)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:33:08 [worker(39024)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:33:08 [worker(39024)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:33:09 [worker(39024)] [INFO] using CocoaAppInfoProvider
10:33:09 [worker(39024)] [INFO] using CocoaSource
10:33:09 [worker(39024)] [INFO] using MacInjector
10:33:09 [worker(39024)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:33:09 [worker(39024)] [INFO] using CocoaClipboard
10:33:09 [worker(39024)] [INFO] monitoring the status of secure input
10:33:09 [worker(39024)] [INFO] monitoring the status of the daemon process
10:33:36 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:33:36 [worker(39024)] [INFO] engine eventloop has terminated, propagating exit event...
10:33:36 [worker(39024)] [INFO] waiting for engine exit mode...
10:33:36 [worker(39024)] [INFO] exiting worker process...
10:33:36 [daemon(2146)] [INFO] spawning the worker process...
10:33:36 [worker(39071)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:33:36 [worker(39071)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:33:36 [worker(39071)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:33:36 [worker(39071)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:33:36 [worker(39071)] [INFO] using CocoaAppInfoProvider
10:33:36 [worker(39071)] [INFO] using CocoaSource
10:33:36 [worker(39071)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:33:36 [worker(39071)] [INFO] using MacInjector
10:33:36 [worker(39071)] [INFO] monitoring the status of the daemon process
10:33:36 [worker(39071)] [INFO] monitoring the status of secure input
10:33:36 [worker(39071)] [INFO] using CocoaClipboard
10:34:45 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:34:45 [worker(39071)] [INFO] engine eventloop has terminated, propagating exit event...
10:34:45 [worker(39071)] [INFO] waiting for engine exit mode...
10:34:45 [worker(39071)] [INFO] exiting worker process...
10:34:45 [daemon(2146)] [INFO] spawning the worker process...
10:34:45 [worker(39174)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:34:45 [worker(39174)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:34:45 [worker(39174)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:34:45 [worker(39174)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:34:45 [worker(39174)] [INFO] using CocoaAppInfoProvider
10:34:45 [worker(39174)] [INFO] using CocoaSource
10:34:45 [worker(39174)] [INFO] using MacInjector
10:34:45 [worker(39174)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:34:45 [worker(39174)] [INFO] using CocoaClipboard
10:34:45 [worker(39174)] [INFO] monitoring the status of the daemon process
10:34:45 [worker(39174)] [INFO] monitoring the status of secure input
10:36:26 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:36:26 [worker(39174)] [INFO] engine eventloop has terminated, propagating exit event...
10:36:26 [worker(39174)] [INFO] waiting for engine exit mode...
10:36:26 [worker(39174)] [INFO] exiting worker process...
10:36:27 [daemon(2146)] [INFO] spawning the worker process...
10:36:27 [worker(39346)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:36:27 [worker(39346)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:36:27 [worker(39346)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:36:27 [worker(39346)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:36:27 [worker(39346)] [INFO] using CocoaAppInfoProvider
10:36:27 [worker(39346)] [INFO] using CocoaSource
10:36:27 [worker(39346)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:36:27 [worker(39346)] [INFO] using MacInjector
10:36:27 [worker(39346)] [INFO] monitoring the status of secure input
10:36:27 [worker(39346)] [INFO] monitoring the status of the daemon process
10:36:27 [worker(39346)] [INFO] using CocoaClipboard
10:37:21 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:37:21 [worker(39346)] [INFO] engine eventloop has terminated, propagating exit event...
10:37:21 [worker(39346)] [INFO] waiting for engine exit mode...
10:37:21 [worker(39346)] [INFO] exiting worker process...
10:37:21 [daemon(2146)] [INFO] spawning the worker process...
10:37:21 [worker(39460)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:37:21 [worker(39460)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:37:21 [worker(39460)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:37:21 [worker(39460)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:37:21 [worker(39460)] [INFO] using CocoaAppInfoProvider
10:37:21 [worker(39460)] [INFO] using CocoaSource
10:37:21 [worker(39460)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:37:21 [worker(39460)] [INFO] using MacInjector
10:37:21 [worker(39460)] [INFO] monitoring the status of the daemon process
10:37:21 [worker(39460)] [INFO] monitoring the status of secure input
10:37:21 [worker(39460)] [INFO] using CocoaClipboard
10:37:40 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:37:40 [worker(39460)] [INFO] engine eventloop has terminated, propagating exit event...
10:37:40 [worker(39460)] [INFO] waiting for engine exit mode...
10:37:40 [worker(39460)] [INFO] exiting worker process...
10:37:40 [daemon(2146)] [INFO] spawning the worker process...
10:37:40 [worker(39491)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:37:40 [worker(39491)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:37:40 [worker(39491)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:37:40 [worker(39491)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:37:40 [worker(39491)] [INFO] using CocoaAppInfoProvider
10:37:40 [worker(39491)] [INFO] using CocoaSource
10:37:40 [worker(39491)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:37:40 [worker(39491)] [INFO] using MacInjector
10:37:40 [worker(39491)] [INFO] monitoring the status of secure input
10:37:40 [worker(39491)] [INFO] monitoring the status of the daemon process
10:37:40 [worker(39491)] [INFO] using CocoaClipboard
10:39:51 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:39:51 [worker(39491)] [INFO] engine eventloop has terminated, propagating exit event...
10:39:51 [worker(39491)] [INFO] waiting for engine exit mode...
10:39:51 [worker(39491)] [INFO] exiting worker process...
10:39:51 [daemon(2146)] [INFO] spawning the worker process...
10:39:51 [worker(39712)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:39:51 [worker(39712)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:39:51 [worker(39712)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:39:51 [worker(39712)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:39:51 [worker(39712)] [INFO] using CocoaAppInfoProvider
10:39:51 [worker(39712)] [INFO] using CocoaSource
10:39:51 [worker(39712)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:39:51 [worker(39712)] [INFO] using MacInjector
10:39:51 [worker(39712)] [INFO] monitoring the status of secure input
10:39:51 [worker(39712)] [INFO] monitoring the status of the daemon process
10:39:51 [worker(39712)] [INFO] using CocoaClipboard
10:44:43 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:44:43 [worker(39712)] [INFO] engine eventloop has terminated, propagating exit event...
10:44:43 [worker(39712)] [INFO] waiting for engine exit mode...
10:44:43 [worker(39712)] [INFO] exiting worker process...
10:44:43 [daemon(2146)] [INFO] spawning the worker process...
10:44:44 [worker(40242)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:44:44 [worker(40242)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:44:44 [worker(40242)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:44:44 [worker(40242)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:44:44 [worker(40242)] [INFO] using CocoaAppInfoProvider
10:44:44 [worker(40242)] [INFO] using CocoaSource
10:44:44 [worker(40242)] [INFO] using MacInjector
10:44:44 [worker(40242)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:44:44 [worker(40242)] [INFO] using CocoaClipboard
10:44:44 [worker(40242)] [INFO] monitoring the status of the daemon process
10:44:44 [worker(40242)] [INFO] monitoring the status of secure input
10:45:15 [daemon(2146)] [INFO] configuration change detected, restarting worker process...
10:45:15 [worker(40242)] [INFO] engine eventloop has terminated, propagating exit event...
10:45:15 [worker(40242)] [INFO] waiting for engine exit mode...
10:45:15 [worker(40242)] [INFO] exiting worker process...
10:45:15 [daemon(2146)] [INFO] spawning the worker process...
10:45:15 [worker(40292)] [INFO] reading configs from: "/Users/my_username_redacted/Library/Application Support/espanso"
10:45:15 [worker(40292)] [INFO] reading packages from: "/Users/my_username_redacted/Library/Application Support/espanso/match/packages"
10:45:15 [worker(40292)] [INFO] using runtime dir: "/Users/my_username_redacted/Library/Caches/espanso"
10:45:15 [worker(40292)] [INFO] system info: Darwin v14.7 - kernel: 23.6.0
10:45:15 [worker(40292)] [INFO] using CocoaAppInfoProvider
10:45:15 [worker(40292)] [INFO] using CocoaSource
10:45:15 [worker(40292)] [INFO] using MacInjector
10:45:15 [worker(40292)] [INFO] binded to IPC unix socket: /Users/my_username_redacted/Library/Caches/espanso/espansoworkerv2.sock
10:45:15 [worker(40292)] [INFO] using CocoaClipboard
10:45:15 [worker(40292)] [INFO] monitoring the status of secure input
10:45:15 [worker(40292)] [INFO] monitoring the status of the daemon process
10:54:20 [worker(40292)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...

### Your environment

- Operating system and version (e.g., Ubuntu 20.04.2 LTS): MacOS Sonoma 14.7 (23H124), MacBook Pro, Apple M3 Pro
- Espanso version (e.g., 2.1.4-beta): 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
This is probably a matter which you can resolve by changing the [injection mechanism](https://espanso.org/docs/matches/basics/#injection-mechanism).

I find both `clipboard` and `inject`/`keys` work in my plain text editor (`xed`), but in terminals (e.g. xfce4-terminal and Console) I have to use `inject`/`keys`.

The problem with _long_ expansions occurs because in `backend: auto` Espanso switches from `inject` to `clipboard` (at the threshold specified in [clipboard_threshold](https://espanso.org/docs/configuration/options/)), and the latter doesn't work well in some program environments.

OS: Linux Mint 21.2 x86_64 Xfce 4.18

**Comment by eccentricon** [comment]
Thanks very much, Stephen! `force_mode: keys` seemed to do the trick here:

```
  - trigger: ";;lorum"
    replace: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    force_mode: keys
```
Really, I should just install the [`lorem`](https://hub.espanso.org/lorem) package.

Thanks so much for the help! I'm just a day in to trying Espanso.

Ted

**Comment by smeech** [comment]
It's good to explore these things, and your example demonstrates several issues important to getting Espanso working smoothly.

Bear in mind that `force_mode: keys` is primarily for testing expansions and environments. If your other expansions are to work correctly, you'll need to follow the advice in the last paragraph of https://espanso.org/docs/matches/basics/#injection-mechanism.

Let me know if you need any further help - you'll find me here, on Discord, and on Reddit.
