### ISSUE TITLE
Does Espanso work in macOS Sequoia 15?

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#2071]
### Description

Is this tested under macOS Sequoia 15 ?
I would like to upgrade my macOS from Sonoma to Sequoia, but want to be sure whether espanso still works under Sequoia.

### Steps to reproduce

1.Run under macOS Sequoia.
2. Does it work ?

### Your environment

- Operating system and version : macOS 15.x

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
There's probably not enough activity here for you to receive a definitive reply.

I would suggest you join us on [Discord](https://discord.gg/4QARseMS6k) and ask there - there are several macOS users frequently around.

**Comment by skylatian** [comment]
Can confirm it works. Needed to click "Launch SecureInput auto-fix" and close (then re-open) my password manager, but it's working flawlessly now.

**Comment by smeech** [comment]
Thank you for reporting back - that's good to know.

I'll change the title to make it easier for others to find.
