### ISSUE TITLE
Date Extension | Calculate Calendar week and W/C date

### ISSUE THREAD

**Issue by schnapsldee** [federico-terzi/espanso#2072]
### Description

Hi! 
I'd like to be able to calculate the Calendar week using the Date extension. As of now, I'm only able to offset the date by a fixed amount, but would like to fill in calendar weeks as well as the date of the Monday/the date of the current week commencing. Ideally these could then also be offset by a week etc. 

### Motivation

This feature would allow for quick and easy inserts of specific date/week references, complementing the date functions. 

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
[`date:`](https://espanso.org/docs/matches/extensions/#date-extension) returns the week number calculated from Sunday or Monday using the format [`%U` or `%W`](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) respectively.

I'm not quite sure I understand the latter part of your second sentence, so do feel free to clarify

Whilst one might attempt to extract an `offset:` from a Regex trigger, Espanso doesn't do arithmetic (to calculate `offset:`'s seconds from a more human unit), and `offset:` won't accept a string, and therefore neither a variable anyway.

 I have saved some example methods in my [Pastebin](https://pastebin.com/8wy9dAU3). 

#1076

**Comment by smeech** [comment]
> and `offset:` won't accept a string, and therefore neither a variable anyway.

It appears that `offset:` is parsed as a "number" [here](https://github.com/espanso/espanso/blob/9d19f1cf84f727d64b670923018e8d8d8351e40e/schemas/match.schema.json#L269) but [this](https://github.com/espanso/espanso/blob/9d19f1cf84f727d64b670923018e8d8d8351e40e/espanso-render/src/extension/date.rs#L476) uses a string anyway.

Is it as simple as changing the first to "string"?

Edit: Apparently not! Multiple downstream changes needed.

**Comment by AucaCoyan** [comment]
I find this feature request a bit "too feature-full". It's not a bad idea, but we need to trace a limit of what _can_ we do with `offset:`. It would be difficult to explain in the docs "yeah, you can also pick the 3rd day of the next week too!" and thus misleading the name.

On the other side, we do have a current solution for this without adding new code (and tests, and maintainability so on and so forth). I don't see any need to merge a PR if the current dev version works fine.

> Is it as simple as changing the first to "string"? Edit: Apparently not! Multiple downstream changes needed.

Correct! also my intentions in the json schema were _Dear user: you are supposed to write a number here, even if writing a string is possible_. In the future I would like to refactor the offset into an actual int, not a str
