### ISSUE TITLE
add ability to add scripts to tray menu 

### ISSUE THREAD

**Issue by namoran** [federico-terzi/espanso#2083]
### Description

There is plenty of room to add a list of user configurable triggers to the tray menu that could perform any action that could be done with a script. Launch apps, change settings, etc. It would be good to allow users to trigger items in that way.

### Motivation

By adding this feature the app could become even more useful as it could function as a quicklaunch toolbar. It could launch triggers with forms as well allowing the user to create multi-button menus. I'd be happy to help but I don't know Rust of C++ but it seems simple enough that I might try anyway if you can point be to the starting place. 

### Have you tried building it? Or would you like it?

- [X] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
Interesting idea. There are, of course, any number of programs or system tools that do this already. Whilst many of us have come up with imaginative ways of using Espanso, I wonder if this idea is better suited to the existing tools than a program which is primarily about producing text?

**Comment by namoran** [comment]
maybe so, but Ill counter that what makes espanso appealing and powerful is that it is not limited to simple text replacement. It uses variables, calls scripts, even allows the user to make forms to modify the text output. You can also call espanso triggers from a builtin search. That is quite advanced stuff.
Also, although it could be done with another app, the appealing thing is that config for this would be done in the config files for espanso. If I had scripts I wanted to launch in multiple ways I only must know how to use espanso, and not espanso and another app. I wouldnt have to rewrite scripts to accommodate two different programs.
Espanso is a means to get your computer to do what you want it to do the moment you think it. But if your hands are on mouse instead of the keyboard you have to switch. <- Thats a cardinal sin. Now that I'm al revved up, I say we add the ability to add triggers to the rightclick context menu too!

**Comment by AucaCoyan** [comment]
quoting:
> I wonder if this idea is better suited to the existing tools than a program which is primarily about producing text?

and

> If I had scripts I wanted to launch in multiple ways I only must know how to use espanso, and not espanso and another app. I wouldnt have to rewrite scripts to accommodate two different programs.

I think it's a bit more than we can chew in an application. I prefer having small applications doing exactly what I want, than having an app that does a lot of stuff that I don't use. Overtime its features tend to stagnate and harder to maintain.
I like the possiblity to send scripts from the taskbar, but I think it's a lot more than "a text expander".
