### ISSUE TITLE
Enhancing Espanso for German Keyboard Layout

### ISSUE THREAD

**Issue by shortyorty** [federico-terzi/espanso#2088]
### Description

German keyboards are currently not fully supported:

Ö, Ä, Ü: These are essential German characters that are handy shortcut keys because they are at the center of the German keyboard.

Alt Gr: This modifier key is commonly used in combination with other keys to produce special characters, including those mentioned above, and is not the same as alt_right.

# Example Combo
search_shortcut: ALT_GR+Ü

### Motivation

As a German user, I've encountered some limitations when using Espanso with my keyboard layout. Specifically for the aforementioned keys, which are currently not supported.

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
I suspect this is related to the other issues with non-English keyboards.
https://github.com/espanso/espanso/issues/345
https://github.com/espanso/espanso/issues/498
https://github.com/espanso/espanso/issues/511
https://github.com/espanso/espanso/issues/996
https://github.com/espanso/espanso/issues/1112
https://github.com/espanso/espanso/issues/1133
https://github.com/espanso/espanso/issues/1286
https://github.com/espanso/espanso/issues/1153
https://github.com/espanso/espanso/issues/1609

? https://github.com/espanso/espanso/issues/628
? https://github.com/espanso/espanso/issues/680
? https://github.com/espanso/espanso/issues/1028
? https://github.com/espanso/espanso/issues/1327
? https://github.com/espanso/espanso/issues/1347
? https://github.com/espanso/espanso/issues/1408
? https://github.com/espanso/espanso/issues/1439
? https://github.com/espanso/espanso/issues/1507
