### ISSUE TITLE
Chance "Disable" to "Disble Espanso" 

### ISSUE THREAD

**Issue by maxandersen** [federico-terzi/espanso#209]
I only touch espanso rarely but I honestly keep forgetting what the name is of the tool that has a "e" in my menubar so a few   times I had to google search my way to remember it is espanso :) 

thus I suggest to change the menu entry to say "Disable Espanso" so it gives a little hint.

**Comment by federico-terzi** [comment]
Hey @maxandersen,

I apologize for the late reply. That's surely a fair point! I'll make sure that in the next versions of espanso there will be a clear indication of espanso in the context menu.

Thanks for your feedback :)

**Comment by federico-terzi** [comment]
Hey, 
now espanso list "Exit espanso" instead of "Exit" in the context menu. This should things more clear :)

**Comment by maxandersen** [comment]
perfect :)
