### ISSUE TITLE
Limit activation to text fields

### ISSUE THREAD

**Issue by eugenesvk** [federico-terzi/espanso#2090]
### Description

Add an ability to detect whether any text field is currently active with a text cursor and limit espanso expansion macros only when it is

### Motivation

If I have `,ee` as an activation trigger, this activates even when I press those 3 keys outside of any text field, which doesn't make sense and also prevents from using some short combo for non-espanso-related purposes like an extra control sequence in an app

### Alternatives

n/a

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
The current implementation is, I think, intended. For example, `#acfg#` and `#detect#` and other Espanso shortcuts work whether a text-field is available or not, and one could envisage user-triggers that generate non-text activities such as starting scripts and programs etc..

The workarounds for your difficulty are probably to use app-specific configurations and triggers which don't match program shortcuts, to prevent unintended Espanso expansions, although I can see the problem.

Unless others consider this a significant problem, I don't envisage this being changed, I'm afraid.

**Comment by eugenesvk** [comment]
> one could envisage user-triggers that generate non-text activities 

The simple solution to this is to make the `is_a_text_field` a per-command condition so your `#detect#` etc. can continue to work everywhere 

And your suggestion is not a workaround, but just "don't do that", as I precisely would like to use the same shortcuts within the app, just not when I'm typing

**Comment by smeech** [comment]
Thank you for your reply. I am not one of those involved in coding Espanso, so I don't know how simple a solution it would be to implement across the various OSs, DEs, and different text fields. With the very small team involved, it's unlikely to be implemented unless you'd like to have a go.

I do spend a lot of time trying to assist users, hence my suggestion. I realise it's not a solution.
