### ISSUE TITLE
More easy input

### ISSUE THREAD

**Issue by herrdeh** [federico-terzi/espanso#2094]
### Description

To be honest - the yaml data input method is a little tricky and geeky. Couldn't there be an option for the rest of us? - A csv table e.g. ?

### Motivation

Make handling more easy for people not familiar with yaml files

### Alternatives

CSV, ods, text files 

### Have you tried building it? Or would you like it?

- [ ] I'd be willing to contribute this feature to Espanso myself.

**Comment by smeech** [comment]
For the more complex structure of forms, scripts etc. one needs a data serialization format like YAML or JSON. Ideally the user wouldn't have to grapple with text at all,  which is where a [`GUI`](https://github.com/Pebkac03/espanso_gui) comes in.

That having been said,  there have been other requests for a simpler format for plain `trigger:`/`replace:` pairs which I would search out if I weren't 10,000 miles from my PC!

**Comment by herrdeh** [comment]
The GUI approach will certainly be helpful, but it does not look as if the GUI for Linux will be ready soon. For this reason as well, CSV may still be a good thing.

**Comment by AucaCoyan** [comment]
> For this reason as well, CSV may still be a good thing.

the problem with CSV files is that it still a text format, and also is rare to find it as a configuration file. It's harder to parse than yaml, json, toml or even ini files.
With yaml you can use the language server in vs code to have error highlitings like this
![317813094-a6365233-4c88-4c04-9fb4-ae8c87ff4076](https://github.com/user-attachments/assets/808176fa-73c4-4f97-bb52-767b57b7b816)

you need to add the line
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
```
on the `base.yml` and
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
```

on the config yaml.

don't forget to add the [yaml extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) to make the schemas useful!

**Comment by w5nh6o** [comment]
There's [espansoGUI](https://github.com/unobserved-io/espanso-gui), but I'm not sure it meets your requirements.

**Comment by AucaCoyan** [comment]
I'm closing this as it is out of the project scope as it is today.
We have a couple of companion alternatives!
