### ISSUE TITLE
Strange and unwanted behavior on Ubuntu/Gnome/Wayland

### ISSUE THREAD

**Issue by Adspectus** [federico-terzi/espanso#2097]
### Description

I would not consider it a bug but I have found the following behavior which I do not want/like:

1. There is a strange pixel effect in the middle of my display on the desktop background (see Screenshot).
2. There is a icon with a gear and no description in the dash which I can't remove (Screenshot)
3. Upon starting my desktop there is always a friendly notification that espanso has started - this is useless and not needed. If every application would send such a notification I would need half a day just to dismiss these notifications.

![Bildschirmfoto vom 2024-10-09 10-55-06](https://github.com/user-attachments/assets/e604d195-2e1c-4d71-b021-e4597f13e904)

### Steps to reproduce

1. Install espanso by following the instructions for wayland

### Expected behavior

1. No pixel effect on my desktop background
2. No gear icon in dash or option to remove it
3. No notification that espanso has started - a taskbar icon would be nice.

### Screenshots

See above

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Ubuntu 22.04.5 LTS (Jammy Jellyfish)
- Espanso version (e.g., 2.1.4-beta): espanso 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by morgan-dgk** [comment]
This is fixed on dev but not yet in release branch. See #1826

**Comment by AucaCoyan** [comment]
Yup! morgan did the job a while ago!
We are unable to release a new production version for a license issue (personal license vs organizational license).

If you feel adventurous, you can compile the development version and see what results show.
ask for help in the discord for any doubts!
