### ISSUE TITLE
Weird regex matches when restricting the start of the match

### ISSUE THREAD

**Issue by TK-517** [federico-terzi/espanso#2105]
### Description

According to the Rust regex implementation I'd expect espanso to match the regex »regex: "(^| |\\.)\\.h\\.(?P<name>.{2,}) "« like this
![grafik](https://github.com/user-attachments/assets/f1bb3299-9b9d-45be-9a54-97222e2f6ca8)

But it actually does matches like this
![grafik](https://github.com/user-attachments/assets/b3c4d7ce-2696-4881-9e01-66cc78840b2b)

Which would correspond to the regex »regex: "(^| |\\.)\\.h\\. (?P<name>.{2,}) "« with a » « between »h\\.« and »(?P« in my opinion 

Without the restriction on the start of the match »(^| |\\.)« espanso matches the following regex »regex: "(^| |\\.)\\.h\\.(?P<name>.{2,}) "« as expected (see picture below) and does not need a » « in the middle - but it matches the Germany abbreviation »d.h.« which I try to prevent.

![grafik](https://github.com/user-attachments/assets/e1ee2c97-6c0b-4f77-989d-7bca359d6ee4)

Is this a bug or do I need a different syntax for espanso regex?

BTW: lookaround is not supported in espansos regex backend, or is there a was to use a lookaround?

### Steps to reproduce

Use the regex matches given above an try with the input given in the screenshots

### Your environment

- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Win 10
- Espanso version (e.g., 2.1.4-beta): 2.2.1 portable

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by AucaCoyan** [comment]
Hi!
I'm testing the trigger. I'm not sure yet if it's a bug or a mistake on the trigger. So far I tested with:
```yaml
  - regex: "(^| |\\.)\\.h\\. (?P.{2,}) "
    replace: "triggered!"
```
As soon as I get more info I'll tell you!

**Comment by AucaCoyan** [comment]
yup, i could make it work with:
```yaml
  - regex: "(^| |\\.)\\.h\\.(?P<name>.*) "
    replace: "triggered!"
```
with `..h.Auca ` triggers

I guess the `{2,}` part of the regex was never triggering because you can keep "writing the trigger" forever.

**Comment by TK-517** [comment]
Hi!

Thanks for your recommendation, looks like this solves my problem - when the first part works, I don't necessarily need the »{2,}«. 

At the same time I don’t really understand why it triggers with ».*« triggers while it doesn’t with »{2,}« - in both cases the I could keep writing the trigger forever.
