### ISSUE TITLE
Espanso emmits "Wayland compositor detected: ..." every second into system log 

### ISSUE THREAD

**Issue by Schlaefer** [federico-terzi/espanso#2106]
### Description

Since #2101 the system log gets filled with a wall of

`espanso ... [daemon(2025)] [INFO] Wayland compositor detected: kwin_wayland_wr`

This makes the system log really hard to read.

### Steps to reproduce

1. Start espanso in wayland manager
2. Open systemlog and watch output

### Expected behavior

It works, but that is too much winning. ;) This has to be throttled in some way.

### Screenshots

![Screenshot_20241021_125502](https://github.com/user-attachments/assets/f11e0246-7d6a-4bac-8d8f-f24d9500335a)

### Logs

[espanso.log](https://github.com/user-attachments/files/17459587/espanso.log)

### Your environment

Operating System: CachyOS Linux 
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.4-4-cachyos (64-bit)
Graphics Platform: Wayland
Espanso version (e.g., 2.1.4-beta): 3aad6eee667d040ee909b16cbdfd7d3b3692f04a

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by morgan-dgk** [comment]
My apologies, I clearly was not thinking clearly - this is called like once a second to check the keyboard layout 😅

**Comment by morgan-dgk** [comment]
@AucaCoyan can you please revert #2101 until I figure out a better way to do this - preferably only once during startup. 

edit: or, perhaps just remove the log line since we are already checking every second if the compositor is gnome or not and I don't think this is a massive overhead.

**Comment by AucaCoyan** [comment]
I would delete the log message, or change the level to debug, so it's not printed in the file
(i assume debug aren't printed on the log file, right?, checking...)

**Comment by morgan-dgk** [comment]
Yep, either should do the trick I think

**Comment by AucaCoyan** [comment]
Yes, apparently this is where logs only INFO and above
https://github.com/espanso/espanso/blob/dev/espanso/src/logging/mod.rs#L105

**Comment by AucaCoyan** [comment]
Merged! wait until is built and check again please 🙏
