### ISSUE TITLE
Extend Timeout for Scripts

### ISSUE THREAD

**Issue by grahamjpark** [federico-terzi/espanso#211]
I'm trying to get a script working that performs a get request. It seems like the request is taking too long and nothing is being populated. The script works fine when I run it, and if I take out the request in the script espanso runs fine.

I believe that espanso is cutting the script short for taking too long. Is that right? Is there a reason for cutting it off?

**Comment by federico-terzi** [comment]
Hey @grahamjpark,

That's super strange, as there is no timeout for script commands!
Could you please share an example so I can reproduce it?

Cheers :)

**Comment by grahamjpark** [comment]
Thanks for the reply. When I looked over it with fresh eyes I realized it may have been because I was trying to read environment variables. You can see the script here:
https://github.com/grahamjpark/useful-scripts/blob/master/daily-template.py

Storing the key in file now instead and it's working great!

**Comment by federico-terzi** [comment]
Hey @grahamjpark,

> When I looked over it with fresh eyes I realized it may have been because I was trying to read environment variables. 

That's most likely it! As you may now imagine, the scripts that espanso executes inherit its environment variables, and probably they didn't include the one you were trying to use.

Glad you sorted it out, cheers :)
