### ISSUE TITLE
Unable to register espanso

### ISSUE THREAD

**Issue by NeoTeo** [federico-terzi/espanso#212]
On macOS, when running `espanso register` (or even `sudo espanso register`) it fails with
`Path had bad ownership/permissions`

My home is on a different drive from the boot drive so it may cause problems if espanso is making some assumptions about ownership?

**Comment by NeoTeo** [comment]
I have figured out the issue. The external drive had "Ignore ownership on this volume" enabled (set via the info view on the drive in Finder) and then I needed to change the ownership of the .plist to root:wheel with
`sudo chown root:wheel /SomeDrive/Users/SomeUser/Library/LaunchAgents/com.federicoterzi.espanso.plist`

**Comment by federico-terzi** [comment]
Hey @NeoTeo,
Glad to hear you found a solution :)
Cheers

**Comment by NeoTeo** [comment]
@federico-terzi Yes. Thought I'd leave it here for others to find.
Thank you for writing the tool. Very useful :)
