### ISSUE TITLE
Espanso should offer a script option in addition to Auto, Clipboard, and Inject.

### ISSUE THREAD

**Issue by jheroy** [federico-terzi/espanso#2121]
### Description

I noticed that using clipboard mode in Wayland actually sends a Shift+INSERT keystroke. This works correctly in most applications, but it behaves unexpectedly in a few, such as kitty(he Shift+INSERT key is mapped to paste_from_selection instead of paste_from_clipboard).

### Motivation

 If a script option were provided, users could easily implement functionality using their own clipboard manager(Because the wl-copy and wl-paste commands do not work well with XWayland apps sometimes.), for example:
```bash
#!/bin/bash
copyq copy $1
copyq clipboard
```

**Comment by smeech** [comment]
Have you explored the current [options](https://espanso.org/docs/configuration/options/#options-reference)?

In particular, `paste_shortcut` enables you to change the method of pasting, globally in `default.yml`, and in [app-specific configurations](https://espanso.org/docs/configuration/app-specific-configurations/). There are others which enable one to choose the clipboard method, like `x11_use_xclip_backend` although these are heavily weighted towards X11.

Alternatively, you might be able to [script](https://espanso.org/docs/matches/extensions/#script-extension) some of the features you're seeking. Let me know if I can help!

**Comment by jheroy** [comment]
Sorry, I didn't think that the paste_shortcut option could be used in app-specific config.
