### ISSUE TITLE
Longer expansion does not add space at the end on Windows

### ISSUE THREAD

**Issue by pyxelr** [federico-terzi/espanso#2130]
### Description

I think there is a problem with longer replacements:

```yml
  - trigger: ";yt " # download audio
    replace: "yt-dlp --add-metadata --parse-metadata \"%(artists)l:%(meta_artist)s\" --embed-thumbnail -o \"%(artists)l - %(title)s.%(ext)s\" "
  - trigger: ";ytm " # extract mp3 from video 
    replace: "yt-dlp --embed-thumbnail --audio-quality 320k --extract-audio --no-part --audio-format mp3 --add-metadata -o \"%(uploader)s - %(title)s.%(ext)s\" "
  - trigger: ";ytv " # download video of best quality
    replace: "yt-dlp -f bestvideo -ciw --write-thumbnail -o \"%(uploader)s - %(title)s.%(ext)s\" "
```

When I type `;yt` in Windows Terminal and press the space bar, the expansions end up with the following:

```
yt-dlp --add-metadata --parse-metadata "%(artists)l:%(meta_artist)s" --embed-thumbnail -o "%(artists)l - %(title)s.%(ext)s"
```

There is no space character after the end (after the last `"` character). This is not a problem in any macOS terminals.

Looking at the snippet above, `;ytm` also has this issue, while `;ytv` works fine.

### Screenshots

![image](https://github.com/user-attachments/assets/1ed8f719-e934-4399-b765-350dc322f26f)

### Logs

❯ espanso log

```
19:47:26 [daemon(20332)] [INFO] reading configs from: "C:\\Users\\pawel\\AppData\\Roaming\\espanso"
19:47:26 [daemon(20332)] [INFO] reading packages from: "C:\\Users\\pawel\\AppData\\Roaming\\espanso\\match\\packages"
19:47:26 [daemon(20332)] [INFO] using runtime dir: "C:\\Users\\pawel\\AppData\\Local\\espanso"
19:47:26 [daemon(20332)] [INFO] system info: Windows v11 (26100) - kernel: 26100
19:47:26 [daemon(20332)] [INFO] watching for changes in path: "C:\\Users\\pawel\\AppData\\Roaming\\espanso"
19:47:26 [daemon(20332)] [INFO] espanso version: 2.2.1
19:47:26 [daemon(20332)] [INFO] spawning the worker process...
19:47:26 [daemon(20332)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
19:47:26 [worker(5976)] [INFO] reading configs from: "C:\\Users\\pawel\\AppData\\Roaming\\espanso"
19:47:26 [worker(5976)] [INFO] reading packages from: "C:\\Users\\pawel\\AppData\\Roaming\\espanso\\match\\packages"
19:47:26 [worker(5976)] [INFO] using runtime dir: "C:\\Users\\pawel\\AppData\\Local\\espanso"
19:47:26 [worker(5976)] [INFO] system info: Windows v11 (26100) - kernel: 26100
19:47:26 [worker(5976)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
19:47:26 [worker(5976)] [INFO] using Win32AppInfoProvider
19:47:26 [worker(5976)] [INFO] monitoring the status of the daemon process
19:47:26 [worker(5976)] [INFO] using Win32Source
19:47:26 [worker(5976)] [INFO] using Win32Injector
19:47:26 [worker(5976)] [INFO] using Win32Clipboard
```

### Your environment

- Operating system and version: Windows 11 Pro 24H2
- Espanso version: 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
I would start by removing the external [quote-marks](https://espanso.org/docs/matches/quotes/) and the internal escapes (because you'll no longer need them), so that the `replace:` value looks exactly like you'd like the output. If you need a space on the end, add it and enclose the whole string in *single-quotes*.

The difference in behaviour may relate to the replacement length. If you type `#acfg#` in your program and find `backend: Auto`, be aware that Espanso will change from the Inject to the Clipboard injection mechanism at the length specified in `clipboard_threshold:` which is probably set at `100`. You may need to change your backend globally in `config/default.yml` or add an [app-specific configuration](https://espanso.org/docs/configuration/app-specific-configurations/). Do some experimenting with the ['force_mode'](https://espanso.org/docs/matches/basics/#injection-mechanism) keys on the individual triggers.

**Comment by AucaCoyan** [comment]
I tested the trigger and have the same result in windows terminal, as a quick test, I copied `something    ` (+4 spaces after) and when I pasted into Windows terminal the app trimmed the final space.
I think it might be a problem of the Windows terminal app.

With:
```
backend: inject
```
In the `config/default.yml`  works properly (with the added space). It is a bit slower though

**Comment by pyxelr** [comment]
@smeech @AucaCoyan: Thanks!

The issue is resolved by specifying `backend: inject` in `config/default.yml` (I previously didn’t have a backend set).

Additionally, switching the `replace` value to single quotes simplified the configuration, like so:

```yaml
replace: 'yt-dlp --add-metadata --parse-metadata "%(artists)l:%(meta_artist)s" --embed-thumbnail -o "%(artists)l - %(title)s.%(ext)s" '
```

**Comment by smeech** [comment]
You're welcome!
