### ISSUE TITLE
Windows 11 - Open Search Bar not working

### ISSUE THREAD

**Issue by z1spark** [federico-terzi/espanso#2131]
### Description

All of a sudden, open search bar doesn't work either from the menu or the Alt-Space hotkey.  I tried to reinstall the latest version but still get the problem.  Is it being open off screen somehow?   Anyone else experience this?  
There's an error in the log.

### Logs

11:17:16 [worker(20000)] [ERROR] modulo exited with non-zero status code: Some(101)
11:17:16 [worker(20000)] [ERROR] SearchUI reported an error: modulo returned an empty output

### Your environment

- Public source code:
- Environment name and version (e.g., Rust 1.59.0):
- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Windows 11
- Espanso version (e.g., 2.1.4-beta): 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by pyxelr** [comment]
I am on Windows 11 using espanso 2.2.1, and I have never experienced this issue. The search bar always opens in the centre of the default screen. Maybe some other software interferes?

**Comment by smeech** [comment]
> 11:17:16 [worker(20000)] [ERROR] SearchUI reported an error: modulo returned an empty output

The posted Log entry suggests the Search Bar is failing for some reason. I doubt if it is appearing anywhere.

I don't know what OS you're using, but when I view the running tasks and filter them for "espanso" I see four currently. If I open the Search Bar, a fifth (`usr/bin/espanso modulo search -j -i -`) appears until it closes. You may be able to try something similar, but I suspect, in your case, the additional task won't appear.

**Comment by z1spark** [comment]
Update:  I tired the latest portable version and the Open Search Bar is working there.

**Comment by smeech** [comment]
> Update: I tired the latest portable version and the Open Search Bar is working there.

Excellent! Thank you for letting us know.

I'll close the issue as you've found a solution, so we won't be investigating it further.
