### ISSUE TITLE
Search bar does not work with LibreOffice Writer

### ISSUE THREAD

**Issue by gcailly** [federico-terzi/espanso#2151]
### Description

With LibreOffice Writer, Search bar appears, but pressing [Enter] does nothing.

### Steps to reproduce

1. Open LibreOffice Writer 24.8.
2. Press Alt+Space.
3. Type a trigger and press Enter.

### Expected behavior

The "replace" string should be inserted.

### Screenshots

https://github.com/user-attachments/assets/c6a5eb97-c995-4179-959e-b6de1e991ba9

### Logs

Nothing relevant.

### Your environment

- Operating system and version (e.g., Ubuntu 20.04.2 LTS): Windows 11
- Espanso version (e.g., 2.1.4-beta): 2.2.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by smeech** [comment]
I'm unable to replicate the problem here (Linux Mint Xfce) which limits my ability to help. However, there's a _slightly_ similar Issue #1738, with a solution you could try.

**Comment by gcailly** [comment]
Thank you very much, it solved the problem !

**Comment by gcailly** [comment]
I filled a bug on LibreOffice bugzilla about this issue : https://bugs.documentfoundation.org/show_bug.cgi?id=164008

**Comment by smeech** [comment]
I note the other workaround you posted there, which I'll copy here for future reference:
> I found another workaround : pressing ALT one time, then ALT + SPACE. And the string is pasted.

Did you try changing the Search Bar shortcut setting in [options](https://espanso.org/docs/configuration/options/#options-reference) - `search_shortcut:` to a different key combination so you don't need to use \<ALT>?

**Comment by gcailly** [comment]
Indeed : CTRL + SPACE works like a breeze. 🙂
I mentionned it on the LibreOffice bug, it seems it is related with the ALT key.
