### ISSUE TITLE
Patchars Phetchuai

### ISSUE THREAD

**Issue by 2392711432** [federico-terzi/espanso#230]
> Good tool
> But I hope to support Chinese
> Thanks

_Originally posted by @2392711432 in https://github.com/federico-terzi/espanso/issues/101#issuecomment-609521737_

**Comment by federico-terzi** [comment]
For everyone reading this comment: in the recent hours the project has received a huge number of spammy issues. I don't like to be harsh, but to keep things manageable I will close any of those issues and ban the relative users.
