### ISSUE TITLE
ไทยพาณิชย์

### ISSUE THREAD

**Issue by 2392711432** [federico-terzi/espanso#231]
2392711432​

**Comment by 2392711432** [comment]
None yet

**Comment by 2392711432** [comment]
None ye

**Comment by 2392711432** [comment]
2392711432​

**Comment by 2392711432** [comment]
พั

**Comment by 2392711432** [comment]
Chrome​and

**Comment by 2392711432** [comment]
https://help.github.com/articles/github-community-guidelines

**Comment by federico-terzi** [comment]
For everyone reading this comment: in the recent hours the project has received a huge number of spammy issues. I don't like to be harsh, but to keep things manageable I will close any of those issues and ban the relative users.
