### ISSUE TITLE
Does espanso work on Chrome OS?

### ISSUE THREAD

**Issue by asheeshr** [federico-terzi/espanso#235]
Chrome OS has support for Linux package and applications and I'm wondering if anyone's tried or gotten it to work on Chrome OS.

**Comment by federico-terzi** [comment]
Hey @asheeshr,

Unfortunately, at the moment this is not possible as Chrome OS is not based on X Server.
If the request is high enough, I could consider adding support in the future.

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm closing the issue as at the moment, there's not much demand for Chrome OS support and the current 3 platforms are already challenging enough given my little time. I hope you will understand...
Cheers :)

**Comment by asheeshr** [comment]
Thanks for the response! Totally understandable.
