### ISSUE TITLE
Auto-reload settings option

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#239]
Some users requested a feature to "auto-reload" the espanso automatically after a configuration file change.

**Comment by federico-terzi** [comment]
This have been shipped in espanso 0.6.0!
To enable the feature, please add the following line to your config:

```yaml
auto_restart: true
```

**Comment by danielvartan** [comment]
Hi there,

Regarding the same subject. Is there a shortcut for `Reload config`?

![image](https://github.com/user-attachments/assets/746c170a-f79f-4ae3-acbb-eba9a45b8a16)

This would be useful when changing imported files. Not ideal, though. It would be better if those files were tracked.

**Comment by smeech** [comment]
Just the command `espanso restart` or `espanso service restart`, AFAIAA.
