### ISSUE TITLE
Espanso doesn't run on Fedora 31.

### ISSUE THREAD

**Issue by eduardosramos** [federico-terzi/espanso#240]
Hi,

I installed everything as the site indicates, the daemon is running but nothing happens.
Can you help me?

espanso log
17:35:30 [ INFO] espanso version 0.5.4
17:35:30 [ INFO] using config path: /home/suporte/.config/espanso
17:35:30 [ INFO] using package path: /home/suporte/.local/share/espanso/packages
17:35:30 [ INFO] starting daemon...
17:35:30 [ INFO] Binded to IPC unix socket: /home/suporte/.local/share/espanso/espanso.sock
17:35:30 [ INFO] espanso is running!

**Comment by federico-terzi** [comment]
Hey @eduardosramos,

I'm sorry you experienced this problem. If you type "espanso status" in a terminal, what do you see?

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.

This issue is related to #304, so keep track of that one if you want to stay updated.

Let me know if you have other questions.
Cheers :)
