### ISSUE TITLE
Espanso doesn't work properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by Sebreiro** [federico-terzi/espanso#243]
Hi,

When i'm starting espanso it says started correctly but daemon isn't running
```
user@ubuntu:~$ espanso start
Daemon started correctly!
user@ubuntu:~$ espanso status
espanso is not running
```

logs:
```
user@ubuntu:~$ espanso log
11:30:57 [ INFO] espanso version 0.5.5
11:30:57 [ INFO] using config path: /home/user/.config/espanso
11:30:57 [ INFO] using package path: /home/user/.local/share/espanso/packages
11:30:57 [ INFO] starting daemon...
11:30:57 [ERROR] Error, can't connect to X11 context
```

If i launch espanso directly with `espanso -v deamon` it's working
```
~$ espanso -v daemon
12:05:58 [ INFO] espanso version 0.5.5
12:05:58 [ INFO] using config path: /home/user/.config/espanso
12:05:58 [ INFO] using package path: /home/user/.local/share/espanso/packages
12:05:58 [ INFO] starting daemon...
12:05:58 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/espanso.sock
12:05:58 [ INFO] espanso is running!
```
But it's is not a proper way to run expanso, right?

I've read discussion on #161 , but there is no solution how to run espanso with `expanso start`

i'm using Kubuntu 18.04:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
With KDE Plasma:
```
plasmashell 5.12.9
```

Xorg version:
```
~$ xdpyinfo | grep version
version number:    11.0
X.Org version: 1.20.5
```

Display Environament Variable:
```
~$ echo $DISPLAY
:0
```

**Comment by federico-terzi** [comment]
Hey @Sebreiro,

I'm sorry you experienced this problem. Could you please open a terminal, start the following command, and see if espanso works? (while keeping the terminal open).

```
espanso -v daemon
```

Let me know if that works, so that I can diagnose the problem further

Cheers :)

**Comment by Sebreiro** [comment]
it's works with `espanso -v daemon`
```
~$ espanso -v daemon
14:41:20 [ INFO] espanso version 0.5.5
14:41:20 [ INFO] using config path: /home/user/.config/espanso
14:41:20 [ INFO] using package path: /home/user/.local/share/espanso/packages
14:41:20 [ INFO] starting daemon...
14:41:20 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/espanso.sock
14:41:20 [ INFO] espanso is running!
```

**Comment by federico-terzi** [comment]
Ok so it seems to be a problem with your Systemd configuration.
You could opt-in for the unmanaged mode, by adding the following line to your `default.yml` file:

```yaml
use_system_agent: false
```

The only downside of this approach is that you have to manually start espanso with `espanso start` at system startup (or configure a script to do so automatically).

Let me know if that works.

Cheers :)

**Comment by Sebreiro** [comment]
Yes, that works

Thank you for your help

**Comment by federico-terzi** [comment]
You're welcome :)
