### ISSUE TITLE
Propagate case with a prefix symbol

### ISSUE THREAD

**Issue by femtocept** [federico-terzi/espanso#244]
If you use the propagate case setting but use a symbol like : that has no case for the first symbol it will not work. Perhaps propagate_case could look starting at the first alphabet character. This is correct according to your documentation but perhaps an oversight. Propagate case will not work with a trigger string like ";gry" but it will work for something like "gry-", even though you cannot capitalize a "-".

Thanks for making espanso, it's pretty great.

**Comment by federico-terzi** [comment]
Hey @femtocept,

Thank you for the nice words! I see your point, I'll add it to the roadmap.

Cheers :)

**Comment by yksyks** [comment]
One more vote for this from me. I'm using a "§" prefix for accenting Portuguese characters (like **§a** making **ã**, and while it's not a big deal to enter all of them twice, it would be great.

**Comment by federico-terzi** [comment]
All right, thanks for the insight @yksyks

**Comment by federico-terzi** [comment]
Hey,
I'm currently releasing espanso 0.6.0 that also ships with this feature, so don't forget to update :)
Let me know if you experience any issues
