### ISSUE TITLE
Does not wait when Sublime Text is set as editor

### ISSUE THREAD

**Issue by swrobel** [federico-terzi/espanso#245]
```
$ espanso edit
Editing file: "~/Library/Preferences/espanso/default.yml"
<no wait here, this immediately prints, while the file opens in sublime>
File has not been modified, avoiding reload
$ echo $EDITOR
subl
```

macOS 10.15.4
espanso 0.5.5
Sublime Text 3

**Comment by federico-terzi** [comment]
Hey @swrobel,

Thank you for the report. That is probably due to the fact that `subl` spawns a sublime editor without waiting for its termination, causing this weird behaviour.

At the moment, there is no solution, but once #239 gets implemented, things should get better.

Cheers :)

**Comment by swrobel** [comment]
Previously I had set `EDITOR="subl -w"` to tell it to wait, but espanso didn't like that. It worked everywhere else (I've had it in my zshrc for years until I edited it for espanso).

```
$ EDITOR="subl -w" espanso edit
Error: could not start editor at: subl -w
```

(btw, no change if I set it to `/usr/local/bin/subl -w`

**Comment by federico-terzi** [comment]
This is most probably a bug then! I'll make sure to check this myself and get back to you in a few days.

Thanks for your help :)

**Comment by swrobel** [comment]
Thank **_you!_** 🙏

**Comment by federico-terzi** [comment]
Hey,
Just wanted to let you know that a fix for this bug will be shipped in the next release!
Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm currently releasing espanso 0.6.0 that also fixes this bug, so don't forget to update :)
Let me know if you experience any issues

**Comment by dym-sohin** [comment]
still happens with `EDITOR=subl` (even full path) on NixOS
i'll try to see if changing command to `/bin/sh` (the default on nix) would fix that
