### ISSUE TITLE
Case propagation applying when it should not

### ISSUE THREAD

**Issue by femtocept** [federico-terzi/espanso#252]
Hey Federico,

I noticed that expansions get triggered when they should not be if they are propagate case. A simple example for you to test this below:

```
  - trigger: "ther"
    replace: "there"
    propagate_case: true
    word: true
```

Testing:

- "ther" "Ther" and "THER" all correct properly, yes.
- type "other", it's fine with no match
- type "Other" and it will correct to Othere
- type "Xther" and it will correct to Xthere 
- type "OTHER" and it's fine with no match

It still happens if I change it to "thex" and "thexe" so I do not think it has to do with other matches I have configured. I don't use nested matches anywhere.

It might have something to do with the initial capital match but not the others.

I am currently on a Mac with espanso 0.5.5 

Thanks for everything.
BM

**Comment by federico-terzi** [comment]
Hey @femtocept,

Thanks for the feedback, this is definitely a bug! I'll do my best to fix it in the next release :)

Cheers

**Comment by yksyks** [comment]
Here it's even worse: even the published example **without** the propagate_case directive doesn't work. It generates _othere_. (Windows 10 Home, Estenso 0.5.5)

**Comment by federico-terzi** [comment]
> Here it's even worse: even the published example **without** the propagate_case directive doesn't work. It generates _othere_. (Windows 10 Home, Estenso 0.5.5)

You are right, I've just tested it on Windows. Thanks for pointing that out :)

**Comment by yksyks** [comment]
I thank you for your effort. I am new here, so at first I was afraid that I'm doing some mistake.

**Comment by federico-terzi** [comment]
Hey,
I'm currently releasing espanso 0.6.0 that also fixes this bug, so don't forget to update :)
Let me know if you experience any issues
