### ISSUE TITLE
[Documentation] A couple of small documentation issues

### ISSUE THREAD

**Issue by Adam13531** [federico-terzi/espanso#256]
Hey, I couldn't find a repo for the documentation itself, otherwise I would have submitted these as PRs:

## Issue 1
`toggle_key` on [this page](https://espanso.org/docs/configuration/) doesn't have a value of `OFF` listed:

![image](https://user-images.githubusercontent.com/7192897/80672593-19a6a080-8a62-11ea-8a52-1a3ca16cda80.png)

This value was added by @NickSeagull based on [this issue](https://github.com/federico-terzi/espanso/issues/126#issuecomment-557834178) and seems to require capitalization.

## Issue 2
Incorrect form of "its" on [this page](https://espanso.org/docs/configuration/) (see bolded text):

![image](https://user-images.githubusercontent.com/7192897/80672702-3f33aa00-8a62-11ea-9799-518db4829c2a.png)

...and on [this page](https://espanso.org/docs/get-started/):

![image](https://user-images.githubusercontent.com/7192897/80672861-a9e4e580-8a62-11ea-8128-c2311c330050.png)

**Comment by federico-terzi** [comment]
Hey  @Adam13531,

Thank you very much for your help! I'll fix them as soon as get my hands on documentation.

Cheers :)

**Comment by federico-terzi** [comment]
These errors should be fixed now. Thanks for your help :)
