### ISSUE TITLE
Textexpander like form expansion

### ISSUE THREAD

**Issue by maxandersen** [federico-terzi/espanso#257]
I saw there were now plans for a bundled web based UI.

Would that open up a way to get form expansion similar to textexpander fillins  https://textexpander.com/help/desktop/fillins.html with ability to have multiple choices ?

That would be excellent :)

**Comment by federico-terzi** [comment]
Hey @maxandersen,

Thanks for your feedback, this could be a great feature indeed!
I'll add it to the roadmap.

Cheers :)

**Comment by federico-terzi** [comment]
This can be closed at this point :)

**Comment by maxandersen** [comment]
Did it get implemented or?

**Comment by federico-terzi** [comment]
Yep, since version 0.7.0: https://espanso.org/docs/forms/
They still have a few rough edges, but they should improve over the next few versions
