### ISSUE TITLE
Backspace + space retriggers a replacement

### ISSUE THREAD

**Issue by Adam13531** [federico-terzi/espanso#264]
Repro GIF:
![test](https://user-images.githubusercontent.com/7192897/81032470-ce670600-8e44-11ea-97ed-228c6b510860.gif)

Repro:
1. Type `hi
2. Type space
3. Type backspace
4. Repeat from step 2

Expected: the text only expands a single time
Actual: the text just keeps expanding

Platform: Windows 10
Espanso version: 0.5.5
Config file:
```yaml
matches:
  - trigger: "`hi"
    replace: "Hello there"
    word: true
```

`espanso log` doesn't show anything interesting:
```
03:19:52 [ INFO] espanso version 0.5.5
03:19:52 [ INFO] using config path: C:\Users\agd13_000\AppData\Roaming\espanso
03:19:52 [ INFO] using package path: C:\Users\agd13_000\AppData\Local\espanso\packages
03:19:52 [ INFO] starting daemon...
03:19:52 [ INFO] Initializing Espanso resources in C:\Users\agd13_000\AppData\Local\espanso
03:19:52 [ INFO] BMP already initialized, skipping.
03:19:52 [ INFO] ICO already initialized, skipping.
03:19:52 [ INFO] espanso is running!
03:19:52 [ INFO] Binded to IPC tcp socket: 127.0.0.1:34982
```

This happens in every program I tested (Notepad, Visual Studio Code, Chrome, and some others). It does *not* happen on a brand new install of Windows 10 in Hyper-V. I dumped the config file from the VM to compare it with my physical machine, but there were no significant differences (just symbols like `→` or `€` which probably just pasted strangely into Notepad).

**Comment by federico-terzi** [comment]
Hey @Adam13531 ,

Thank you for reporting the problem, this is definitely a bug!
I'll look into it asap, so that hopefully we ship a fix in the next release.

Cheers :)

**Comment by federico-terzi** [comment]
I had a look to the problem, I was able to (partially) reproduce it once, but I still haven't found a reliable way to trigger this behavior.
It may be due to something installed on your machine, as it didn't happen on your Hyper-V VM either.
Do you have any tool that may manipulate key presses installed?
Which keyboard layout are you using?

Cheers :)

**Comment by Adam13531** [comment]
> Which keyboard layout are you using?

I'm on a QWERTY keyboard.

> Do you have any tool that may manipulate key presses installed?

It turns out that having either AutoHotkey *or* a program called `itype.exe` running will cause this bug (I'd only disabled AutoHotkey yesterday while investigating). FYI: `itype.exe` is installed for various Microsoft keyboards, which I am indeed using.

This bug is affecting me multiple times per day, so I suppose that for now, I'll have to switch back to AutoHotkey's hotstrings. 😢 I'd switched away from them in the first place due to two *other* bugs that I was experiencing. I'm now wondering if `itype.exe` is interfering with AutoHotkey as well.

Thanks for investigating this and for making espanso!

**Comment by federico-terzi** [comment]
Hey @Adam13531,
Thank you for the help tracking down the problem. I'll take a look at `itype` and let you know if there is something we can do about that!
Also, I don't want to break compatibility with AutoHotKeys, so I'll investigate.
Cheers :)

**Comment by federico-terzi** [comment]
Next release should mitigate this problem, if you have the chance, try it out when it goes public :)

**Comment by Adam13531** [comment]
I tried this out (sorry for the delay!) and couldn't get it to repro in my limited testing. 👍 However, part of that could be due to the Backspace Undo feature (#319) since it changes the expected behavior.

I'm not sure if I'll be able to test this for an extended amount of time, but given that it looks like it's fixed, I'll close the bug for now.

Thanks again!

**Comment by federico-terzi** [comment]
@Adam13531 Glad to hear that! Indeed, there were a couple of changes in the backspace handling which could have solved the issue
