### ISSUE TITLE
Cross-platform paths in ScriptExtension

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#265]
Introduce a way to define cross-platform paths for scripts. It may happen that, for example, a user wants to share a script between a Windows and macOS machine. 
To avoid producing duplicates, a solution could be to define keywords such as "%HOME%" that will be automatically expanded by espanso. 

In this way, a user could reference a script with:
`%HOME%/scripts/script.py`

This will solve problems such as: https://github.com/federico-terzi/espanso/issues/156#issuecomment-623910973

**Comment by federico-terzi** [comment]
Look at the discussion in #262

**Comment by federico-terzi** [comment]
Hey,
I'm currently releasing espanso 0.6.0 that ships with the possibility to define cross-platform paths!
Just use `%HOME%` at the beginning of your path, such as: `%HOME%/scripts/script.py`
Let me know if you experience any issues

**Comment by killtux** [comment]
is it possible to set os-specific triggers? for example i would like to get this work on my windows machine too:

for example:
  - trigger: ":excfg"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
            cmd: "echo vim $HOME/Library/Preferences/espanso/default.yml"

**Comment by federico-terzi** [comment]
> is it possible to set os-specific triggers? for example i would like to get this work on my windows machine too.

> for example:
> 
> * trigger: ":excfg"
>   replace: "{{output}}"
>   vars:
>   
>   * name: output
>     type: shell
>     params:
>     cmd: "echo vim $HOME/Library/Preferences/espanso/default.yml"

Even though it could be possible (with a lot of workarounds), this is not really meant for what you are trying to achieve. For this reason, I opened another issue (see #276). If you have any doubt/question, please ask them in that issue.

Hopefully, it will be shipped in the next release :)
