### ISSUE TITLE
Set trim option for shell script default to true

### ISSUE THREAD

**Issue by atika** [federico-terzi/espanso#272]
Most of the usage of shell script expander is for returning a simple text variable for a template, most of the commands return a new line at the end.
I think that __the result returned by the script__ should have to __be trimmed by default__ to avoid unexpected results. I personally have to set this option everywhere, when I started using this I was surprised to see that the terminal tried to execute the returned text as a command.

**Comment by federico-terzi** [comment]
Hey @atika,
This is indeed a good point. I'll keep the issue open for discussion, and if no-one raises any concern, I'll implement it in the next release.

Thanks for your help :)
