### ISSUE TITLE
User defined matches should have higher priority than package matches

### ISSUE THREAD

**Issue by atika** [federico-terzi/espanso#273]
When I installed a package I immediately thought if there was a way to overwrite or disable one of the expanders of it.
I tried with the emoji package and wanted to overwrite the `:sad` expander by creating a new one in the default YAML config file.
But this doesn't worked as expected because the package takes precedence to the default local file and the text replaced is from the package and not from the user config file.

**Comment by federico-terzi** [comment]
Hey
I agree with you on this one, the default config should have a higher priority than packages.
I'll make sure to fix this behavior in the next release.

Thanks for your help :)

**Comment by atika** [comment]
Thanks for you work, and to rename my title 😂

**Comment by federico-terzi** [comment]
No problem, thanks for pointing that out :)
