### ISSUE TITLE
Awkward expansion in VS Code (connected via Remote SSH)

### ISSUE THREAD

**Issue by dufferzafar** [federico-terzi/espanso#280]
The VS Code editor has a Remote SSH plugin that allows you to edit remote files with ease.

An issue with that setup is that there is some input latency involved, which causes such things to happen with Espanso, where it first expands and then deletes!

![Peek 2020-05-14 12-03](https://user-images.githubusercontent.com/1449512/81900892-5387b300-95db-11ea-9313-f6a72334052f.gif)

**Comment by federico-terzi** [comment]
Hey @dufferzafar,

That's surely an interesting behavior! What OS are you using?

Cheers :)

Cheers :)

**Comment by dufferzafar** [comment]
I'm using Manjaro KDE. And as I said, this happens only when I'm connected to a remote. So it doesn't happen in VS Code while editing local files. Since the input latency isn't a lot.

**Comment by federico-terzi** [comment]
If you have the latest version installed (0.6.0), then you could try fiddling with the `inject_delay` and `backspace_delay` and see if that helps.
In particular, add the `inject_delay` value to your default.yml config with a value like 10:

```yaml
inject_delay: 10
```

If you see an improvement, then we can convert it to an app-specific config so that it only works for VS code

**Comment by dufferzafar** [comment]
So, this isn't happening in all tabs of VS Code Remote either. Only when I'm editing a markdown file. In the same window, when I'm editing a python file or a plain text file, things are fine. This is getting weird. 

I tried with these settings, btw, the injection does become slow, but still some characters from the replacement get gobbled up:

```
inject_delay: 100
backspace_delay: 0
```

**Comment by federico-terzi** [comment]
> So, this isn't happening in all tabs of VS Code Remote either. Only when I'm editing a markdown file. In the same window, when I'm editing a python file or a plain text file, things are fine. This is getting weird.

At this point, it could be due to the way VS Code handles markdown files rather than an espanso issue :)

> I tried with these settings, btw, the injection does become slow, but still some characters from the replacement get gobbled up:
> 
> ```
> inject_delay: 100
> backspace_delay: 0
> ```

All right, I wasn't really expecting these settings to solve the problem, but without trying you never know!

**Comment by federico-terzi** [comment]
Hey @voidcase,
Please see if this solution works for you: https://github.com/federico-terzi/espanso/issues/248

**Comment by voidcase** [comment]
@federico-terzi 
No noticable difference. Even with

```
filter_class: "Firefox"
backspace_delay: 1000
inject_delay: 1000
```
in `~/.config/espanso/user/firefox.yaml`

espanso version: 0.6.1
installed via snap

**Comment by federico-terzi** [comment]
> @federico-terzi
> No noticable difference. Even with
> 
> ```
> filter_class: "Firefox"
> backspace_delay: 1000
> inject_delay: 1000
> ```
> 
> in `~/.config/espanso/user/firefox.yaml`
> 
> espanso version: 0.6.1
> installed via snap

Please try to rename the `firefox.yaml` into `firefox.yml` and see if that helps :)

**Comment by voidcase** [comment]
Aye, that works :) @federico-terzi

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
