### ISSUE TITLE
line breaks do not work

### ISSUE THREAD

**Issue by Philipp0205** [federico-terzi/espanso#285]
Thanks for making espanso! 
I have the following replacement: 
```
- trigger: ":mfg"
    replace:  Mit freundlichen Grüßen\n Philipp Kurrle
```

But when I type :mfg it pastes

```
Mit freundlichen Grüßen\n Philipp Kurrle
```
without linebreak.

At the top of my config I have `backend: Auto` and `auto_restart:true`. The backend prop was recommended on reddit where somebody had the same problem. 

Thanks!

**Comment by federico-terzi** [comment]
Hey @Philipp0205,

I'm sorry you experienced this problem, does it happen on every application?
Also, can you post the output of `espanso log` here?

Cheers :)

**Comment by Philipp0205** [comment]
Hey @federico-terzi 
here is the log: 

```
18:27:41 [ INFO] espanso version 0.6.0
18:27:41 [ INFO] using config path: /home/philipp/.config/espanso
18:27:41 [ INFO] using package path: /home/philipp/.local/share/espanso/packages
18:27:41 [ INFO] spawning worker process...
18:27:41 [ INFO] Binded to IPC unix socket: /home/philipp/.local/share/espanso/espanso.sock
18:27:41 [ INFO] initializing worker process...
18:27:41 [ INFO] Binded to IPC unix socket: /home/philipp/.local/share/espanso/worker.sock
18:27:41 [ INFO] worker is running!
18:27:41 [ INFO] watching for changes in path: /home/philipp/.config/espanso
```
I restarted espanso and triggered :mfg one time. This happens on every application.

**Comment by federico-terzi** [comment]
All right, thank you.

Could you please try to add double quotes and see if that helps?

```yaml
- trigger: ":mfg"
  replace:  "Mit freundlichen Grüßen\n Philipp Kurrle"
```

Let me know it that helps :)

**Comment by Philipp0205** [comment]
Okaaay. Now it works in most applications. In some relevant like Thunderbird not but that just might be specific to that application. Thanks!

**Comment by federico-terzi** [comment]
No problem :)
Thunderbird is known to be a bit problematic. What you could do is adding a file named `thunderbird.yml` in the `user/` directory with the following content:

```yaml
name: Thunderbird

filter_class: "Thunderbird"
backend: Clipboard
paste_shortcut: CtrlShiftV
```

This could help a bit :)
