### ISSUE TITLE
When two triggers have the same "root" name, expansion is not possible for the trigger with the longer name

### ISSUE THREAD

**Issue by ggyanez** [federico-terzi/espanso#289]
Hi, I've just found this tool, and it's freaking amazing! I've recently used Mac and Windows10 (I'm now using Ubuntu), and tried many different text expansion tools. But this is the best one so far (and the documentation/website is nice).

Congrats and thanks for making it open-source!

Ok, regaring the issue (I don't actually know if this is an issue, or if it's normal behaviour): if two triggers have the same "root" in the name, then there's no way to trigger the one with the longer trigger name.

Example: if there're two triggers called: ":test" and ":testname", then there's no way to use ":testname" because when you type ":test", the first expansion is automaticdally triggered before you can even finish typing "...name".

![image](https://user-images.githubusercontent.com/41060379/82573625-63177680-9b5c-11ea-9a60-dfa249684c05.png)

Is there any workaround to this? I've noticed that other expander tools let you configure the expansion trigger event. For example, on some tools the expansion is triggered/evaluated only when you press space, tab, etc. On espanso, text expansion is done automatically. But if it had the possibility to only expand after a space press, then it would be possible to type ":testname" and trigger this expansion by pressing space.

**Comment by federico-terzi** [comment]
Hey @ggyanez 

Thanks for the kind words :) Indeed espanso (by default) expands a match as soon as you type the trigger. If you want to expand it only after pressing space, you can use [word triggers](https://espanso.org/docs/matches/#word-triggers).

The fact that if one trigger is the prefix of another one prevents the expansion of the latter is a known problem, see #178. Spoiler alert, no solution yet :)

Cheers :)
