### ISSUE TITLE
[sugestion] Arguments in Active mode

### ISSUE THREAD

**Issue by stheid** [federico-terzi/espanso#292]
related to the issue of prefixes (#178) normally this would not be possible, but i would suggest it as follows

# usage:
`:cmd/.*/` exectues trigger cmd with the args. Note that in this case the backslashes are mandatory, as the second backslash will finish the trigger.

# config:
- add a flag for `has_args`

it is probably also useful to enforce a maximum length of the argument in order to avoid user eerrors when the second backslash has been forgotten.

**Comment by federico-terzi** [comment]
Hey @stheid 

Thank you for the feedback! Even though I'd like active mode arguments as well, there are some core issues that could not be easily solved. For example, only to name a few:
* Espanso would need to keep in memory an indefinite length of pressed chars, which could be bad from a security perspective.
* If the user types `:cmd/.*` and then changes application or forgets to close the slash, then espanso would be incapable of expanding any other match, thinking that the user was still entering the argument.

I'm not saying that those problems are insurmountable, but I don't think there is a robust way to implement it as of now. Therefore, I prefer to avoid introducing an instable feature.

Please see #257 for an alternative to this approach, which will be likely introduced after the GUI makes its way out there!

Cheers :)
