### ISSUE TITLE
espanso fails with error BadWindow

### ISSUE THREAD

**Issue by jcassee** [federico-terzi/espanso#312]
Sometimes, espanso dies with an error like this:
```
jun 05 15:43:49 stevens espanso[42009]: X Error of failed request:  BadWindow (invalid Window parameter)
jun 05 15:43:49 stevens espanso[42009]:   Major opcode of failed request:  20 (X_GetProperty)
jun 05 15:43:49 stevens espanso[42009]:   Resource id in failed request:  0x6400063
jun 05 15:43:49 stevens espanso[42009]:   Serial number of failed request:  23
jun 05 15:43:49 stevens espanso[42009]:   Current serial number in output stream:  23
```

This happens a few times each day. Not that big of a deal as it is restarted, but it does cause a notification to pop up: "espanso started".

A quick internet search suggests espanso is trying to query a window that no longer exists (was just closed), so the error could probably be caught and ignored?

**Comment by federico-terzi** [comment]
Hey @jcassee 
Thanks for reporting this bug! Could you give me the following info:
* What distro/espanso version are you using?
* Do you have any idea about which app triggers this error?

Cheers :)

**Comment by federico-terzi** [comment]
All right, thank you @jcassee. Yes indeed that seems to be the same error as the #302 comment, I'll dig into it as soon as I get my hands on my Linux machine

**Comment by jcassee** [comment]
I have found a way to trigger this error problem. I use [Easystroke](https://github.com/thjaeger/easystroke/wiki) gestures, and every time I close a window using a gesture (I use a single down stroke mapped to Alt-F4) espanso exits with this error. The error does not trigger if I press Alt-F4 one the keyboard or close a window with the mouse.

**Comment by federico-terzi** [comment]
All right, thank you for the help @jcassee. Hopefully I will be able to track down the issue now :)

**Comment by D1mon** [comment]
```bash
espanso daemon
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  101 (X_GetKeyboardMapping)
  Value in failed request:  0x0
  Serial number of failed request:  35
  Current serial number in output stream:  35
10:33:41 [ERROR] worker process exited with non-zero code: 1, exiting

espanso log
10:33:27 [ INFO] espanso version 0.6.2
10:33:27 [ INFO] using config path: /home/user/.config/espanso
10:33:27 [ INFO] using package path: /home/user/.local/share/espanso/packages
10:33:27 [ INFO] spawning worker process...
10:33:27 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/espanso.sock
10:33:27 [ INFO] initializing worker process...
10:33:27 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/worker.sock
10:33:27 [ INFO] worker is running!
10:33:27 [ INFO] watching for changes in path: /home/user/.config/espanso
10:33:41 [ERROR] worker process exited with non-zero code: 1, exiting
```
not working:
1) install aur -> espanso-bin (v0.6.2) and espanso-bin(v0.6.0)
2) cp espanso ~/bin from github (0.6.2)

espanso (v.0.4.0) - works fine

**Comment by federico-terzi** [comment]
Hey @D1mon
This problem should be fixed in the next release, in the meanwhile I suggest you to install the espanso package rather than espanso-bin

Cheers

**Comment by jcassee** [comment]
Thanks, @federico-terzi!
