### ISSUE TITLE
Send tab on Windows

### ISSUE THREAD

**Issue by mrrcollins** [federico-terzi/espanso#313]
It would be nice to be able to send the tab key under windows. 😄

**Comment by federico-terzi** [comment]
Hey,
Thank you for the feedback! I'll add it to the feature requests :)

**Comment by federico-terzi** [comment]
As a reference, it seems to be related to #286

**Comment by iamdoubz** [comment]
Use "\t" for tabs @mrrcollins

**Comment by mrrcollins** [comment]
> Use "\t" for tabs @mrrcollins

It seems that doesn't work under windows. 😄

**Comment by iamdoubz** [comment]
I am on Windows 10 Pro 2004 build 19041.264. It works just fine for me :)

**Comment by federico-terzi** [comment]
At this point, it might be that it only works on certain applications!
In which apps are you having problems @mrrcollins?

**Comment by mrrcollins** [comment]
It was the Brave browser that I was trying to use. Let me try it in a different browser!

**Comment by mrrcollins** [comment]
Same behavior in Firefox so I tested the expansion in VS Code, and it still didn't work. That was odd since it worked for @iamdoubz so I tried a few different tests. I stumbled upon the when it works and doesn't work. On a single line **Replace:**, Espanso will expand the tab. Espanso does not expand a \t to a tab when used in a multi-line replace with the literal block scalar, | or folding block scalar, >.

For my use case, I wanted to be able to put my cursor in to the subject on a new email in Gmail, and expand out a subject, tab to the message area, and expand the rest. Unfortunately, this doesn't work even when I use the single line replace. It's not a deal breaker, just a nice to have. 😄

**Comment by federico-terzi** [comment]
Thank you for the investigation @mrrcollins! That is surely helpful to track down the problem. In the future, I'm planning to introduce a feature which will make this process much smoother

**Comment by hybrid2102** [comment]
I also need this feature.
I'm developing and testing an application that prompts for credentials on every run.
Using TyperTask, for example, I'm able to insert credentials in this way:
ppp=myusername{TAB}mypassword{ENTER}

**Comment by federico-terzi** [comment]
I'm closing this issue in favor of #286 :)
