### ISSUE TITLE
Installed, started, but not running

### ISSUE THREAD

**Issue by storyjesse** [federico-terzi/espanso#314]
Hi I installed espanso from the deb package on LinuxMint 19 Tara, Cinnamon 4.0.10, Kernel: 4.15.0-99-generic x86_64 
It installed without error and `espanso start` returns `Daemon started correctly!` But espanso status then returns `espanso is not running`
```
jesse@Limbo ~ $ espanso status
espanso is not running
jesse@Limbo ~ $ espanso start
Daemon started correctly!
jesse@Limbo ~ $ espanso status
espanso is not running
```

**Comment by federico-terzi** [comment]
Hey 
That's pretty strange! Could you please post the output of `espanso log` here?

Cheers :)

**Comment by storyjesse** [comment]
Sure here ya go:
[xdpyinfo.txt](https://github.com/federico-terzi/espanso/files/4765709/xdpyinfo.txt)

**Comment by federico-terzi** [comment]
Thank you @storyjesse, it seems like the record extension is enabled. Let's try with another thing.
Open a terminal and type:

```
espanso -v worker
```

Then while leaving it running, open any app and type `:espanso`. Let me know if it works in this case

Cheers :)

**Comment by storyjesse** [comment]
Yes that worked! The result was "Hi there!"
I'm happy to continue testing with you but I actually prefer to have espanso only running temporarily rather than as a daemon. If there was a way to restrict which applications it monitored that would be awesome! but without that feature I'd prefer to turn it on and off. No offense intended but I don't feel comfortable with an application monitoring my keystrokes 100% of the time. ;-)

**Comment by federico-terzi** [comment]
Sure! Glad you sorted that out :)

**Comment by gokulsoumya** [comment]
Closely related issue (and possible workaround) - #324
