### ISSUE TITLE
Trigger won't cause replace

### ISSUE THREAD

**Issue by cyberfux** [federico-terzi/espanso#315]
I did a package (german-plz) which is live, but for some reason or another i can't trigger the trigger.

Not always but sometimes - no rhyme no reason.

Screencast of the problem:
[https://drive.google.com/file/d/1LTS4oJ1DAC8jZRoTD22zL2I09YA6_7fs/view?usp=sharing](url)

**Comment by federico-terzi** [comment]
Hey,
Unfortunately I'm not able to see the file, if possible could you post it here? You can just drag it into the comment bar
Cheers :)

**Comment by cyberfux** [comment]
Unfortunately it's bigger then 10MB

**Comment by federico-terzi** [comment]
I see, that's unfortunate

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
