### ISSUE TITLE
tab after newline \n\t inserts only tab on new line

### ISSUE THREAD

**Issue by anaxios** [federico-terzi/espanso#318]
I'm trying to make a template and when I use the tab escape it inserts the tab character on the newline and deletes everything else until the next new line. Output is the same in Obsidian and TextEdit.

config:
`replace: "- Author:: \n\t Category:: \nSubject::"`

```
- Author:: 

Subject:: 
```

BTW - Thanks for making espanso. It's irreplaceable.

**Comment by federico-terzi** [comment]
Hey 

Any chance you could post an animated gif with that happening? I'm sorry but I didn't understand the problem and what you are trying to achieve

Cheers :)

**Comment by anaxios** [comment]
I'm not sure how to make a gif of my screen. If this doesn't help I'll try to figure it out.

```
  # Source Template
  - trigger: ":tmps"
    replace: "- Author:: \n\tCategory:: \nSubject:: \nPublished:: \nThesis:: \nPagination:: what system I'm following for location references (e.g. kindle loc, epub page number) and what the total is (to account for different editions, iBooks resizing) \nPreparatory Brain Dump:: \nTable of Contents:: \nNotes:: \nChapter 1 Pre Read \nChapter 1 \nhas [[Claim]]s \nChapter 1 Summary \n"
    word: true
```
Here's the output:

![With tab](https://anaxios.github.io/images/Screen_shot_with_tab.png)

Here's the desired effect:

![Desired](https://anaxios.github.io/images/Screen_shot_desired.png)

**Comment by federico-terzi** [comment]
All right, it's clear now thank you. Unfortunately, as of now there is no feature to achieve what you want, but I'm actively working on one that should make this possible.
In the meanwhile, what about explicitly adding the `-` and spaces in your replacement text? Such as:

```
  - trigger: ":tmps"
    replace: "- Author:: \n    - Category:: \n- Subject:: \n- Published::"
    word: true
```

**Comment by anaxios** [comment]
I tried that, but it seems Obsidian wants very specific input to get it to work. It's really only a minor convenience and I thought it was maybe a bug I should report.

Thank you for taking your time to investigate it.

**Comment by federico-terzi** [comment]
No problem! I'll let you know once it's possible :)
