### ISSUE TITLE
Backspace to discard expansion

### ISSUE THREAD

**Issue by aburtsev** [federico-terzi/espanso#319]
It would be great to have the ability to discard (revert) an expansion using backspace.

Expected behavior:

1. type ":hi"
1. expand to "hello"
1. press backspace is reverting "hello" to ":hi"

The same behavior would be nice to have with a "word" match too.

Best regards

**Comment by federico-terzi** [comment]
Hey @aburtsev,

Thank you for the feedback! I'll add it to the roadmap as it seems like a very useful feature to have

Cheers :)

**Comment by federico-terzi** [comment]
Happy to say this feature will be released in the next version!

**Comment by federico-terzi** [comment]
Closing as the feature has been shipped in 0.7.0 :)
