### ISSUE TITLE
Let user config files have multiple parents

### ISSUE THREAD

**Issue by avi-cenna** [federico-terzi/espanso#320]
I think enabling user configuration files to have multiple parents would be useful when we have a complex set of filter requirements. For example, imagine the following situation: I some matches that I want to be enabled for all programs, some matches only for Chrome and Firefox, and some matches only for Chrome.

Espanso filter statements cannot overlap, i.e. I can't have one config file that has `filter_title: "(Chrome|Firefox)"` and another file with `filter_title: "Chrome"`.

I'm thinking that one way to solve this would be to have three config files. The first would filter only for Chrome. The second only for Firefox. The third would have a `parent` statement which specifies the first two config files, and it would contain matches that are applicable to both Chrome and Firefox. Then in the Chrome config file I can add additional Chrome-specific matches.

**Comment by federico-terzi** [comment]
Thank you @avi-cenna for the feedback, your idea seems definitely very useful!
I'll add it to the roadmap :)

**Comment by federico-terzi** [comment]
Hey @avi-cenna,

I think we can safely close this issue as the new alpha v2 comes with a redesigned configuration system that handles this use-case pretty well. The documentation is still lacking, but the main changes are explained here: https://espanso.org/docs/next/migration/configuration_changes/

In short, we dropped the concept of `parent`, and now each application can "include" or "exclude" certain matches

Cheers :)
