### ISSUE TITLE
Match anything

### ISSUE THREAD

**Issue by michalsieron** [federico-terzi/espanso#323]
Hi, so I am new to espanso and I am loving it so far.
What I am trying to do is to have some set of math characters replaced. Something like :int -> ∫ or :sum -> ∑ and so on. And I can't find any info whether I can do something like :^{123} -> ¹²³ where 123 could be replaced with anything so I can have one script that tries to replace given characters to super/subscript. So I would like to have trigger like :^{*} where * could be anything and it would be passed to script.

**Comment by federico-terzi** [comment]
Hey @michalsieron,

Thanks for the kind words :) At the moment, your best bet is passive mode; https://espanso.org/docs/passive-mode/

In the future, a much better alternative will be #257 

Cheers :)

**Comment by michalsieron** [comment]
Thanks for quick response! I will check it right away
