### ISSUE TITLE
`espanso start` doesn't work ("can't connect to X11 context") but `espanso daemon` works

### ISSUE THREAD

**Issue by jpetazzo** [federico-terzi/espanso#324]
Hi,

After installing espanso on ArchLinux (using `aur/espanso-bin 0.6.2-1`), this is what I'm seeing:

```
[jp@hex ~]$ espanso start
Daemon started correctly!
[jp@hex ~]$ espanso status
espanso is not running
[jp@hex ~]$ espanso log
06:25:46 [ INFO] espanso version 0.6.2
06:25:46 [ INFO] using config path: /home/jp/.config/espanso
06:25:46 [ INFO] using package path: /home/jp/.local/share/espanso/packages
06:25:46 [ INFO] spawning worker process...
06:25:46 [ INFO] Binded to IPC unix socket: /home/jp/.local/share/espanso/espanso.sock
06:25:46 [ INFO] initializing worker process...
06:25:46 [ERROR] Error, can't connect to X11 context
06:25:46 [ERROR] worker process exited with non-zero code: 100, exiting
```

If I run `espanso daemon` or `espanso -v worker`, it starts:

```
[jp@hex ~]$ espanso -v worker
06:23:04 [ INFO] initializing worker process...
06:23:04 [ INFO] Binded to IPC unix socket: /home/jp/.local/share/espanso/worker.sock
06:23:04 [ INFO] worker is running!
```

I'm using Xorg, started with `startx`. (I wonder if this is because I'm using `startx` instead of a desktop manager?)

Two questions:
1. Is there anything wrong with starting espanso in a different way? (Other than through the systemd unit, I mean)
2. Do you want me to investigate this further? Any particular thing you'd like me to try?

**Comment by federico-terzi** [comment]
Hey @jpetazzo,

Thank you for the feedback!

> 1. Is there anything wrong with starting espanso in a different way? (Other than through the systemd unit, I mean)

My first guess is that in the first example, espanso cannot read the `DISPLAY` env variable (set by the X server) whereas when calling `espanso -v worker` directly it does.

> 2. Do you want me to investigate this further? Any particular thing you'd like me to try?

We should first try to figure out the previous point, as 99% of the times this problem happens when espanso is started and the desktop environment is not "ready".

Cheers :)

**Comment by jpetazzo** [comment]
I think the desktop environment *is* ready, because I'm running `espanso start` from the desktop environment, while it's already running.

**Comment by federico-terzi** [comment]
All right, thank you @jpetazzo. Let's try with a workaround injecting the DISPLAY var directly, and if it works I'll make sure to bundle it in espanso itself:

Modify the `$HOME/.config/systemd/user/espanso.service` file and add the following line under the `[Service]` section:

```
Environment="DISPLAY=:0"
```

Then try again with `espanso start` and see if that works

**Comment by federico-terzi** [comment]
@jpetazzo did it work?

**Comment by jpetazzo** [comment]
It worked on my main machine, yes.

However, on my second machine, `DISPLAY` is `:1` (I think this is because of the Gnome Desktop Manager starting a separate X server for each user, but I'm not quite sure.)

So ... I'm not sure about the right solution :)

Apparently there is a `graphical-session.target` ([docs](https://www.freedesktop.org/software/systemd/man/systemd.special.html)) but it didn't seem to help on my machine (but perhaps I did something wrong).

**Comment by federico-terzi** [comment]
All right, thank you :) In your second machine, did setting `DISPLAY=:1` work?

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)

**Comment by jpetazzo** [comment]
:+1: all good!

For reference (just in case someone has a similar issue), I ended up starting espanso directly from my i3 configuration file, like this:

```
exec --no-startup-id espanso daemon
```

It's been working perfectly fine since then. Thank you!

**Comment by federico-terzi** [comment]
Seems great! Thanks for sharing @jpetazzo

**Comment by pietro14** [comment]
I have a similar problem. If I run `espanso start` everything works at the beginning. But after a while, it stops working. This is what I have done:

Started espanso, and checked if it works:
```
$ espanso start
daemon started!
```

Checked logs (everything is fine):
```
$ espanso log
14:46:25 [ INFO] espanso version 0.7.3
14:46:25 [ INFO] using config path: /home/pietro/.config/espanso
14:46:25 [ INFO] using package path: /home/pietro/.local/share/espanso/packages
14:46:25 [ INFO] spawning worker process...
14:46:25 [ INFO] Binded to IPC unix socket: /home/pietro/.local/share/espanso/espanso.sock
14:46:25 [ INFO] initializing worker process...
14:46:25 [ INFO] Binded to IPC unix socket: /home/pietro/.local/share/espanso/worker.sock
14:46:25 [ INFO] worker is running!
14:46:25 [ INFO] watching for changes in path: /home/pietro/.config/espanso
```

After 15 minutes, it stops working and this is the log:
```
$ espanso log
15:00:01 [ INFO] espanso version 0.7.3
15:00:01 [ INFO] using config path: /home/pietro/.config/espanso
15:00:01 [ INFO] using package path: /home/pietro/.local/share/espanso/packages
15:00:01 [ INFO] spawning worker process...
15:00:01 [ INFO] Binded to IPC unix socket: /home/pietro/.local/share/espanso/espanso.sock
15:00:01 [ INFO] initializing worker process...
15:00:01 [ERROR] Error, can't connect to X11 context
15:00:01 [ERROR] worker process exited with non-zero code: 100, exiting
```

**Comment by federico-terzi** [comment]
Hey @pietro14,

I'm sorry you experienced this problem! Could you please try upgrading to the new v2 and see if the problem persists? See: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by federico-terzi** [comment]
@pietro14 Nice! Glad you got that working

As a side note, the latest version (pre-release) is the v2.1.2-alpha and not 0.7.3. Just pointing that out in case you got confused :)

Cheers :)
