### ISSUE TITLE
Installing my own package returns "Invalid zip header"

### ISSUE THREAD

**Issue by JPUnD** [federico-terzi/espanso#326]
Hi there,

I've just created my own package cloning from the default [espanso-package-example](https://github.com/federico-terzi/espanso-package-example) and the result is my own package [espanso-math-symbols](https://github.com/JPUnD/espanso-math-symbols).

Running:
```
espanso install math-symbols https://github.com/JPUnD/espanso-math-symbols.git --external
```
Returns:
```
Allowing external repositories
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Invalid zip header")', src/package/zip.rs:30:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've done everything as expected, and placing the root dir of the package in `~/.local/share/espanso/packages` works as expected, after hitting `espanso restart` of course.

It might be me doing something dumb, but i've searched around this github for similar issues and found none and documentation doesn't seem to mention anything about this.

Thanks!

**Comment by federico-terzi** [comment]
Hey @JPUnD,

Could you please try removing the `.git` suffix from the URL and try again?

```
espanso install math-symbols https://github.com/JPUnD/espanso-math-symbols --external
```

If that solves the problem, I'll make sure to add a check in the next version of espanso to ignore it.

Cheers :)

**Comment by JPUnD** [comment]
Yup it worked as expected, thanks!

Now that i'm here i'll provide some feedback, this is my first time actually doing something in an open-source project, although it's a very tiny something, but it was pretty easy to have espanso up and running and creating a package for it and thanks to the built-in package manager installing packages is also very easy, really good job so far!

I'm not closing this issue so that you remember to fix this in the next version xD, feel free to close it as soon as it's working as expected.

**Comment by federico-terzi** [comment]
Glad to hear that! :)
