### ISSUE TITLE
espanso notifications settings

### ISSUE THREAD

**Issue by natanavra** [federico-terzi/espanso#327]
Espanso should have notification settings (or alternatively, an option to disable the "secure input" notifications)
Totally disabling notifications prevents you from knowning when espanso was disabled by double "alt" press
Keeping notifications pops up messages every time there's a secure input (mac login window, browser, etc) which can get annoying

**Comment by federico-terzi** [comment]
Hey,

Luckily, there is an option exactly for that :) Just add the following line to your `default.yml` file:

```
secure_input_notification: false
```

I'll change the title of the issue so that if other users search for it they can find it

Cheers :)
