### ISSUE TITLE
Espanso in LibreOffice Write

### ISSUE THREAD

**Issue by eexil** [federico-terzi/espanso#329]
espanso isn't expanding correctly in LibreOffice Writer lately. It started after I moved from Linux Mint to Manjaro and also updated LibreOffice and espanso. My version of LibreOffice is is 6.3.6.2. espanso, I do not know what it version, but I installed it a couple of weeks ago from the instructions on your page.

The expansion works correctly in all other applications, but not in Writer. There the expansions there are erratic and not the same every time. One interesting thing is that the first couple of expansions after a new boot up of the computer and start of Writer it will work ok, but then it will start to fail. Mostly it will not remove the trigger text and the expansion is not expanding correctly.

At first I thought perhaps the function of Word Completion in Writer could be interfering so I disabled that, but it did not fix the issue.

The interesting thing is that I started using espanso because I had the exact same issue with Autokey before, and moved to espanso because of it (https://bugs.documentfoundation.org/show_bug.cgi?id=113842)

Thanks,

**Comment by federico-terzi** [comment]
Hey @eexil,

I'm sorry you are experiencing this issue. My first guess is that you will need to add a patch file for writer:

Add a `writer.yml` file in the `user/` config folder with the following content:

```yaml
filter_class: "libreoffice-writer"
backspace_delay: 10
inject_delay: 10
```

Then restart espanso

Let me know if that helps!

Cheers :)

**Comment by eexil** [comment]
Thank you for getting back to me. I appreciate that very much.

I added the writer.yml file to my config folder as you suggested and restarted espanso, but the issue persisted, so I rebooted the computer, but that did not change anything either.

I tried to increase the numbers to 15, but the issue stayed the same.

**Comment by federico-terzi** [comment]
All right, that's unfortunate! I'll try to take a look at it myself and get back to you if I find a solution!

Cheers :)

**Comment by federico-terzi** [comment]
@eexil Indeed the default behavior is pretty much broken, but I think I might have found a decent solution. Please try with this patch file:

```yaml
filter_class: "libreoffice-writer"
backspace_delay: 15
backend: Clipboard
```

Let me know if that helps!

**Comment by eexil** [comment]
Hi federico-terzi

Should this code substitute the previous in writer.yml in user/config?
If it should then it did not make any difference I am afraid. If it should be put somewhere else, please advice.

regards,

**Comment by federico-terzi** [comment]
That's unfortunate. I suspect the class might be different in your case. Could you please do the following procedure and post the output here:

1. Open a terminal and start `espanso detect`
2. While leaving the terminal open, type something on Libreoffice Writer
3. Then return to the terminal, terminate the script with CTRL+C and copy the output here.

Cheers :)

**Comment by eexil** [comment]
Hi federico-terzi 

Here is my out put:
espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: '~ : bash — Konsole'
==> Class: 'konsole'
==> Executable: ''

Detected change, current window has properties:
==> Title: '~ : espanso — Konsole'
==> Class: 'konsole'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'Plasma'
==> Class: 'plasmashell'
==> Executable: '/usr/bin/plasmashell'

Detected change, current window has properties:
==> Title: 'Untitled 1 - LibreOffice Writer'
==> Class: 'libreoffice-writer'
==> Executable: ''

Detected change, current window has properties:
==> Title: '~ : espanso — Konsole'
==> Class: 'konsole'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'Untitled 1 - LibreOffice Writer'
==> Class: 'libreoffice-writer'
==> Executable: ''

Detected change, current window has properties:
==> Title: '~ : espanso — Konsole'
==> Class: 'konsole'
==> Executable: '

Thank you :)

**Comment by federico-terzi** [comment]
Thank you @eexil, unfortunately it seems like the previous code I gave you was correct so I'm not particularly sure what could be. Let's try with this one:

In your `default.yml` file, add:

```yaml
backspace_delay: 30
backend: Clipboard
```

Then restart espanso and try again with LibreOffice. If it works it means that we messed up something with the patch (which would be easy to solve).

Let me know

**Comment by eexil** [comment]
Hi federico-terzi and than you for your time.

I added the code into a new file /etc/default/default.yml but it did not make any difference.
But then looking at it, I was wondering should it perhaps say 

`filter_class: "libreoffice-writer"` in front?

**Comment by federico-terzi** [comment]
I think we are going in the right direction. The path `/etc/default/default.yml` is probably incorrect, could you please post the output of `espanso path default` here? That would be the correct location of the default file

**Comment by eexil** [comment]
Hi federico-terzi

It seems I finally understood what you wanted me to do :)

So in the /home/XXX/.config/espanso/user/ I created the file writer.yml with your code:

```
backspace_delay: 30
backend: Clipboard
```
and now it is expanding correctly in Libreoffice writer too.

Thank you very much :)

**Comment by federico-terzi** [comment]
Glad to hear that! 

Cheers :)
