### ISSUE TITLE
Add support for Ctrl+Shift+V shortcut on Windows

### ISSUE THREAD

**Issue by OlivierDupre** [federico-terzi/espanso#333]
Hi,

I'm using Ubuntu 20.04 on Windows 10 Pro 1903 (Build 18362.778).
I using:
- WSL 
- **XLaunch** (https://sourceforge.net/projects/vcxsrv/)
- **Terminator** (https://terminator-gtk3.readthedocs.io/en/latest/)
- Either Zsh with OhMyZsh & PowerLevel10k or raw Bash.

And with that exact configuration, replacements are just... dropping the trigger. Cursor is going back to the beggining of the trigger and the trigger is erased without being replaced.

When running the exact same config but in Windows Terminal (so, without Terminator & XLaunch), it's running perfectly fine.
At that stage, I can't tell whether it is related to XLaunch, Terminator or both.

Cheers,
Olivier

**Comment by OlivierDupre** [comment]
Update: I reproduced the same environment directly on Linux Ubuntu 20.04 with Terminator and (as expected) it works like a charm.
Looks like VcXSrv might be the root cause.

**Comment by federico-terzi** [comment]
Hey,

This is an interesting scenario. Just for clarification, are you using a Linux desktop manager on Windows? I'm only familiar with WSL1 which allowed users to execute commands, but I still have to dig into WSL2.

Could you please execute the following procedure and post the output here:
1. Open a Windows terminal and start `espanso detect`
2. While leaving the terminal open, type something on Terminator on XLaunch
3. Then return to the Windows terminal, terminate the script with CTRL+C and copy the output here.

Cheers :)

**Comment by OlivierDupre** [comment]
Hey,

No, not exactly. I'm not using a full Linux DM on Windows. I'm just exporting the display to a third party XServer (VcXSrv aka XLaunch) for soft needing a GUI (terminator here).
This is the best solution I found to have a smooth Linux experience on WSL1 on my Windows 10 (own by my company handling the updates... so without yet WSL2).
WSL2 is known to bring some cool support on this experience but... it's too early for me/my company ;)

If you are interesting in this configuration, here are the 2 configuration files I'm using (it uses AutoHotKey for key binding to launch Terminator in "Guake" mode)
https://github.com/OlivierDupre/ansible-setup/blob/master/wsl-terminator.vbs#L35
https://github.com/OlivierDupre/ansible-setup/blob/master/AutoHotKey.ahk

And here is the listing you asked me:
`PS C:\Users\odupre> espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'Windows PowerShell'
==> Class: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
==> Executable: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'

Detected change, current window has properties:
==> Title: 'Changement de tâche'
==> Class: 'C:\Windows\explorer.exe'
==> Executable: 'C:\Windows\explorer.exe'

Detected change, current window has properties:
==> Title: 'VcXsrv Server - Display LFR044394:0.0'
==> Class: 'C:\Program Files\VcXsrv\vcxsrv.exe'
==> Executable: 'C:\Program Files\VcXsrv\vcxsrv.exe'

Detected change, current window has properties:
==> Title: 'Windows PowerShell'
==> Class: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
==> Executable: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'

Detected change, current window has properties:
==> Title: 'Sélection Windows PowerShell'
==> Class: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
==> Executable: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'

Detected change, current window has properties:
==> Title: 'Windows PowerShell'
==> Class: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
==> Executable: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'`

Cheers,
O.

**Comment by federico-terzi** [comment]
All right, thank you @OlivierDupre. The last missing piece is: can you copy/paste your clipboard content to/from the Terminator window and other Windows apps? If so, which shortcut are you using?

**Comment by OlivierDupre** [comment]
Well. Actually I can, using CTRL-SHIFT-C & CTRL-SHIFT-V _(as CTRL-C is already used for killing foreground processes)_.

**Comment by federico-terzi** [comment]
At the moment, that shortcut is not supported on Windows, but I'll make sure to add support in the next release

**Comment by OlivierDupre** [comment]
Well. I had a look at your code and I understand what you're doing (and why). So I tried to find a turn-around on my side.
The best I can do I think is to enable CTRL-C & CTRL-V for copy/paste. But the former is sending to clipboard only when text is highlighted. While the later works like a charm. But that does not fix the problem. Even though I select text prior to typing an espanso trigger.

**Comment by federico-terzi** [comment]
If you are able to enable CTRL+V on Terminator, then you can tell espanso to use the clipboard instead of the default injection mechanism. In particular, you can try the following:

Create a file `terminator.yml` in your `user/` config directory (the one that also has `default.yml`) with the following content:

```yaml
filter_class: "vcxsrv.exe"
backend: Clipboard
```

and then restart espanso. What this patch does is telling espanso to use the Clipboard when using VXServer.

Let me know if that works for you

**Comment by OlivierDupre** [comment]
Won.Der.Ful.

It works like a charm. You made my day.

Thank you very much.

_PS: I'm not sure I'll be able to keep that Ctrl-C config. We'll see how it competes with default shell behavior. But as of now, it behaves perfectly. Thanks a lot._

**Comment by federico-terzi** [comment]
Great! I'll keep the issue open to remember myself to add the CTRL+SHIFT+V shortcut :)

By the way, you only need to set Ctrl+V, as Ctrl+C is not needed (not sure if you can only set one of them)

**Comment by federico-terzi** [comment]
Hey,
The next release (0.6.3) will ship with the Ctrl+Shift+V shortcut, so you will be able to modify your patch as follows:

```yaml
filter_class: "vcxsrv.exe"
backend: Clipboard
paste_shortcut: CtrlShiftV
```

Cheers :)
