### ISSUE TITLE
Espanso stops working even when it claims to be running

### ISSUE THREAD

**Issue by ngagun** [federico-terzi/espanso#334]
I'm running espanso 0.6.0 on xubuntu 18.04. I don't have any packages, I just have a few text shortcuts set up.

Frequently, it simply doesn't expand text. If I type "espanso status" it reports "espanso is running", but it doesn't actually do anything. If I type "espanso restart", it starts working again. I do *not* know what event(s) causes it to stop working. Please let me know if there's any information I can provide that would help resolve this bug.

**Comment by federico-terzi** [comment]
Hey @ngagun,

This problem should be related to #302 and should have been fixed in version 0.6.2 of espanso. Please update it and see if that solves your problem.

Let me know if you have other doubts

Cheers :)

**Comment by ngagun** [comment]
Thanks, I've installed 0.6.2 and hopefully that will solve the problem. I'll let you know if not. Thanks for your help!

**Comment by federico-terzi** [comment]
You're welcome, let me know if you experience any other issue
