### ISSUE TITLE
Regexp matching in the trigger?

### ISSUE THREAD

**Issue by salopst** [federico-terzi/espanso#335]
Is it possible to add regex matching on the trigger? This would be exceptions handy for those use cases of espanso where it is being used basically as a spell checker... especially for those of who who don't type so well :-)

Awesome piece of code, BTW. Very handy utility!!

**Comment by federico-terzi** [comment]
Hey @salopst,

Thanks for the kind words :) A full regex matching is not possible for performance reasons, but there are already some packages to solve your problem. See: https://github.com/timorunge/espanso-misspell-en if you need some inspiration to get started

Cheers :)
