### ISSUE TITLE
Flagged as malware?

### ISSUE THREAD

**Issue by burhan** [federico-terzi/espanso#338]
Not sure what is going on, but Bitdefender is marking espanso as malware, but only if you install the `all-emojis` pack:

![image](https://user-images.githubusercontent.com/603112/85137821-73e60580-b24a-11ea-9381-1343c821a451.png)

![image](https://user-images.githubusercontent.com/603112/85137924-9c6dff80-b24a-11ea-9e41-7e92f87785e3.png)

**Comment by federico-terzi** [comment]
Hey @burhan,

Thank you for reporting the issue! Does it happen with all packages? I suspect it might be because that package contains a lot of unicode codes, enough to trigger a false positive

Cheers :)

**Comment by burhan** [comment]
No, when I installed the initial basic pack, it did not complain. It also did not complain when I installed the application itself. Only with the all emojis pack did it forcibly kill the app and move all files to quarantine.

**Comment by federico-terzi** [comment]
I'm pretty sure this is a false positive, I've tested the package on VirusTotal and there was no match: https://www.virustotal.com/gui/file/6718066a85b15058be15cd9383f84e562ba9b8a083d10f5503ac64812c88a5b5/detection

**Comment by burhan** [comment]
Oh I am sure it isn't, but I guess bitdefender is being extra cautious. I restored the files from quarantine and that will tell bitdefender not to scan them, so hopefully that fixes it.

**Comment by federico-terzi** [comment]
Thank you @burhan, BTW espanso already had problems when working with Bitdefender #183
