### ISSUE TITLE
Some characters in replacement are wrong (2020ß06ß23 instead of 2020-06-23)

### ISSUE THREAD

**Issue by stefan2904** [federico-terzi/espanso#341]
I slightly modified the format string of the `:date` trigger:

![2020-06-23_16-37-28](https://user-images.githubusercontent.com/527767/85417914-7ad58680-b570-11ea-8e96-5e6aec03bee4.png)

Which (after e.g. a reboot) replaces `:date` with

![2020-06-23_16-36-35](https://user-images.githubusercontent.com/527767/85417919-7c06b380-b570-11ea-97ec-fcd585198d93.png)

(The `ß` is a variant of the letter `s`, so its a normal key on my keyboard, in case that is relevant.)

After reloading the file, it works and looks like

![2020-06-23_16-37-15](https://user-images.githubusercontent.com/527767/85417917-7c06b380-b570-11ea-8f57-a6c0fbec3a77.png)

This also happens for other commands.

Any ideas? Is this a bug?

---

* OS: Debian Buster
* WM: i3
* Espanso: espanso 0.6.2
* Keyboard layout: german
* Capslock: is off

**Comment by federico-terzi** [comment]
Hey @stefan2904,
I'm sorry you are experiencing this issue. Non-English keyboard layouts on Linux can cause those problems. A quick solution would be to add the `force_clipboard: true` option:

```yaml
- trigger: ":date"
  replace: "{{mydate}}"
  force_clipboard: true
  vars:
.....
```

Cheers :)

**Comment by stefan2904** [comment]
Thanks for the fast answer, Federico!

Good to know ... I'll give it a try.

**Comment by federico-terzi** [comment]
You're welcome! Let me know if that helps :)

**Comment by stefan2904** [comment]
Seems to work, thanks again.

Is this the same as setting `backend: Clipboard` once in the config? 
Might be easier than `force_clipboard: true` on all triggers.

**Comment by federico-terzi** [comment]
> Is this the same as setting `backend: Clipboard` once in the config?
> Might be easier than `force_clipboard: true` on all triggers.

It's pretty much the same, except you force all your matches to go through the Clipboard (which can be less performant/inconvenient than the inject backend).
So the rule of thumb is: if only some of your matches are giving you problems, then use `force_clipboard` on them and leave the default  `backend`, otherwise go full `Clipboard` :)
