### ISSUE TITLE
Refactor Linux CI step to use Archlinux base image

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#344]
In order to solve bugs such as #304 and #343, the CI agent used to build the `prebuilt binary` will be changed to use an `Archlinux` based Docker container.

In particular, starting from the `archlinux` image, these are roughly the steps needed:

```
pacman -Syu --noconfirm
pacman -S rust git make base-devel libxtst xdotool --noconfirm

# Then in the repository directory
cargo build --release
```

This process has been verified and the resulting binary works correctly on Manjaro, I still need to check whether it will work on Ubuntu and Fedora

**Comment by stheid** [comment]
I would not recommend setup a CI with a rolling os like arch. I am an Arch user myself, but i think for a CI i assume it is better to be as standard as possible (ubuntu/debian). Or do you want to use arch additional for validation?

**Comment by federico-terzi** [comment]
I was considering using Arch to build the release as currently I'm using the (heavily customized by Microsoft) Ubuntu agent available on Azure Pipelines, which seems to cause quite a few problems on Arch based systems (see the ones linked above).

Perhaps the issue could be solved without Arch by using a standard Ubuntu agent instead of the heavily customized one. I'll definitely experiment further.

The problem seems to be related to a mismatch between the libx11 versions between the build agent and user's Arch machines.

Thanks for your feedback :)

**Comment by federico-terzi** [comment]
Even with the standard Ubuntu agent, it doesn't work correctly on Manjaro.

I'm currently considering dropping the prebuilt binary all together as it causes more harm than good given how fragmented the Linux ecosystem is. @Scrumplex do you think dropping the prebuilt release would be a huge loss?
