### ISSUE TITLE
Character "»" can’t be expanded correctly in BBedit

### ISSUE THREAD

**Issue by UomoMacchina** [federico-terzi/espanso#346]
I’ve added 2 triggers:

```
  # Virgolette Basse Aperte
  - trigger: "<<"
    replace: "«"

  # Virgolette Basse Chiuse
  - trigger: ">>"
    replace: "»"
```` 

The first one works good, but the second one add the expanded "»" next to the trigger ">>" and delete 2 line below in [BBedit](https://www.barebones.com/products/bbedit/).
The triggers work as expected in other text editors I’ve tried.

Any idea?

**Comment by federico-terzi** [comment]
Hey @UomoMacchina (guess you are Italian :))

You could try using the `force_clipboard: true` option on that one, such as:

```yaml
  - trigger: ">>"
    replace: "»"
    force_clipboard: true
```

let me know if that helps

Cheers :)

**Comment by UomoMacchina** [comment]
Hi Federico.
Adding the suggested parameter does not help, but the trigger not works at all. :(
I think the problem is related to the BBedit feature which automatically add the closing tag for HTML and other languages (i.e. <, ", \ and so on).

BTW, is there a package for automatic replace the punctuations?

**Comment by federico-terzi** [comment]
> Adding the suggested parameter does not help, but the trigger not works at all. :(
> I think the problem is related to the BBedit feature which automatically add the closing tag for HTML and other languages (i.e. <, ", \ and so on).

That's most probably it then, there is not much we can do about it :(

> BTW, is there a package for automatic replace the punctuations?

Not that I know of :)

**Comment by federico-terzi** [comment]
Hey,
I'm closing this issue as this bug seems to be related more to BBedit than espanso.
Cheers :)
