### ISSUE TITLE
Error on Windows 8: Entry Point Not Found

### ISSUE THREAD

**Issue by zicklag** [federico-terzi/espanso#347]
Not sure if Windows 8 is supported or not, but I'm getting an error after installing it:

![image](https://user-images.githubusercontent.com/25393315/85962994-3a637780-b979-11ea-9e83-8f07a68d5822.png)

I can totally understand if you don't support this operating system, though, ( I'm doing everything I can to get off of it as soon as possible, I'm just stuck on it at the moment. :wink: ).

**Comment by federico-terzi** [comment]
Hey @zicklag,

Unfortunately, versions older than Windows 10 are not supported... (it's already hard enough to support 3 operating systems :))

Cheers :)

**Comment by zicklag** [comment]
No problem, I'll try this out as soon as I get my new Linux machine. It looks really neat. :smiley:
