### ISSUE TITLE
Clipboard not working on macOS

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#352]
I set a clipboard trigger:

```` - trigger: ";clip"
    replace: "{{clipboard}}"
    vars:
      - name: "clipboard"
        type: "clipboard"

but it issued an error :

````espanso start
Error parsing YAML file '/Users/klaas/Library/Preferences/espanso/default.yml', invalid syntax: while parsing a block mapping, did not find expected key at line 131 column 13

I have the latest version 0.63.

The example on this page https://espanso.org/docs/matches/ issued the same error.

```` - trigger: ":a"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"

**Comment by federico-terzi** [comment]
Hey,

I'm pretty sure this is a YAML formatting problem, try to paste your configuration into a validation as see if it outputs a more useful message: http://www.yamllint.com/

Cheers :)

**Comment by freebrowser1** [comment]
I tried it and now it went OK and espanso restart also went OK, but the trigger did not work. Every other trigger did work, so probably clipboard is not supported.

````
  - trigger: ";clip"
    replace: "{{clipboard}}"
    vars:
      -
        name: clipboard
        type: clipboard

**Comment by federico-terzi** [comment]
All right, thank you for reporting this! I'll make sure to check it as soon as I get my hands on a mac :)

**Comment by deckarep** [comment]
I setup Espanso on my Mac today. Clipboard is working just fine for me. Brilliant application!

**Comment by freebrowser1** [comment]
deckarep: Can you show the script section triggering the clipboard ?

**Comment by deckarep** [comment]
The example in the docs works for me no problem.

```
  - trigger: ":a"
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"
```

- Place this in your default.yaml file ^
- Ensure expanso reloads the script or manually request it to reload.
- Next copy some text into the clipboard by highlighting a word and doing CMD + C
- Execute the trigger by typing: `:a`

<a href='blah blah was in my clipboard' /></a>

**Comment by freebrowser1** [comment]
Weird. I tried this, but does nothing. All other triggers do work.
Do you have a different version of macOS or Espanso ?

I have macOS 15.5 and espanso 0.63.

**Comment by freebrowser1** [comment]
I tried again now and everything (including clipboard) worked. So this ticket can be closed.

**Comment by federico-terzi** [comment]
@freebrowser1 Glad to hear that! Let me know if you have other issues
