### ISSUE TITLE
Thread panic when expanding U+0000 (ASCII NULL) character.

### ISSUE THREAD

**Issue by yashlala** [federico-terzi/espanso#354]
I am trying to use Espanso as a method to insert certain ASCII control characters (eg. newline, tab, null, form feed, etc). The pertinent section of this file goes as follows: 

```
matches:
  # FORM FEED (FF)
  - trigger: "`FF"
    replace: "\u000c"

  # NULL
  - trigger: ":NUL"
    replace: "\u0000"
```

Attempting to expand the ":NUL" match causes espanso to panic with the following output (via pastebin):  
https://pastebin.com/6arcb8eL

I am running espanso 0.6.3 on Arch via the `espanso` AUR package. Espanso was built with rustc 1.44.1. 

I'm assuming the NULL character is causing issues with string termination somewhere, causing the program to panic. 
I'm happy to start digging through the espanso code and try construct a PR. However, I've never really coded in rust before; I thought asking someone who already knows the codebase might make more sense first. For all I know, the fix might just be explicitly tracking a buffer size rather than relying on NUL termination (or maybe using U+FFFF, which is guaranteed not to be a unicode character; this would guarantee espanso works on unicode, while not imposing too many checks for "is this a binary file"). 

If you're busy (or if you'd rather not spend time on an admittedly weird edge case), I'm down to give a solution a try. 

Cheers.

**Comment by federico-terzi** [comment]
Hey @yashlala,

Thanks for reporting this issue! Unfortunately, I don't think a fix is easily possible with the current architecture, as the native interop heavily relies on null-terminated strings.

Have you considered using tools like `xdotool` to inject those characters?

Even though I'm usually pretty open to new features, I don't think this one would benefit many users and changing the native side should always be avoided when possible.

**Comment by yashlala** [comment]
Your logic makes sense. Thanks for the prompt reply!

I've tested your suggestion and it seems to work; I'm recording my steps here on the off chance it will be helpful to someone later on:
  
Espanso's `shell` option can be used to trigger a wrapper script around `xdotool`. Provided the script doesn't send its output to espanso at any point (only inserting via xdotool), NULL characters can be included in the replacement text without any problems.

**Comment by federico-terzi** [comment]
Glad you sorted that out :)
