### ISSUE TITLE
Error on launching espanso snap

### ISSUE THREAD

**Issue by papioara** [federico-terzi/espanso#356]
Hello,
Today I installed the espanso snap on my Linux Mint 19.3 machine. Unfortunately there is an error "/ has 'other' write 40777" on launch. What does this mean? Can I fix it? Is it a bug?

Help greatly appreciated

**Comment by federico-terzi** [comment]
Hey @papioara,

I'm sorry you experienced this problem. Not sure what could be causing it, but it seems to be related to a permission problem.
The easiest way to solve the problem could be to uninstall espanso from snap (`sudo snap remove espanso`) and then try the DEB installation: https://espanso.org/install/linux/

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
