### ISSUE TITLE
How to Upgrade??

### ISSUE THREAD

**Issue by skostojohn** [federico-terzi/espanso#358]
Sorry for the simple question.  I was running espanso 0.4.1 on Ubuntu 18.04.

I followed the instructions to download and install 0.6.3 via deb package.

But when I enter `espanso --version` I still get 0.4.1 :(

How do I get on the new version?

Thanks!!!!!

Scott

**Comment by skostojohn** [comment]
I figured this out.  I went in and removed espanso from /usr/local/bin

Scott

**Comment by federico-terzi** [comment]
I'm sorry you experienced this problem, I know the upgrade process is still not super clear...
I'll do my best to make it clearer in one of the next releases :)
And by the way, thank you very much for sponsoring the project! I really appreciate it :)

**Comment by skostojohn** [comment]
No problem, Federico. Your app is simply great - the only real solution for this need on linux that I have found.

Keep up the great work!!!
Scott Kostojohn
E // scott@teamdecimal.com (mailto:scott@teamdecimal.com)
P // 206.321.6892 (tel:206.321.6892)
W // http://www.teamdecimal.com
