### ISSUE TITLE
Unexpected behavior with triggers ending with certain special characters

### ISSUE THREAD

**Issue by mimmiepower** [federico-terzi/espanso#361]
I have found that triggers that ends with a single ```[```,  ```]```, ```{```, ```}``` or```\``` (properly escaped when applicable) does not actually get replaced when typed, instead the "replace" part is appended to what is already written. If made a Word Trigger instead of a normal trigger, then it does however work as expected. You might not want to make it a word trigger though. Some special characters that do not have this issue are ```'```, ```"```, ```(```, ```)```, ```%```, ```/```, ```#``` and ```§```.

Triggers that ends with a single backslash do *not* work:

> ```
>   - trigger: "a\\"
>     replace: "b"
> ```
> 
> expected behavior:
> ```
> input: a\
> output: b
> ```
> 
> actual behavior:
> ```
> input: a\
> output: a\b
> ```

Triggers that ends with a single square bracket do *not* work:

> ```
>   - trigger: "a]"
>     replace: "b"
> ```
> 
> expected behavior:
> ```
> input: a]
> output: b
> ```
> 
> 
> actual behavior:
> ```
> input: a]
> output: a]b
> ```

Triggers that begins with a backslash *do* work:

> ```
>   - trigger: "\\a"
>     replace: "b"
> ```
> 
> 
> behavior:
> ```
> input: \a
> output: b
> ```

Triggers that has a backslash somewhere in the middle *do* work:

> ```
>   - trigger: "a\\b"
>     replace: "c"
> ```
> 
> 
> behavior:
> ```
> input: a\b
> output: c
> ```

Triggers containing multiple backslashes *do* work:

> ```
>   - trigger: "a\\\\"
>     replace: "b"
> ```
> 
> 
> behavior:
> ```
> input: a\\
> output: b
> ```
> 

Triggers that ends with various other special characters *do* work:

> ```
>   - trigger: "a%"
>     replace: "b"
> ```
> 
> 
> behavior:
> ```
> input: a%
> output: b
> ```

*Word Triggers* that ends with a backslash *do* work as well:

> ```
>   - trigger: "a\\"
>     replace: "b"
>     word: true
> ```
> 
> 
> behavior:
> ```
> input: a\.
> output: b.
> ```
>

**Comment by federico-terzi** [comment]
Hey @mimmiepower,

Thanks for reporting this issue! Could you please give me this information:
* Your keyboard layout
* Your operating system

At first glance, it might be related to #307, but I might be wrong.

Cheers :)

**Comment by mimmiepower** [comment]
> 
> 
> Hey @mimmiepower,
> 
> Thanks for reporting this issue! Could you please give me this information:
> 
>     * Your keyboard layout
> 
>     * Your operating system
> 
> 
> At first glance, it might be related to #307, but I might be wrong.
> 
> Cheers :)

Yep, that has got to be it. I changed to US keybord in Windows settings and the problem disappeared. I use Swedish QWERTY layout. The problem only happens with ALT GR.

Thank you for your reply.

**Comment by federico-terzi** [comment]
All right, thank you @mimmiepower. I'm going to close this issue in favor of #307, so if you have any other suggestions please write them there :)
