### ISSUE TITLE
Time extension?

### ISSUE THREAD

**Issue by deckarep** [federico-terzi/espanso#362]
Would a time extension be useful at all seeing as there is a date extension?

This would give the user the basic ability to pop in the current time using 12 or 24 format.

I do realize a shell or script could accomplish this. The existing date extension could as well if the user wanted to specify a formatted for it...but then they lose the ability to have dates.

**Comment by federico-terzi** [comment]
Hey @deckarep,

Could you please explain what would the Time extension do compared to the current Date one? As you already pointed out, the user could specify a time-only expansion with the DateExtension.

Cheers :)

**Comment by deckarep** [comment]
Actually it just occurred to me that one could configure two configurations of the date extension to have their needs met. Closing.

**Comment by federico-terzi** [comment]
No problem :)
