### ISSUE TITLE
Multiline text not expanded in newline in RoamResearch

### ISSUE THREAD

**Issue by herrowna** [federico-terzi/espanso#363]
Hey @federico-terzi,

First of all, thank you so much for creating Espanso. I'm grateful that you're sharing this tool and I've been using it for emoji and date replacements. Very happy with it!

In RoamResearch, I have been trying to use Espanso for creating metadara 'templates' where I enter an Espanso command to get a set of related metadata tags. These prompts should be returned in multiline format.

Here is a sample of expected output for `:article`:

```
Author::
Source::
Tags:: #article
```

Plus expected output on Roam's [WYSIWYM](https://www.wikiwand.com/en/WYSIWYM) editor:
<img width="438" alt="Screenshot 2020-07-12 at 7 21 38 PM" src="https://user-images.githubusercontent.com/6374909/87245073-f42c0f00-c474-11ea-8acf-3bdadab64b94.png">

Instead, I am getting the text on a single line with the line breaks empty:

<img width="332" alt="Screenshot 2020-07-12 at 7 23 09 PM" src="https://user-images.githubusercontent.com/6374909/87245088-276e9e00-c475-11ea-9d38-4b2cc25e9e8c.png">

I tried the options outlined in Espanso [docs](https://espanso.org/docs/matches#multi-line-expansions):

```
  - trigger: ":test1"
    replace: "line one\nline two"

  - trigger: ":test2"
    replace: |
              line one
              line two
```

Here's a demo of what happens in Roam:

https://www.loom.com/share/f4357ce867ed46959f793ffd2647b712

I can also verify that the newline feature is working fine on another app, like MacOS Notes.

Potentially related issue: https://github.com/federico-terzi/espanso/issues/121

Thank you for looking into it!

**Comment by federico-terzi** [comment]
Hey @herrowna,

Thank you for the kind words! My first suggestion would be to try using the `force_clipboard: true` parameter on that match, such as:

```yaml
  - trigger: ":test1"
    replace: "line one\nline two"
    force_clipboard: true
```

Let me know if that helps

Cheers :)

**Comment by herrowna** [comment]
Hey @federico-terzi ,

That trick worked flawlessly. Thank you for your time! 🥇

**Comment by federico-terzi** [comment]
Glad you sorted that out :)

**Comment by jacquestardie** [comment]
@herrowna in my experience, this results in an entry like:

```md
- line one
  line two
```

Instead of:

```md
- line one
- line two
```

Is that what you see as well, and if so, are you keeping all of your metadata refs together in a single bullet?

**Comment by herrowna** [comment]
@jacquestardie On Roam it checks out fine, here's a screenshot:

<img width="188" alt="Screenshot 2020-10-27 at 9 19 07 AM" src="https://user-images.githubusercontent.com/6374909/97245218-8219e300-1835-11eb-8dc9-521af58f51da.png">

In certain cases I do get the single bullet entry like you, e.g. when using [Eloquent](https://eloquent.works/) for Roam.
