### ISSUE TITLE
Passive_mode does not work with non-default layout on macOS

### ISSUE THREAD

**Issue by olbrichj** [federico-terzi/espanso#367]
My main use case is expanding boiler plate code (creating classes etc). As far as I can see the passive mode is the only way to use parameters.

Normal mode works perfectly fine.

When using my macs default layout (German) expansion in passive\_mode works fine. Using [Neo2](https://www.neo-layout.org), the log message states:

`17:33:42 [ INFO] Avoiding passive expansion, as the user didn't select anything`

- In sublime text nothing else happens  
- In TextEdit the selected text gets right aligned
- Tried META and CTRL as keys, but the same happens

Is there anything I can do to provide more information (e.g. a different log_level)?

My system:
macOS Catalina 10.15.5
espanso: 0.6.3

Keyboard Layouts:
- German
- Neo2

Further Tools affecting layout:
- Karabiner Elements

My configuration:

```yml
ConfigSet {
    default: Configs {
        name: "default",
        parent: "self",
        filter_title: "",
        filter_class: "",
        filter_exec: "",
        log_level: 0,
        conflict_check: false,
        ipc_server_port: 34982,
        worker_ipc_server_port: 34983,
        use_system_agent: true,
        config_caching_interval: 800,
        word_separators: [
            ' ',
            ',',
            '.',
            '?',
            '!',
            '\r',
            '\n',
            '\u{16}',
        ],
        toggle_key: ALT,
        toggle_interval: 230,
        preserve_clipboard: true,
        passive_match_regex: "(?P<name>:\\p{L}+)(/(?P<args>.*)/)?",
        passive_arg_delimiter: '/',
        passive_arg_escape: '\\',
        passive_key: META,
        enable_passive: true,
        enable_active: true,
        paste_shortcut: Default,
        backspace_limit: 3,
        restore_clipboard_delay: 300,
        secure_input_watcher_enabled: true,
        secure_input_watcher_interval: 5000,
        secure_input_notification: true,
        backend: Inject,
        exclude_default_entries: false,
        show_notifications: true,
        show_icon: true,
        fast_inject: true,
        backspace_delay: 0,
        inject_delay: 0,
        auto_restart: true,
        matches: [
            Match {
                triggers: [
                    ":espanso",
                ],
                content: Text(
                    TextContent {
                        replace: "Hi there!",
                        vars: [],
                        _has_vars: false,
                    },
                ),
                word: false,
                passive_only: true,
                propagate_case: false,
                force_clipboard: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'o',
                        ),
                    ],
                ],
            },
            Match {
                triggers: [
                    ":date",
                ],
                content: Text(
                    TextContent {
                        replace: "{{mydate}}",
                        vars: [
                            MatchVariable {
                                name: "mydate",
                                var_type: "date",
                                params: Mapping {
                                    map: {
                                        String(
                                            "format",
                                        ): String(
                                            "%m/%d/%Y",
                                        ),
                                    },
                                },
                            },
                        ],
                        _has_vars: true,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            'd',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'e',
                        ),
                    ],
                ],
            },
            Match {
                triggers: [
                    ":shell",
                ],
                content: Text(
                    TextContent {
                        replace: "{{output}}",
                        vars: [
                            MatchVariable {
                                name: "output",
                                var_type: "shell",
                                params: Mapping {
                                    map: {
                                        String(
                                            "cmd",
                                        ): String(
                                            "echo Hello from your shell",
                                        ),
                                    },
                                },
                            },
                        ],
                        _has_vars: true,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'h',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'l',
                        ),
                    ],
                ],
            },
        ],
        global_vars: [],
    },
    specific: [],
}

```

**Comment by federico-terzi** [comment]
Hey,

Thanks for reporting this issue! I'm not familiar with Neo2, but I suspect it might not be that easy to solve. Do you still use CMD+C to copy text when using that layout?

Cheers :)

**Comment by olbrichj** [comment]
I used the mapped version. CMD is the same physical key, the physical key for C in neo2 would be R. Keyboard commands are no different, just different physical keys.

**Comment by federico-terzi** [comment]
> I used the mapped version. CMD is the same physical key, the physical key for C in neo2 would be R. Keyboard commands are no different, just different physical keys.

That might be it. Unfortunately, there is currently no option to change the copy shortcut, so your best bet is to keep this issue open until we can figure something out :)

**Comment by olbrichj** [comment]
I'm guessing right now, but is your solution for passive mode to copy the marked code and then replacing it?

**Comment by federico-terzi** [comment]
> I'm guessing right now, but is your solution for passive mode to copy the marked code and then replacing it?

Yes indeed. It copies the current selection, renders the text and paste it back in. As far as I know, there is no other cross-platform way to do it. That said, passive mode is still experimental, as there are still some fundamental issues.

**Comment by olbrichj** [comment]
Do you have a description, how to get up and running for development? I've never worked with Rust :D but I think I have an idea how to solve the issue for macOS (at least I want to try).

**Comment by olbrichj** [comment]
answering myself for anyone else curious about this:
- install rustup-init via brew (brew install rustup-init)
- run rustup-init and install rust
- run cargo build in the project directory

**Comment by olbrichj** [comment]
So what I tried didn't work. Catalina remove Carbon entirely so no luck with HIToolbox. 

Out of curiosity, (I can only guess about the inner workings at the moment..) How does the detection work in active mode? Does it register every keystroke and check the received input against the triggers? would it maybe make sense instead of reacting directly on detection to wait for the next character? if it's a space just do the expansion, if it's a slash continue reading input until you find a space?

For me parameters are THE reason to use espanso :)

**Comment by federico-terzi** [comment]
Hey @olbrichj,

There are a number of problems with active mode parameters, please see #292. That said, this will be solved once #257 will get implemented :)

PS: if you managed to compile espanso, I have one idea that you could try:

You can modify this method: https://github.com/federico-terzi/espanso/blob/master/native/libmacbridge/bridge.mm#L173
to replace the `CMD+V` shortcut with `CMD+R` shortcut and see if that works with Neo2.
In particular, you should replace the `0x09` in the press/release events with `0x0F`

Let me know if that helps :)

**Comment by olbrichj** [comment]
Hey @federico-terzi ,

thanks for your feedback :)  yesterday I tried a few things. So changing 0x08 to 0x0F uses the c key correctly. But it's not yet working. It tries to print :D (cmd+p which would correspond to the correct key in neo2).  
I guess you are also using cmd+v to paste the text right? So I also tried replacing 0x09 with 0x0D. Which corresponds with v.

It seems like it's copying. The selection gets lost and the trigger (:br) stays the same (in TextEdit) or it gets pasted a second time (Sublime Text).  In Sublime Text it confirms the copy step (3 characters copied). So it seems like the engine doesn't detect the clipboard changes.

The log still states:
```
17:50:45 [ INFO] Passive mode activated
17:50:45 [ INFO] Avoiding passive expansion, as the user didn't select anything
```
Are there any settings to improve the output of the log? (e.g. what's inside the clipboard manager?). I had a look through the code but truth be told, didn't get a lot as Rust is far away from Swift or Obj-C (I'm an iOS/macOS dev).

Regarding the other issues. Especially #257 I prefer having the arguments directly in the input and not opening an extra form. The extra form is what keeps me from using other expanders (e.g. Dash) as it breaks my rhythm while coding.

But I do see the problems with the buffer and switching applications. Though there are apps who keep track which apps are in focus. So maybe having multiple buffers would at least solve the switching problem.


my config:
```yml
enable_passive: true
passive_key: META

matches:
  - trigger: ":espanso"
    replace: "Hi there!"
    passive_only: true

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
```

**Comment by federico-terzi** [comment]
Hey @olbrichj,

The passive mode roughly works as follows:

1. Trigger a CMD+C shortcut on the current application to copy the selection in the clipboard
2. Get the clipboard content, render it, and save it back to the clipboard
3. Trigger a CMD+V shortcut in the app to print the current expanded match

I'm pretty sure either the first or the second shortcut does not work as expected. You should try changing both the `trigger_copy` and `trigger_paste` methods, replacing the keycodes with the corresponding ones.

let me know if that works :)

**Comment by olbrichj** [comment]
so passive mode workes as I thought :)

My guess something is preventing it to work with the clipboard. Another option is, that the CMD key has also been remapped (what I don't think as sublime states it copied 3 characters):

<img width="588" alt="Bildschirmfoto 2020-07-15 um 21 27 47" src="https://user-images.githubusercontent.com/11819884/87587259-2a21fb00-c6e2-11ea-9b9f-e50e15126468.png">

Directly afterwards it states:  
`Copied 7 characters`
`Copied 1 character``

my changes:
```rust
void trigger_paste() {
    dispatch_async(dispatch_get_main_queue(), ^(void) {
        CGEventRef keydown;
        keydown = CGEventCreateKeyboardEvent(NULL, 0x37, true);  // CMD
        CGEventPost(kCGHIDEventTap, keydown);
        CFRelease(keydown);

        usleep(2000);

        CGEventRef keydown2;
        keydown2 = CGEventCreateKeyboardEvent(NULL, 0x0D, true);  // V key
        CGEventPost(kCGHIDEventTap, keydown2);
        CFRelease(keydown2);

        usleep(2000);

        CGEventRef keyup;
        keyup = CGEventCreateKeyboardEvent(NULL, 0x0D, false);
        CGEventPost(kCGHIDEventTap, keyup);
        CFRelease(keyup);

        usleep(2000);

        CGEventRef keyup2;
        keyup2 = CGEventCreateKeyboardEvent(NULL, 0x37, false);  // CMD
        CGEventPost(kCGHIDEventTap, keyup2);
        CFRelease(keyup2);

        usleep(2000);
    });
} 

void trigger_copy() {
    dispatch_async(dispatch_get_main_queue(), ^(void) {
        CGEventRef keydown;
        keydown = CGEventCreateKeyboardEvent(NULL, 0x37, true);  // CMD
        CGEventPost(kCGHIDEventTap, keydown);
        CFRelease(keydown);

        usleep(2000);

        CGEventRef keydown2;
        keydown2 = CGEventCreateKeyboardEvent(NULL, 0x0F, true);  // C key
        CGEventPost(kCGHIDEventTap, keydown2);
        CFRelease(keydown2);

        usleep(2000);

        CGEventRef keyup;
        keyup = CGEventCreateKeyboardEvent(NULL, 0x0F, false);
        CGEventPost(kCGHIDEventTap, keyup);
        CFRelease(keyup);

        usleep(2000);

        CGEventRef keyup2;
        keyup2 = CGEventCreateKeyboardEvent(NULL, 0x37, false);  // CMD
        CGEventPost(kCGHIDEventTap, keyup2);
        CFRelease(keyup2);

        usleep(2000);
    });
}
```

What happens? When I trigger it in Sublime Text, it copies `:br` and replaces this with `:br:br`. In TextEdit it just moves the cursor (so I guess copies and pastes it over the selected trigger).

logfiles (for some reason the time is 2h off):
```
19:22:35 [ INFO] Avoiding passive expansion, as the user didn't select anything
```

**Comment by federico-terzi** [comment]
I'm not really sure what to try next at this point :(

**Comment by olbrichj** [comment]
is there an option to see, what's inside the clipboard? Maybe that's where the problem lies. It doesn't identify :br as a trigger?

**Comment by federico-terzi** [comment]
You could try playing with this method: https://github.com/federico-terzi/espanso/blob/4878bc58bd70874f7eb582a0bab1ccd5ffc7c2fd/src/engine.rs#L336

Printing the various clipboard contents, such as:

```rust
println!("{:?}", self.clipboard.get_clipboard());
```

**Comment by olbrichj** [comment]
ok so it definitely copies to the clipboard. Sadly we have two times the same error message:
1. Clipboard is empty
2. Clipboard is equalt to old clipboard

Adding your output at multiple places in `fn on_passive` I get the following output:
```
1. execution
Some("uiae")
Some("uiae")
Some("uiae")
Some("uiae")
Some("uiae")
2. execution
Some(":br")
Some(":br")
Some(":br")
Some("v\n")

3. execution
Some("v\n")
Some("v\n")
Some("v\n")
```

`uiae` was to clear the clipboard so it won't run in the same clipboard message  
`:br` is the result from running it a second time for some reason it replaced `:br` with `:br:br\nv`
`v\n` I have no clue where the v is coming from O.o

**Comment by olbrichj** [comment]
@federico-terzi no problem :) Thanks for looking into it whenever you have time. I will post updates if I find out something new.

**Comment by federico-terzi** [comment]
@olbrichj thank you for the help :)

**Comment by olbrichj** [comment]
I didn't find time to look too deeply but i stumbled upon a few things:
- The macBooks with ButterFly Keyboard had a polling problem, where one press created a lot events. It got improved, but I guess this would result in the above multiple error messages (maybe this error is not only the case for ButterFly keyboards?) Is there currently any handling in case the OS fires multiple times per key pressed (except for the check whether the pasteboard did change)?
- There is a lib (I didn't find time yet to play around with it) which can convert key codes from current keyboard etc. Maybe this can help for at least macOS with different keyboard layouts: https://github.com/Clipy/Sauce

**Comment by federico-terzi** [comment]
@olbrichj Interesting! Thanks for pointing this out. The library seems promising

**Comment by federico-terzi** [comment]
Hey,

Sorry for the late reply! Given that in the v2 passive mode has been deprecated in favor of [Regex triggers](https://espanso.org/docs/next/matches/regex-triggers/), I'm closing this issue as it's not present in the v2

Cheers :)
