### ISSUE TITLE
espanso in Thunderbird can't handle umlauts and 'ß'

### ISSUE THREAD

**Issue by papioara** [federico-terzi/espanso#376]
Hi,
I find espanso very useful, but it gives me a headache in Thunderbird (my machine: Linux Mint 20 cinnamon). Unfortunately the expansion does not work reliably across my frequently used applications:

1. Thunderbird: espanso does not expand matches correctly which contain umlauts (a must for a German). As soon as I change them to ae, oe instead of ä, ö, it works.
2.  Libre Office Writer: after expanding the triggers remain there in front of the expanded text, and sometimes they are not even fully expanded like the date where the last two digits of the year are missing. Images can be expanded, though.
3.  Softmaker Office: Text expansions are ok, even with umlauts, but I cannot expand to an image.
4.  Text editors like gedit work perfectly with text expansions - also umlauts, but they do not do images, but that is no surprise...

Sorry for the long list, but I think you need to know about these problems so hopefully you can fix them one by one - or maybe they are even connected somehow.
Thank you for your work anyway.

**Comment by federico-terzi** [comment]
Hey @papioara,

I'm sorry you experienced this problem. Indeed those applications are known to be problematic, so you have to add a few patch files (in the future I'm planning to ship them by default, but as of now you have to create them manually).
Follow these instructions:

1. Thunderbird: https://github.com/federico-terzi/espanso/issues/130#issuecomment-559881358
2. Writer: https://github.com/federico-terzi/espanso/issues/329#issuecomment-645837353
3. Not sure about this one

Let me know if those work for you

Cheers :)

**Comment by papioara** [comment]
Thank you! I will try these patches today and report back.

Till soon...

**Comment by papioara** [comment]
Hi Federico,

I have done the tests with my 3 main text programs according to your recommendations, and here are the results:

    Thunderbird: The line returns are now being expanded correctly, but there still is a problem as soon as there is a mark for a cursor position. The cursor is not in the defined position after the expansion with the correct definition. I messed around with spaces and finally managed to get it right, but at the expense of incorrect expansions in gedit and Writer, of course.
    Writer: It is really crazy what happens there now: expansions are perfect as long as there is an umlaut involved. Switching to a different language is useless, because the language is reset apparently on expanding the text. As long as there is some umlaut in the text, everything is perfect, but without umlaut the trigger remains visible after the extension plus the extension is not even complete. There are characters missing at the end.
    Softmaker Office Textmaker: flawless - no problems whatsoever except for pasting images, but this is not possible either by other means, too. So, this is not a bug, but apparently a feature or something you have to activate somewhere in the settings.

That's it for the moment...

all best

Hajo

**Comment by federico-terzi** [comment]
Hey,

> Thunderbird: The line returns are now being expanded correctly, but there still is a problem as soon as there is a mark for a cursor position. The cursor is not in the defined position after the expansion with the correct definition. I messed around with spaces and finally managed to get it right, but at the expense of incorrect expansions in gedit and Writer, of course.

Not really sure how we could solve this problem... Are you using it with multiline replacements?

> Writer: It is really crazy what happens there now: expansions are perfect as long as there is an umlaut involved. Switching to a different language is useless, because the language is reset apparently on expanding the text. As long as there is some umlaut in the text, everything is perfect, but without umlaut the trigger remains visible after the extension plus the extension is not even complete. There are characters missing at the end.

This is really strange! Could you please try changing the writer patch file to:

```yaml
filter_class: "libreoffice-writer"
backspace_delay: 30
backend: Clipboard
```

Let me know it that helps :)

**Comment by 73** [comment]
@papioara can you check whether it works correctly when you change keyboard layout order? Maybe you have something like #392

**Comment by papioara** [comment]
Yes, I can, but tell me: is espanso "expecting" a US layout as a default? Of course, as you will be able to guess I use a German layout...

**Comment by papioara** [comment]
A quick test switching keyboard layouts to English US and English International produces exactly the same results as with German layout: expansion is ok, but the cursor is misplaced after the expansion.

**Comment by 73** [comment]
> Yes, I can, but tell me: is espanso "expecting" a US layout as a default? Of course, as you will be able to guess I use a German layout...

No. `espanso` uses `xdotool` for keystroke emulation. `xdotool` seem to have some "difficulties". So the first bug is a lag when `xdotool` should type a letter that is not on the currently active layout. `US International` is good for ß, `US` is bad. 

> A quick test switching keyboard layouts to English US and English International produces exactly the same results as with German layout: expansion is ok, but the cursor is misplaced after the expansion.

Did you also change order? The active keyboard layout should be the first in the list. 
![image](https://user-images.githubusercontent.com/529346/89638030-6ee91e00-d8ab-11ea-8d95-322c820e3d18.png)

If you are on the first one (no matter which one is your first), it should have less delay.

**Comment by papioara** [comment]
I switched around my keyboard settings again, but to no avail. I attach two screenshots so you can see the espanso output with the wrong cursor position (cursor should be in the empty space as I defined it in the match), and the keyboard setting I was using.

![EspansoKeyboardSelection](https://user-images.githubusercontent.com/31970041/89644246-c7261d00-d8b7-11ea-9f15-fc6a9fe55266.png)
![EspansoTB_KeybUSInternational](https://user-images.githubusercontent.com/31970041/89644248-c7beb380-d8b7-11ea-8041-f645819c632e.png)

**Comment by papioara** [comment]
sorry, that was meant for another thread...

**Comment by 73** [comment]
The only workaround I can think of would be to split it, into two snippets.

**Comment by papioara** [comment]
Yes, that would be a workaround. Since I am not a programmer: I have been using Quicktext, a TB addon for a while. This one works perfectly, but under the hood it is probably completely different from espanso, I assume. AutoKey also works, but I find it too cumbersome to define stuff there. So I just tried it, but never became fond of it. The upside of espanso is more fluent typing for me without any ENTER keys in between. 
I hope that this bug in TB can be fixed one day. On the other hand, instead of splitting the match into two snippets, I coulld also press the DOWN key twice - not the end of the world. I'll see what's better. 
Thank you anyway for your assistance and take care

**Comment by damufo** [comment]
> ```yaml
> filter_class: "libreoffice-writer"
> backspace_delay: 30
> backend: Clipboard
> ```

This work for me.
Thanks!

**Comment by michaelaye** [comment]
can you confirm that Thunderbird by now should supports german accents (o" replaced to ö, etc.)?
It doesn't work here, I was wondering if that is because I am using the Colemak Keyboard layout (Linux)?
