### ISSUE TITLE
Automatically toggles state when switching between local machine and remote desktop machine.

### ISSUE THREAD

**Issue by zacharywhite1** [federico-terzi/espanso#377]
I'm running Windows 10 on my local machine, and I'm RDP'ing to another machine that is also running Windows 10. 
**The remote machine is the one that has Espanso installed.**
When I click into my local machine and then back into the remote machine, Espanso will toggle its state (so if it was enabled when I clicked into my local machine, it will disable when I click back into the remote machine, and vice versa).

**Comment by swcurran** [comment]
I'm having this issue as well and so would love an approach.  For example, is there a way to not disable espanso?  Or some idea of what might be triggering the state toggling?

Thanks!

**Comment by zacharywhite1** [comment]
@swcurran 
He suggested I try adding 
`toggle_key: OFF`
to the config and that has fixed my problem.

**Comment by swcurran** [comment]
Ah -- cool!  I thought that was a different issue.  Didn't realize it solved this one.

It worked.  Thanks!

Espanso is awesome BTW.  :-)

**Comment by federico-terzi** [comment]
Glad you all sorted it out :)
