### ISSUE TITLE
Can't change or disable toggle key on remote desktop machine.

### ISSUE THREAD

**Issue by zacharywhite1** [federico-terzi/espanso#378]
I'm running Windows 10 on my local machine, and I'm RDP'ing to another machine that is also running Windows 10.
**The remote machine is the one that has Espanso installed.**
I've tried changing the toggle key to several things and none have worked. Even adding:
`TOGGLE_KEY: OFF`
doesn't do anything -- it still registers the default double-ALT.

**Comment by federico-terzi** [comment]
Hey @zacharywhite1,

Please try using the option as lowercase:

```yaml
toggle_key: OFF
```

This might also fix your other issue #377 

Let me know if that helps

Cheers :)

**Comment by zacharywhite1** [comment]
@federico-terzi 
That has fixed both issues! Thanks! 
Was this some sort of platform issue? I recall the documentation shows it written in all-caps.

**Comment by federico-terzi** [comment]
Glad you sorted it out :) All options are lowercase, so maybe you got confused with the fact that the option *values* are uppercase
