### ISSUE TITLE
Unable to reload config due to an error

### ISSUE THREAD

**Issue by walidelaghil** [federico-terzi/espanso#381]
Every time I get to save my config file, I get this.
P.S. I'm only using text matching, nothing fancy 🙂
![C3TZNQdVOd](https://user-images.githubusercontent.com/57701642/87880080-d7a54f00-c9ff-11ea-95be-4d353c756128.png)

**Comment by federico-terzi** [comment]
Hey,

It's most probably due to a syntax error in your configuration. To get a better explanation, please open a terminal and type `espanso log`. That shows the actual error.

Let me know it that helps

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
