### ISSUE TITLE
Configurable simulated typing speed ?

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#387]
What I mean is the following:
When using espanso shortcuts in some environments like Citrix, Virtual Box VM, the generated text when typing a shortcut goes too fast for the environment, so it results as an only partial replacement, e.g. when it should be "replace" then it 'types' (i.e. simulates typing) "rple", swallowing some characters.
Is there a way letting (with a setting) espanso restricting the time span between two characters not shorter than xxx milliseconds, which matches more a real human typing speed, so Citrix et.al. do not swallow characters 'typed' too fast ?
I hope I am clear enough.

**Comment by federico-terzi** [comment]
Hey @freebrowser1,

There is already a "workaround" option used for similar problems, though it's still not super stable yet. You can give it a try with:

```
backspace_delay: 30
inject_delay: 30
```

Both of these options take the number of milliseconds as argument.

Let me know it that helps

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
