### ISSUE TITLE
VS Code editor - Espanso

### ISSUE THREAD

**Issue by nandhukumar86** [federico-terzi/espanso#388]
Espanso is not working with VSCode.
1. Command/PS terminal doesn't recognize espanso
2. Code editing like py, ipynb, and event txt is not getting supported.

**Comment by federico-terzi** [comment]
Hey @nandhukumar86,

That's strange! I use espanso with VSCode every day and it's working pretty decently. Could you give me a bit more details on your setup? What do you mean by not-working?

Cheers :)

**Comment by nandhukumar86** [comment]
Hi Federico,
First of all, I would like to thank for developing such a nice tool. That's awesome too.
Please refer to the screenshot for the issue mentioned. No other customizations in yml files, all are simple triggers except the parent-child relationships.




Regards,
Nandhakumar.(9008253734) 

    On Saturday, 1 August, 2020, 09:47:51 pm IST, Federico Terzi <notifications@github.com> wrote:  
 
 


Hey @nandhukumar86,

That's strange! I use espanso with VSCode every day and it's working pretty decently. Could you give me a bit more details on your setup? What do you mean by not-working?

Cheers :)

**Comment by nandhukumar86** [comment]
I just missed the screenshot from my previous message

![image](https://user-images.githubusercontent.com/39767305/89199479-38ba4e80-d5cc-11ea-9111-9e07a154c936.png)

**Comment by nandhukumar86** [comment]
I got an another clue for you!!

### By Default I open my VS code in administrator mode. This is where the problem arises.

When I disabled the admin mode -> espanso is working. Sorry for the delayed response -> Couple of minutes back I found this!!

**Comment by nandhukumar86** [comment]
To Confirm - running the editors in admin mode is the issue, I opened my notepad++ in admin mode. Surprisingly the espanso couldn't run comparing with non-admin mode. 

So could I say, any editor app running in admin mode doesn't support espanso?

**Comment by federico-terzi** [comment]
Hey,

Thank you for the update!

> So could I say, any editor app running in admin mode doesn't support espanso?

I wasn't aware of this issue, but it definitely makes sense now that I think about it. The OS blocks a program from injecting text into another Admin-level one for safety reasons.

Unfortunately there is not much we can do about it :( I have to close this issue

Cheers :)

**Comment by nandhukumar86** [comment]
Hi @federico-terzi 

That's fine I understand that. I will use espanso without the admin mode.
Thanks for making such a nice app.

Cheers :)
