### ISSUE TITLE
[Windows] Start espanso without the popup

### ISSUE THREAD

**Issue by felubra** [federico-terzi/espanso#390]
Thank you for the great work on espanso!

I would like a option to start the daemon on windows without the popup (a quiet mode):

![image](https://user-images.githubusercontent.com/25326257/89107220-cb5cc100-d405-11ea-8031-e79893ad7ae1.png)

**Comment by felubra** [comment]
Sorry!
I didn't notice the [`show_notifications`](https://espanso.org/docs/configuration/#options) setting.

**Comment by federico-terzi** [comment]
Glad you figured that out :)
