### ISSUE TITLE
Linux: Replacement takes >2 seconds on alternatives keyboard layouts in GNOME

### ISSUE THREAD

**Issue by 73** [federico-terzi/espanso#392]
Hi,

replacement on Linux takes about two seconds. I have tested on:
Ubuntu 20.04 (X11) with espanso 0.6.2.

Any faster would be greatly appreciated.

Thanks again for espanso!
--73

**Comment by federico-terzi** [comment]
Hey,

I'm sorry you experienced this problem. Did you use some custom options such as `fast_inject` or `backend`?

Cheers :)

**Comment by 73** [comment]
Hey,

not so much a "problem" more "room for improvement". Something that would make espanso even greater! Currently I have:
```yml
backend: Clipboard 
fast_inject: true
```

`Clipboard` is most reliable backend. With the other one, there are issues where part of the trigger is not consumed or the replacement does not show.

**Comment by federico-terzi** [comment]
Are you sure you have `fast_inject: true` and not `false`? With `fast_inject: true` you should have a pretty good performance.
Does it happen with all matches and in all apps?

**Comment by 73** [comment]
I am as sure as I can be. It happens in all apps and all matches. Well, I did not try them all, but the emojis I use the simple text snippets.

**Comment by federico-terzi** [comment]
I see... Have you tried with `fast_inject: false` instead?

**Comment by 73** [comment]
I did just know an the time goes up to over 5 seconds.

**Comment by federico-terzi** [comment]
What Keyboard layout are you using?

**Comment by federico-terzi** [comment]
If you are using a non US keyboard layout, you can try with this workaround: https://github.com/federico-terzi/espanso/issues/237#issuecomment-614774625

**Comment by 73** [comment]
Okay. Well. I am not sure what I gotten myself into here. It seems I have run into an 8 years old [xdotool issue](https://github.com/jordansissel/xdotool/issues/10). This behavior is only shown on *additional* keyboard layouts. I could not replicate the issue on my first layout, no matter what the first layout is.

**Comment by federico-terzi** [comment]
Have you tried with the workaround I linked above? Another user had a similar problem with the Portuguese layout and that solved the issue...

**Comment by 73** [comment]
I might have explained that well. Let my try again. I don't have a problem with a specific layout. In GNOME one is able to configure multiple keyboard layouts. The issue does not appear on the first layout, only on the following (I tried it with three so far).

Let's say I have configured two layouts `de,en`, then I have the problem only on `en`, because it is not the first one. If I swap them to `en,de`, I have the problem with `de` but not with `en` anymore. It is not the layout that makes the problem, but the position in the list of configured layouts.

**Comment by 73** [comment]
As a workaround I use this script to cycle though my keyboard layouts:
```sh
#!/bin/bash

# we will not split at the space
_ifs_backup=$IFS

IFS=$'\n'
_layouts=( $(gsettings get org.gnome.desktop.input-sources sources | grep -Po "\([^)]+\)") )


IFS=$', '
_value=`echo "[${_layouts[@]:1}, ${_layouts[0]}]" `
gsettings set org.gnome.desktop.input-sources sources "$_value"
IFS=$_ifs_backup

gdbus call --session --dest org.gnome.Shell \
--object-path /org/gnome/Shell \
--method org.gnome.Shell.Eval \
 "imports.ui.status.keyboard.getInputSourceManager().inputSources[0].activate()"
```

**Comment by federico-terzi** [comment]
@73 That's pretty strange! Thanks for sharing, I'm sure many people will find it useful :)

**Comment by 73** [comment]
Comming to think of it, why am I running into `xdotool` errors when my config reflects to use the clipboard?
```yml
backend: Clipboard 
```

**Comment by federico-terzi** [comment]
@73 That's a good question! In order to work, the Clipboard backend still injects some keystrokes:
* The sequence of backpresses to delete the word
* The CTRL+V combination to paste the content
So there's still a dependency on libxdo, but not for the actual string injection

**Comment by 73** [comment]
I see.

**Comment by federico-terzi** [comment]
Hey,

I'm closing the issue as the new v2 should not suffer from this problem

Cheers :)
