### ISSUE TITLE
[FEATURE] Whitelist and/or Blacklist Program List

### ISSUE THREAD

**Issue by iamdoubz** [federico-terzi/espanso#396]
Would it be possible to have somewhere in the config files, the ability to add if I'm in a certain program typing... let's say Remote Desktop, I don't want to use Espanso.

**Use case**

Basically, since virtually everyone is working remote now, they might be remoting into other computers. When they do, I want to disable all shortcuts from Espanso as what happens "across the wire" is the change is made, but fails to remove the short text.

**Example**

I use AnyDesk to remote into my computer at work. When I trigger one of my keyboard shortcuts by typing `url1`, when I'm not on my remote computer, `url1` becomes `www.google.com`. If I type `url1` on remote computer, I get `url1www.google.com`.

**Comment by federico-terzi** [comment]
Hey,

This is indeed possible, you can setup an [app-specific configuration](https://espanso.org/docs/configuration/#application-specific-configurations).

An example would be:

```
name: AnyDesk
filter_class: AnyDesk #I haven't verified this filter, please find the correct one by following the instructions.
enable_active: true
```

Make sure to find the correct filter with the method explained in the docs.

Cheers :)

**Comment by iamdoubz** [comment]
Neat! I tried to do it, but am a little unsure how to use it. This is what I have so far:

**Output of** `espanso detect`:
```
Detected change, current window has properties:
==> Title: 'RemoteCompName - AnyDesk'
==> Class: 'C:\Program Files (x86)\AnyDesk\AnyDesk.exe'
==> Executable: 'C:\Program Files (x86)\AnyDesk\AnyDesk.exe'
```

**My espanso/user/AnyDesk.yml**:
```
name: AnyDesk

filter_exec: 'C:\Program Files (x86)\AnyDesk\AnyDesk.exe'

enable_active: false
```

After I `espanso restart`, the replacement still changes on the remote computer in AnyDesk. What did I miss?

**Comment by federico-terzi** [comment]
Hey,
My first guess is that the backslashes are messing with the regex. Could you please try with:

```yaml
name: AnyDesk
filter_exec: 'AnyDesk'
enable_active: false
```

Let me know if that helps :)

**Comment by iamdoubz** [comment]
That did it thanks!

**Comment by federico-terzi** [comment]
Glad to hear that!

**Comment by Masacroso** [comment]
Im unsure if open a different thread for something almost identical to the title of this one so I would prefer to write here my question: there is a way to use various filters for the same file, such that you can use the same user.yml file for various programs? At this moment if I try to put various `filter_title`to some *.yml custom file then espanso throw an error.

**Comment by federico-terzi** [comment]
@Masacroso That seems related to #320

**Comment by Masacroso** [comment]
> @Masacroso That seems related to #320

I solved. I dont knew that you can put a list of words in the yml file with the syntax

```
filter_title: word1 | word2 | word3
```
I could be a good thing to put this in the documentation.

**Comment by federico-terzi** [comment]
@Masacroso Yes, that's a possibility given that the filters are regexes.

> I could be a good thing to put this in the documentation.

Good idea
