### ISSUE TITLE
How to set Proxy

### ISSUE THREAD

**Issue by OlivierMary** [federico-terzi/espanso#408]
Hi there,

I didn't find any information to set a proxy for `espanso install` command.

That didn't take http_proxy, https_proxy exports

Any idea ?

**Comment by federico-terzi** [comment]
Hey @OlivierMary,
That's interesting! Espanso uses the [reqwest](https://github.com/seanmonstar/reqwest) library to make HTTP requests and it seems like it should support system proxies: https://docs.rs/reqwest/0.10.7/reqwest/#proxies

What OS are you using?

**Comment by OlivierMary** [comment]
Hi,

I tried on Windows and WSL

**Comment by federico-terzi** [comment]
> I tried on Windows and WSL

That's unexpected. So you run espanso on WSL? Why don't you run it directly from the Windows Prompt or Powershell?

**Comment by OlivierMary** [comment]
I tried on cmd / powershell / and wsl
(can't retry today at home... will try to test it again)

**Comment by OlivierMary** [comment]
I think he didn't use it cause that work :
```sh
PS C:\Users\mary.o> $env:HTTP_PROXY = 'http://fake.com:3128'
PS C:\Users\mary.o> $env:HTTPS_PROXY = 'http://fake.com:3128'
PS C:\Users\mary.o> espanso.exe install lorem
Updating package index...
Index updated!
lorem successfully installed!

You need to restart espanso for changes to take effect, using:
  espanso restart
PS C:\Users\mary.o> env |grep HTTP
HTTPS_PROXY=http://fake.com:3128
HTTP_PROXY=http://fake.com:3128
```

**Comment by federico-terzi** [comment]
@OlivierMary Thank you. Unfortunately, I don't have any idea about the cause so I'll leave this issue open. Hopefully one day we will be able to figure that out :)

**Comment by memiks** [comment]
Hi All,

I have the same issue but unable to install package 👎 
![espansoProxy](https://user-images.githubusercontent.com/1905927/91013290-69693300-e622-11ea-8a13-33cfbc01cea6.png)

BR,
Memiks.

**Comment by OlivierMary** [comment]
@memiks I can' t at work, at home no problem with fake proxy in env vars, so that never use proxy :o

**Comment by federico-terzi** [comment]
I added an option to support proxies, so in the next version you'll be able to use:

```
espanso install shruggie --proxy=http://fake.com:3128
```

Cheers :)

**Comment by qiujiangkun** [comment]
The option doesn't work for me, neither does env vars
```
espanso install basic-emojis --proxy=http://127.0.0.1:8092
error: Found argument '--proxy' which wasn't expected, or isn't valid in this context

USAGE:
    espanso install [FLAGS] [ARGS]

For more information try --help
```

**Comment by federico-terzi** [comment]
Hey @qiujiangkun,

I'm sorry you experienced this problem! Please try changing the order:

```
espanso install --proxy=http://127.0.0.1:8092 basic-emojis 
```

Cheers :)

**Comment by qiujiangkun** [comment]
I upgraded my espanso to 0.7.3 and problem solved&nbsp;



Sincerely,&nbsp;
Jack&nbsp;Quinn


------------------ Original ------------------
From: Federico Terzi ***@***.***&gt;
Date: Sat, May 15, 2021 1:32 AM
To: federico-terzi/espanso ***@***.***&gt;
Cc: QiuJiangkun ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [federico-terzi/espanso] How to set Proxy (#408)





 
Hey @qiujiangkun,
 
I'm sorry you experienced this problem! Please try changing the order:
 espanso install --proxy=http://127.0.0.1:8092 basic-emojis   
Cheers :)
