### ISSUE TITLE
Python scrip not executed.

### ISSUE THREAD

**Issue by dxcore35** [federico-terzi/espanso#410]
This is my python script inside (Documents/Scripts/test.py`)

```
#!/usr/bin/python

print("Testing")
```

This is my Espanso script (from example):

`  - trigger: ":tsun"
    replace: "{{output}}"
    vars:
      - name: Sun
        type: script
        params:
          args:
            - python
            - /Users/user/Documents/Scripts/test.py`

After executing of trigger the Espanso triger in deed fire, the text is removed but nothing more will happen.

**Comment by federico-terzi** [comment]
Hey, I'm closing this issue as I just answered on your reddit post :)
https://www.reddit.com/r/espanso/comments/idcsnk/cannot_get_output_from_python_script/
