### ISSUE TITLE
Copy Paste loosing after uses 

### ISSUE THREAD

**Issue by jeff38100** [federico-terzi/espanso#418]
Hi,

I use espanso with Windows 10. I loose paste function after using espanso.

To retrieve it, i need to reload config.

Thx

**Comment by federico-terzi** [comment]
Hey @jeff38100,

Thank you for reporting! Indeed I noticed this problem myself a couple of days ago. It doesn't always happen, but sometimes it does. Do you have any idea of what match could be triggering it? I wasn't able to reproduce it now

Let me know if you figure out the steps to reproduce it.

Cheers :)

**Comment by stdt** [comment]
Maybe related to this I got another bug.

I use "dt-" to get the actual date "2020-08-26" with espanso. 
This replacement works only the first time. The second try gives me "2dt-" instead of "2020-08-26". 
After "Reload config" it works as it should, however only at the first time. Next time the replacement shows "2dt-".
Same with ":espanso" - it gives at the second time "H:espanso" back. 

Windows 10 Pro Version 2004, 64bit.

**Comment by federico-terzi** [comment]
@stdt thank you for the report. I'm not able to reproduce the issue reliably, but it does happen sometimes and it's pretty annoying. I'll make sure to investigate on this one asap. Could you please post the output of `espanso log` here?

Cheers :)

**Comment by federico-terzi** [comment]
Guys I've tracked that down, I'll ship a fix in the next release (hopefully coming in a couple of days)

**Comment by AntoineQ1** [comment]
Thanks for the issue. I had exactly the same problem and I was actually trying tons of methods to fix it (I didn't think it was caused by espanso). But I personnaly need to completely stop espanso so as to make paste function work again.

**Comment by federico-terzi** [comment]
Guys I released the new version, please update espanso and let me know if the problem is still present

**Comment by federico-terzi** [comment]
My bad, it seems the problem is still there after this release. I'll make sure to investigate further

**Comment by federico-terzi** [comment]
Actually, this is pretty strange. I can't reproduce it anymore, so this release might have fixed the problem. When you have the chance, install the new version and try it out

**Comment by AntoineQ1** [comment]
Still the same problem for me... Can't use copy/paste (and it makes impossible the understanding of my other problems) with 0.7.1

**Comment by federico-terzi** [comment]
@AntoineQ1 Thank you for the help, indeed that release did not fix the problem. Digging further I found an old bug in the Windows codebase which basically caused the Clipboard to be broken if the user had an image in the Clipboard beforehand.
I'm currently deploying the fix, I'll let you know once it's ready to try.
Thanks

**Comment by federico-terzi** [comment]
@AntoineQ1 Please try again when you have the chance [Windows Installer](https://github.com/federico-terzi/espanso/releases/download/v0.7.1/espanso-win-installer.exe)

**Comment by AntoineQ1** [comment]
Thanks, it works perfectly now (this problem at least :D) 👍
