### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#420]
Include a Search Bar feature, such as [Typinator's Quick Search](https://www.ergonis.com/products/typinator/features.html) or [TextExpander's equivalent](https://textexpander.com/blog/textexpander-how-to-search-snippets-mac-pc/).

This will be possible thanks to [modulo](https://github.com/federico-terzi/modulo) search UI, which is already there but not wired up yet

**Comment by sidouglas** [comment]
For those coming from google - I've side-stepped this issue by using Ulauncher's shortcut feature. Execute the espanso expansion by using the cli script. https://i.imgur.com/VX1vwlr.png. A menu though would be idea.

**Comment by fstamour** [comment]
Hello, 

As I said in #601, I was wondering if you planned to implement "fuzzy search" for espanso's search bar? À la fzf?

For example (I took from #154), if the choices are:
```txt
kaldır (which means "remove")
kadar (which means "up to")
kriter (which means "criteria")
kurtar (which means "recover")
and many more
```
the user could just type "ld" and it would match "ka**ld**ir"


(I'm pretty hyped for this feature. The number 1 reason why I don't use code snippets is I can never remember all the triggers I've created and by the time I figure out what's the shorthand for a piece of code I could've written that snippet from scratch. Especially because the snippets I want to use are for pieces of code that I don't use too often.)

**Comment by federico-terzi** [comment]
@fstamour The search feature will be like you described! In fact, modulo already implements a fuzzy search module, I just haven't wired it up yet to espanso :) https://github.com/federico-terzi/modulo/blob/master/modulo/src/search/algorithm.rs#L5

**Comment by fstamour** [comment]
Perfect! In the meantime I might try to use espanso's script extension to invoke emacs of fzf 🤔... maybe

**Comment by backward-crazy-mage-puppy-36** [comment]
Any updates on this? This is a really great feature. Ability to select expansions based on searching trigger and replace string contents could mean using hundreds of snippets in espanso vs maybe 20-30 that one can remember in their heads.

**Comment by federico-terzi** [comment]
@backward-crazy-mage-puppy-36 It's coming as part of #594 :) I'm terrible with ETAs, but I hope to ship an alpha version before the end of summer!

**Comment by backward-crazy-mage-puppy-36** [comment]
> @backward-crazy-mage-puppy-36 It's coming as part of #594 :) I'm terrible with ETAs, but I hope to ship an alpha version before the end of summer!

Thanks for the update. Have subscribed to https://github.com/federico-terzi/espanso/issues/594 .

**Comment by davidsword** [comment]
I wrote a small matches searcher for the terminal here https://github.com/davidsword/espanso-search

**Comment by federico-terzi** [comment]
Hey guys,

I think we can now safely close this one, as the new alpha version ships with a search bar that lets you choose the right match without having to remember it :)

<img width="546" alt="searchbar-dark" src="https://user-images.githubusercontent.com/20475953/136691369-9456df01-98b8-4443-9e8c-0fec54c5cf12.png">

You can also assign the same trigger to multiple matches, and the search bar will automatically open to "disambiguate" between them. For example, I have the `:sig` trigger  associated with multiple signatures, and when I type it, Espanso shows me the search bar to select the right one:

![image](https://user-images.githubusercontent.com/20475953/136691705-d5c8184c-e484-40e0-b25a-7f8bbd47dc9c.png)


Cheers :)

**Comment by davidleejy** [comment]
Hi, would it be possible to recognize a "description" field in the yaml file containing trigger definitions? (as per @federico-terzi's comment  https://github.com/espanso/espanso/discussions/1196#discussioncomment-3069067)
