### ISSUE TITLE
Can't install when Start Menu Folder is unavailable

### ISSUE THREAD

**Issue by AntoineQ1** [federico-terzi/espanso#426]
Hello,

When we install Espanso and there are some problems with file rights, it may make the installation impossible.
For example, if the ![image](https://user-images.githubusercontent.com/57227666/91344889-daede080-e7de-11ea-8fdd-904d36e6f02e.png) is unavailable to the programm, the following box will appear : 
![image](https://user-images.githubusercontent.com/57227666/91344916-e6d9a280-e7de-11ea-8cab-c0a5196cd4b9.png). 

Then, the setup will abort the installation and reverting it.
But if we kill the process before it happens, the install is complete (except for an optional shortcut) and espanso works perfectly.
There should be a possibility not to abort and revert the install in such a (rare) case.

Goodbye,

**Comment by federico-terzi** [comment]
Hey @AntoineQ1,
Thank you for reporting, I'll make sure to investigate the issue
Cheers :)

**Comment by federico-terzi** [comment]
I think the only way to solve the issue would be to create the portable mode that doesn't require the access to the start menu, related to #309

**Comment by federico-terzi** [comment]
Hey,

I know it's been a while, but the new alpha v2 ships with a portable mode for Windows, which doesn't write anything outside his folders and thus should not suffer from this problem :)

Feel free to reopen if you'd like to discuss this further!

Cheers :)
