### ISSUE TITLE
Enhancement: possibility to setup the maximum length for titles detected by espanso

### ISSUE THREAD

**Issue by Masacroso** [federico-terzi/espanso#431]
This is just an enhancement petition. I was testing `filter_title`, in particular I had written a small script to write HTML tags faster and I restrict it to the web freeCodeCamp putting in the top of the yaml file `filter_title: "freeCodeCamp"`. Everything was working as expected but I find [an HTML with a long title](https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/use-the-css-transform-property-skewx-to-skew-an-element-along-the-x-axis) that, although the string `freeCodeCamp`  was in it, espanso doesn't found the string.

Then I ran `espanso detect` to see what was going on and I saw that espanso doesn't took the whole title of this web, just a part of it, so the string `freeCodeCamp` that was almost at the end of the title, was not seen by espanso. So, this is my question/petition: there is a way to increase the maximum length of the detection of titles by espanso? If not I think that an option to set this length will be a nice addition to espanso.

P.S.: unfortunately Im not programmer and I dont know something about the rust language to try to read the source code and implement something like that.

**Comment by federico-terzi** [comment]
Hey @Masacroso,
Thank you for the feedback! For reference, how long was the `freeCodeCamp` title?
Cheers :)

**Comment by Masacroso** [comment]
> Hey @Masacroso,
> Thank you for the feedback! For reference, how long was the `freeCodeCamp` title?
> Cheers :)

The title is "Learn Applied Visual Design: Use the CSS Transform Property skewX to Skew an Element Along the X-Axis | freeCodeCamp.org", and julia says its length is of 120. The thing is that the general keyword, freeCodeCamp, is just at the end and everything else can vary depending of the tutorial.

**Comment by federico-terzi** [comment]
@Masacroso That makes sense, as currently the title is clipped at length 100. I think it's reasonable to increase this size to 256 so I'll make sure to do so in the next release 👍

**Comment by federico-terzi** [comment]
This has been fixed in the new release! See: https://github.com/federico-terzi/espanso/releases
