### ISSUE TITLE
Change menu bar logo when disabled (MacOS)

### ISSUE THREAD

**Issue by pedrorrivero** [federico-terzi/espanso#432]
It can be useful to have a dedicated espanso logo in the menu bar whenever it is disabled. I would suggest a crossed 'e'.

**Comment by federico-terzi** [comment]
Hey @pedrorrivero,

Thank you for the feedback! This is indeed a good idea and I was going to add it myself in one of the next releases. So let's keep this issue open to stay updated

Cheers :)

**Comment by pedrorrivero** [comment]
Let me help you out, see if you like this logo:

![icon](https://user-images.githubusercontent.com/52980156/91480888-36fd4700-e869-11ea-9479-c4eda87f2900.png)

**Comment by federico-terzi** [comment]
@pedrorrivero Thank you, that could be a good possibility. It might be a good idea to combine it with a lower opacity so that it's really clear that espanso is disabled. Not sure what's the best way to do that with the mac bar yet

**Comment by pedrorrivero** [comment]
The menu bar accepts an alpha channel so this should suffice:
<img width="88" alt="espanso-off-trans" src="https://user-images.githubusercontent.com/52980156/91502011-a8022600-e88c-11ea-899a-49af7f0cc23d.png">
I have also updated the original icon:
![espanso-off](https://user-images.githubusercontent.com/52980156/91502018-ac2e4380-e88c-11ea-8b74-6e30189290f8.png)

**Comment by federico-terzi** [comment]
Thank you @pedrorrivero, I'll make some experiments with your icons and get back to you :)
