### ISSUE TITLE
Disabling Espanso entirely on a per-application basis

### ISSUE THREAD

**Issue by macintacos** [federico-terzi/espanso#433]
It's not immediately obvious to me how I can disable Espanso when in certain applications. The [documentation](https://espanso.org/docs/configuration/) seems to indicate that you can enable certain expansions on a per-application basis, which is great don't get me wrong, however I can't see how to have an on/off switch per app from what I'm reading there. I found issue #396, but it seemed to only really cover what is mentioned in the documentation.

I tried putting something like the following at the top of my `default.yml` file earlier, but it only seemed to have the effect of disabling Espanso everywhere instead of just VSCode:

```yaml
filter_exec: "Visual Studio Code"
enable_active: false
```

**Comment by federico-terzi** [comment]
@macintacos You are pretty close. Instead of putting that code in the `default.yml` file, you should create another file in the `espanso/user` directory, such as `espanso/user/vscode.yml`.
Inside that file you put the code you suggested
