### ISSUE TITLE
Could it work inside Geforce Now for osx ?

### ISSUE THREAD

**Issue by garethjax** [federico-terzi/espanso#436]
I'm trying Geforce Now and it usually works quite well on my macbook pro laptop.

Unfortunately i'm using a **strong** password inside my steam account and every time i try to load a game, the system asks me to input the password again!

I've tried to create an Espanso shortcut, which works normally, but for some reason it's not doing anything inside the Geforce Now: when i've launched the remote desktop, nothing happens.

Is possible to find a workaround ?

**Comment by federico-terzi** [comment]
Hey @garethjax,

If you are trying to use espanso to inject a password on macOS, unfortunately, that's not possible. macOS has a security feature known as "SecureInput", which prevents any program to interact with password fields.

I'm closing this issue as sadly, there's no solution to this problem...

Cheers :)
