### ISSUE TITLE
Default List Box Entry Missing

### ISSUE THREAD

**Issue by AmberHaelo** [federico-terzi/espanso#438]
On Linux, using 0.71 and the latest modulo, the List Box method never assigns a default, even if one is explicitly given. For example, both of these cases produce an empty entry that you must assign yourself:

![](http://www.semigreenpenny.com/img/forums/20243755-espanso-list_field_never_defaults.png)

```yaml
matches:
  - trigger: ":test"
    form: "Author: {{author}}"
    form_fields:
      author:
        default: "AmberHaelo"
        type: choice
        values:
          - "AmberHaelo"
          - "Two"
          - "Three"
```

It doesn't matter if I specify a default or not, or if the default value is also provided in the values array. And it is not a visual error, as committing the form will result in an empty field.

### GTK version

Not sure if you're using GTK2 or 3, so here are both. This is my laptop running Mint:

```
$ apt version libgtk2.0-0
2.24.32-4ubuntu4
$ apt version libgtk-3-0
3.24.20-0ubuntu1
```

### Logging

I do get an error when running any form-based expansion. Here is the log from the top of a fresh invocation of the daemon:

```

19:29:00 [ INFO] espanso version 0.7.1
19:29:00 [ INFO] using config path: /home/userfolder/.config/espanso
19:29:00 [ INFO] using package path: /home/userfolder/.local/share/espanso/packages
19:29:00 [ INFO] spawning worker process...
19:29:00 [ INFO] Binded to IPC unix socket: /home/userfolder/.local/share/espanso/espanso.sock
19:29:00 [ INFO] initializing worker process...
19:29:00 [ INFO] Binded to IPC unix socket: /home/userfolder/.local/share/espanso/worker.sock
19:29:00 [ INFO] watching for changes in path: /home/userfolder/.config/espanso
19:29:00 [ INFO] Using modulo at "modulo"
19:29:00 [ INFO] worker is running!
19:30:42 [ERROR] modulo reported an error: Gtk-Message: 21:30:38.313: Failed to load module "atk-bridge"

(modulo:42163): Gtk-WARNING **: 21:30:38.445: Error loading theme icon 'gtk-cancel' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
```

P.S. Log file output appears to use UTC time instead of local---maybe that's on purpose but it confused me into thinking there were no recent log outputs. :) I don't think that is normal---you can see GTK is reporting its messages in CEST.

**Comment by federico-terzi** [comment]
Hey @AmberHaelo,
Thanks for reporting this issue! Indeed, this is a bug. I'll make sure to fix it in the next release :)
Cheers :)
