### ISSUE TITLE
Allow Modulo Window to Follow Window Manager Rules

### ISSUE THREAD

**Issue by AmberHaelo** [federico-terzi/espanso#439]
In attempting to solve some difficult and unintuitive focus behaviours (it's probably not something you can solve, but focus-follows-mouse is really awkward in some cases when program A is injecting data into whatever window happens to be under the mouse when it is closed), I figured a good policy would be to change my window manager settings so that new windows are created beneath the mouse pointer. This way, chances are if I pointed at the editor I typed the expansion into anyway, then the Espanso window will appear over it, like a dialogue box. If this window has focus for other reasons (like Alt-Tab or Kupfer use) then the window will come up somewhere else, which will be a strong clue to me to move it to make data injection safer. It's not that the window position matters of course, the mouse position does, but moving the window means moving the mouse, and ensuring that when the window is closed the data goes into the place where the expansion was typed.

However this doesn't seem to work at all. The Espanso window always comes up in the middle of the screen no matter what. I checked the window with `xprop` and it looks like this may be intentional (or perhaps the toolkit's doing):

```
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 230 by 100
		program specified maximum size: 230 by 100
		window gravity: NorthWest
```

These overrides seem to even force themselves over any X settings based on window matching.

If WM hints are things you have direct control over, there may be some other settings work looking into that could solve some of the focus-follows-mouse issues more directly, too. I'm not an expert in X11 coding though, never mind Wayland.

**Comment by federico-terzi** [comment]
Hey @AmberHaelo,

This is a tricky problem! Given that modulo is built on top of [wxWidgets](https://www.wxwidgets.org/), there might be a setting specifically for that. I'll make sure to check it out the next time I get my hands on modulo for Linux 

Cheers :)

**Comment by AmberHaelo** [comment]
Okay, I was afraid it might be tricky! And for anyone else coming along that is running into the same problem, I found a way to force modulo windows to show up under the mouse. The solution will be different depending upon the window manager, but for KDE Plasma:

1. Right click on the Espanso window title bar, and under *More Actions*, select *Configure Special Application Settings...".
2. In the "Window Matching" tab, all you really need is the **Window class (application)** field to be set to `modulo` with exact match (should be default settings).
3. Select the "Size & Position" tab, and set the following options:
    * **Initial placement**: *force*: "Under Mouse"
    * **Ignore requested geometry**: *Apply Initially*: "Yes"

That should do it. It is the directive to ignore requested geometry that seems essential to the other directive to work. With that I can have the window manager go back to placing windows normally, if I prefer.

That seems to be working much better for me. I haven't dumped a template into the wrong window all day.

**Comment by federico-terzi** [comment]
@AmberHaelo Thank you for your detailed report, I'm sure many users will find it helpful :) Should we close the issue at this point?

**Comment by AmberHaelo** [comment]
The work around is fine enough for me. It may still be generally good to let the window follow overall preferences, but I doubt the matter is important to most. You kind of expect popup windows to be in the middle of the screen.
