### ISSUE TITLE
Form CTRL+Enter shortcut doesn't seem to work

### ISSUE THREAD

**Issue by kars-h** [federico-terzi/espanso#440]
Hey Federico,

Just downloaded the newest version.

I've followed the example and put the following gin my config file:

`  - trigger: ":form"
    form: "Hey {{name}}, how are you?"`

It works when clicking the submit button, but when using ctrl+enter is doesn't expand anything.

Video showing:
https://www.loom.com/share/f6ecff7940b54dd09e5efe4db29ec8d3

Looking forward to more updates (specifically the GUI to manage all the expansions 👍 Keep up the great work!

**Comment by federico-terzi** [comment]
Hey @kars-h,
Thanks for reporting this issue! Indeed, I was able to reproduce it on Chrome. It doesn't happen on the Notepad though.
I suspect we might need to add some delay before the injection so that the original application is again on focus.

Cheers :)

**Comment by federico-terzi** [comment]
A fix is coming in the next release :)
