### ISSUE TITLE
French letter é breaks config

### ISSUE THREAD

**Issue by ofaurax** [federico-terzi/espanso#446]
Hello,
I tried to add a simple trigger to say "good day" in french:
```
  - trigger: ":cfbj"
    replace: "Bonne journée"
```
The "é" letter makes the config invalid, and espanso refuses to load it. "Bonne journee" works fine.

This is on windows 10, and default.yml is in iso-8859-1 with CRLF.

I would expect to be able to use any character handled by the file encoding in the trigger and replace strings.

**Comment by federico-terzi** [comment]
Hey @ofaurax,

Indeed, that should work as expected! Make sure to encode your configuration as UTF-8, as that's the format espanso uses to load the configuration.

Let me know if that works

Cheers :)

**Comment by ofaurax** [comment]
Tested OK! Thank you!
Perhaps the default config file should be created in UTF-8.

**Comment by federico-terzi** [comment]
Glad to hear that :)

> Perhaps the default config file should be created in UTF-8.

I'm pretty sure that's the case, I suspect your editor decided to use another encoding when you saved the french accent. As far as I know, unless there is the UTF [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) (which is not required, and sometimes even discouraged), the default config is valid UTF-8 (but the key takeaway is that it's also valid ASCII and valid iso-8859-1, as there are only ASCII characters by default).

Cheers :)
