### ISSUE TITLE
Conflict with Ditto on windows

### ISSUE THREAD

**Issue by ofaurax** [federico-terzi/espanso#448]
I also use Ditto, which enable multi copy/paste (it remembers all your copy's so you can paste it later):
https://sourceforge.net/projects/ditto-cp/

A strange things happen when I use Ditto: each time I paste something, I see the message "espanso (dis|en)able".
I checked and there is no shortcut associated with "Alt Alt" in Ditto.
I wonder how Ditto can trigger the en|disabling of espanso.

I'm not sure if this should be fixed on espanso or on Ditto side.

**Comment by federico-terzi** [comment]
Hey @ofaurax,
Thanks for reporting this issue! Indeed, this behavior is quite strange. Could you please try changing the espanso `toggle_key` to [something else](https://espanso.org/docs/configuration/#customizing-the-toggle-key) and see if the problem remains?

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)

**Comment by arpja** [comment]
> Hey @ofaurax, Thanks for reporting this issue! Indeed, this behavior is quite strange. Could you please try changing the espanso `toggle_key` to [something else](https://espanso.org/docs/configuration/#customizing-the-toggle-key) and see if the problem remains?
> 
> Cheers :)

I just tried this, and it worked for me!
Thank you, my Espanso now works with Ditto! :)
