### ISSUE TITLE
[feature] Display "espanso matches" content in window using hot-key and modulo

### ISSUE THREAD

**Issue by karanrajpal14** [federico-terzi/espanso#450]
Hello,

I'd like to quickly glance into the possible expansions and their triggers sometimes. While I can do that in the terminal, it would be a bit more user friendly to display that in a window. Would you be able to use your `modulo` package to display the content of `espanso matches` upon hitting `Ctrl-Ctrl` perhaps? Or any keystroke will do. The idea is to hit the keystroke, quickly look for what I need and hit `Esc` after that to close the window.

What do you think? This is more of a "nice to have" but it does improve usability to some extent.

**Comment by federico-terzi** [comment]
Hey @karanrajpal14,

Thank you for the feedback! Indeed, I'm planning that feature as well in #420 
I'm going to close this issue, so if you have any other suggestion please continue there :)
