### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by eexil** [federico-terzi/espanso#452]
Hi

I suddenly got the issue that line break stopped working. For instance when writing the trigger signature and I would get it all in one line: Best regards, John Snow

I started to fiddle around and then I get lots errors like this:

Error parsing YAML file '/home/user/.config/espanso/default.yml', invalid syntax: did not find expected <document start> at line 9 column 8 

The line looks ok too me, but then I don't know rust. Also if I remove the line, then there will be an error in another line.

Then since I am on Manjaro and had installed from AUR (version 06) I removed it and installed latest version from snap. However it picked up my old default.yml and I get the same errors.

I think perhaps the easiest would be to pick up a new default.yml and just put in my stuff, and I am sure there used to be one somewhere on espanso.org, but I cannot find it now.

Thank you

**Comment by federico-terzi** [comment]
Hey @eexil,

This is most likely a YAML syntax problem, perhaps with indentation.
1. Make sure to use spaces to indent the file (you can also use tabs, but it's easy to mess up with those)
2. Use a YAML validator (also available online) to find exactly what's wrong in the configuration

Cheers :)

**Comment by eexil** [comment]
Hi Federico,

Thank your for getting back to me.

I finally got it rid of that error. Some of the very first # in the default.yml file was gone. 
Now I am able to restart espanso and it is working. But I still get all in one line.

The trigger is: 
  - trigger: ":sig"
    replace: Best regards,
                 Jon Snow

Is there missing something?

Thank you

**Comment by federico-terzi** [comment]
Great! Could you try with the following to see if that helps:

```yaml
  - trigger: ":sig"
    replace: |
       Best Regards,
       Jon Snow
```

Note the `|` at the beginning. If even this doesn't work, you could try with the `force_clipboard: true` option:

```yaml
  - trigger: ":sig"
    force_clipboard: true
    replace: |
       Best Regards,
       Jon Snow
```

Cheers :)

**Comment by eexil** [comment]
Thank you!
Now all of my problems are solved :+1:

**Comment by federico-terzi** [comment]
Great :)
