### ISSUE TITLE
App matching for a filter precluded another match in another yaml file

### ISSUE THREAD

**Issue by rsuzuki0** [federico-terzi/espanso#457]
When there are multiple app-specific config files beginning with their own filter_exec lines, but say one like (App1|TextEdit) and another like (App2|TextEdit) where TextEdit is added for the convenience (say when the expansion is needed in an unexpected app, and using TextEdit as a temporary buffer, or simply for a debug purpose). Of course, it can be anything, not just TextEdit.

Now, when one yaml matches TextEdit, that precludes TextEdit matching any other app-specific config files.

My reading of the documentation suggests that this was not intended behavior.

**Comment by federico-terzi** [comment]
@rsuzuki0 Indeed, this is not possible with the current architecture but will be once #320 is implemented

I'm closing this issue in favour of that one, so keep there the conversation if you have any other suggestion :)
