### ISSUE TITLE
Passive expansion trigger issue

### ISSUE THREAD

**Issue by rsuzuki0** [federico-terzi/espanso#459]
I have noticed that modifier key taps can be problematic. There are other apps that use this trigger (Launchbar, etc.) and the trigger may not be reliable. Is there a way to trigger passive expansion by more regular shortcuts, like Cmd-control-S or something?

Also, when passive exp is triggered, is there a way to know it was at least triggered? Nothing is recorded in the log, making this hard to troubleshoot...

**Comment by federico-terzi** [comment]
@rsuzuki0 Unfortunately, passive mode has never been very reliable (still experimental and unlikely to be further developed in the future now that Forms are available). That said, have you tried changing the key to another one?: https://espanso.org/docs/configuration/#customizing-the-toggle-key

> Also, when passive exp is triggered, is there a way to know it was at least triggered?

Strange, that should be in the log :P

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
