### ISSUE TITLE
Simulate a keystroke Cmd UpArrow in place of $|$?

### ISSUE THREAD

**Issue by rsuzuki0** [federico-terzi/espanso#460]
$|$ is a very convenient feature, and very useful especially in short expansions, but it can get so slow in a long expansion. In that case, $|$ is almost always placed near the top, so if espanso could simulate Cmd UpArrow or Home after pasting/"typing" the text, a similar result can be achieved in almost no time.

Obviously, if espanso could simulate other keystrokes, that would be also very useful in a different way, but I'm primarily interested in having a faster alternative to $|$ at this point.

**Comment by federico-terzi** [comment]
Hey @rsuzuki0,
Thank you for the feedback! As of now, espanso is not able to output arbitrary keys, but it's been already requested in https://github.com/federico-terzi/espanso/issues/286

So I'm closing this issue in favour of the other one, so in case you want to add something, let's continue that conversation

Cheers :)
