### ISSUE TITLE
Uninstall Espanso

### ISSUE THREAD

**Issue by emrebaran7** [federico-terzi/espanso#461]
How do I uninstall espanso?

**Comment by federico-terzi** [comment]
Hey @emrebaran7, 
That depends on your OS and installation method, which operating system and installation method did you use?
Cheers :)

**Comment by emrebaran7** [comment]
I installed via command line and I use Mac OS X. Cheers!

**Comment by federico-terzi** [comment]
@emrebaran7 great, then you should be able to uninstall by opening the terminal and type:

```
espanso unregister
brew remove espanso
```

Cheers :)
