### ISSUE TITLE
Configure snap remove hook to unregister espanso service

### ISSUE THREAD

**Issue by madeindjs** [federico-terzi/espanso#464]
After uninstalling a previous version Espanso (from snap) on Ubuntu 20.04.1 LTS, I have this error:

```bash
$ sudo tail -f /var/log/syslog
Sep 24 11:10:57 alexandre-G501VW systemd[1199]: Started espanso daemon.
Sep 24 11:10:57 alexandre-G501VW systemd[11656]: espanso.service: Failed to execute command: No such file or directory
Sep 24 11:10:57 alexandre-G501VW systemd[11656]: espanso.service: Failed at step EXEC spawning /snap/espanso/45/bin/espanso: No such file or directory
Sep 24 11:10:57 alexandre-G501VW systemd[1199]: espanso.service: Main process exited, code=exited, status=203/EXEC
Sep 24 11:10:57 alexandre-G501VW systemd[1199]: espanso.service: Failed with result 'exit-code'.
Sep 24 11:11:01 alexandre-G501VW systemd[1199]: espanso.service: Scheduled restart job, restart counter is at 747.
Sep 24 11:11:03 alexandre-G501VW systemd[1199]: Stopped espanso daemon.
```

So I had to `rm` service manually and reboot

~~~bash
$ rm /home/alexandre/.config/systemd/user/default.target.wants/espanso.service  /home/alexandre/.config/systemd/user/espanso.service
$ sudo reboot
~~~

**Comment by madeindjs** [comment]
I think you just should run `espanso unregister` on [Snap remove hook](https://snapcraft.io/docs/supported-snap-hooks).

**Comment by federico-terzi** [comment]
Hey @madeindjs,

Thank you for the feedback! This should be definitely added, so I'll add it to the roadmap :)

Cheers :)

**Comment by LyraLover** [comment]
Bump

**Comment by federico-terzi** [comment]
In the next version, I'm shipping an updated remove hook that will stop the espanso service when removing the snap :)
I've tried unregistering the service as well inside the hook, but I've encountered some limitations: https://github.com/federico-terzi/espanso/commit/bf1d184ae9a660010ef05126a9bc308c89c38d1b

It seems it's pretty tricky to interact with a user systemd service while running as root. Until then, this should at least solve all the problems we had with old versions still running after an update
