### ISSUE TITLE
Disable argument rendering for matches by default unless args are present

### ISSUE THREAD

**Issue by And-re** [federico-terzi/espanso#465]
I have the following replacement:
```
- trigger: ":abc"
  replace: "hello$10$world"
```
and when I use it, I get "helloworld" instead of "hello$10$world".

I use MacOS Catalina but maybe the system is not relevant.

**Comment by federico-terzi** [comment]
Hey @And-re,
Thanks for reporting this issue! This is due to the fact that `$0$` is the syntax used to inject passive mode arguments, but unfortunately there is no option (yet) to disable it. I'll add it to the roadmap :)

Cheers :)

**Comment by And-re** [comment]
@federico-terzi Thank you for the quick reply. I'm glad that you know immediately what the root cause is. 
"$2a$10$" is a part of a password hash generated by BCrypt and it indicates the algorithm used.
In the issue description I prepared a simplified example.

**Comment by federico-terzi** [comment]
@And-re Thanks for the info 👍 I'll get back to you once a fix is shipped

**Comment by And-re** [comment]
@federico-terzi Thank you.

**Comment by And-re** [comment]
@federico-terzi Thank you for the new version. Now it works great :)

**Comment by federico-terzi** [comment]
Great :)
