### ISSUE TITLE
loginwindow always blocking espanso

### ISSUE THREAD

**Issue by maxandersen** [federico-terzi/espanso#469]
not sure what changed but recently I can no longer get espanso to work I constantly get this:

```
WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: loginwindow
PROC: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

Please close it or disable SecureInput for that application (most apps that use it have a
setting to disable it).
Until then, espanso might not work as expected.
Daemon started correctly!
``

i tried killed loginwindow but it keeps respawning instantly.

any idea on how to fix it ?

**Comment by federico-terzi** [comment]
Hey,
Thanks for reporting this issue! That's unfortunate but doesn't seem to be limited to espanso: https://smilesoftware.com/textexpander/secureinput/#loginwindow

I'm wondering whether analyzing the process tree with `pstree` (which could be installed via homebrew) could give us some more insights.

What version of macOS are you running?

**Comment by federico-terzi** [comment]
Also, are you using 1Password? https://blog.twonegatives.com/post/48609305893/textexpander-disabled-because-of-loginwindow

**Comment by maxandersen** [comment]
Catalina and yes 1Password user. I'll try see if ptree can reveal something

**Comment by federico-terzi** [comment]
All right, thank you. I bet this is due to 1Password keeping SecureInput active then...

**Comment by federico-terzi** [comment]
Hey,
Closing the issue as it doesn't seem to be related to espanso.
Cheers :)

**Comment by SantoshSrinivas79** [comment]
I am having the same issue ... is there a way to identify which app is using loginwindow? ... I don't have 1Password

**Comment by federico-terzi** [comment]
@SantoshSrinivas79 I'm sorry you experienced this problem! Could you please try quitting the apps one by one when this happens until espanso is enabled again? Hopefully, that way we can identify the culprit...

**Comment by tclancy** [comment]
Just to add to this, I never saw this issue with 1Password until this week; I notice there was a [new update this week that may be relevant.](https://releases.1password.com/b5x/stable/)

**Comment by federico-terzi** [comment]
@tclancy Thank you for the investigation! I never considered Teams as a possible culprit, very helpful

> `ioreg -l -w 0 | grep SecureInput` is . . . kind of helpful for finding the culprit. So is closing things one by one as suggested above.

Espanso already uses this mechanism for detecting a possible culprit for SecureInput, but unfortunately, as far as my testing goes, it's not reliable if SecureInput is enabled in the background. In that case, the previous command will indicate the app that was in the foreground as the culprit instead of the actual one...
