### ISSUE TITLE
Using a trigger with last char using ALT as modifier deletes last word before when replacing (MacOS)

### ISSUE THREAD

**Issue by diesistmeinname** [federico-terzi/espanso#470]
Using a trigger with last char using ALT as modifier deletes not only the trigger but also the last word before the trigger when replacing (at least on MacOS).
E.g. using "d " (d and ALT+Space) for date ("%m/%d/%Y") first time gets "09/25/2020", second time gets "09/2509/25/2020" and so on (same for "d∂" (d and ALT+d) and so on …). 
Needed me some time to understand this, but I think it is because espanso is then deleting the trigger with BACKSPACE+ALT, so it is deleted word wise.
Every other trigger with ALT as modifier not for the last char of the trigger is OK (e.g. " d" (ALT+Space and d) or "∂d" (ALT+d and d)).

**Comment by federico-terzi** [comment]
Hey @diesistmeinname,

Thanks for reporting this issue! We should make sure to check whether all modifiers are released before triggering an expansion, which luckily shouldn't be too difficult to support. I'll investigate

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
An experimental fix for this problem will be shipped in the next release, so stay tuned!
Because it's an experimental feature, you will need to enable it by adding the following line to your `default.yml` config:

```yaml
wait_for_modifiers_release: true
```

Cheers :)

**Comment by diesistmeinname** [comment]
Hey Federico,
thanks a lot!
I'll do!
Cheers

Am Fr., 23. Okt. 2020 um 21:55 Uhr schrieb Federico Terzi <
notifications@github.com>:

**Comment by federico-terzi** [comment]
This has been added to the new release! See: https://github.com/federico-terzi/espanso/releases
Let me know if that works :)

**Comment by diesistmeinname** [comment]
Yeah!
Thanks a lot!!

Am Do., 3. Dez. 2020 um 20:59 Uhr schrieb Federico Terzi <
notifications@github.com>:
