### ISSUE TITLE
Add support for macOS Big Sur

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#471]
Some users reported problems when installing espanso on macOS Big Sur.

**Comment by pseudomichael** [comment]
I am using Public Beta 9 and haven't had any trouble using Espanso

**Comment by federico-terzi** [comment]
@pseudomichael Thank you for reporting! I've opened this one for a specific user, but turned out to be a problem related to Homebrew and not espanso (but forgot to close it)
Thanks :)
