### ISSUE TITLE
Long delays with Modulo invocation

### ISSUE THREAD

**Issue by AmberHaelo** [federico-terzi/espanso#472]
I've just switched to a new laptop and am getting everything set up again, and while I have modulo installed correctly, and it works, it takes about 15 to 20 seconds to come up, after the text trigger occurs. I've run `espanso log`, but nothing terribly out of the ordinary shows up, other than the message I was getting on the previous machine:

```
23:49:10 [ERROR] modulo reported an error: Gtk-Message: 01:48:38.196: Failed to load module "atk-bridge"
```

But, I had no delays there, so I doubt it is related. Is there anything I can do to help you troubleshoot this? I don't see an excessive amount of CPU being used or anything. modulo comes up briefly in top upon invocation, then drops to effective 0 for the long duration.

**Comment by federico-terzi** [comment]
Hey @AmberHaelo,

Does it happen every time you invoke it? It might be related to the AppImage format, as modulo itself is pretty fast...
I'm wondering whether extracting the bundle could help. If you are willing to try: https://superuser.com/questions/1301583/how-can-i-extract-files-from-an-appimage

By the way, which distro are you using?

Let me know what you think

Cheers :)

**Comment by AmberHaelo** [comment]
Okay, I tried:

```
$ ~/.config/espanso/modulo.AppImage --appimage-extract
$ sudo ln -sf ~/.config/espanso/squashfs-root/usr/bin/modulo /usr/bin/modulo
```

I get the same result, and yes, it has a 100% reproduction rate.

Potentially relevant configuration info: Debian Testing / XCFE 4.14 / Kernel 5.8.10-1

I noticed there is a CLI interface I could use, so I gave that a spin:

```
$ echo "layout: test" | treport squashfs-root/usr/bin/modulo form -i -
Gtk-Message: 15:50:01.922: Failed to load module "atk-bridge"
{}
Program: squashfs-root/usr/bin/modulo form -i -
Elapsed: 0:26.03
User: 0.08
System: 0.02
CPU: 0%
```

So that's definitely where the delay is. Sorry, should have probably posted this to the modulo git instead.

**Comment by federico-terzi** [comment]
@AmberHaelo Thank you for the extensive testing! That's strange, as I tested it on a few distros before publishing and it was always pretty fast. I'll investigate :)

**Comment by federico-terzi** [comment]
@federico-terzi I tested the latest version and it's still pretty fast for me. Could you please try with the following commands and see at which point it gets stuck?

```
echo "layout: hello" > form.yml
ltrace modulo form -i form.yml
strace modulo form -i form.yml
```

I'm also wondering, do you have an AppImageLauncher running?

**Comment by AmberHaelo** [comment]
Here you go!

**ltrace**:

```
_ZN20wxTopLevelWindowBase8DoCentreEi(0x55a8c20d5940, 14, 0x7f193430e500, 0x55a8c1ffed01) = 0
{}
+++ exited (status 0) +++
```

**strace**: [debug.txt.gz](https://github.com/federico-terzi/espanso/files/5287218/debug.txt.gz)

**Comment by federico-terzi** [comment]
@AmberHaelo thank you! Unfortunately, those outputs looks pretty much as expected... Maybe adding the timestamps could help us pinpoint the problematic call. Could you please try with:

```
echo "layout: hello" > form.yml
strace -r modulo form -i form.yml
```

Make sure to start the command and wait at least 5/10 seconds before interrupting it. That way we *should* be able to find the problematic line.

Cheers :)

**Comment by AmberHaelo** [comment]
Ah yeah, I meant to draw your attention to where it was hanging in the strace dump, but forgot to do so. This file is the full dump, from start to end of execution, but I've edited it to place the string `# BREAKPOINT` between the line where it times out and where it picks up again. I've confirmed this is the point where it breaks off when hitting `Ctrl-C`, but let me know if you also want the partial dump.

[debug2.txt.gz](https://github.com/federico-terzi/espanso/files/5288946/debug2.txt.gz)

Tchau!

**Comment by federico-terzi** [comment]
I investigated a bit, and it might be that the problem is related to a misconfiguration in your system, see:
* https://bbs.archlinux.org/viewtopic.php?id=239331
* https://bbs.archlinux.org/viewtopic.php?id=230036

**Comment by AmberHaelo** [comment]
Many thanks for putting me down the right path. I'm afraid it a little more complicated than the Arch setup described (but as usual, the Arch community enlightens all others), as by default Debian uses a more complicated Xsession initialisation approach (at least with lightdm + Xfce). I've determined that if I opt out of that and more simply start up a window manager with some core xinit stuff, modulo launches flawlessly. But any attempt to invoke the snarl of D-Bus and other stuff going on in Debian/Testing at the moment is the culprit.

I also confirmed that if I launch modulo in a self-contained dbus session, with `dbus-launch --exit-with-session modulo form -i test.yml` that it loads instantly. However that's not a good solution because (a) it spawns a dbus fork that ends up orphaned and (b) espanso isn't going to be executing it that way. I could probably find a way to fix (b) with a wrapper, but the thought of having dozens of dbus sessions laying around from every little completion makes me shudder.

I'll probably just wait it out until the Debian devs get it fixed, and meanwhile use awesomewm or something simple.

The one odd thing about it is that, as far as I could tell, modulo was the only GTK program suffering from this. I tried a bunch of the usual suspects, like gedit, gtk3-demo, filezilla and VLC (where you see people reporting this problem), but everything else loaded up instantly. So *maybe* there is something you should be doing better on a d-bus hosted system? I'll leave that to you whether it's worth looking into however.

Thanks again, sorry to waste your time on a system issue!

**Comment by federico-terzi** [comment]
Hey @AmberHaelo,
Thanks for the interesting insight! It's always nice to learn something new :)

> So maybe there is something you should be doing better on a d-bus hosted system?

The biggest problem is that I'm using wxWidgets and not GTK directly, so that might be a bug on their end as well :)
