### ISSUE TITLE
Icon in menubar gets repositioned when enabling / disabling (MacOS)

### ISSUE THREAD

**Issue by pedrorrivero** [federico-terzi/espanso#474]
When toggling between enabled and disabled, the menubar icon gets relocated to first place in the menubar, instead of preserving its assigned position.

**Comment by federico-terzi** [comment]
@pedrorrivero Thanks for reporting this issue! I didn't experience this issue when testing the new feature as I only had one icon in the status bar. I'll investigate

**Comment by federico-terzi** [comment]
This has been fixed in the new release! See: https://github.com/federico-terzi/espanso/releases
