### ISSUE TITLE
Toolbar icon creates clickable whitespace on the right after first click

### ISSUE THREAD

**Issue by Kiailandi** [federico-terzi/espanso#480]
After clicking on the icon a clickable whitespace is added on its right. The only way to remove it is by restarting the app.

I'm on macOS Catalina with dark mode enabled.

After startup:
![image](https://user-images.githubusercontent.com/1914074/95186411-40fc5900-07ca-11eb-9fd7-84671ddc4bf5.png)

After clicking on the icon for the first time:
![image](https://user-images.githubusercontent.com/1914074/95186354-32ae3d00-07ca-11eb-988d-79d687e8f55f.png)

**Comment by federico-terzi** [comment]
Hey @Kiailandi,

Thanks for reporting this issue! Seems to be related to #474 
I'll make sure to fix it in the next release

Cheers :)

**Comment by federico-terzi** [comment]
This has been fixed in the new release! See: https://github.com/federico-terzi/espanso/releases
