### ISSUE TITLE
fast_xdo.h:9:10: fatal error: xdo.h: No such file

### ISSUE THREAD

**Issue by sl5net** [federico-terzi/espanso#483]
```
--- stderr
In file included from /home/m/IdeaProjects/espanso/native/liblinuxbridge/bridge.cpp:21:
/home/m/IdeaProjects/espanso/native/liblinuxbridge/fast_xdo.h:9:10: fatal error: xdo.h: No such file or directory
    9 | #include <xdo.h>
      |          ^~~~~~~
compilation terminated.
```

**Comment by Scrumplex** [comment]
You need to install xdotool and (depending on your distro) the corresponding -dev packages.
On Arch based the package you need should just be `xdotool`.

**Comment by Scrumplex** [comment]
I *think* you need `libxdo-dev` for Debian-based distros.

**Comment by sl5net** [comment]
`sudo apt install libxdo-dev` on Debian/Ubuntu systems.`
https://www.reddit.com/r/espanso/comments/eam3og/unable_to_find_xdoh_when_compiling/fatzcxp?utm_source=share&utm_medium=web2x&context=3
