### ISSUE TITLE
Cursor hint not working in Windows Terminal

### ISSUE THREAD

**Issue by dariodjuric** [federico-terzi/espanso#484]
Hello,

I have the following snippet defined:

```
  - trigger: ":gcm"
    replace: "git commit -m \"$|$\""
```

However, the cursor hint doesn't seem to work in Windows Terminal. In other applications it works.

**Comment by federico-terzi** [comment]
Hey @dariodjuric,

Thanks for reporting this issue! I was able to reproduce, so I'll investigate and get back to you once I discover something

Cheers :)
