### ISSUE TITLE
:espanso does nothing

### ISSUE THREAD

**Issue by sl5net** [federico-terzi/espanso#485]
i installed espanso

and started it with

cargo run

without errors.

But :espanso does nothing but it should say hello ( https://espanso.org/install/linux/#installing-on-ubuntu--debian )

**Comment by federico-terzi** [comment]
Hey,
Espanso is a bit more complex to execute when using cargo, as it's usually composed of multiple processes. If you want to use espanso for testing purposes (without hot reload), you can use

```
cargo run -- -v worker
```

Keep in mind that as soon as you close the terminal, espanso exits. If you want to use it as intended (as daemon), you should first build espanso with `cargo build --release`, and then copy the resulting binary (/target/release/espanso) inside `/usr/local/bin`.

Then you will be able to use espanso as advertised in the docs :)

**Comment by sl5net** [comment]
yes a)  works:
`cargo run -- -v worker`
and is possible to stop by CTRL+C

- b.1) cargo build --release
Finished release [optimized] target(s) in 47.35s

- b.2) then copy the resulting binary 
`./target/release/espanso`
 inside 
`/usr/local/bin`

![image](https://user-images.githubusercontent.com/5634759/95370816-a5f2a480-08d9-11eb-904b-9d13ce7854f5.png)

really? you mean all from
/home/administrator/IdeaProjects/espanso/target/debug/build/
or all from 
/home/administrator/IdeaProjects/espanso/target/release/

BTW What you use during developing ? a) probably ?

BTW is it possible to switch fast beetween a) and b)

**Comment by federico-terzi** [comment]
Hey, 
No need to copy everything inside the `build` directory, only the `espanso` binary. 
So you will just need to copy `target/release/espanso` inside `/usr/local/bin`.

> BTW What you use during developing ? a) probably ?

When I'm developing espanso, I usually just stop the currently running version with `espanso stop` and then run `cargo run -- -v worker`, to test the changes.
When I'm done with testing, I stop the worker with CTRL+C and I restart the normal espanso installation.

Cheers :)
