### ISSUE TITLE
Modulo not working 

### ISSUE THREAD

**Issue by renandincer** [federico-terzi/espanso#490]
Modulo integration not working for me on MacOS 10.15.7

```22:08:14 [ INFO] espanso version 0.7.2
22:08:14 [ INFO] using config path: /Users/renandincer/Library/Preferences/espanso
22:08:14 [ INFO] using package path: /Users/renandincer/Library/Application Support/espanso/packages
22:08:14 [ INFO] spawning worker process...
22:08:14 [ INFO] Binded to IPC unix socket: /Users/renandincer/Library/Application Support/espanso/espanso.sock
22:08:14 [ INFO] initializing worker process...
22:08:14 [ INFO] Status icon already initialized, skipping.
22:08:14 [ INFO] Status icon (disabled) already initialized, skipping.
22:08:14 [ INFO] Initializing EspansoNotifyHelper in /Users/renandincer/Library/Application Support/espanso
22:08:14 [ INFO] EspansoNotifyHelper already initialized, skipping.
22:08:14 [ INFO] Binded to IPC unix socket: /Users/renandincer/Library/Application Support/espanso/worker.sock
22:08:14 [ INFO] worker is running!
22:08:14 [ INFO] watching for changes in path: /Users/renandincer/Library/Preferences/espanso
22:08:37 [ERROR] Attempt to invoke modulo even though it's not configured
22:08:37 [ERROR] modulo form didn't return any output
22:08:37 [ WARN] Could not generate output for variable: form1```

**Comment by federico-terzi** [comment]
Hey @renandincer,
I'm sorry you experienced this issue! Could you please try to uninstall and reinstall espanso with the following:

```
espanso stop
espanso unregister
brew remove espanso
brew install espanso
espanso register # Giving also the accessibility permissions
espanso start
```

Seems like your installation is missing `modulo`, but another user got it working by reinstalling espanso: https://github.com/federico-terzi/espanso/issues/424#issuecomment-704653359

Cheers :)

**Comment by renandincer** [comment]
Hey thanks for the quick reply!

FWIW, I installed manually via GH releases, not using brew.

**Comment by federico-terzi** [comment]
@renandincer That's why then! You will need to also install [modulo](https://github.com/federico-terzi/modulo) manually.
To do that, head to the [Releases](https://github.com/federico-terzi/modulo/releases/tag/v0.1.1) page, download `modulo-mac`, make it executable and copy it in `/usr/local/bin`:

```
chmod u+x ./modulo-mac
sudo mv ./modulo-mac /usr/local/bin/modulo
```

Make sure to rename it to `modulo` and not `modulo-mac`. Then restart espanso and everything should be working!

Cheers :)

**Comment by renandincer** [comment]
Thanks!

**Comment by federico-terzi** [comment]
You're welcome! Let me know if you face any other issue
I'll make sure to update the docs to better explain the situation
