### ISSUE TITLE
Issue with barcode reader

### ISSUE THREAD

**Issue by Medestrac** [federico-terzi/espanso#491]
Context: windows10 - Datalogic reader TD1100 USB alternate Keyboard mode, Code128 Barcode
For the test, i read barcode and print them in an Excel cell

Espanso closed:
read 045110 => print 45110 (yep...Excel removes the first 0)
read ThisIsATest => print ThisIsATest

Espanso started
read 045110 => randomly enable/disable Espanso, print between 1 and 3 random characters and then 110
read ThisIsATest => randomly enable/disable Espanso, print a few random characters and then sATest
![image](https://user-images.githubusercontent.com/69801126/96237382-8aecf800-0f9d-11eb-93bd-79b19979343a.png)

**Comment by federico-terzi** [comment]
Hey @Medestrac,
That's interesting! Could you please try to include the following line in your `default.yml` config and see if that helps?

```yaml
toggle_key: OFF
```

Cheers :)

**Comment by Medestrac** [comment]
Hi Federico,

Where should I include that line?
I tried  before the "matches:" line. It's worse: only the last t of ThisIsATest is correct.

I tried after the "matches:" line, with the same indentation as the "trigger:". I get "ATest" preceded by bullshit characters, that's the same behavior as without that line.

**Comment by federico-terzi** [comment]
This is getting interesting... Are you running other software that might interfere with the keyboard? Other text expanders, AutoHotKey, or software that inject text, ecc.

**Comment by Medestrac** [comment]
No, just Espanso and my barcode reader. When I exit Espanso everything is fine, but when Espanso is running, it disturbs my barcode reading. 
If Espanso is enabled before reading, I get a quick Espanso disabled popup immediately followed by the Espanso enabled popup, and a bad reading.
If I disable Espanso before reading, it doesn't show the popup, but the reading is still bad.
If I use the "Toggle key off", then I have the same behaviour as the disabled mode: no popup, but bad reading.
The only way to get a correct reading is by exiting Espanso.

**Comment by Medestrac** [comment]
OK. I'll keep trying to check my barcode reader parameters to find some ideas.

**Comment by Medestrac** [comment]
I've made a keylogger to check my input.
When I try to read "502994", the output is : [ALT]053[ALT]048[ALT]050[ALT]057[ALT]057[ALT]052[ENTER]
Each character is sent as an ASCII code.
My reader use an "Alternate Keybard" mode, with alternate key encoding. I've tried to change this parameter to "Standard Keyboard" with standard key encoding...but then when I read 502994 the output is (àéçç'[ENTER] (I use a french AZERTY keyboard)
![image](https://user-images.githubusercontent.com/69801126/96713277-a17dbf80-13a0-11eb-9845-b9f36da85c97.png)

**Comment by Medestrac** [comment]
Ok, I've found that I've to give the keyboard country to my reader. The default country mode is US, that I corrected to France. Now, with "standard keyboard" mode, when I read 502994 the output is [MAJ]5[MAJ]0[MAJ]2[MAJ]9[MAJ]9[MAJ]4[ENTER], which is really 502994. Great. And it works fine with espanso. Great again. 
So...let's say the issue is close I guess.

**Comment by federico-terzi** [comment]
@Medestrac Glad to hear that! And thanks for the investigation. That barcode reader was pretty clever, to avoid problems with specific keyboard layouts, it injected a sequence of ALT+ascii code for each digit...
