### ISSUE TITLE
Lorem ipsum package proposal

### ISSUE THREAD

**Issue by Polyterative** [federico-terzi/espanso#492]
Usage:
`:ipsum`

Result:
`Lorem ipsum dolor sit amet, consectetur adipisci elit, sed do eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullamco laboriosam, nisi ut aliquid ex ea commodi consequatur. Duis aute irure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum`

Would be useful

**Comment by federico-terzi** [comment]
Hey @Polyterative,

I suspect you might be looking for this https://hub.espanso.org/packages/lorem/
Cheers :)

**Comment by Polyterative** [comment]
I wonder why I haven't found it that's good news!
