### ISSUE TITLE
When using simple text expansion, sometimes it is eating up a character before expansion.

### ISSUE THREAD

**Issue by a22a-dev** [federico-terzi/espanso#494]
For example,
`This is :nml.` should do `This is normal.` But instead it does this `This isnormal.`.

**Comment by federico-terzi** [comment]
Hey @aak9t9,

Thanks for reporting this issue! What OS are you using?

Cheers :)

**Comment by aak9t9** [comment]
Manjaro 20.1

**Comment by federico-terzi** [comment]
@aak9t9 Is it happening only in Firefox or Thunderbird?

**Comment by aak9t9** [comment]
in trilium notes

**Comment by aak9t9** [comment]
why did you ask for firefox or thunderbird specifically?

**Comment by federico-terzi** [comment]
@aak9t9 I see, nevermind. I asked because Firefox and Thunderbird are known to be a bit problematic. Could you please try to set:

```
backend: Clipboard
```

in your `default.yml` file and see if that solves your problem?

Cheers :)

**Comment by aak9t9** [comment]
Ok, I will try that.

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow-up.
Let me know if you have other questions.
Cheers :)
