### ISSUE TITLE
Form execution triggered keypad UI with beeping sound??

### ISSUE THREAD

**Issue by oaustegard** [federico-terzi/espanso#497]
I just tried out the form module on Windows 10 with a custom Jira JQL statement as the replacement.
When executed this triggered the display of what looked like a keypad, along with a beep-beep-beep sound about once per second. I killed espanso rather quickly so didn't get a good look at it.

I was since unable to reproduce it, but it was an unsettling experience to say the least...

**Comment by federico-terzi** [comment]
Hey @oaustegard,

I'm sorry you experienced this problem! Unfortunately, without some additional details, it's impossible for me to diagnose your issue... Could you please post your match here?

Cheers :)

**Comment by oaustegard** [comment]
Yeah, I know - a bit of a wild goose chase - I since edited it to make it work (as expected), so don't have much to go on. 

To the best of my recollection it looked something like this (JQL to be executed in Jira):
``` yaml
  - trigger: ":jass"
    form: "assignee = {{name}} or (assignee was {{name}} and status not in (\"Open\", \"In Progress\")) or (\"Analysis Team\" in ({{name}}) and status in (Analysis,\"In Review\", \"Peer Review\", Verification))"
```

This was a naive implementation where I'd thought reusing the same parameter would only ask for it once so the first surprise was the three input fields. I tried filling out just the first one, hit submit and the numeric keypad appeared with the beep sound. Other than ensuring there are no explicit shenanigans going on inside the forms module I wouldn't expect any action on this. More of a "if this happens again" type of log.

**Comment by federico-terzi** [comment]
Thank you @oaustegard 

> This was a naive implementation where I'd thought reusing the same parameter would only ask for it once so the first surprise was the three input fields.

I understand this might be confusing at first, I'll think about ways to improve the situation!

> I tried filling out just the first one, hit submit and the numeric keypad appeared with the beep sound.

What do you mean by "numeric keypad"? Like an on-screen keyboard? This sounds really strange!

**Comment by oaustegard** [comment]
Indeed - it looked almost like a poorly designed calculator - or a numeric keypad on-screen keyboard. That popping up and the beeping sound (while on a conference call with an open mic) had me focusing more on trying to locate the process to shut it down rather than getting a proper look at it I'm afraid. The form AND the beep went away when I shut down espanso.

**Comment by federico-terzi** [comment]
I'm really sorry about that, probably it was a combination of shortcuts that triggered the On-Screen keyboard (or something equivalent). Unfortunately, without a bit more details it's pretty hard to figure out. I'll keep investigating and I'll let you know if I discover something :)

**Comment by oaustegard** [comment]
![image](https://user-images.githubusercontent.com/3268739/99098029-69842980-25a6-11eb-99ed-2db05766265b.png)
I randomly stumbled upon what (iirc) is the same number pad - it is actually from Webex Teams. Not sure what caused it to be triggered, but would consider this such an edge case as to not worth looking at further. Sorry for the wild goose chase.

**Comment by federico-terzi** [comment]
No worries! And thanks for letting me know, I was really curious about that :)
