### ISSUE TITLE
espanso arguments

### ISSUE THREAD

**Issue by niksingh710** [federico-terzi/espanso#501]
It is not a bug but it is a feature request.

setting up default.yml is quite easy but sometimes I quickly want to add some things in there that I know I will forget after some time so opening default.yml in the editor is a bit tedious task.

it would be very handy if we can have a command like `espanso --trigger-"textToChange" --replace-"ChangedText" `

for e.g `espanso --trigger-":espanso" --replace-"Hi there!" `

**Comment by federico-terzi** [comment]
Hey @niksingh710.
Thank you for the feedback! #384 should be what you are looking for so I'll close this issue in favor of that one :)
Feel free to continue the conversation there if you have other ideas!

Cheers :)
