### ISSUE TITLE
triple curly braces (and umlauts again)

### ISSUE THREAD

**Issue by MK-nap** [federico-terzi/espanso#503]
Hi,

I am trying to use espanso for writing bibliographies in BibTex. The replacement therefor needs to cope with triple curly braces. It doesn't outright but in most cases a caret `{^{{` does the trick. But if I use umlauts (äüö) in forms it doesn't work either.

Is there another/correct way to escape tripe curly braces?

I tested this on manjaro/kde with kwrite and nano.

I found that triple curly braces doesn't work (see last paragraph) but `{^{{FORM}}}` does:
```
  - trigger: ":test "
    form: |
      Test 1 = {^{{TEST1}}},
      Test 2 = {^{{TEST2}}},
```
output looks like this:
```
Test 1 = {a},
Test 2 = {u},
```
but if I insert umlauts in the form the caret gets somehow handled differently and I get
```
Test 1 = {^ä},
Test 2 = {^u},
```

BTW without carets same input look like this:
```
Test 1 = {},
Test 2 = {},
```

kind regards and thanks for your work!
Martin

**Comment by federico-terzi** [comment]
Hey @MK-nap,

I didn't have the chance to test it, but could you please try by double escaping the brackets like:

```
  - trigger: ":test "
    form: |
      Test 1 = \\{{{TEST1}}\\},
      Test 2 = \\{{{TEST2}}\\},
```

I just realized that forms might not be able to handle bracket escaping correctly yet, so a fix might be needed :)

Let me know if that helps

Cheers :)

**Comment by MK-nap** [comment]
Hi,
thanks for the fast reply!

double escaping doesn't work.
output:
```
Test 1 = \{\},
Test 2 = \{\},
```

I guess putting a caret in between and not getting it in the output was a fluke/not working as intended.

**Comment by federico-terzi** [comment]
@MK-nap  I see, thank you for looking into it. I'll investigate and let you know once I discover something!

> I guess putting a caret in between and not getting it in the output was a fluke/not working as intended.

Yes, it wasn't intended :) Not sure why that happened, I'll investigate this as well

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I've released a new version with the fix! You'll be able to do:

```
  - trigger: ":test "
    form: |
      Test 1 = \{{{TEST1}}\},
      Test 2 = \{{{TEST2}}\},
```

which produces:

```
Test 1 = {test},
Test 2 = {test2},
```

Cheers :)

**Comment by MK-nap** [comment]
works as advertised.

Thanks a lot
Martin

There is still some strange behaviour around umlauts where auto-indentation is switched of if a umlaut is present. But this is probably a problem with the text editor rather than expanso. Not a major problem anyway, bibtex works just as well without indentation.

```
  - trigger: ":book "
    form: |
      @Book\{{{BibKey}},
        author = \{{{Author}}\},
      title = \{{{Title}}\},
      }
```

```
gives
@Book{SomeKey,
  author = {SomeAuthor},
  title = {Some Title},
  }
```
yet

```
@Book{SomeKey,
  author = {SomeAuthor},
title = {Söme Äüthör},
}
```

**Comment by federico-terzi** [comment]
@MK-nap could you please try with the `force_clipboard: true` argument and see if that helps with the umlauts? Like:

```yaml
  - trigger: ":book "
    force_clipboard: true
    form: |
      @Book\{{{BibKey}},
        author = \{{{Author}}\},
        title = \{{{Title}}\},
      }
```

Cheers :)
