### ISSUE TITLE
espanso and non-systemd systems

### ISSUE THREAD

**Issue by tmsg-gh** [federico-terzi/espanso#504]
I am running a non-systemd system (no politics involved, it just happens to be the distro that works best for me :smile: ). Or, to be 
more precise, a system with the systemd shim but no actual systemd running.

Basically, espanso works absolutely flawlessly on that system if started with "espanso daemon". However, I do get error messages whenever I call "espanso restart". That's NBD (because normally espanso reloads the config automatically when it changes) but perhaps it is possible to change this in such a way that it works w/o error messages on a non-systemd machine.

**Comment by federico-terzi** [comment]
Hey @tmsg-gh,

It's not documented (because it's not well tested), but you might have some luck with the `use_system_agent` option. More info here: https://github.com/federico-terzi/espanso/issues/243#issuecomment-616173677

Cheers :)
