### ISSUE TITLE
Espanso fails on MacOS - unclear error message

### ISSUE THREAD

**Issue by jamescridland** [federico-terzi/espanso#507]
I'm currently getting this error...

```
jamescridland@Jamess-MacBook-Pro ~ % espanso restart
WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: loginwindow
PROC: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

Please close it or disable SecureInput for that application (most apps that use it have a
setting to disable it).
Until then, espanso might not work as expected.
Daemon started correctly!
```

Among my open apps was Bitwarden, which had auto-locked and was waiting for me to unlock it. Closing that application made this message disappear. (Reopening it and leaving it waiting for login, though, also worked.)

What I was expecting is some mention of Bitwarden in the above; not a generic message about the MacOS login window...

**Comment by federico-terzi** [comment]
Hey,

Thanks for the feedback!

> What I was expecting is some mention of Bitwarden in the above; not a generic message about the MacOS login window...

Unfortunately, there's not much I can do about it... That's a quirk of macOS. Espanso tries its best to determine the offending application, but sometimes it can't (which often happens with password managers).
For example, also Text Expander suffers from this problem: https://smilesoftware.com/textexpander/secureinput/#loginwindow

Cheers :)
