### ISSUE TITLE
image expansion doesn't work in most applications

### ISSUE THREAD

**Issue by alx365** [federico-terzi/espanso#512]
(I can only test this on linux, so assume this as linux only)
The image expanding barely works - the only app where i could get it to work, was libreoffice other applications like discord or onlyoffice didn't expand the image but they removed the text - which is a real bummer because the only reason i wanted the image expansion was because of discord. 

(dunno why obs or ffmpeg messed that up so bad /shrug)
![espanso2](https://user-images.githubusercontent.com/30902201/98567440-d4341d00-22a7-11eb-9db7-ad3afbb29971.gif)

(this one is fine for whatever reason)
![espanso2](https://user-images.githubusercontent.com/30902201/98567012-5e2fb600-22a7-11eb-821f-31938fdf2d65.gif)

So any idea on how to get it to work?

**Comment by alx365** [comment]
Update: maybe this would work? https://github.com/mwh/dragon

**Comment by federico-terzi** [comment]
Hey @alx365,

Thank you for the feedback! Under the hoods, espanso copy the image into the clipboard and then tries to paste it using CTRL+V into the current program. So we should figure out what of these steps is failing in your case.

If you copy an image from the webbrowser (by right clicking and then "Copy image"), can you paste it with CTRL+V inside discord?

Cheers :)

**Comment by alx365** [comment]
Thanks for the response @federico-terzi,
copying the image and then pasting it did work!

**Comment by federico-terzi** [comment]
@alx365 Interesting! Then it might be due to `xclip`. Could you please run this command (with a valid image):

```
xclip -selection clipboard -t "image/png" -i yourimage.png
```

and then paste it with CTRL+V inside discord?
Also, what image format are you using?

**Comment by alx365** [comment]
The image format is jpg.. going to edit this response with the result in a sec

**Comment by alx365** [comment]
It worked with png! so it was a discord issue after all. Thanks for your help

**Comment by federico-terzi** [comment]
Glad you figured that out :)
