### ISSUE TITLE
Suggestion menu feature

### ISSUE THREAD

**Issue by fedeiglesias** [federico-terzi/espanso#514]
Good Afternoon! I love this tool.
At this moment I using some similar tool that show a Menu with a quick search containing all the "templates" that are available to use. I paste a screenshot here:

![image](https://user-images.githubusercontent.com/21363793/98972536-d6e67a80-2512-11eb-8e6c-1688e2e85fa3.png)

So if I press a combination of keys for example ALT+CTRL+E (For expanso ;)) 
I can see this menu and I don’t need to remember all the text shorcuts to print the templates.
Also have a quick search if you don’t remember in where group is located the template

I think is "nice to have" feature! 
Do you have this in mind for the future ? 

Thank you for this incredible toool!!!!!

**Comment by federico-terzi** [comment]
Hey @fedeiglesias,

Thanks for the kind words and feedback! Yes, a similar feature is already planned, see: #420 
Feel free to write any suggestion there if you have any idea :)
