### ISSUE TITLE
Doesn't work on guake terminal

### ISSUE THREAD

**Issue by matheusfillipe** [federico-terzi/espanso#516]
I just installed guake and one of the first things I noticed is that espanso is not working on it :P I don't know whose fault is this either.

The paste keybinding is set to be ctrl+shift+v there (and it works), I am not sure if espanso is not detecting it as a terminal window (not sure if that's how it works either). 

How can I more properly see what's going wrong or any idea already why that happens?

SYSTEM INFO: 
OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by matheusfillipe** [comment]
Oh okay! The problem is only for emojis btw, shell scripts and simple text work.

**Comment by matheusfillipe** [comment]
Okay this is just a duplicate or variation of #495

**Comment by matheusfillipe** [comment]
Okay so is there a way to set a custom paste keybind that matches some wm_class. Would be final solution for all this.

**Comment by matheusfillipe** [comment]
And this fixed it:

```yml
filter_class: "Guake"
backend: Clipboard
paste_shortcut: CtrlShiftV

```

**Comment by federico-terzi** [comment]
Glad you sorted that out @matheusfillipe  :)

**Comment by matheusfillipe** [comment]
I am now looking for a way to turn espanso off for some matches. I use synergy for controlling another computer and I would like it to automatically turn off when I am on this second computer or at least to have some control.

This is what happens when I switch to the other screen:

```
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
Detected change, current window has properties:
==> Title: ''
==> Class: ''
==> Executable: ''

```

Can i match empty title class and executable like that and then turn espanso off on this "window"? Is it possible now? If you want me to I could create a new issue for this but maybe I just didn't find how to "turn it off" in a match.

**Comment by matheusfillipe** [comment]
Tried something like:
```

filter_exec: ''
backend: Clipboard
paste_shortcut: MetaV
```

and 

```

filter_exec: '^$'
backend: Clipboard
paste_shortcut: MetaV
```

Where the MetaV shortcut does nothing on my other machine anyway. Doesn't work. I will file a new issue.
