### ISSUE TITLE
Support disabling over synergy/barrier 

### ISSUE THREAD

**Issue by matheusfillipe** [federico-terzi/espanso#517]
It would be nice to get espanso automatically disabled when changing screen/machine focus over synergy/barrier. This is what `espanso detect` outputs when I focus the client machine (I am running espanso on the host only)

```
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
Detected change, current window has properties:
==> Title: ''
==> Class: ''
==> Executable: ''
```

I tried doing a workaround like this:

```
filter_exec: '^$'
backend: Clipboard
paste_shortcut: MetaV
```
With either filter_exec, filter_class and filter_title. MetaV does nothing on the other machine but it is still pasting there so there was no match. 

Maybe there should be an option to disable espanso on those undetectable windows that raises XGetWindowProperty errors or maybe there is any workaround that would suffice.

**Comment by federico-terzi** [comment]
Hey @matheusfillipe,
If you want to disable espanso in that configuration, you could create an app-specific config with the content:

```yaml
filter_exec: '^$'
enable_active: false
```

I haven't personally tested it, but that's your best bet :)

**Comment by matheusfillipe** [comment]
Didn't work.  I created: `~/.config/espanso/user/synergy.yml` file and added exactly:

```
filter_exec: '^$'
enable_active: false
```
I reloaded and restarted it just to be sure but it is still trying to write to my other laptop over synergy. It still tries to open type whenever I use a trigger and pastes whatever I have on my clipboard there. Also that one has a problem that espanso is not detecting my firefox executable for some reason so espanso stoped working on firefox :P 

Here I switched from firefox to the other screen/machine:

```Detected change, current window has properties:
==> Title: 'Support disabling over synergy/barrier · Issue #517 · federico-terzi/espanso - Mozilla Firefox'
==> Class: 'firefox'
==> Executable: ''

Detected change, current window has properties:
==> Title: '~ : espanso — Yakuake'
==> Class: 'yakuake'
==> Executable: '/usr/bin/yakuake'

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
Detected change, current window has properties:
==> Title: ''
==> Class: ''
==> Executable: ''

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
(...)
``` 

I also tried with `filter_title: '^$'` and `filter_class: '^$'`... won't work over the other screen. It isn't possible to match multiple filters at the same time? But seems like espanso is not using filters when there are those XGetWindowPropery errors maybe? 

Thanks for your feedback.. I know this problem isn't quite espanso's responsibility anyway and I will look for another workaround 😅

**Comment by federico-terzi** [comment]
Hey,
I'm sorry to hear that! Unfortunately, I'm not sure how to solve the problem, as I've never used Synergy before.
If you find a workaround, please let me know. I'm sure many users will benefit from it :)

**Comment by matheusfillipe** [comment]
This is a workaround for synergy/barrier users. Run synergy like this on the client machine (or just run barrierc instead of synergc):

```
synergyc -f --debug INFO $1 | while read line; do
  if echo $line | grep entering; then    
     ssh 10.42.0.1 -- espanso cmd disable
  fi
  if echo $line | grep leaving; then    
     ssh 10.42.0.1 -- espanso cmd enable
  fi

done >> /dev/null

```

Would be nice to have something like `espanso cmd status` to help in the case if synergy is disabled on the server then i don't re-enable it. I didn't found another way to check it.

**Comment by federico-terzi** [comment]
Thanks @matheusfillipe!

Have you tried with `espanso status`? That might help, otherwise I'll need a little bit more details :)

**Comment by matheusfillipe** [comment]
No `espanso status` only reports if the espanso daemon is running, not if it is disabled or enabled like by the command `espanso cmd disable`. That's why I wondered if something like `espando cmd status` should exist. 

``` 
$ espanso status
espanso is running

$ espanso cmd disable 

$ espanso status     
espanso is running

$ systemctl stop espanso --user 

$ espanso status               
espanso is not running

$ systemctl start espanso --user

$ espanso status                
espanso is running

```

**Comment by federico-terzi** [comment]
I see! That makes sense. Could you please open a new issue for that one?

Cheers :)

**Comment by matheusfillipe** [comment]
#536
