### ISSUE TITLE
Can't install package when branch is not "Master"

### ISSUE THREAD

**Issue by not-AMM** [federico-terzi/espanso#526]
Yesterday I created my first package and I couldn't install it. The same error appeared all the time: `thread 'main' panicked at 'called Result::unwrap() on an Err value: InvalidArchive("Invalid zip header")`. I tried removing the `.git` and it didn't solve the problem.

After some hours I tried again and found that all packages have the same branch name: `Master`. So, I **changed the default branch from `Main` to `Master` and it worked**.

**Comment by fuzzyweapon** [comment]
Yep.  New default is main, but a lot of people still have old repos.  It'd be nice to support both.

**Comment by federico-terzi** [comment]
Hey @not-AMM,

Thanks for reporting this issue! Indeed, I originally assumed the master branch would be the default one... I'll make sure to fix them in the upcoming releases :)

**Comment by fuzzyweapon** [comment]
I think just switching it over could break a lot of repositories for people
or dictate the name branch that they work off of.  I may be still ignorant
of a setting, but it'd be nice to retain the ability to switch the branch
name at will after changing the default.  Another, albeit quick and dirty,
usage of this could be that I have a branch named test and I want a few
users to grab upcoming changes to try them out.  This is something that is
easier to instruct non-tech savvy users.

**Comment by federico-terzi** [comment]
Hey @fuzzyweapon,

Thank you for the feedback! We could add a flag to specify the branch name so that hopefully that use-case will be covered

Cheers :)

**Comment by fuzzyweapon** [comment]
Sounds great!

**Comment by federico-terzi** [comment]
Hey guys,

It's been a while since the last follow-up, sorry about that! The new version (v2) supports different branches with the `--git-branch` option. Such as:

```
espanso install dummy-package --git https://github.com/espanso/dummy-repository --git-branch main --external
```

Keep in mind that this only works in the new version (v2) and with the new package format, more info here: https://espanso.org/docs/next/packages/external-packages/

Cheers :)

**Comment by not-AMM** [comment]
Thank you so much! Don't worry, you working on espanso it's a lot to be thankful for, especially with this, since it'll be very helpful. I appreciate all your effort!
