### ISSUE TITLE
Support for private repositories?

### ISSUE THREAD

**Issue by fuzzyweapon** [federico-terzi/espanso#527]
as of espanso 0.7.2

Would it be possible to get support for private repositories?  There are just some packages that aren't useful for others.  I don't want these public, but I'd still like the ability to `install --external` with them.

**Comment by fuzzyweapon** [comment]
closing as dupe of #308

**Comment by federico-terzi** [comment]
Hey Julia,
Thank you for the feedback! I'm planning some changes in this area in the upcoming months, so hopefully, your use-case will be covered :)
