### ISSUE TITLE
Can't connect to X11 context

### ISSUE THREAD

**Issue by mealies** [federico-terzi/espanso#528]
I have just re-installed my Arch machine and getting errors when trying to run Espanso.  

I have tried standard AUR install + manual installs of 0.7.2 and 0.7.1 and getting the same error.

```
espanso log
09:37:45 [ INFO] espanso version 0.7.2
09:37:45 [ INFO] using config path: /home/mealies/.config/espanso
09:37:45 [ INFO] using package path: /home/mealies/.local/share/espanso/packages
09:37:45 [ INFO] spawning worker process...
09:37:45 [ INFO] Binded to IPC unix socket: /home/mealies/.local/share/espanso/espanso.sock
09:37:45 [ INFO] initializing worker process...
09:37:45 [ERROR] Error, can't connect to X11 context
09:37:45 [ERROR] worker process exited with non-zero code: 100, exiting
```

I am running luke Smith's LARBS setup which is DWM window manager running on top of X11.  My X11 info is:

```
xdpyinfo | grep version
version number:    11.0
X.Org version: 1.20.9
```

On another machine running the same DWM setup, the service is running fine.  I have confirmed that all the dependencies listed in the installation instructions are installed and the system is fully up to date.

Does anyone have any information on how to fix this error?

**Comment by federico-terzi** [comment]
Hey @mealies,

I'm sorry you experienced this problem! A user had a very similar one some time ago and we found a workaround. See this thread: https://github.com/federico-terzi/espanso/issues/151

Let me know if that helps!

Cheers :)

**Comment by mealies** [comment]
@federico-terzi Thanks for the fast response.  The workaround in #151 worked for me.  I copied xinitrc from its default location to home folder and espanso starts automatically as expected.

**Comment by federico-terzi** [comment]
Glad it worked! :)
