### ISSUE TITLE
\t to change between fields in forms

### ISSUE THREAD

**Issue by jorgechurriana** [federico-terzi/espanso#537]
When you are in a form and expand something with \n, is like you press ENTER in the form. Wich is very useful.
But not happend the same with \t. It don't change field, why??
Or in clacl, you can use
  - trigger: "xxxx"
    replace: "1\n2\n3"
    word: false
And the program fills three rows. Nice!!
But with:
  - trigger: "xxxx"
    replace: "1\t2\t3"
    word: false
espanso don't fill three cols!!! WHY???
i'm doing something wrong?
Can you add this funtionality to espanso?

best regards,

**Comment by federico-terzi** [comment]
Hey @jorgechurriana,

Thank you for the feedback! Unfortunately, this is not yet possible, but it will be once https://github.com/federico-terzi/espanso/issues/286 is implemented :)

I'll close this one in favor of that one

Cheers :)
