### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by niksingh710** [federico-terzi/espanso#541]
Not a bug!
Just a feature suggestion. It is big to ask but thought if I can give some ideas.

![Screenshot_20201208_004111](https://user-images.githubusercontent.com/60490474/101394127-158f0b00-38ee-11eb-85cc-340aada02d81.png)

as in github while typing we get this small prompt but this feature is not available in native desktop (Linux) is it possible with espanso to have a small popup showing emoji list of matches?

**Comment by federico-terzi** [comment]
Hey @niksingh710,

Thank you for the feedback! At the moment, this is not possible. Once #154 and #420 are implemented, you'll be able to do something similar!

Cheers :)
