### ISSUE TITLE
Stopping sharing in Webex triggers disabling of Espanso

### ISSUE THREAD

**Issue by oaustegard** [federico-terzi/espanso#542]
Cisco Webex and Espanso continue [unexpected interactions](https://github.com/federico-terzi/espanso/issues/497)...  

This one is possibly related to https://github.com/federico-terzi/espanso/issues/524

Twice now I have observed that the "Espanso disabled" dialog has appeared when I hit Stop Share in a Webex meeting. This is a mouse-button click - no Alt key in sight.

**Comment by federico-terzi** [comment]
Hey @oaustegard,

Thank you for the feedback! Could you please try to disable the toggle key and see if that still happens?

Add the following to the config file

```yaml
toggle_key: OFF
```

I suspect Webex is injecting ALT keypresses in some ways...

Cheers :)

**Comment by oaustegard** [comment]
thanks! toggling `toggle_key` to `OFF` seems to have prevented Webex from disabling - I'll be `espanso cmd enable/disable` toggling from now on I guess...

**Comment by federico-terzi** [comment]
@oaustegard Great! Then Webex must be injecting ALT key presses in the background...

You can also change the key to something else: https://espanso.org/docs/configuration/#customizing-the-toggle-key

Cheers :)
