### ISSUE TITLE
EpansoNotifyHelper multiplying

### ISSUE THREAD

**Issue by lkbm** [federico-terzi/espanso#547]
I noticed this in htop the other day:

<img width="1317" alt="Screen Shot 2020-12-15 at 2 14 51 PM" src="https://user-images.githubusercontent.com/1130247/102267997-4e2b7780-3ee0-11eb-8fd2-1aacc800d542.png">

```
~⟩⟩ps aux | grep -i espanso | wc
      98    1083    9636
```

That's 1 worker, 1 daemon, one grep process, and 85 EpansoNotifyHelper processes. They seem basically harmless, and "Exit espanso" menu option removed them all.

The above screenshot and grep is from 0.7.2 on macOS 10.15.7, but I've since updated to 0.7.3. I updated around 4pm yesterday, and as of 9:30am, there are eight new EpansoNotifyHelper processes. Again, seemingly harmless but likely a small memory leak.

Here's the output of `espanso log` since starting it up:

```
20:32:01 [ INFO] worker is running!
20:37:10 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
20:43:44 [ INFO] SecureInput has been disabled.
20:44:50 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
20:48:03 [ INFO] SecureInput has been disabled.
21:20:28 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
21:21:50 [ INFO] SecureInput has been disabled.
21:51:17 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
22:00:20 [ INFO] SecureInput has been disabled.
22:50:55 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
23:05:16 [ INFO] SecureInput has been disabled.
14:08:57 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:09:02 [ INFO] SecureInput has been disabled.
14:09:07 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:10:55 [ INFO] SecureInput has been disabled.
14:12:11 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:12:36 [ INFO] SecureInput has been disabled.
14:16:04 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:16:24 [ INFO] SecureInput has been disabled.
14:19:11 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:19:32 [ INFO] SecureInput has been disabled.
14:22:14 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:26:14 [ INFO] SecureInput has been disabled.
14:27:20 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:29:44 [ INFO] SecureInput has been disabled.
14:30:25 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:31:26 [ INFO] SecureInput has been disabled.
14:32:37 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:33:49 [ INFO] SecureInput has been disabled.
14:41:24 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
14:42:51 [ INFO] SecureInput has been disabled.
15:06:15 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
15:06:20 [ INFO] SecureInput has been disabled.
15:31:20 [ INFO] SecureInput has been acquired
```

So seems there's fewer than one than one process for each disable+reenable cycle.

For what it's worth, I was initially digging around because I experience #238  ("espanso disabling it self and not turning on again ?") multiple times a day, but I'm fairly certain it's been fewer than once for each of those eight processes, so I suspect that's unrelated.

Let me know if you need any additional information. I'm happy to help with debugging to the extent that I'm able.

**Comment by federico-terzi** [comment]
Hey @lkbm,

This is definitely a bug, thanks for reporting! The EspansoNotifyHelper process is spawned every time a notification is displayed, but it should quit automatically after a while. At this point, it's clear this is not happening correctly, I'll investigate and let you know :)

By the way, the next time it happens, could you please try to clear all the notifications in the notification center and see if that closes the processes?

Cheers :)

**Comment by lkbm** [comment]
Thanks for looking into this.

I just cleared the notification center and it doesn't seem to gave done anything. There were eight processes before and the same number remain.

For what it's worth, there were more than eight of those notifications in the notification center -- I always forget that it's a thing, and quite a few had accumulated over the past few days.

**Comment by federico-terzi** [comment]
@lkbm Thank you for investigating! I'll definitely look into the problem asap :)

**Comment by federico-terzi** [comment]
Hey,

The new alpha v2 comes with a brand new notification system that does not rely on spawning an `EspansoNotifyHelper` process, therefore it should not suffer from this problem. Thank you again for the report and investigation!

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
