### ISSUE TITLE
Prevent multiple espanso processes from being run after auto-reload

### ISSUE THREAD

**Issue by mamichels** [federico-terzi/espanso#548]
Hi there!
I was working on the config when i noticed my matched get inserted multiple times. Seems like something does now work properly with re auto reload:
![image](https://user-images.githubusercontent.com/48212402/102471634-bcde1180-4055-11eb-9407-b66b8395519e.png)

As a note, i wasn't able to close any of those through their context menues and had to use a kill command on all of them.

Obviously running it on Windows 10.

**Comment by federico-terzi** [comment]
Hey @mamichels,

Thanks for reporting this issue! Indeed, this is a bug, I'll investigate and hopefully fix it in one of the next few releases :)
The most likely cause is a series of fast rewrites of the configuration files, do you have any idea of what could cause that in your system? (maybe a synchronization program?)

Cheers :)

**Comment by mamichels** [comment]
Hi @federico-terzi,

tried to reproduce it without success, but this is what i done yesterday. Maybe its a clue, maybe not.
 If i want to call the config via `espanso edit` it has some issues calling notepad for whatever reason.
As shown in the terminal below, the path to the default.yml is completly valid, also the notpad.exe is correclty located. If I try it on a different program in the same terminal e.g. `npm config edit` its working fine.

![image](https://user-images.githubusercontent.com/48212402/102591650-acd83780-4112-11eb-8cb2-e76ffc059680.png)

A side note on the bugs behaviour, while there were like 5 processes only 3 of them replaced the tags. When i was using it in MS Teams it also instantly submitted the message after replacing those tags. Probably a whole other story but it may helps.

Thanks for caring!

**Comment by federico-terzi** [comment]
Hey @mamichels,

That's a pretty strange behavior! I will need to do some more testing before accepting the PR, as for me the path was working... Are you using CMD or Powershell inside the Terminal?

Cheers :)

**Comment by mamichels** [comment]
Hi @federico-terzi,

thats for sure on the testing part.
The issue as shown in the picture does only occure on the git bash on windows. cmd and powershell just work fine.

**Comment by federico-terzi** [comment]
> does only occure on the git bash on windows. cmd and powershell just work fine.

@mamichels I see, that might explain this behavior, as perhaps bash does not understand backslashes on file paths...

**Comment by fstamour** [comment]
As stated in #602 I had the exact same issue after creating a bunch of files with a script.

<hr>

This might help: some editors (like Visual Studio Code, Atom, Sublime and I think emacs and vim) does "atomic saves", I won't go into details, but it can trigger a file watcher multiple times for every file save.

See [this StackOverflow](https://stackoverflow.com/a/20639093/1564493) for some more details

Cheers.

**Comment by federico-terzi** [comment]
@fstamour Very interesting, I didn't know about atomic writes! Thank you very much for sharing

**Comment by fstamour** [comment]
No problem! Watching files correclty is hard :P . Almost any other programs can come and fiddle with your files :/

**Comment by federico-terzi** [comment]
Hey guys,

The new alpha v2 comes with a brand new watcher system that should not suffer from this problem
I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
