### ISSUE TITLE
Install packages from Repositories outside espanso hub.

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#55]

**Comment by karbassi** [comment]
@federico-terzi it would be amazing to use the following:

```sh
espanso install [github URL]
```

For example:

```sh
espanso install https://github.com/karbassi/espanso-package-excel
```

I understand the issue would be validating that the repo is valid and not running malicious code.

**Comment by federico-terzi** [comment]
Hey @karbassi,
It seems like many users would like this feature, I'll try my best to implement it soon :)

**Comment by federico-terzi** [comment]
Hey guys,
You can now install packages from outside the hub!
The command to use has the following format:

```
espanso install <package_name> <repo_url> --external
```

Those repositories must comply with the format specified in the [package-example](https://github.com/federico-terzi/espanso-package-example/).
