### ISSUE TITLE
A customizable sticky window showing the triggers

### ISSUE THREAD

**Issue by abuakram** [federico-terzi/espanso#551]
Hi, What a great app... 

I'd love when typing :info for example, a tiny in width window shows up to the right/left of screen, with all available triggers... it is hard to memorize all of them...

Is this possible???

**Comment by jczanfona** [comment]
You can type `espanso match list` or you can create another trigger with the resume of all of them.
In any way, I think your suggestion can be the best solution...

**Comment by federico-terzi** [comment]
Hey,
Thank you for the feedback! This should be possible once #420 is implemented :)
