### ISSUE TITLE
Espanso causes random characters to appear when pressing ALT + Arrow key on Windows

### ISSUE THREAD

**Issue by tch123** [federico-terzi/espanso#552]
When running Espanso, press Alt + Up, Alt + Down, Alt + Left, Alt + Right, in Windows MS Word
there will be some special characters, even if Espansois disabled.
[Demonstrate animation](https://i.loli.net/2020/12/21/bK2NUlH1TeutD4j.gif)  https://i.loli.net/2020/12/21/bK2NUlH1TeutD4j.gif

**Comment by federico-terzi** [comment]
Hey @tch123,

Thanks for reporting this issue! That's strange indeed, could you please give me a bit more details on your setup?
* Operating system
* Keyboard layout
* Language
* Does it happen also on other applications?
* Does it happen only when espanso is running?

Cheers :)

**Comment by tch123** [comment]
Operating system: 
    Windows  20H2  (19042.685)
Keyboard layout:
    Test over multiple keyboard layouts, English keyboard layout, Chinese keyboard layout，Have this problem
Language: 
    System Language  "Chinese"
Does it happen also on other applications?
     Currently only found this problem in MS Word
Does it happen only when espanso is running?
     Only when the Espanso is running, even if it is disabled.

**Comment by federico-terzi** [comment]
@tch123 All right, thank you! I'll investigate and let you know if I discover something :)

**Comment by j-a-s-o-n-g** [comment]
I'm encountering this same issue in Sublime Text when using espanso. Alt + up/right/down/left produce special characters and interferes with my native/sublime keyboard shortcuts.

**Comment by federico-terzi** [comment]
@j-a-s-o-n-g Interesting, thank you very much. I was indeed able to reproduce the issue now, I'll investigate

**Comment by thorio** [comment]
This AutoHotKey script captures the keypresses and sends them directly to the active window, which apparently bypasses espanso:
```ahk
#If WinActive("ahk_exe devenv.exe") | WinActive("ahk_exe otherprogram.exe")

!Up::ControlSend,, !{Up}
!Down::ControlSend,, !{Down}
!Left::ControlSend,, !{Left}
!Right::ControlSend,, !{Right}
```
Works in Visual Studio but untested in other programs.
