### ISSUE TITLE
Resource extraction fails when the username contains non-ascii char on Windows

### ISSUE THREAD

**Issue by einarmagnus** [federico-terzi/espanso#554]
I have an "ú" in my name and windows has created my home folder using that character. This confuses some part of espanso and if gives me this error message every time I show a form:

![image](https://user-images.githubusercontent.com/15872/103022814-00041d00-454d-11eb-95dc-bfed5055d76a.png)

It has no problem loading my config though.

**Comment by federico-terzi** [comment]
Hey @einarmagnus,

I'm sorry you experienced this problem! I'll investigate and hopefully get it fixed in one of the future releases

Cheers :)

**Comment by einarmagnus** [comment]
I had a similar problem on Deno, and they recently fixed it. Maybe that fix has info that'll help you. 
https://github.com/denoland/deno/issues/9096

**Comment by federico-terzi** [comment]
@einarmagnus Interesting, thank you! The issue you linked seems to be a great starting point to solve the problem
