### ISSUE TITLE
espanso not running on Windows 10

### ISSUE THREAD

**Issue by TSSlade** [federico-terzi/espanso#566]
Earlier today my espanso commands stopped being able to be updated. Existing rules worked just fine, but changes to the default.yml file were not being recognized by `espanso restart`. (I could verify by `cat`-ing them that they were in fact present in the file that espanso was nominally reading.)

I stopped and restarted my Windows device, and espanso failed to run on startup. I've attempted to install the latest update both via GUI / .exe download from GH and via choco. The output of `espanso help` and several other commands is below:

![image](https://user-images.githubusercontent.com/3211478/104384891-1ddaf700-54e7-11eb-927a-7e8fd6823b6a.png)

I cannot find the espanso daemon. Double-clicking on espanso.exe fails to trigger any action, and nothing recognizable as espanso shows up in Task Manager as either a Process or a Service.

My Windows version information is as follows:
![image](https://user-images.githubusercontent.com/3211478/104384919-28958c00-54e7-11eb-9cd3-6b49ede2a005.png)

**Comment by federico-terzi** [comment]
Hey @TSSlade,
I'm sorry you experienced this problem! This is very strange, could you please try to open a Powershell and type `espanso log` to see if that is recognized? 
If that doesn't work, my suggestion would be to delete all files in the `C:\Users\USER\AppData\Local\espanso`, re-install espanso (https://espanso.org/install/win/) and reboot your computer.

Let me know if that helps

Cheers :)

**Comment by federico-terzi** [comment]
Perhaps is because you installed espanso via choco (not sure how that would work, I don't maintain the choco package). Make sure to uninstall it from choco before trying to reinstall it from the normal way

**Comment by federico-terzi** [comment]
Also, if you write `where.exe espanso` in a terminal, what do you see?

**Comment by TSSlade** [comment]
@federico-terzi - I had a suspicion it might have something to do with my workplace installing Thycotic (https://thycotic.com/) in an attempt to prevent us from using any software that is not explicitly approved by our IT staff. 😡  I think that's what it currently is - there's just no very good way to verify whether that's what is going on. I hoped you might have some insight.

```
(base) tslade@RTI-107301:~$ where espanso
C:\Users\tslade\AppData\Local\Programs\espanso\espanso.exe
```
After I ran Windows Update today, this new "Unknown Application" window started cropping up:

![image](https://user-images.githubusercontent.com/3211478/104530200-4edb2a80-55c0-11eb-9fb0-112c7139d5e2.png)

So, yes, I'm pretty sure it's the IT folks blocking it. Although *in theory* I should be able to use it after selecting the proper attestation and then clicking `Run` - and that process indeed works for other applications - but I cannot.

There is no response from any espanso triggers in any window or application context. The only way I can trigger some kind of response is to invoke `espanso <whatever>` from the command line (either Powershell or Git Bash in Windows Terminal), and then in every instance the response is the same: that window pops up.

1. If there are any other places I can check to see processes spawning, etc. to understand how exactly the PAM might be intercepting the launch of espanso, I'm open to suggestions.
2. If it's not too much trouble, it occurs to me that adding "espanso" to the `properties of the install file` (as indicated in that popup) might be useful for other people encountering such IT restrictions in the future.

My current action is not on this front via you, but rather with my IT people. However if you have anything useful to share with them as an argument for why espanso should be whitelisted, I'd be very happy to take your suggestions!

**Comment by federico-terzi** [comment]
@TSSlade I suspect you are right! That would explain what you are currently experiencing.

> However if you have anything useful to share with them as an argument for why espanso should be whitelisted, I'd be very happy to take your suggestions!

Unfortunately, I don't have any argument... If your IT department doesn't want it, I can't do much to help :)
What I can say is that I'm planning to add a digital signature in the future, so that espanso can be considered more trustworthy

I'm closing the issue as the problem does not seem to be related to espanso. Feel free to re-open it if you discover something else :)

**Comment by TSSlade** [comment]
Agreed, @federico-terzi - the IT thing is not something for you to take action on. The one bit of useful feedback you could provide would be insight into whether there's a process spawning somewhere that I can try to hunt down that's _different_ for `$ espanso help` vs. `$ espanso <anything-else>`. I find it disconcerting that the help command clearly works well, but nothing else really does. That suggests to me an avenue of further exploration.

I realized that I had neglected your earlier comment re: `choco` - that's the way I'd installed espanso in the first place, and that package management ecosystem is pretty good about staying up to date with the software it installs (or failing gracefully if it has gotten out of date). So just wanted to clarify it wasn't an issue on the choco side.

**Comment by federico-terzi** [comment]
> The one bit of useful feedback you could provide would be insight into whether there's a process spawning somewhere that I can try to hunt down that's different for $ espanso help vs. $ espanso <anything-else>. I find it disconcerting that the help command clearly works well, but nothing else really does. That suggests to me an avenue of further exploration.

That's strange indeed, but I think that has to do with the other commands spawning separate processes. You see, espanso works in a multi-process architecture. There is the daemon process (which monitors the config changes) and the worker process (which does the actual "expansion" work). I suspect Thycotic is blocking this behavior...

> So just wanted to clarify it wasn't an issue on the choco side.

Good to know, thank you for pointing that out!

**Comment by TSSlade** [comment]
@federico-terzi - just flagging that we got things working under Thycotic (they enabled a custom filter), but I've since run into an issue that might actually be #591 as well. Will add comments over there.

**Comment by federico-terzi** [comment]
@TSSlade Glad you got it working! Regarding the symlink, I'm wondering whether Thycotic is preventing espanso from working as well. Anyway, after #267 is implemented, this problem should be solved so better to wait for that :)

**Comment by TSSlade** [comment]
It turns out it's not Thycotic! We were able to replicate the brokenness both WITH Thycotic and WITHOUT it. (With it disabled, with my being an admin on my machine again, etc.) We were also able to replicate the function both pre-Thycotic and post-Thycotic...the key issue was symlinking versus using a direct `config.yml`

**Comment by federico-terzi** [comment]
@TSSlade Thanks for the explanation! This will be useful when investigating
