### ISSUE TITLE
Improvement: reset espanso "cache memory" after click somewhere

### ISSUE THREAD

**Issue by Masacroso** [federico-terzi/espanso#568]
I would like to see the following improvement in espanso, if possible: that the memory where the keystrokes are saved will be reset after clicking with the mouse. I will explain why I propose this: I had a unique problem using espanso, it is that many times when typing I move from one part of the text to other with the mouse, then when I edit something many times some unwanted match happens between places because clicking doesn't affect the matching capabilities of espanso.

An example to clarify the unwanted behavior: suppose that I've defined the following triggering/replacement in espanso:

- trigger: abc
- replace: hello!

Then I type "ab", after I move to other point of the document with the mouse and type "c", then immediately the replacement is triggered but I doesn't want this replacement, I was just writing normally but the click of the mouse doesn't break that the string "abc" is triggered.

**Comment by federico-terzi** [comment]
Hey @Masacroso,

This is a great idea, thank you for sharing. I'll make sure to add it to the roadmap!

Cheers :)

**Comment by federico-terzi** [comment]
Hey @Masacroso,

The new alpha v2 should not suffer from this problem, as mouse clicks now act as word separators and thus "clear" the matcher state.

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
