### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by zeromancer1972** [federico-terzi/espanso#571]
Even after "disabling" espanso, it still appears in my menu bar (macOS) after reboot. How do I get completely rid of it?

**Comment by federico-terzi** [comment]
Hey @zeromancer1972,

The procedure to uninstall espanso depends on the method you used to install it:
* If you used homebrew, a simple `brew remove espanso` should remove espanso.
* If you used the manual method, you should remove the `espanso` binary in the `/usr/local/bin/` directory.

You might also want to remove the launch agent from the `~/Library/LaunchAgents` directory.

PS: may I ask you why are you uninstalling espanso? I'm happy to hear some feedback :)

Let me know if you have other doubts

Cheers :)

**Comment by zeromancer1972** [comment]
Thanks for the hint. I remove it because I simply do not need it. It may be a nice tool though.

**Comment by federico-terzi** [comment]
@zeromancer1972 Sounds good! Thank you for the feedback :)

**Comment by herrherrmann** [comment]
This procedure should be documented somewhere! It looks like it isn’t explained on the [installation page](https://espanso.org/install/) or the [documentation](https://espanso.org/docs/get-started/).

**Comment by JoeSlain** [comment]
Note that you can also delete those:
~/Library/Application\ Support/espanso
/Applications/Espanso.app
