### ISSUE TITLE
allow form to be submitted by hitting 'enter' key on windows

### ISSUE THREAD

**Issue by GorvGoyl** [federico-terzi/espanso#578]
Title says it all. Right now I need to click on the submit button to paste. Can't it be done by hitting the standard `enter` keyboard key?

![image](https://user-images.githubusercontent.com/7106086/106797920-420f9b00-6683-11eb-8fe4-1b460dd0e513.png)

OS: Win10

**Comment by federico-terzi** [comment]
Hey @GorvGoyl,

Thank you for the feedback! The Enter key is problematic to support, as you might have multiline input fields. That said, you can use CTRL+Enter to achieve the same thing :)
I'll definitely need to add a label for this, as it's not immediately clear!

Cheers :)
