### ISSUE TITLE
at sign (@) expands to (2) on terminal

### ISSUE THREAD

**Issue by stratosgear** [federico-terzi/espanso#579]
This:

```
  - trigger: ":email"
    replace: "some@email.net"
```

expands as:

```
$ some2email.net
```

on my linux kitty terminal on arch.

On other apps (firefox, vscode, mousepad etc) it works correctly.

Am I the only one?  How can this be debugged?

Thanks for an really sweet util!

**Comment by federico-terzi** [comment]
Hey @stratosgear,

Thanks for reporting this issue! Kitty has always been a bit problematic, could you please try adding `force_clipboard: true` and see if that helps?

```
  - trigger: ":email"
    force_clipboard: true
    replace: "some@email.net"
```

Cheers :)

**Comment by stratosgear** [comment]
Yes, this works! Thanks!

I tried to find what `force_clipboard` does, or maybe even edit them to add a potential usage with similar issues like mine, but could not find it in the docs.  Did I miss it, or you should be adding it...?

I'll be closing the issue now!

**Comment by federico-terzi** [comment]
@stratosgear Glad to hear that! I'm currently working on a patch that should automatically solve some of these problems #310 

Cheers :)

**Comment by jakeprice-dev** [comment]
Thanks for this @federico-terzi, I was having similar issues that I raised on Kitty's GitHub issues (described [here](https://github.com/kovidgoyal/kitty/issues/4487)), and `force_clipboard` fixes it completely.
