### ISSUE TITLE
Copy-pasted all steps in Terminal, nothing happens. "zsh: command not found: espanso"

### ISSUE THREAD

**Issue by brent-van** [federico-terzi/espanso#590]
Can you make the installation process better? I don't understand why copy-pasting 5 steps results in failure.

% espanso register:
"zsh: command not found: espanso"

**Comment by federico-terzi** [comment]
Hey @brent-van,

I'm sorry you experienced this problem! Could you give me a bit more details about your system and installation method?

I suspect you are using a macOS system. In that case, make sure you correctly created a symbolic link with:

```
sudo ln -s /usr/local/espanso/bin/espanso /usr/local/bin
```

Generally, when you get "command not found" it means that you failed to add it to the PATH env variable (which can be achieved to the previous command)

Cheers :)

**Comment by brent-van** [comment]
macOS 10.15.7.

```
sudo ln -s /usr/local/espanso/bin/espanso /usr/local/bin:
ln: /usr/local/bin: File exists

```

**Comment by federico-terzi** [comment]
@brent-van Interesting, thank you. What do you see if you type the following commands?

```
which espanso
ls -la /usr/local/espanso/bin/espanso
echo $PATH
```

Cheers :)

**Comment by brent-van** [comment]
`espanso not found`

Is there a way one can install espanso by downloading a dmg, opening and dragging to Applications folder? I don't know how the process works, but I can imagine the application cost blood, sweat and tears so it only deserves a smooth installation process! Might make it more accessible to other Mac users with limited Unix skills.

**Comment by federico-terzi** [comment]
> Is there a way one can install espanso by downloading a dmg, opening and dragging to Applications folder? I don't know how the process works, but I can imagine the application cost blood, sweat and tears so it only deserves a smooth installation process! Might make it more accessible to other Mac users with limited Unix skills.

You are definitely right! I'm actively working to convert espanso to a normal app bundle in the next release :)

**Comment by brent-van** [comment]
In the meantime, how can I install espanso? I've used it in the past and I consider it an essential for my computer.

**Comment by brent-van** [comment]
I don't know if this helps, but does this look normal?

![Screen Shot 2021-02-09 at 10 32 14](https://user-images.githubusercontent.com/57384844/107410599-5bb94400-6ac2-11eb-9f76-16412e1af450.png)

**Comment by federico-terzi** [comment]
Hey @brent-van,

Your situation is pretty strange! Could you please run these command and post the output here?

```
ls -la /usr/local
```

And

```
echo $PATH
```

Cheers :)

**Comment by brent-van** [comment]
Do you think updating to Big Sur might help?

```
 ls -la /usr/local

total 0
drwxr-xr-x   4 root  wheel  128 Feb  1 20:08 .
drwxr-xr-x@ 11 root  wheel  352 Jan 28 18:11 ..
lrwxr-xr-x   1 root  wheel   30 Feb  1 20:08 bin -> /usr/local/espanso/bin/espanso
drwxr-xr-x   3 root  wheel   96 Feb  1 20:08 espanso

echo $PATH

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by federico-terzi** [comment]
@brent-van All right, thank you! You should be able to solve your problem with:

```
sudo rm /usr/local/bin
sudo mkdir /usr/local/bin
sudo ln -s /usr/local/espanso/bin/espanso /usr/local/bin
```

What happened was interesting: if you run `sudo ln -s /usr/local/espanso/bin/espanso /usr/local/bin`, it creates a sym link called "espanso" within the /usr/local/bin folder. The problem is that if the folder `/usr/local/bin` doesn't exist, it misbehaves. So the solution (proposed in the above steps) is to delete the `bin` link which is wrong, create a bin directory and then run the linking command again

Let me know if that helps

**Comment by brent-van** [comment]
That solved it! Thanks for your lightning-fast responses. I have shared espanso on Twitter so other people can discover it.

**Comment by federico-terzi** [comment]
@brent-van glad you solved the problem! And thanks for your support :)
