### ISSUE TITLE
Wrong text expansion: ''' instead of ``` 

### ISSUE THREAD

**Issue by Luctins** [federico-terzi/espanso#593]
One of my matches (below)
```yaml
  - trigger: ";m;"
    replace: "\u0060\u0060\u0060"
```
expands to `'''` instead of ` ``` ` after system start up. Most of the times restarting espanso manually, solves the problem temporarily.
I've tried also  ` ``` ` and 
```
`\u0060`
```
no effect, and the leftover text if I try to erase `'''` is `çmç` instead of `;m;`

It seems to be some sort of text encoding issue.

System Info:
* Keyboard Layout: `pt-br`
* OS: 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal

gnome-shell --version
GNOME Shell 3.36.4
```

**Comment by federico-terzi** [comment]
Hey @Luctins,

Thanks for reporting this issue! This might be related to #489 and #447, so I'm closing this one in favor of the others. Feel free to continue the discussion there if you have anything to add :)

Cheers :)
