### ISSUE TITLE
Cursor hint not working when using passive mode?

### ISSUE THREAD

**Issue by NicolasWebDev** [federico-terzi/espanso#597]
I have the following match, using passive mode: 
```yaml
  - trigger: ":ems" # greet/bye for emails in spanish
    replace: |
      Hola $0$

      ¿Cómo estás?

      $|$

      ¡Saludos!
    passive_only: true
```
When I expand it using for example `:ems/Pablo/`, the cursor hint (`$|$`) is added textually in the expansion and the cursor is left at the end of the expansion.

I also have tried with single line matches and in different editors/places to rule out possible problems on my side.

So is the use of the cursor hint one other limitation of the passive mode, or am I doing something wrong?

**Comment by federico-terzi** [comment]
Hey @NicolasWebDev,

Thank you for the feedback! Unfortunately, cursor hints don't work with passive mode :(

Cheers :)
