### ISSUE TITLE
Watcher doesn't seem to be debounced on Windows

### ISSUE THREAD

**Issue by fstamour** [federico-terzi/espanso#602]
I tried to generate a bunch of rules using a script. Everytime I ran the script, creating or updating multiple files at the same time, espanso detected the different changes at the same time and restarted once for every changes. But the real problem is that I **ended up with multiple espanso instances running at the same time** conflicting with each other.

I was on Windows, when I tried on Linux (NixOS to be exact) I wasn't able to reproduce that behaviour.

On a related note: I noticed that the configurations get reloaded whenever there's a change in the configuration folder. But maybe it would be better to watch only `default.yml` and the `user` folder, and maybe watch only for events on `*.yml` files? I'm saying that because I somebody wants to add files like a readme, a `.git` folder or some scripts, espanso will restart everytime any of those files are touched.

**Comment by federico-terzi** [comment]
Hey @fstamour,

Thanks for reporting this issue! Indeed, this is a known problem (#548), and happens when multiple changes occur near each other. Given that I'm rewriting espanso from scratch in #594, I decided to wait for the next big release to tackle this one :)

Cheers :)

**Comment by fstamour** [comment]
ok, I took a look at the code yesterday, but there was nothing obvious. You're using the RecommendedWatcher... sounds like it's the recommended thing to do

https://github.com/federico-terzi/espanso/blob/901058a62e482ae2b0d4d1479775cad2d6d03da8/src/main.rs#L568

Anyaway, you can close this issues as duplicate of #548

**Comment by fstamour** [comment]
Actually, I just saw that _I_ can close the issue :P

**Comment by federico-terzi** [comment]
@fstamour The biggest problem is that if multiple reloads happen near each other, the IPC pipe espanso uses to "exit" the previous instance has not been initialized yet, and thus multiple espanso copies keep running. I'll make sure to fix this problem in the next release, given that it requires some non-trivial changes to the IPC architecture :)

**Comment by fstamour** [comment]
That's interesting (about the IPC), this might not be the best place to discuss this, but why does espanso need to be separated in 2 processes?

On a side note, I circumvented the problem by adding `espanso stop` at the start of my script and an `espanso start` at the end, here's the script I was (am still) using:  https://gist.github.com/fstamour/97ee60069322ec27eed7cfef2198670f

**Comment by federico-terzi** [comment]
@fstamour Thanks for sharing!

> but why does espanso need to be separated in 2 processes?

It was mostly because, in the initial design, the loaded configuration was immutable. So in order to reload a config, restarting the process was the most robust thing to do, and thus a "daemon" process was needed to manage (and restart) the "worker" process :) Perhaps, that might change in the next release
