### ISSUE TITLE
Finder activate SecureInput

### ISSUE THREAD

**Issue by jacopocarotenuto** [federico-terzi/espanso#604]
# Description
When i open espanso, it tells me finder ha activated secureInput. If I restart finder (from the Force Quit menu) and then restart espanso, it tells me everything worked and it succesfully restarted, but it does nothing. If I type a trigger, it doesn't replace it my match. It does everything it should in the terminal, so my guess is it doesn't know secureInput is still active, so it can't see what i'm typing. If I logout and then log-in again, the SecureInput notification tell me that Finder is the culprit again. I tried everything from restarting my entire computer to deleting every file related to Espanso and then reinstall it. 
I found [this](https://forum.keyboardmaestro.com/t/disable-secure-input/2410/4) thread and found that the culprit is, even by this method, Finder. 
It all started when i changed syncing directory, but i tried and even using the default file with no symlink the problem persist.
I'm on a MacMini late 2012 running macOS Catalina versione 10.15.7
Espanso works in my MacBook Air, with Big Sur versione 11.2.1
Thank you for the wonderful app anyway

**Comment by jacopocarotenuto** [comment]
My mistake. After a more cautious restart where i disabled the "open at login" apps, i discovered there was an instance of bitwarden not shown in the menubar and that wasn't asking for any input. After closing BitWarden Espanso worked. It probably masked as the Finder in some way, so espanso was detecting it as such. 
Thank you again for this awesome app.

**Comment by federico-terzi** [comment]
Hey @jacopocarotenuto,

Thank you for the feedback! Indeed, the app detection is not flawless, and sometimes it does not detect the application properly. Are you using the Bitwarden Desktop app?

Cheers :)

**Comment by jacopocarotenuto** [comment]
Yes, I was using the Bitwarden Desktop app. But i had enabled a option to not show the icon on the status bar. I didn't think of it because it was not showing any window, but apparently it activated SecureInput anyway.

**Comment by federico-terzi** [comment]
@jacopocarotenuto I see, thank you for explaining!
