### ISSUE TITLE
Text-Expansion not working after repeated device sleep / wrong keycodes

### ISSUE THREAD

**Issue by pc-coholic** [federico-terzi/espanso#605]
I've setup espanso 0.7.3 on my Ubuntu 20.04.2 LTS, keyboard layout is a regular German QWERTZ-layout with dead keys.

98% off all time, espanso just works as expected - however after extended usage of my device with repeated restarts of GDM and/or putting the device to sleep and waking it up again, my expansions start to be slightly screwed up.

Some of my macros contain URL that are suddenly not expanded correctly anymore.

For example, instead of `https://docs.pretix.eu/en/latest/user/events/email.html#spam-issues`, I'll end up with `httpsÖ--docs.pretix.eu-en-latest-user-events-email.html§spamßissues`.

This is not exclusive to URLs - also hyphenated names like `Franz-Xaver Nord-Bottrop` would become `FranzßXaver NordßBottrop`.

The first time this occurred, I tried switching off `fast_inject`. That did indeed solve the issue - until it arose again. This time, enabling `fast_inject` made the problem go away. Not long after that, I figured that just restarting espanso would solve the issue.

So right now I'm thinking about just having a macro that restarts espanso whenever needed - but that's also kinda cheating ;-)

Please let me know if I can provide you with any further information to help solve this issue.

**Comment by federico-terzi** [comment]
Hey @pc-coholic,

I'm sorry you experienced this problem! This seems to be the same issue as #489, so I'll close this issue in favor of that one. Feel free to add anything there, or to reopen this issue if you think those issues are not the same!

I'm currently rewriting espanso as part of #594, and I think that some of these problems will be solved with the new implementation, so your best bet is to use the workaround until the new version is out!

Thank you for the detailed report, that will be helpful to solve the problem :)

**Comment by pc-coholic** [comment]
Oh, sorry! I didn't see that issue 🙈

Thanks for pointing it out and thanks for this great piece of software!

**Comment by federico-terzi** [comment]
@pc-coholic No worries! Thank you for raising the issue :)
