### ISSUE TITLE
Can't make filter_title work

### ISSUE THREAD

**Issue by fharper** [federico-terzi/espanso#607]
Firstly, thanks for the app!

I'm testing it to see if I could replace aText with it (always prefer OSS), but on macOS 11.1 (Big Sur), the `filter_title` configuration is never applied: the shortcut is working on all applications no matter what. I wonder if it's me who missed something or if it's a bug.

my `default.yml` file content
```
matches:
  - trigger: ":espanso"
    replace: "Hi there!"
```

my app specific file `iTerm.yml` content
```
name: iTerm
parent: default

filter_title: "iTerm"

matches:
  - trigger: ":ok"
    replace: "👍"
```

I can type `:ok` in any apps, not just iTerm and it will replace with the emoji. I restarted the app even if the new configuration were reloaded automatically. I also set the right macOS permission since there is a text replacement. There is no errors in the log file either.

Any ideas what is going on?

**Comment by federico-terzi** [comment]
Hey @fharper,

I'm sorry you experienced this problem! Could you please try to remove the `parent: default` line? That tells espanso to merge the current configuration with the `default.yml` file.
PS: I know this is not obvious at first, in the next release (#594 ) things will greatly improve in this area!

Cheers :)

**Comment by fharper** [comment]
> I'm sorry you experienced this problem!

No stress!

> Could you please try to remove the `parent: default` line?

Now the `:ok` doesn't work anywhere.

**Comment by federico-terzi** [comment]
Hey @fharper,

Perhaps the `filter_title` flag is not the best one in this case, could you please try with the procedure described in the "Finding the right filters" section: https://espanso.org/docs/configuration/#application-specific-configurations and see if that helps?

Cheers :)

**Comment by fharper** [comment]
I tried all three, it is not working. I also tried with another app than iTerm.

May be related, but the detection doesn't work with most apps, even if I stay minutes on them.

Also, the title returned seems to be the class instead:
```
Detected change, current window has properties:
==> Title: 'com.googlecode.iterm2'
==> Class: 'com.googlecode.iterm2'
==> Executable: '/Applications/iTerm.app'
```

Maybe there is something with the fact that I'm on a M1 processor, which I wouldn't see why since the basic shorcuts works.

**Comment by federico-terzi** [comment]
@fharper Interesting, thank you. Where did you place the `iTerm.yml` file?

Given those properties, could you please try with:

```yml
name: iTerm

filter_class: "iterm2"

matches:
  - trigger: ":ok"
    replace: "👍"
```

> May be related, but the detection doesn't work with most apps, even if I stay minutes on them.

This might be also related to Big Sur, but I haven't got the chance to try it out yet! As soon as I get my hands on a macOS machine running Big Sur I'll investigate

**Comment by fharper** [comment]
> Where did you place the `iTerm.yml` file?

in the `user` folder.

> Given those properties, could you please try with

Using those, without `parent` works!

Thanks a lot. I let you close the issue if you prefer to open another one for the information returned by the detection process.

> This might be also related to Big Sur, but I haven't got the chance to try it out yet! As soon as I get my hands on a macOS machine running Big Sur I'll investigate

Let me know if there is anything I can do to help? I don't have time now to check on my own, but more than happy to do tests if you let me know what to check. In a near future, I can give it a closer look by myself while checking the code.

**Comment by federico-terzi** [comment]
@fharper Glad to hear that!

> Let me know if there is anything I can do to help? I don't have time now to check on my own, but more than happy to do tests if you let me know what to check. In a near future, I can give it a closer look by myself while checking the code.

Thank you, I appreciate your help! I'm currently rewriting espanso as part of #594, after that I'll be happy to have some big-sur related feedback :)
