### ISSUE TITLE
Is there a way to have Espanso press key combinations?

### ISSUE THREAD

**Issue by DillFrescott** [federico-terzi/espanso#608]
For example have Espanso press CTRL + A

Please let me know! :)

**Comment by federico-terzi** [comment]
Hey @DillFrescott,

Thank you for the feedback! Unfortunately, this is not yet possible, but will be once #286 is implemented :)

Cheers :)

**Comment by DillFrescott** [comment]
@federico-terzi ok. Thank you!! Looking forward to the addition! :)
