### ISSUE TITLE
macOS Configuration in Wrong Location

### ISSUE THREAD

**Issue by rawkode** [federico-terzi/espanso#611]
As per the macOS guidelines, the espanso config should live under "Application Support" and not "Preferences" o macOS.

> Preferences | This directory contains app-specific preference files. You should not create files in this directory yourself. Instead, use the NSUserDefaults class or CFPreferences API to get and set preference values for your app.

>  Application Support | Use  this directory to store all app data files except those associated with  the user’s documents. For example, you might use this directory to  store app-created data files, configuration files, templates, or other  fixed or modifiable resources that are managed by the app. An app might  use this directory to store a modifiable copy of resources contained  initially in the app’s bundle. A game might use this directory to store  new levels purchased by the user and downloaded from a server.All  content in this directory should be placed in a custom subdirectory  whose name is that of your app’s bundle identifier or your company.

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

I'm building a configuration management tool that provides the `CONFIG_DIR` to users as `Application Support`, as per the guidelines and this means espanso configs need to be provisioned using `HOME_DIR` with extra path information to be correctly picked up.

Would love to see this fixed 😃

**Comment by federico-terzi** [comment]
Hey @rawkode,

Thank you for pointing this out! Espanso uses the "dirs" package to automatically determine the correct configuration location, and after some investigation, it looks like the most recent version is indeed using `Application Support` (source: https://github.com/dirs-dev/dirs-rs#3) instead of `Preferences`

That said, we'll need to think about the best way to actually support this migration in the next release, as the `Application Support` directory is currently used by espanso to store some espanso-generated files.
I understand that macOS suggests putting both data files and config files there, but that's far from being elegant...

I think the idea of separating user-generated files from espanso-generated files is crucial to make the config manageable and easy to synchronize, as the espanso-generated ones are not supposed to be copied.

Do you have any suggestions?

Cheers :)

**Comment by rawkode** [comment]
Hi @federico-terzi, I hit this problem with `dirs` too, my project is Rust also. 

I actually was expecting to get `$HOME/.config` and I’m considering overwriting what `dirs` returns 😅
 

I agree that separating them is definitely a plus. If `espanso` can recreate its auto generated files when required, could use the macOS cache directory. Bonus is that this isn’t backed up to iCloud.

**Comment by federico-terzi** [comment]
Hey @rawkode,

> I actually was expecting to get $HOME/.config and I’m considering overwriting what dirs returns
> I agree that separating them is definitely a plus. If espanso can recreate its auto generated files when required, could use the macOS cache directory. Bonus is that this isn’t backed up to iCloud.

Thank you for the suggestions! Those are great starting points indeed. The cache directory seems like the perfect fit for the espanso-generated files (I should have chosen it in the first place!), so I'll look forward to change it in the future version :)

Regarding the `$HOME/.config/espanso` location, I totally agree with you! In fact, espanso already supports that location if you manually move the files there. In the upcoming version, I'm looking forward to introducing a way to manually specify the config location (through a command-line flag or env variable), so that the user can easily change it based on its needs.

I'd say a good compromise could be to use the `Application Support` location as the new default, while supporting custom paths, including `$HOME/.espanso` and `$HOME/.config/espanso`

What do you think?

As a side note, thank you for the donation! I really appreciate it :)

**Comment by itaiferber** [comment]
Not @rawkode, but this sounds great. I've had my eye on moving to Espanso from TextExpander for a while but was hoping to get to place a config in `$HOME/.config` along with all of my other dotfiles. Support for `.config` is news to me so I'll definitely give it a shot now — having it more explicitly supported sounds like a big win. (In fact, I came here to post an issue debating just this but glad I read this one first.)

**Comment by rawkode** [comment]
> I'd say a good compromise could be to use the Application Support location as the new default, while supporting custom paths, including $HOME/.espanso and $HOME/.config/espanso

PERFECT 🎉

**Comment by federico-terzi** [comment]
@itaiferber @rawkode Great, thank you! 

For reference, related issue #267

**Comment by quintrino** [comment]
> Regarding the `$HOME/.config/espanso` location, I totally agree with you! In fact, espanso already supports that location if you manually move the files there.

Just following up on this because I'm still not sure, if I'm currently using Mac and place all my espanso config files in $HOME/.config/espanso it will work as expected? 

If there's files in both the default and $HOME/.config/espanso will it read both?

**Comment by federico-terzi** [comment]
Hey @quintrino,

>  if I'm currently using Mac and place all my espanso config files in $HOME/.config/espanso it will work as expected?

Yes

> If there's files in both the default and $HOME/.config/espanso will it read both?

No, only the first one in the sequence (currently `.config/espanso`)

Cheers :)

**Comment by SpecialCharacter** [comment]
I just intalled espanso on my Mac (and it works), but I find it nether under "Application Support" nor under "Preferences"... any help?

**Comment by federico-terzi** [comment]
@SpecialCharacter Try to run `espanso path` in a terminal :)

**Comment by SpecialCharacter** [comment]
Thanks, it was hidden; it works now! :)

**Comment by federico-terzi** [comment]
Great! :)

**Comment by garyo** [comment]
I've been using espanso for a while now, and just ran across this while trying to sync my dotfiles between Mac and Windows and Linux. Didn't realize espanso can always use `.config/espanso` -- that's a huge help to me!

**Comment by sandstrom** [comment]
@federico-terzi I second the comment above, would be great if `~/.config/espanso` was mentioned as an alternative location for the config file. I couldn't find it in the docs, but found this thread after googling a while.

**Comment by smeech** [comment]
> [@federico-terzi](https://github.com/federico-terzi) I second the comment above, would be great if `~/.config/espanso` was mentioned as an alternative location for the config file. I couldn't find it in the docs, but found this thread after googling a while.

We'll run some checks, and I'll update the docs accordingly. Thank you for bringing this to my attention!

As I don't have a macOS machine, can you lay out the steps you took to make this work, please?

**Comment by sandstrom** [comment]
@smeech Great!

1. Install espanso (I downloaded the app, but should be the same with [brew install](https://github.com/espanso/homebrew-espanso/blob/main/Casks/espanso.rb)).
2. Start the app
3. Check current location with `espanso path`
4. Move the config files (see below)
5. Reload the config (via app menu)
6. Verify by calling `espanso path`
```sh
mkdir -p ~/.config/espanso
mv ~/Library/Application\ Support/espanso ~/.config/espanso
```

**Comment by smeech** [comment]
Thank you. I guess it makes sense to stop Espanso while making the move, and I presume the "`\`" above is a typo.

**Comment by sandstrom** [comment]
You are welcome! 🙂 

- `\` is needed to escape the space.
- I didn't stop it, there is an explicit reload command.

**Comment by smeech** [comment]
> * `\` is needed to escape the space.

I'm more used to surrounding paths with spaces with quote-marks. As long as it works (for the benefit of anyone else who discovers this thread).

**Comment by AucaCoyan** [comment]
Yup, it does work. I'm surprised.
When you move the files espanso crashes because it cannot load the config file on a different location _at runtime_. But if you `espanso start` again on the terminal, it just works!

```bash
bash-3.2$ espanso path
Config: /Users/username/.config/espanso
Packages: /Users/username/.config/espanso/match/packages
Runtime: /Users/username/Library/Caches/espanso
```

**Comment by AucaCoyan** [comment]
the path to resolve the config comes from [here](https://github.com/espanso/espanso/blob/b1e96bfe7a232ddec2fffe050da89172b38e1f03/espanso-path/src/lib.rs#L91).

If it drills down to the default config, it calls the dependency `dirs::config_dir()` which uses:
```rust
/// Returns the path to the user's config directory.
///
/// The returned value depends on the operating system and is either a `Some`, containing a value from the following table, or a `None`.
///
/// |Platform | Value                                 | Example                                  |
/// | ------- | ------------------------------------- | ---------------------------------------- |
/// | Linux   | `$XDG_CONFIG_HOME` or `$HOME`/.config | /home/alice/.config                      |
/// | macOS   | `$HOME`/Library/Application Support   | /Users/Alice/Library/Application Support |
/// | Windows | `{FOLDERID_RoamingAppData}`           | C:\Users\Alice\AppData\Roaming           |
pub fn config_dir() -> Option<PathBuf> {
    sys::config_dir()
}
```
as the config dir

**Comment by smeech** [comment]
Thanks - I'll make a minor addition to https://espanso.org/docs/get-started/#configuration
