### ISSUE TITLE
Some packages don't work

### ISSUE THREAD

**Issue by matildeopbravo** [federico-terzi/espanso#613]
I installed some packages, such as espanso-latex and blackboard-letters and they don't seem to work. Every other package I installed does

**Comment by federico-terzi** [comment]
Hey Matilde,

Thanks for reporting this issue! Did you experience any particular problem or they simply didn't work?

Cheers :)

**Comment by matildeopbravo** [comment]
Hello! It mysteriously started working again, I have no idea why! The only one which doesn't work is the ip package. I installed dig as requested and whenever I type :ip it replaces it by nothing

**Comment by federico-terzi** [comment]
@matildeopbravo Interesting, thank you! You might be able to understand why that isn't working by reading the output of `espanso log`, which usually includes the error encountered when executing shell commands

**Comment by matildeopbravo** [comment]
This was in log file:
22:03:38 [ERROR] Error, can't connect to X11 context
22:03:38 [ERROR] worker process exited with non-zero code: 100, exiting

**Comment by federico-terzi** [comment]
@matildeopbravo Thank you! This does not seem to be related to packages but rather to an X11-related error. Would you mind sharing some details about your system? (Distro, graphical environment, etc)

Thanks :)

**Comment by matildeopbravo** [comment]
I am running Arch Linux and i3 as a window manager. Do you need any more information?

**Comment by federico-terzi** [comment]
@matildeopbravo Thank you, nothing strange with this... Let's keep an eye on it, if it happens again with the next version we'll investigate further :)

I'm closing the issue, feel free to open it again if you have anything to add :)
