### ISSUE TITLE
Add indentation to matches examples

### ISSUE THREAD

**Issue by oaustegard** [federico-terzi/espanso#617]
The teeniest of nit-picks with the documentation on pages like https://espanso.org/docs/matches/:

The yaml is lacking one level of indentation to take into account the `matches:`, so when as a user you copy paste into your config you end up with an indentation error

i.e. the ask is to indent all the examples by two spaces so as to allow copy/paste with no further changes needed

**Comment by federico-terzi** [comment]
Hey @oaustegard,

Thank you for the feedback! This is a great suggestion, I'll make sure to add the level of indentation when rewriting the documentation for #594 

Cheers :)

**Comment by federico-terzi** [comment]
Hey,

The new documentation should have the indentations in the right place :)  https://espanso.org/docs/next/matches/basics/

Thanks for your help :)

**Comment by oaustegard** [comment]
Great, thanks!
