### ISSUE TITLE
Official Apple M1 support

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#619]
Originally proposed in #615, I move here the important bits:

Currently, installing Espanso via Homebrew installs an 86_64 version, even if using the -s (--build-from-source) option.

A git clone and cargo build --release works perfectly to create an arm64 version.

It looks like configuring to build a universal binary should be pretty easy, though I've never done it before.

Unfortunately, it looks like the release artifacts are made with Azure Pipelines CI, which doesn't yet have a MacOS 11 (Big Sur) option, so I'm not sure there is anything actionable on this yet.

But I thought it might be helpful for other users to know that a local clone and compilation works great on Apple Silicon, and hopefully once Azure supports Big Sure we can migrate the release artifact to a universal binary.

At the moment, it seems that Rust does not support building universal binaries yet, though it might be coming: https://github.com/rust-lang/cargo/issues/8875

I'll post-pone this one after #594 is ready so that we have a solid foundation to support the new M1 processor

**Comment by jgchristopher** [comment]
If anyone else is interested in using this method to get espanso installed on an M1. Here is what I did (this may be documented elsewhere :) ). 

This assume you already have rust and cmake installed via `brew install rust` and `brew install cmake`

1. git clone the repo
2. cd into the repo
3. `cargo build --release`
4. `cd target/release`
5. Follow the Manual install steps at [Espanso Install](https://espanso.org/install/mac/), starting with the "Create a folder to house the binary:" step. The espanso binary will be in the folder you are in.
6. Continue following the installation instructions

**Comment by federico-terzi** [comment]
@jgchristopher Thanks for sharing!
