### ISSUE TITLE
Can I receive filename of the current document to use this as variable in the replace

### ISSUE THREAD

**Issue by andriyor** [federico-terzi/espanso#620]

**Comment by federico-terzi** [comment]
Hey @andriyor,

Sorry for the late reply!

> Can I receive filename of the current document to use this as variable in the replace?

It depends. The short answer is no, but depending on your editor you might be able to set up a custom script to extract the file. For example, I personally use the [shell extension](https://espanso.org/docs/matches/#shell-extension) to extract the window with xdotool: https://stackoverflow.com/questions/3983946/get-active-window-title-in-x

Depending on your editor/use case, you might be able to make it work

I'm closing the issue as there is not much espanso can do on this one

Cheers :)
