### ISSUE TITLE
Feature request: Uninstall option for packages

### ISSUE THREAD

**Issue by telmotrooper** [federico-terzi/espanso#63]
Right now we can programmatically install a package, but not uninstall it.

For some reason the `basic-emojis` package is slow in my computer so I ended up removing its folder from `~/.espanso/packages` manually.

**Comment by federico-terzi** [comment]
Hi,
Thank you very much for the feedback. 
Right now you can uninstall a package using this command:

```
espanso package remove basic-emojis
```
At this point it's clear that it's not a user friendly naming choice, so in the next release I will make this command available:

```
espanso uninstall basic-emojis
```
This should solve the issue.

Another question, which operating system do you use? Because if you are using linux, the slow emojis could be solved with a simple option.

**Comment by telmotrooper** [comment]
@federico-terzi Yes, I'm using Arch Linux. What option is it?

**Comment by federico-terzi** [comment]
Ok, in that case, you can try with `backend` option:

In your `default.yml` configuration file, add the following option:

```
backend: Clipboard
```

And then restart espanso.

On linux, unfortunately, the default backend is not working super well ( compared to Windows or macOS ) while the "Clipboard" backend works much better. I'm considering making it the default one on Linux, but I wanted to receive some feedback first.

Please let me know if it helps :)

**Comment by telmotrooper** [comment]
With `backend: Clipboard` it does indeed work much faster, but for some reason does not work in GNOME Terminal (it erases the text but does not add the emoji(s)).

I'd say it's a sane default for Linux, but you should probably add that bit of information in the documentation.

**Comment by federico-terzi** [comment]
Thanks for the feedback, I will work about that issue.
Regarding the integration with the GNOME terminal, [this bug](https://github.com/federico-terzi/espanso/issues/65) should be easily solvable. In the next release I will fix it.

**Comment by one-none** [comment]
Hi there, how can I fully manul remove espanso from OSX Mojace?
