### ISSUE TITLE
MacOS Catalina - Error starting launchd daemon

### ISSUE THREAD

**Issue by tweinreich** [federico-terzi/espanso#633]
Hi, I just installed espanso and the following error occured:
`Error starting launchd daemon with status: exit code: 3`

When launching `espanso daemon` I saw the following message:
`[ WARN] Unable to delete Unix socket: No such file or directory (os error 2)`

Then my system warned me about espanso needing access to "accessibility" which I allowed in options / security & privacy / accessibility.

Then I did an `espanso register` which told me the registry entry was created and loaded correctly. Doing `espanso status` told me "espanso is not running" but another `espanso start` made the icon appear in the menu and produced the message "Daemon started correctly!".

I am noting this here for others who may wonder how to get it to work correctly with a similar setup.

Thank you for creating and sharing this great tool!

**Comment by 4lch4** [comment]
Hey @tweinreich, out of curiosity, what was your install method? I'm guessing homebrew, but I could be entirely wrong 😅

**Comment by tweinreich** [comment]
Hey @4lch4, you are entirely correct with your assumption 😜

**Comment by 4lch4** [comment]
Thanks! I'm gonna see if I can't recreate this behavior and find a way to fix it automatically.

**Comment by tweinreich** [comment]
Thank you for your time and your work! 😀

**Comment by federico-terzi** [comment]
Hey @tweinreich,
Thank you for the feedback! The current behavior is not the most user-friendly, with the next release, we plan to improve the situation :)

@4lch4 thank you for the help! :)

**Comment by tweinreich** [comment]
Hey @federico-terzi, 
Thank you for this great tool!

For me this is not a problem but less technical users may have difficulties. I just got you a coffee as a little thank you for your effort :)

**Comment by xplosionmind** [comment]
Hello everybody. I am experiencing the same issue and I do not know any workaround. Should I wait for the next release or there is a way to make espanso work in the meanwhile?

Thanks a lot!

**Comment by tweinreich** [comment]
Hey @xplosionmind, did you try the workaround I described? Can you provide us with more details what you did and what exactly did not work?

**Comment by xplosionmind** [comment]
> Can you provide us with more details what you did and what exactly did not work?

@tweinreich sure, sorry!

As you can see from the screenshot below, the espanso does not even come up in Security and Privacy \> Accessibility. I restarted the computer and deleted `Modulo.app`, as @federico-terzi suggested me in #565; still nothing.

Should I open a new issue?

<img width="677" alt="Screenshot 2021-04-02 at 12 06 47 PM" src="https://user-images.githubusercontent.com/42862428/113406755-52ef3b00-93ac-11eb-8171-6ee310d31f4d.png">

**Comment by tweinreich** [comment]
Hey @xplosionmind, no problem.

Yes I think this is another issue and it would be better to open a new ticket for it.

Another idea: did you try adding Espanso to the settings manually? (*notice the '+' icon below the list, in my case the binary is in `/usr/local/Cellar/espanso/0.7.3/bin/`*)

**Comment by xplosionmind** [comment]
I will not open another issue since this worked, thanks a lot @tweinreich!

Best,  
T

**Comment by tweinreich** [comment]
You're welcome @xplosionmind - happy that it finally works for you, too! :)

**Comment by federico-terzi** [comment]
@xplosionmind Glad you figured it out! Out of curiosity, did you run `espanso register` beforehand? That's the command that should add espanso to the accessibility list

**Comment by xplosionmind** [comment]
> @xplosionmind Glad you figured it out! Out of curiosity, did you run `espanso register` beforehand? That's the command that should add espanso to the accessibility list 

I did. Thank you for your great help and for your terrific work with espanso.

Happy Easter!  
T

**Comment by federico-terzi** [comment]
@xplosionmind Interesting, thank you! Happy Easter too!

**Comment by federico-terzi** [comment]
Hey guys,

The new alpha v2 version now comes as an App bundle on macOS, which should solve most of these problems and make it easier to deal with in general.

I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
