### ISSUE TITLE
Frequently need to restart espanso

### ISSUE THREAD

**Issue by pouriaalmassi** [federico-terzi/espanso#635]
Approximately 1 to 2 times a week I restart espanso due to text completions not triggering. 

espanso log output:

```
00:25:09 [ INFO] espanso version 0.7.3
00:25:09 [ INFO] using config path: /Users/pouriaalmassi/Library/Preferences/espanso
00:25:09 [ INFO] using package path: /Users/pouriaalmassi/Library/Application Support/espanso/packages
00:25:09 [ INFO] spawning worker process...
00:25:09 [ INFO] Binded to IPC unix socket: /Users/pouriaalmassi/Library/Application Support/espanso/espanso.sock
00:25:09 [ INFO] initializing worker process...
00:25:09 [ INFO] Status icon already initialized, skipping.
00:25:09 [ INFO] Status icon (disabled) already initialized, skipping.
00:25:09 [ INFO] Initializing EspansoNotifyHelper in /Users/pouriaalmassi/Library/Application Support/espanso
00:25:09 [ INFO] EspansoNotifyHelper already initialized, skipping.
00:25:09 [ INFO] Binded to IPC unix socket: /Users/pouriaalmassi/Library/Application Support/espanso/worker.sock
00:25:09 [ INFO] Using modulo at "/usr/local/bin/modulo"
00:25:09 [ INFO] Created Modulo APP stub at: "/Users/pouriaalmassi/Library/Application Support/espanso/Modulo.app/Contents/MacOS/modulo"
00:25:09 [ INFO] worker is running!
00:25:09 [ INFO] watching for changes in path: /Users/pouriaalmassi/Library/Preferences/espanso
00:25:40 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox
00:25:50 [ INFO] SecureInput has been disabled.
```

Could this be triggered by `00:25:40 [ INFO] SecureInput has been acquired by Firefox, preventing espanso from working correctly. Full path: /Applications/Firefox.app/Contents/MacOS/firefox`? 

Environment details: 
    - OS: macOS Big Sur 11.2.3 (20D91)
    - espanso version 0.7.3

**Comment by federico-terzi** [comment]
Hey @pouriaalmassi,

I'm sorry you experienced this problem! Are you sure you didn't accidentally press the Alt key twice? That disables espanso.
Otherwise, it might be related to the secure input https://github.com/federico-terzi/espanso/issues/612

Are you using 1Password? That might also be related

Cheers :)

**Comment by pouriaalmassi** [comment]
@federico-terzi Almost certainly not pressing Alt twice. 

I think you're right that it's related to #612. 

I am using 1Password. 

Thanks for your help!

**Comment by federico-terzi** [comment]
@pouriaalmassi Thank you! I'm still investigating how to make the process smoother for users, hopefully it will get better with time :)
