### ISSUE TITLE
how to customise default editor 

### ISSUE THREAD

**Issue by tanay-pingalkar** [federico-terzi/espanso#636]
i have to change nano editor to vim , how can i do that, i have found it on espanso doc but didnt understand where to puth this `EDITOR=/usr/bin/vim`

**Comment by tanay-pingalkar** [comment]
Linux

**Comment by tanay-pingalkar** [comment]
I have to change bashrc?

**Comment by federico-terzi** [comment]
@tanay-pingalkar All right, thank you

> I have to change bashrc? or zhsrc?

This depends on the shell you are using, so the first thing I would do is running `ps -p $$` to see which one you are running.

In my case it's `zsh`, so I would edit the `.zshrc`, adding at the bottom:

```
EDITOR=/usr/bin/vim
```

At this point, you can close the current terminal and open a new one. If you now call `echo $EDITOR` you should see `/usr/bin/vim` and espanso edit should work as expected

Cheers :)
