### ISSUE TITLE
Request to add TAB keypress functionality

### ISSUE THREAD

**Issue by MatazaNz** [federico-terzi/espanso#637]
Espanso has been great so far with speeding up workflows.
However, one feature that's lacking is the ability to send keypresses. The main keypress that I really care about is TAB.

Is this possible to add? If I use \t in a replacement, it enters a text tab character, which is fine, but in some circumstances, I would like to be able to send a TAB keypress, so it can enter text into multiple text fields with a single trigger.

**Comment by federico-terzi** [comment]
Hey @MatazaNz,

Thank you for the feedback! This is not currently possible, but we are working on it #286 

Cheers :)
