### ISSUE TITLE
espanso prints with different characters

### ISSUE THREAD

**Issue by e4e6** [federico-terzi/espanso#644]
the issue is espanso printing "source sanalpy.bın.actıvate" when it should have printed "source sanalpy/bin/activate"

this problem fixes  when i restart espanso daemon but after sometime (dont know exactly) it broke again, ( happened twice in a row , now i am here )

espanso version ;
  0.7.3

OS ; 
  ubuntu 20 LTS

macro;
  - trigger: ",,s"
    replace: "source sanalpy/bin/activate"

The out put when ",,s" ;
   source sanalpy.bın.actıvate

espanso log

17:12:11 [ INFO] espanso version 0.7.3
17:12:11 [ INFO] using config path: /home/muhammet/.config/espanso
17:12:11 [ INFO] using package path: /home/muhammet/.local/share/espanso/packages
17:12:11 [ INFO] spawning worker process...
17:12:11 [ INFO] Binded to IPC unix socket: /home/muhammet/.local/share/espanso/espanso.sock
17:12:11 [ INFO] initializing worker process...
17:12:11 [ INFO] Binded to IPC unix socket: /home/muhammet/.local/share/espanso/worker.sock
17:12:11 [ INFO] worker is running!
17:12:11 [ INFO] watching for changes in path: /home/muhammet/.config/espanso

espanso dump

ConfigSet {
    default: Configs {
        name: "default",
        parent: "self",
        filter_title: "",
        filter_class: "",
        filter_exec: "",
        log_level: 0,
        conflict_check: false,
        ipc_server_port: 34982,
        worker_ipc_server_port: 34983,
        use_system_agent: true,
        config_caching_interval: 800,
        word_separators: [
            ' ',
            ',',
            '.',
            '?',
            '!',
            '\r',
            '\n',
            '\u{16}',
        ],
        toggle_key: ALT,
        toggle_interval: 230,
        preserve_clipboard: true,
        passive_match_regex: "(?P<name>:\\p{L}+)(/(?P<args>.*)/)?",
        passive_arg_delimiter: '/',
        passive_arg_escape: '\\',
        passive_key: OFF,
        passive_delay: 100,
        enable_passive: false,
        enable_active: true,
        undo_backspace: true,
        paste_shortcut: Default,
        backspace_limit: 3,
        restore_clipboard_delay: 300,
        secure_input_watcher_enabled: true,
        secure_input_watcher_interval: 5000,
        post_inject_delay: 100,
        secure_input_notification: true,
        backend: Auto,
        exclude_default_entries: false,
        show_notifications: true,
        show_icon: true,
        fast_inject: true,
        backspace_delay: 0,
        inject_delay: 0,
        auto_restart: true,
        matches: [
            Match {
                triggers: [
                    ":espanso",
                ],
                content: Text(
                    TextContent {
                        replace: "Hi there!",
                        vars: [],
                        _has_vars: false,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                is_html: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'o',
                        ),
                    ],
                ],
            },
            Match {
                triggers: [
                    ":date",
                ],
                content: Text(
                    TextContent {
                        replace: "{{mydate}}",
                        vars: [
                            MatchVariable {
                                name: "mydate",
                                var_type: "date",
                                params: Mapping {
                                    map: {
                                        String(
                                            "format",
                                        ): String(
                                            "%m/%d/%Y",
                                        ),
                                    },
                                },
                            },
                        ],
                        _has_vars: true,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                is_html: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            'd',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'e',
                        ),
                    ],
                ],
            },
            Match {
                triggers: [
                    ":shell",
                ],
                content: Text(
                    TextContent {
                        replace: "{{output}}",
                        vars: [
                            MatchVariable {
                                name: "output",
                                var_type: "shell",
                                params: Mapping {
                                    map: {
                                        String(
                                            "cmd",
                                        ): String(
                                            "echo Hello from your shell",
                                        ),
                                    },
                                },
                            },
                        ],
                        _has_vars: true,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                is_html: false,
                _trigger_sequences: [
                    [
                        Char(
                            ':',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'h',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'l',
                        ),
                    ],
                ],
            },
            Match {
                triggers: [
                    ",,s",
                ],
                content: Text(
                    TextContent {
                        replace: "source sanalpy/bin/activate",
                        vars: [],
                        _has_vars: false,
                    },
                ),
                word: false,
                passive_only: false,
                propagate_case: false,
                force_clipboard: false,
                is_html: false,
                _trigger_sequences: [
                    [
                        Char(
                            ',',
                        ),
                        Char(
                            ',',
                        ),
                        Char(
                            's',
                        ),
                    ],
                ],
            },
        ],
        global_vars: [],
        modulo_path: None,
        wait_for_modifiers_release: false,
    },
    specific: [],
}

**Comment by Konfekt** [comment]
I suppose this hinges on the keyboard layout. Does this happen when you use, say, a  [US keyboard layout](https://altgr-weur.eu/)?

**Comment by e4e6** [comment]
i dont use US keyboard layout , it is turkish TR keyboard

**Comment by Konfekt** [comment]
I doubt that the change was complete. Anyway, which turkisch layout? The [Q](https://en.wikibooks.org/wiki/Turkish/Computing_in_Turkish) layout? Probably Espanso sends the key code for `i` which on the Q layout produces an `ı`.

**Comment by kemifl** [comment]
I have a similar problem using ubuntu 18.04 with a norwegian keyboard. When espanso is initialized during system startup, it assumes US keyboard layout and some characters are wrong. If I stop it and start it again, then it assumes Norwegian keyboard and all is OK. The strange thing is, that when it is not working properly, even switching to a US keyboard layout doesn't help.

**Comment by e4e6** [comment]
thanks for helpful response @kemilf , i do tried few startup scripts in places like /etc/profile.d but did not work, in the end putting command "espanso restart" to ubuntu startup applications did work as a workaround this problem

![image](https://user-images.githubusercontent.com/73366454/114172998-1b016e00-993f-11eb-9767-52ad24caa67e.png)

**Comment by kemifl** [comment]
Thanks for the workaround!

**Comment by federico-terzi** [comment]
Thank you for the suggestions! Closing in favor if #489

Cheers :)
