### ISSUE TITLE
Enable/disable on mod/alt key listener should ignore other modifiers

### ISSUE THREAD

**Issue by Cybolic** [federico-terzi/espanso#646]
In other words, espanso enable or disables itself when alt+other-modifier is tapped in succession, instead of just when alt is tapped. This interferes with my window manager shortcuts (which use super+mod+ctrl / win+alt+ctrl to not interfere with anything else), so espanso enables and disables itself when I'm moving between windows.

**To reproduce:**
Tap alt+ctrl or alt+shift or alt+win in succession

**What should happen:**
Nothing

**What happens:**
Epanso enables or disables itself (reacts to the double-alt-tap)

**Workaround:**
Change the `toggle_key` in `default.yml` to something not used elsewhere; e.g. `toggle_key: RIGHT_ALT`

**Comment by federico-terzi** [comment]
Hey @Cybolic,

Thank you for the feedback! Good point, I can see how that behavior might be confusing for some people. On one hand, the current behavior for `toggle_key`  it's tricky to change in a way that filters out other modifiers being pressed. The good news is that in the next release (#594), espanso will support also shortcut, so we might introduce a `toggle_shortcut` field that accepts a combination (such as `CTRL+ALT+F2`) and would behave like a regular hotkey (not require the double-tap).

Could this solve your use-case?

Cheers :)

**Comment by Cybolic** [comment]
My current work-around is fine for me, so I don't really need the shortcut functionality.
I do consider this a bug though, not a feature request, as the current implementation doesn't function as described and can interfere with other programs when it really shouldn't.

**Comment by federico-terzi** [comment]
@Cybolic I see, thank you. What operating system are you using?

**Comment by Cybolic** [comment]
I'm running Linux without a desktop environment (xinit with bspwm).

**Comment by federico-terzi** [comment]
Hey,

I just wanted to say that some work is being done regarding this issue #815, so I'm closing this one. Feel free to continue the discussion there!

Cheers :)
