### ISSUE TITLE
There seems to be a minimum time before next trigger

### ISSUE THREAD

**Issue by jpmvferreira** [federico-terzi/espanso#647]
So I was using Espanso and noticed that I couldn't expand two triggers when they were side by side. Then, after using it in a different place I thought it was due to the way that windows behaved, so I recorded the following gif in Facebook Messeger:
![messeger](https://user-images.githubusercontent.com/41581666/114286700-01ece000-9a59-11eb-9908-863b9407e8ea.gif)

As you can see sometimes they expand, sometimes they don't. 

I decided to try in other places but it just got even more inconsistent, until I realized that it was a matter of time, somehow. Here's an example where I trigger one match, start to write something else really fast right after expanding, and you can see that it doesn't expand:
![teste](https://user-images.githubusercontent.com/41581666/114286768-9c4d2380-9a59-11eb-803c-3ab20a7eeaba.gif)

But if I wait just a tiny bit before even typing a different character, I always get the wanted result, which is expanding regardless of how fast I type:
![teste2](https://user-images.githubusercontent.com/41581666/114286776-b1c24d80-9a59-11eb-84fe-7b132909cf67.gif)

This seems to be consistent across all different windows I've tested it, from Firefox to Atom.

**Comment by jpmvferreira** [comment]
I forgot to say my system:
- Manjaro
- Espanso 0.7.3 (Installed from the AUR package espanso-bin)
- Kernel 5.4.108
- xclip 0.13

**Comment by federico-terzi** [comment]
Hey @jpmvferreira,

Thanks for reporting this issue! This seems to be related to #588, so I will close this one :)
With the new version (#594) the situation should improve, hopefully :)

**Comment by jpmvferreira** [comment]
Ah I'm unsure how I missed that, I'll comment saying that it happens on Linux too.
