### ISSUE TITLE
Not replacing triggers at all

### ISSUE THREAD

**Issue by pattyrocks** [federico-terzi/espanso#649]
I am using W10 and through terminal I can edit, reload, restart no problema. However, whenever I type my triggers, nothing happens, no matter which text editor I'm using.

Is there any configuration I'm forgetting perhaps?

**Comment by federico-terzi** [comment]
Hey @pattyrocks,

I'm sorry you experienced this problem! Could you please post the output of `espanso log` here?

Cheers :)

**Comment by pattyrocks** [comment]
Somehow I restarted the PC for the third time and now it's working. Thanks for the reply, I contact again if it happens and I can't fix it :)

**Comment by federico-terzi** [comment]
@pattyrocks Sounds great!
