### ISSUE TITLE
Trigger text doesn't fully delete in Chrome's address bar

### ISSUE THREAD

**Issue by ryinyang** [federico-terzi/espanso#651]
Similar to #248, except that it's occurring in Chrome's address bar. I tried the fix proposed in that thread and although it didn't fix the problem, it did help me understand the cause. Chrome's address bar will try to predict what you're typing by autocompleting. And so when you type something like "\you" in the address bar, Chrome predicts you're looking for "youtube" and so will autofill and highlight "tube." This means that when espanso sends the first backspace keystroke, it's deleting "tube" instead of the "u" in "\you"

### Steps to reproduce: 

1. Create a trigger that Chrome will try to replace. For example:
```
- trigger: "\\you"
  replace: "https://youtube.com"
```
2. Go to Chrome's address bar and trigger the replacement
3. Notice that the backslash is remains even after replacement

**Comment by federico-terzi** [comment]
Hey @ryinyang,

Thanks for reporting this issue! Indeed, your hypothesis is correct, the fact that chrome auto-suggests a completion messes up with the number of backspaces sent by espanso.

Unfortunately, there is no way to solve this problem yet, but it will become trivial once #286 and #556 are implemented. So your best bet is to turn on the notifications for those two and wait :)

Cheers :)
