### ISSUE TITLE
feature: replacing a match by a keyboard shortcut?

### ISSUE THREAD

**Issue by Jiehong** [federico-terzi/espanso#652]
Hi,

I am wondering if a match can be replaced by a keyboard shortcut instead of a text?

Example of usage:

You're in your IDE, and you want to trigger a specific action, like run the unit test. Typing :run could be replaced by entering Shift+F12 for example.

Although, it might make more sense if this could be done in a specific expanso UI instead of inside a text field in the application instead.

Alternatively, a package that could convert typed things to actual shortcuts. For example, using the Emacs syntax, that would give: `:C-t` would trigger `Ctrl + t`, and `C-M-o` would trigger `Ctrl + Alt + o`.

Would something like that even be possible?

**Comment by federico-terzi** [comment]
Hey @Jiehong,

Thank you for the feedback! Indeed, this feature would be very useful and is already planned #383. I'm closing this issue in favor of that one, feel free to continue the discussion there

Cheers :)

**Comment by Jiehong** [comment]
@federico-terzi I think #383 is actually the opposite: it's to trigger espanso text expansion via a keyboard shortcut.

Here this is the opposite.

**Comment by federico-terzi** [comment]
@Jiehong I see, sorry for the misunderstanding! If that's the case, then #556 and #286 should solve your problem once they are implemented :)
