### ISSUE TITLE
On Windows 10, Espanso often freezes after configuration reload

### ISSUE THREAD

**Issue by undecomposed** [federico-terzi/espanso#656]
Hey,

I am using Espanso on both Windows and macOS. On Windows, after saving a change to the configuration file, Espanso would sometimes freeze and won't load the file correctly. The only way out is to kill the process. I have implemented a workflow where I am adding new keywords using Powershell, and after a keyword is added I stop Espanso, kill the process, then start it again. Probably not ideal.

Is there a way to enable debug logging so maybe I can discover what causes the freeze?

**Comment by federico-terzi** [comment]
Hey @undecomposed,

Thanks for reporting this issue! Could you please check in the task manager how many espanso processes do you see running after it freezes?

Cheers :)

**Comment by undecomposed** [comment]
@federico-terzi I often see two processes there. Is that what you're looking for?

**Comment by federico-terzi** [comment]
@undecomposed That's good, thank you. Two processes are expected, so nothing to worry about. Given that espanso is being rewritten as part of #594, perhaps the new version will fix this problem out of the box. Let's wait and see :)

**Comment by undecomposed** [comment]
@federico-terzi thank you! As an additional note, I have created a Powershell function to make it easier for me to add new values, and it actually works well! I don't have Espanso freezing so far, meaning that a note in one of the tickets mentioned "atomic saves" by some text editors may be valid here - I did seem to experience some issues when creating new items with Notepad++.

Thank you!
