### ISSUE TITLE
On Windows, expanding after tab triggers after the tab rather than before it

### ISSUE THREAD

**Issue by undecomposed** [federico-terzi/espanso#657]
Steps to reproduce:

1. Open Microsoft Outlook.
2. Open a new email.
3. Click Subject line.
4. Enter an abbreviation.
5. Press tab.

Expected result:
Espanso expands the abbreviation on the Subject line and moves to the body.

Actual result:
Espanso leaves the abbreviation in place, moves to the email body, expands the abbreviation, and then enters the terminative Tab.

**Comment by federico-terzi** [comment]
Hey @undecomposed,

I'm sorry you experienced this problem! Could you please post a recording of that happening?

Cheers :)

**Comment by undecomposed** [comment]
https://user-images.githubusercontent.com/40839400/116855523-32f8a480-ac02-11eb-9a15-7fabc3b7dbb2.mp4

@federico-terzi here you go! Sorry, I should have thought of this before.

**Comment by federico-terzi** [comment]
@undecomposed Thank you! 

> Espanso expands the abbreviation on the Subject line and moves to the body.

Unfortunately, there is no way for espanso to do what you would like to. By the time you press Tab, Outlook already moved to the next field, and espanso cannot "go back" to the previous field. Once #286 and #556 will be implemented, you will be able to work around this problem, but until then, you won't be able to use Tab unfortunately :)

**Comment by undecomposed** [comment]
@federico-terzi interesting! Thank you for letting me know. For reference, I have uploaded an example of AutoHotKey doing this successfully, though I can't say I understand how they manage to achieve this.

Thank you for your work!

https://user-images.githubusercontent.com/40839400/116994303-344cce80-ace1-11eb-8392-4c6c29b9ef46.mp4

**Comment by federico-terzi** [comment]
@undecomposed AutoHotKey is indeed a great piece of software :) The problem here is that in order to support many platforms, espanso had to adopt a different architecture that makes supporting the Tab key very problematic... Perhaps in the future it will become possible, but it's definitely not a priority at the moment :)

**Comment by jfirwin** [comment]
Hi, I'm on MacOS and I'm trying to think of a way that this could be done. Would it be possible to run the trigger in the body and have espanso set the a subject line to the clipboard? I know this would interfere with people who are using the clipboard option as their backend.

**Comment by federico-terzi** [comment]
@jfirwin Thank you for the feedback! Once #556 is implemented, these things will become possible OOTB. Until then, you can either create a custom script (for example, with Python and pyautogui), but that won't be particularly clean :)
