### ISSUE TITLE
On Windows, Espanso can't trigger multiple expansions in a row

### ISSUE THREAD

**Issue by undecomposed** [federico-terzi/espanso#658]
Hey,

Wanted to report the issue I encountered with Espanso on Windows. I am attaching the video of the issue. It appears Espanso waits a bit between expansions.  This is evident both by waiting between the two abbreviations, but also by Espanso sometimes expanding **;admin** into **;adminute**, because I have a separate expansions of **min** to **minute**.

https://user-images.githubusercontent.com/40839400/116654827-9da3a900-a992-11eb-9e0a-f79ec667333d.mp4

**Comment by federico-terzi** [comment]
Hey,

Thanks for reporting this issue! This is a known bug, see #588. The next major version should solve this problem as well!
Closing the issue in favor of the other one

Cheers :)
