### ISSUE TITLE
Using forms, it would be great to avoid pressing 'ctrl + enter' and press just 'enter' to expand text

### ISSUE THREAD

**Issue by brunochaina** [federico-terzi/espanso#659]
If the form is not multi-line, it would really improve the insertion speed if I'm just able to press enter (OS: Windows in my case)

**Comment by federico-terzi** [comment]
Hey @brunochaina.

Thank you for the feedback! I'll mark it as a feature request 👍

Cheers :)

**Comment by federico-terzi** [comment]
Hey,

I'm closing this issue in favor of #709, as they cover the same problem

Cheers :)
