### ISSUE TITLE
Typo in espanso docs

### ISSUE THREAD

**Issue by es183923** [federico-terzi/espanso#662]
link: [https://espanso.org/docs/matches/](https://espanso.org/docs/matches/)
> In this case, typing `:quote` will expand randomly to one of the tree quotes.

should be

> In this case, typing `:quote` will expand randomly to one of the three quotes.

**Comment by federico-terzi** [comment]
Hey @es183923,

Thanks for your help! I'm tagging as a documentation todo

Cheers :)

**Comment by tantan31418** [comment]
Hi, I've fixed the typo and submitted PR in website repo, please review.

**Comment by federico-terzi** [comment]
@tantan31418 Looks great, thank you!
