### ISSUE TITLE
Espanso CLI does not work on my machine anymore. The daemon can not be started.

### ISSUE THREAD

**Issue by Lyokolux** [federico-terzi/espanso#664]
Every command of the CLI (except `espanso edit`) returns the following error:
>ERROR: no action specified for match ::, please specify either 'replace', 'markdown', 'html', image_path' or 'form'

(coming from the file ` espanso/src/matcher/mod.rs ` l.236 as far as I see)

Thus, I can not paste the result of the `epanso log`  command.

Here some infos about my system that may be useful:
espanso 0.7.3
>Operating System: Ubuntu 20.10
Kernel: Linux 5.8.0-50-generic
Architecture: x86-64

**Comment by Lyokolux** [comment]
I have checked and it was an error in my configuration. :+1:  Thanks a lot !

**Comment by federico-terzi** [comment]
Glad to hear that! Closing the issue :)
