### ISSUE TITLE
Espanso may have a problem with repeat characters.  Or maybe Firefox.  Or maybe a specific website.

### ISSUE THREAD

**Issue by deezznutz** [federico-terzi/espanso#668]
On inmotionhosting.com's login page (https://secure1.inmotionhosting.com/index/login), I have a username that has three repeated characters.  When I use espanso to enter my username, some of the time (one in five?), one of the three characters gets dropped. It does it much less often (one in twenty or so) if I change fast_inject to false, but it does still do it.

I suppose this could be a Firefox or InmotionHosting issue, but I thought I'd start here.

**Comment by federico-terzi** [comment]
Hey @deezznutz,

I'm sorry you experienced this problem! Are you on Linux? If that's the case, you will need to apply this patch for now: https://github.com/federico-terzi/espanso/issues/248

Once #310 is implemented, this won't be necessary anymore :) Feel free to reopen the issue if that doesn't solve your problem

Cheers :)
