### ISSUE TITLE
[bug] espanso cmd enable / enable / toggle always return exit code 1

### ISSUE THREAD

**Issue by jaklan** [federico-terzi/espanso#670]
As in title:
```console
❯ espanso cmd enable
❯ echo $?
1
```
The result doesn't depend on the current status of `espanso`. The same for `espanso cmd disable`, `espanso cmd toggle`. 

That's why when using Raycast scripts for `espanso`:
https://github.com/raycast/script-commands/tree/master/commands#espanso
we get:
![image](https://user-images.githubusercontent.com/24907857/118352748-59ec9a00-b563-11eb-9122-e7234908e7c0.png)

**Comment by federico-terzi** [comment]
Hey @jaklan,

Thanks for reporting this issue! This seems like a bug, I'll investigate :)

Cheers :)

**Comment by federico-terzi** [comment]
Hey @jaklan,

The next version 2.0.5-alpha will include a fix for this problem, thank you for the help!
I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)

Cheers :)
