### ISSUE TITLE
[Help Needed] Use expansions inside rofi

### ISSUE THREAD

**Issue by ivanddm** [federico-terzi/espanso#671]
This is definitely not a bug but I'm just trying to get some help on how to get this to work.

Basically, I want to use espanso expansions inside rofi -dmenu. I have two machines running Arch with rofi-bin installed. In one of them, expansions work without issues inside rofi, that is, I trigger rofi -dmenu, type, e.g., :date and then the current date is expanded as expected. However, in another machine using the same rofi configuration and same espanso snippets, if I type :date, then the current date gets expanded, not in rofi but in the application that was focused when I triggered rofi in the first place, say a terminal instance, which is very weird. If I open rofi as a normal window expansions work without issues.

I really don't know what is causing expansions to work in one machine and not in the other. I have looked for solutions but without luck. Any ideas on how to get it to work regardless of the machine would be greatly appreciated.

**Comment by federico-terzi** [comment]
Hey,

I'm really not sure about what could be causing it, but my first question would be: do both machines use the same OS and desktop environemnt?

Cheers :)

**Comment by ivanddm** [comment]
yes, both of them use Arch and the same desktop environment (dwm). Thanks in any case, I think I will ask this question in the rofi repo as well.

Keep up the good work. I really like espanso. Cheers :)

**Comment by federico-terzi** [comment]
@ivanddm Interesting, thank you :)
