### ISSUE TITLE
Espanso not working correctly on Ubuntu 21.04 Hirsute Hippo

### ISSUE THREAD

**Issue by backward-crazy-mage-puppy-36** [federico-terzi/espanso#672]
I have installed espanso from both snap and deb packages and tried all of the following things on both installations.

Problem Summary: espanso intstalls. Espanso runs. Espanso works only in chromium based browser (works in Brave, Edge, Chrome not in Firefox) address bar and string form fields (not text form fields). Espanso does not work in the Terminal, Sublime Text, default text editor, LibreOffice Writer or any other app (tried a few such as rythmbox search fields).

Here are the espanso configurations and debugging steps that I have tried
filter_class: "Various App Names"
backend: Clipboard || Inject || Auto
paste_shortcut: CtrlShiftV || CtrlV
auto_restart: true || false
enable_passive: true || false
use_system_agent: true || false
force_clipboard: true || false
I have restarted espanso after each config change and tested and gotten the same results. 

espanso detect returns the following:
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)

**Comment by federico-terzi** [comment]
Hey,

I'm sorry you experienced this issue! My first guess is that Ubuntu 21 uses Wayland by default, which is not currently supported by espanso (although experimental support is coming in the next release). I would first check if this hypothesis is true, and if so, select X11 from the gear icon on the login screen to keep using espanso.

Let me know if that helps

Cheers :)

**Comment by backward-crazy-mage-puppy-36** [comment]
@federico-terzi This helped. Everything Working for X11. Is there a issue tracking wayland support? I would like to follow it to stay updated.

**Comment by federico-terzi** [comment]
@backward-crazy-mage-puppy-36 Sure! Here is the thread: #287 

Cheers :)
