### ISSUE TITLE
After some time, espanso stops working os macOS

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#674]
Since version 0.73 it stops working after a few days and when I restart it I get the message 

% espanso start
WARNING: An application is currently using SecureInput and might prevent espanso from working correctly.

APP: loginwindow
PROC: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow

Please close it or disable SecureInput for that application (most apps that use it have a
setting to disable it).
Until then, espanso might not work as expected.
Daemon started correctly!

To make ik work again I have to reboot my Mac.

**Comment by federico-terzi** [comment]
Hey @freebrowser1,

I'm sorry you experienced this problem! This is a known problem on macOS, and I'm not yet sure how we could solve it. Are you using 1Password?

Cheers :)

**Comment by freebrowser1** [comment]
No, but I am using KeepassDroid for macOS but that does nothing with keyboards.
But I do use Karabiner (pqrs.org) which intercepts keystrokes to swap Ctrl and Cmd keys when I am in a Windows or Linux VM or in a Citrix session. In such sessions Espanso does not work properly (which can be expected), but that is not this issue.
It is about using Espanso using keystrokes in native macOS apps more than a few days after a reboot. Before that time, espanso works as expected.

**Comment by federico-terzi** [comment]
@freebrowser1 I see, thank you for the feedback! What version of macOS are you running?

**Comment by freebrowser1** [comment]
The latest, Big Sur 10.16.3.

**Comment by federico-terzi** [comment]
Interesting, thank you

> No, but I am using KeepassDroid for macOS but that does nothing with keyboards.

Do you keep that application running? Do you see a Keepass icon on the status bar?

Password managers interfere with espanso on macOS because they activate a macOS feature known as "Secure Input", which prevents any text expander from working correctly.

The next time this happens, could you please try closing Keepass if it's running?

Cheers :)

**Comment by freebrowser1** [comment]
I'll try when it happens again.
But most of the time I've keepass open (I see it in the Dock) but espanso works normally.
When it does occur again, I'll close keepass.

**Comment by federico-terzi** [comment]
@freebrowser1 Thanks! :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)

**Comment by wxmiked** [comment]
I realize this is a really old thread. But the second comment about **using 1Password** was exactly what the problem was. Espanso had stopped working for two days. I tried restarting many times. But the second I closed 1Password it started working again.
