### ISSUE TITLE
Snap asks to install other software? 

### ISSUE THREAD

**Issue by jlopez777** [federico-terzi/espanso#677]
GOAL: 

Install and run via snap

Details: 

When installing by snap on Pop OS 20.10 I get the following  request to install. See below. 

I thought the purpose of having snap is to bake in any dependencies to make it run no? 

![image](https://user-images.githubusercontent.com/24819585/119372135-fb22d100-bc84-11eb-9000-15dce462ed9c.png)

**Comment by federico-terzi** [comment]
Hey @jlopez777,

Thank you for the feedback! This is a good point, we could include `xclip` in the snap package indeed.
The good news is that version 2 (#594) won't need xclip anymore, so this won't be a problem anymore

I'm closing the issue as this will solve itself with the new version

Cheers :)

**Comment by jlopez777** [comment]
Makes sense. Thanks
