### ISSUE TITLE
How can I create modular files?

### ISSUE THREAD

**Issue by IgorGee** [federico-terzi/espanso#678]
I'm able to create snippets fine in the `default.yml` file. But I'd like to better organize my snippets by having one file per domain:

e.g.:
* `default.yml`
* `sql.yml`
* `rust.yml`
* `emails.yml`

**Comment by federico-terzi** [comment]
Hey @IgorGee,

Good question! Please take a look at this section: https://espanso.org/docs/configuration/#organizing-matches

Keep in mind that the new release #594 will completely change the way multiple match files are handled, so don't get too attached to this method :)
The new version will also come with an automatic migration tool, so you can start experimenting with the current approach

Cheers :)
