### ISSUE TITLE
Add espanso to AUR

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#68]
Some good starting points would be these projects:
mdcat, alacritty and ugdb

**Comment by wezm** [comment]
Someone has added it: https://aur.archlinux.org/packages/espanso/

**Comment by federico-terzi** [comment]
Wow, that's amazing! Thank you very much for letting me know

**Comment by Scrumplex** [comment]
I added a few variations of the package to the AUR.

This now includes:
 - [espanso](https://aur.archlinux.org/packages/espanso/)<sup>AUR</sup> - Builds from latest (stable) release
 - [espanso-git](https://aur.archlinux.org/packages/espanso-git/)<sup>AUR</sup> - Builds from latest commit (in master branch)
 - [espanso-bin](https://aur.archlinux.org/packages/espanso-bin/)<sup>AUR</sup> - Downloads latest (stable) prebuilt release

**Comment by federico-terzi** [comment]
This is wonderful, thank you very much @Scrumplex 
In the next few days, I will update the documentation for Arch/Manjaro users. 
In your opinion, which of these 3 options should be the recommended way to install espanso?

**Comment by Scrumplex** [comment]
> In your opinion, which of these 3 options should be the recommended way to install espanso?

I think you should generally recommend using espanso-bin, as you recommend your pre-compiled binaries for other platforms, too, but should definitely mention, that there are also `espanso` and `espanso-git`, which may be preffered methods of installing, as these compile on the user's machine.

**Comment by federico-terzi** [comment]
All right, thank you very much @Scrumplex, in the next few days I will update the website :)

**Comment by federico-terzi** [comment]
Hi @Scrumplex,
I'm in the process of updating the docs and I don't really know what should be the recommended procedure to install espanso from AUR.
I'm not an Arch user and I thought it would be easy, but I found many different solutions online and I don't know which one is the best.
Could you help me with the sequence of commands to install espanso from AUR?

Sorry to bother you :)

**Comment by wezm** [comment]
The only officially supported way to build and install AUR packages is with the `makepkg` tool. Many people use AUR helpers but because they are not officially supported and there's a lot of them I'd recommend documenting the use of `makepkg`, which looks like this:

## Installing on Arch Linux and Derivatives

Espanso is available in the AUR. Install the pre-compiled binary as follows:

    git clone https://aur.archlinux.org/espanso-bin.git
    cd espanso-bin
    makepkg -si

If you would prefer to build from source there is also [espanso](https://aur.archlinux.org/packages/espanso/) and [espanso-git](https://aur.archlinux.org/packages/espanso-git/).

**Comment by federico-terzi** [comment]
Hi @wezm,
Thank you very much for your help, I will update the documentation with your suggestion in the next few days.

**Comment by federico-terzi** [comment]
I added the instructions on the official documentation: https://espanso.org/install/linux/#installing-from-aur
