### ISSUE TITLE
Replacement works not correctly on windows 10

### ISSUE THREAD

**Issue by xmu714** [federico-terzi/espanso#681]
Thanks for developing such awesome application! It works perfectly on Linux.
But on windows, it is very strange that **the replacement shows twice**, and all of them are shown within **one line**.

In Notepad, I type in ":espanso", got "Hi thhi there1", then I hit Enter to line 2, and typed in the same thing, another "Hi thhi there1" went to line 1 following the former one, 

Here is my screenshot:

![image](https://user-images.githubusercontent.com/25820665/120129482-a20feb80-c1f6-11eb-8fc0-e362bd7cbd9b.png)

**Comment by federico-terzi** [comment]
Hey @xmu714,

I'm sorry you experienced this problem! Could you please see if this post solves your problem?: https://github.com/federico-terzi/espanso/issues/673

There is a bug in the current version that sometimes cause this problem, but we are working on a fix in version 2 #594 
Feel free to reopen the issue if this doesn't solve your problem

Cheers :)
