### ISSUE TITLE
Problem on windows 10

### ISSUE THREAD

**Issue by xmu714** [federico-terzi/espanso#682]
Hi, a few hours ago I post an issue #681 , and then I followed the method of #673 。
On task manager, there are **exactly 2 process** named of espanso, no more sub-process:

![image](https://user-images.githubusercontent.com/25820665/120160742-28ddbc00-c229-11eb-8bb2-20147b59fbf8.png)

I tried terminate them through task manager / right click the tray button and exit, but the issue remains unchanged after I reopened espanso and type in ":espanso".

Is there any way I can try to solve that?

**Comment by xmu714** [comment]
Update: I found out that the main reason is that my windows 10 is a **VM guest** running on manjaro host system, in which I have espanso installed. So when I type in the trigger, **replacement on host and guest took place at the same time**.

Is there any way to **block VM process in espanso replacement** on my LInux host? I want the two works independently on host and VM guest.
Now I can only press double ALT to disable espanso before I use VM, and enable it after VM shutdown.

**Comment by federico-terzi** [comment]
@xmu714 Thanks for sharing! Now that I think about it, I've been hurt by this behavior as well in the past...

> Is there any way to block VM process in espanso replacement on my LInux host? I want the two works independently on host and VM guest.

There could be a way, please see try to follow these instructions: https://espanso.org/docs/configuration/#application-specific-configurations

In short, you should create an app-specific config on manjaro for your VM window with the option `enable_active: false`, which should disable espanso only when using the VM.

Let me know if that helps

**Comment by xmu714** [comment]
Hi, following your instructions, I created a file `vm.yml`:

```yaml
name: vm
enable_active: false
filter_class: "Virt-manager"
```
After reloading the config, everything worked perfectly! 

Thanks for your help!
