### ISSUE TITLE
Is it possible to have "modes" to deal with switching languages?

### ISSUE THREAD

**Issue by SpecialCharacter** [federico-terzi/espanso#687]
Completely new to this, but it could just be what I'm searching for!

The thing is, I often switch languages. Is it possible to have "modes"?
E.g. ae --> ä (German mode), ae –> æ (Danish mode).
Mode could be changed by Win-G/Win-D.

**Comment by federico-terzi** [comment]
Hey @SpecialCharacter,

Thank you for the feedback! This is not currently possible, but it's planned: #462
I'm closing this issue in favor of the other one, feel free to add any other comment there!

Cheers :)
