### ISSUE TITLE
Relocate config files

### ISSUE THREAD

**Issue by danraymond** [federico-terzi/espanso#688]
It would be nice to be completely portable. Is it possible to have espanso config etc files in its actual folder. I keep it in a separate on my D: drive, but all config and other data is somewhere under user/roaming or use/local.

Can the configs be moved?

**Comment by federico-terzi** [comment]
Hey @danraymond,

Thank you for the feedback! This is not currently possible, but the new version #594 will come with this feature out of the box!
See also this issue #623 
I'm closing this issue in favor of the other one, feel free to add any other comment there!

Cheers :)
