### ISSUE TITLE
Question: how to ignore espanso in certain apps ?

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#690]
Espanso has a well-documented feature which allows custom triggers per app (window title or app identifier ot path to binary), but as far as I know there is no way to ignore espanso completely in certain apps.

As the shortcuts don't work properly in e.g. a Virtual box VM session or in a Citrix session, I want to ignore espanso in VirtualBox or Citrix and in the case of VB, install espanso in the VM itself natively.

Is there a way to ignore espanso in certain apps completely ?

**Comment by federico-terzi** [comment]
Hey @freebrowser1,

You could set up an [app-specific configuration](https://espanso.org/docs/configuration/#application-specific-configurations) and then add this option:

```
enable_active: false
```

This will prevent espanso from working in those apps :)

Cheers :)

**Comment by pbek** [comment]
Note: Page went to https://espanso.org/docs/configuration/app-specific-configurations/.

**Comment by pbek** [comment]
@freebrowser1, were you ever able to fix the issue in Virtual Box? I didn't find a working way to disable Espanso in the VM Window, so that only the Espanso in the client VM is reacting on the triggers, and not both the host and client.

**Comment by pbek** [comment]
For future reference: Under Linux, I used a `filter_class` of `VirtualBox Machine` in the end.

**Comment by freebrowser1** [comment]
> @freebrowser1, were you ever able to fix the issue in Virtual Box? I didn't find a working way to disable Espanso in the VM Window, so that only the Espanso in the client VM is reacting on the triggers, and not both the host and client.
I use this in a file espanso/match/utm.yml (basename can be any):
````
filter_class: com.utmapp.UTM 
enable: false
````
I use UTM but you can replace `com.utmapp.UTM` by `com.oracle.virtualbox` (I don't know the exact name).
