### ISSUE TITLE
Support external package installation from GitLab.com

### ISSUE THREAD

**Issue by katrinleinweber** [federico-terzi/espanso#695]
As a smaller iteration compared to https://github.com/federico-terzi/espanso/issues/253, would it be feasible to insert a URL check into the [.zip download logic](https://github.com/federico-terzi/espanso/blame/v0.7.3/src/package/zip.rs#L42) to branch off into a `gitlab.com`-specific download?

[Something like this](https://github.com/federico-terzi/espanso/compare/master...katrinleinweber:695-investigate-gitlab-support)?

**Comment by federico-terzi** [comment]
Hey @katrinleinweber,

Thank you for the feedback! Yes, I think it could be a good idea to support also non-github installation methods.
Given that the package system is being rewritten, this will probably be delayed for a while, but I'll add it to the roadmap!

Cheers :)

**Comment by federico-terzi** [comment]
Hey @katrinleinweber,

The new version (v2) supports both private packages and public ones on GitLab: https://espanso.org/docs/next/packages/external-packages/

The documentation is not 100% complete yet, but I'm working on it :)

Thanks for the help!
