### ISSUE TITLE
espanso stops again on macos

### ISSUE THREAD

**Issue by freebrowser1** [federico-terzi/espanso#696]
My previous ticket is gone so I open a new one.

Same issue: `espanso log`

````18:59:51 [ INFO] Created Modulo APP stub at: "/Users/user/Library/Application Support/espanso/Modulo.app/Contents/MacOS/modulo"
18:59:51 [ INFO] worker is running!
18:59:51 [ INFO] SecureInput has been acquired by loginwindow, preventing espanso from working correctly. Full path: /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
18:59:51 [ INFO] watching for changes in path: /Users/user/Library/Preferences/espanso
````
I don't have Keypass or other password managers running.
But what is 'loginwindow' ? How can I stop that app ?
The only way to get around this is rebooting.

**Comment by federico-terzi** [comment]
Hey @freebrowser1,

I'm sorry you experienced this problem! This is a known bug, and I'm not sure how we can solve it yet.
From my research, I've discovered that if an application activates SecureInput while in the background (for example the LastPass extension activating on Chrome while the browser is not focused), then "loginwindow" is displayed instead of Chrome. Unfortunately, as far as I can tell, all text expanders suffer from this problem on macOS.

The next time this happens, try to close all applications  (especially the browsers) one by one to see if espanso gets enabled again, and if so, please let us know what you discover :)

Cheers :)

**Comment by jjorissen52** [comment]
This bug is present is other auto-expanders like Keyboard Maestro as well. One workaround is to lock (cmd+ctrl+q) and unlock your computer. This works for me 100% of the time.

**Comment by federico-terzi** [comment]
@jjorissen52 Thanks for sharing!

**Comment by freebrowser1** [comment]
I'll try when espanso is disabled next time.

**Comment by tnorthcutt** [comment]
This happens to me too, but so far I've been able to click enable in the toolbar menu, or disable and then enable. Which is great because the other expander I use (aText) does not provide this option – or at least it doesn't fix the problem.

**Comment by federico-terzi** [comment]
@tnorthcutt That's interesting, as enabling/disabling espanso shouldn't have any effect on secure input :)

**Comment by mbaierl** [comment]
> This bug is present is other auto-expanders like Keyboard Maestro as well. One workaround is to lock (cmd+ctrl+q) and unlock your computer. This works for me 100% of the time when it happens to Keyboard Maestro. I have not used espanso yet so I cannot comment on its effectiveness there.

Yes, same for me - locking and logging in again fixes the issue all the time.

**Comment by chenlianggu** [comment]
confirming LOCKING and re-login is a valid workaround on OSX Catalina 10.15.7

**Comment by jmhammond** [comment]
> This happens to me too, but so far I've been able to click enable in the toolbar menu, or disable and then enable. Which is great because the other expander I use (aText) does not provide this option – or at least it doesn't fix the problem.

This has been my solution as well. 

Glad to learn that there's an existing reason why espanso keeps getting disabled.

**Comment by federico-terzi** [comment]
Hey guys,

I've written a section about this on the docs (relative to the v2), which hopefully will explain the problem and some possible workarounds https://espanso.org/docs/next/troubleshooting/secure-input/

Cheers :)
