### ISSUE TITLE
Question: where are packages installed?

### ISSUE THREAD

**Issue by ntjess** [federico-terzi/espanso#700]
The documentation on packages and getting started doesn't seem to mention where packages are installed. If I run

`espanso install espanso-latex`,

where will the files be located on my computer? I checked `C:\Users\<user>\AppData\Roaming\espanso` since this was mentioned [here](https://espanso.org/docs/get-started/#configuration), but there are no files present other than the default. I recommend including this information at least on the [Packages documentation](https://espanso.org/docs/packages/) if possible.

Thanks!

**Comment by federico-terzi** [comment]
Hey @ntjess,

Thank you for the feedback! You can run `espanso path` to see where espanso is saving your packages :)

Cheers :)
