### ISSUE TITLE
Donate via Paypal not accepting payment from India

### ISSUE THREAD

**Issue by the-shank** [federico-terzi/espanso#703]
Hello,

When trying to donate via PayPal, I get the following message:

![image](https://user-images.githubusercontent.com/546476/124346391-2c83aa80-dbfc-11eb-9630-2310bb5738b0.png)

**Comment by federico-terzi** [comment]
Hey @the-shank,

I really appreciate your kindness and I'm sorry you experienced this problem! Unfortunately, this seems to be a PayPal restriction over which I don't have any control: https://stackoverflow.com/a/17750720/10850333
In the future, I'll research other ways to support development (such as a pay-what-you-want download page) which will also be available in India, but for now, we'll have to pass on this one :)

**Comment by the-shank** [comment]
Thanks for the quick response @federico-terzi and thanks for creating this wonderful tool!
It is strange that I am able to donate to some other projects through paypal. Maybe they dont make it as a "donation" ¯\_(ツ)_/¯

PS: the shrug symbol above is using the shruggie package :)

**Comment by federico-terzi** [comment]
> Thanks for the quick response @federico-terzi and thanks for creating this wonderful tool!
> It is strange that I am able to donate to some other projects through paypal. Maybe they dont make it as a "donation" ¯_(ツ)_/¯

Thank you for the kind words! Yes, I guess there are ways to accept the donation by using the "pay for a service" option in PayPal, but given that supporters don't get anything in return (except for my gratitude! :) ), I prefer to keep it as it is :)

> PS: the shrug symbol above is using the shruggie package :)

Great choice ¯\_(ツ)_/¯
