### ISSUE TITLE
Submit forms by just pressing Enter

### ISSUE THREAD

**Issue by yosamshiyam** [federico-terzi/espanso#709]
One problem I'm having is having to press control+enter in order to finally paste (that is, to get out of the pop up window when using forms). it'd be great if one just had to press enter. Unless there's a way to do this already.

**Comment by federico-terzi** [comment]
Hey,
Thank you for the feedback! We didn't support this previously as it could conflict with a multiline form field (in which pressing enter should add a new line, not submit).
Given that many people have requested this feature, we'll think about a way to make those two items coexist.

Cheers :)

**Comment by yosamshiyam** [comment]
I think multiline form field should be done with ctrl+enter, and single line form field, just enter.  just seems natural as one builds on the other

**Comment by federico-terzi** [comment]
Hey guys,

The next version (v2.0.5-alpha) will include a fix for this problem, in particular:

* You can now submit by just using Enter on most controls
* If a control requires the Enter key (such as multiline text fields), you can submit with Ctrl+Enter.
* Forms now include a help text at the bottom

![enter forms](https://user-images.githubusercontent.com/20475953/139729253-9b3a45a0-6a43-4f28-9e78-5d4734efa5bf.gif)

Thanks for your help :)

**Comment by yosamshiyam** [comment]
cool, look forward!

**Comment by federico-terzi** [comment]
Hey,

I'm publishing a fix in the upcoming v2.0.5-alpha release, thank you for the help!

Cheers :)
