### ISSUE TITLE
Window where Cursor is

### ISSUE THREAD

**Issue by yosamshiyam** [federico-terzi/espanso#711]
When the pop-up window comes up when usings the forms module, it would be nice if the window popped up wherever the cursor was, so that the experienced were streamlined at one's sight suddenly doesn't have to shift

**Comment by federico-terzi** [comment]
Hey @yosamshiyam,

Thank you for the feedback! Unfortunately, as much as I would like to add this feature, from my research there is no robust cross-platform way to detect where the cursor is located on the screen. Feel free to reopen the issue if you find a way!

Cheers :)
