### ISSUE TITLE
Regex triggers

### ISSUE THREAD

**Issue by nudefireninja** [federico-terzi/espanso#717]
### Feature request

It would be cool if you could use wildcards or regular expressions in triggers.

An example of what that could be used for: type 1/4` and it gets replaced with the fraction ¹⁄₄ (this would work for any number in the denominator and numerator)

The replacement could be done by a custom script but it needs pattern matching support in the trigger.

**Comment by federico-terzi** [comment]
Hey @nudefireninja,

Thank you for the feedback! This is coming in the next release, so stay tuned :) See #594 

Cheers :)

**Comment by nudefireninja** [comment]
Epic!
