### ISSUE TITLE
espanso not running

### ISSUE THREAD

**Issue by eexil** [federico-terzi/espanso#720]
Yesterday there was some updates on my manjaro xcfe and today espanso is not running. 
So I ran
 `espanso status` 
and the reply was
`/var/lib/snapd/snap/espanso/91/snap/command-chain/snapcraft-runner: line 3: /var/lib/snapd/snap/espanso/91/bin/espanso: No such file or directory`

But if I go to the directory I can see that the directory is there. 

Snap version is:
snap     2.51.3-2
snapd    2.51.3-2
series   16
manjaro  -
kernel   5.10.53-1-MANJARO
 
Any ideas?

**Comment by eexil** [comment]
I reinstalled using the instructions on snapcraft.io and now it works again!

One happy camper!

**Comment by federico-terzi** [comment]
Hey @eexil,

I'm sorry you experienced this problem! Indeed, reinstalling is a good option in this case

Cheers :)
