### ISSUE TITLE
Feature Idea: Dynamic matches

### ISSUE THREAD

**Issue by G4bbix** [federico-terzi/espanso#724]
Dear Federico

Recently I wanted to create a dynamic match that would enable me to execute a nslookup. This would need 2 additonal features:
1) Dynamic matches would have to be possible. To give an example ":ns (.*)" would have to match ":ns espanso.com"
2) Regular Expression (.*) would have to be able to be passed into the command following trigger.

What do you think of that?

Cheers G4bbix

**Comment by federico-terzi** [comment]
Hey @G4bbix,

Thank you for the feedback! This is coming in the next release :) I will be known as Regex triggers #594 

Cheers :)
