### ISSUE TITLE
after removal of espanso  ... still it's service tries to start

### ISSUE THREAD

**Issue by abuakram** [federico-terzi/espanso#727]
Hi Federico,

I removed espanso since I hardly need it... 
But since then it keeps trying to start a service ... 
I also noticed that hide.me. cli is trying the same 
I run Ubuntu 21.04 

And here is what I get when running journalctl:  

`Aug 06 03:03:21 *** systemd[1]: hide.me@SERVER.service: Scheduled restart job, restart counter is at 2486. 
Aug 06 03:03:21 *** systemd[1]: Stopped Hide.me CLI connection to SERVER.
Aug 06 03:03:21 *** systemd[1]: Starting Hide.me CLI connection to SERVER.
Aug 06 03:03:22 *** hide.me[159833]: Main: [ERR] No Access-Token available
Aug 06 03:03:22 *** systemd[1]: hide.me@SERVER.service: Failed with result 'protocol'. 
Aug 06 03:03:22 *** systemd[1]: Failed to start Hide.me CLI connection to SERVER. 
Aug 06 03:03:22 *** systemd[4419]: espanso.service: Scheduled restart job, restart counter is at 4176.
Aug 06 03:03:22 *** systemd[4419]: Stopped espanso daemon.
Aug 06 03:03:22 *** systemd[4419]: Started espanso daemon.
Aug 06 03:03:22 *** systemd[159840]: espanso.service: Failed to locate executable /usr/bin/espanso: No such file or directory
Aug 06 03:03:22 *** systemd[159840]: espanso.service: Failed at step EXEC spawning /usr/bin/espanso: No such file or directory
Aug 06 03:03:22 *** systemd[4419]: espanso.service: Main process exited, code=exited, status=203/EXEC
Aug 06 03:03:22 *** systemd[4419]: espanso.service: Failed with result 'exit-code'.
Aug 06 03:03:25 *** systemd[4419]: espanso.service: Scheduled restart job, restart counter is at 4177.
Aug 06 03:03:25 *** systemd[4419]: Stopped espanso daemon.
Aug 06 03:03:25 *** systemd[4419]: Started espanso daemon.
Aug 06 03:03:25 *** systemd[159844]: espanso.service: Failed to locate executable /usr/bin/espanso: No such file or directory
Aug 06 03:03:25 *** systemd[159844]: espanso.service: Failed at step EXEC spawning /usr/bin/espanso: No such file or directory
Aug 06 03:03:25 *** systemd[4419]: espanso.service: Main process exited, code=exited, status=203/EXEC
Aug 06 03:03:25 *** systemd[4419]: espanso.service: Failed with result 'exit-code'.`

**Comment by federico-terzi** [comment]
Hey @abuakram,

I'm sorry you experienced this problem! Please open a terminal and disable the espanso service with

```
systemctl --user disable espanso.service
```

Let me know if that helps

Cheers :)
