### ISSUE TITLE
Replacements not working since installing macOS Monterey Beta

### ISSUE THREAD

**Issue by bradleysawler** [federico-terzi/espanso#730]
I noticed that my triggers were not activating with the newly installed macOS Monterey Version 12.0 Beta (21A5294g). 

I removed espanso from Accessibility, then `espanso register` and toggled it back on. I `espanso restart` but still nothing. No errors were found in `espanso log`. I'm hoping it has to do with the Beta install. 

```bash
09:23:18 [ INFO] espanso version 0.7.3
09:23:18 [ INFO] using config path: /Users/bgs/Library/Preferences/espanso
09:23:18 [ INFO] using package path: /Users/bgs/Library/Application Support/espanso/packages
09:23:18 [ INFO] spawning worker process...
09:23:18 [ INFO] Binded to IPC unix socket: /Users/bgs/Library/Application Support/espanso/espanso.sock
09:23:18 [ INFO] initializing worker process...
09:23:18 [ INFO] Status icon already initialized, skipping.
09:23:18 [ INFO] Status icon (disabled) already initialized, skipping.
09:23:18 [ INFO] Initializing EspansoNotifyHelper in /Users/bgs/Library/Application Support/espanso
09:23:18 [ INFO] EspansoNotifyHelper already initialized, skipping.
09:23:18 [ INFO] Binded to IPC unix socket: /Users/bgs/Library/Application Support/espanso/worker.sock
09:23:18 [ INFO] Using modulo at "/usr/local/bin/modulo"
09:23:18 [ INFO] Created Modulo APP stub at: "/Users/bgs/Library/Application Support/espanso/Modulo.app/Contents/MacOS/modulo"
09:23:18 [ INFO] worker is running!
09:23:18 [ INFO] watching for changes in path: /Users/bgs/Library/Preferences/espanso
```

**Comment by federico-terzi** [comment]
Hey @bradleysawler,

Thanks for reporting this issue! Interesting, I still haven't got the chance to try espanso on Monteray, but this seems to be a critical issue. Could you please try to:

1. Run `espanso unregister`
2. Run `espanso register` and grant Accessibility permissions

You might also want to try to add espanso to the "Input Monitoring" category, which wasn't necessary until BigSur, but perhaps could help in this case.

A few more questions:
* Do you see the espanso icon on the status bar?
* Are you using a customized keyboard layout?

Thank you for your help!

Cheers :)

**Comment by bradleysawler** [comment]
Sorry @federico-terzi 

After following the steps I looked at my own notes that says: 
```
# During updates the link might get broken. 
cp ~/git/config_files/espanso/default.yml ~/Library/Preferences/espanso/
ln -sfn ~/git/config_files/espanso/default.yml ~/Library/Preferences/espanso/default.yml
```

I symlink my config files to control them in git. During macOS updates, the links get broken. 

Sorry for the confusion. 

Bradley

**Comment by federico-terzi** [comment]
Thank you for the follow up @bradleysawler! Version 2 should mitigate this issue (as now espanso is an app bundle rather than a binary)

Cheers :)
