### ISSUE TITLE
Make espanso more user-friendly with non-utf8 encodings

### ISSUE THREAD

**Issue by randomarno** [federico-terzi/espanso#732]
Hi !  
I have an issue on Windows with French characters.   
I try to subsitute phrases with `À, é, è` and some other characters.  
For example, the following :  

    J'ai tenté de vous contacter par téléphone sans succès.  
Produces :  

    J'ai tentÃé©  ddee  vvoouuss  ccoonnttaacctteerr  ppaarr  ttéÃl©élpÃh©opnheo nsea nsa nssu cscuècsc.Ã¨s.  

Espanso 0.7.3 running on both Windows 10 and latest Windows 11 insider version.  
I've already tried `force_clipboard: true`  
  

How can I correct this ?   
Thanks for your help !

**Comment by federico-terzi** [comment]
Hey @randomarno,

I'm sorry you experienced this problem! Did you figure out the problem and solution? :)

**Comment by randomarno** [comment]
Hi @federico-terzi.
Sorry for opening and closing issue simultaneously. The issue seems to be related with the way I replicated my default.yml. Starting from scratch with the default file, and now everything seems good.
espanso works well with Windows 11.

**Comment by federico-terzi** [comment]
@randomarno I see, thank you. I suspect this could have been an encoding error. I'd love to make espanso more user-friendly in these cases, so I'll reopen the issue. Hopefully, we'll be able to improve this aspect in the future :)

PS: Is there any way you could send me a corrupted configuration?
