### ISSUE TITLE
Request: zip version for windows

### ISSUE THREAD

**Issue by steb5067** [federico-terzi/espanso#736]
Hi there

Our computers are locked down pretty tight, and there is no install anyway after checking the more info on the "windows protected your PC" blocking screen. With other softwares I can get by this if there is an archive I can unzip. Is this possible?

best wishes

**Comment by federico-terzi** [comment]
Hey @steb5067,

Thank you for the feedback! This will be possible in the next release #594, as it will come with #309 out of the box

Cheers :)

**Comment by steb5067** [comment]
Thanks.

I managed to solve this with innoextract to deconstruct the installer. This
could be a work around for people in the meantime. Longer term the zip will
be great.

Regards

**Comment by federico-terzi** [comment]
Sounds good, thanks for sharing!
