### ISSUE TITLE
Duplicate Replacements

### ISSUE THREAD

**Issue by FrocketGaming** [federico-terzi/espanso#738]
I'm noticing that triggers that are lower-cased are adding duplicate information vs when they're upper-cased.

For Example:
Upper-cased trigger :Grp
"Review Group, inventory remaining"

Lower-cased trigger :grp
"RReevviieeww  GGrroouup,p ,I ninvveennttoorryy  rreemmaaiinninigng"

It doesn't do it all the time but out of 10 attempts, I saw it several times. I tried it in several applications and only run across the issue when the trigger is lower-cased.

**Comment by federico-terzi** [comment]
Hey @FrocketGaming,

Thanks for reporting this issue! What OS are you using?
I suspect you might be running multiple instances of espanso at the same time. Espanso should only have 2 processes running, if you see more, then you have multiple copies (except for the upcoming version 2, which will have 3 processes running, but this is only relevant for future readers).

If you are on Linux or MacOS, try running `killall espanso` and then `espanso start`. On Windows, use the task manager to kill all espanso instances and start espanso again

Let me know if that helps!

Cheers :)

**Comment by FrocketGaming** [comment]
Using Windows 10 and Windows 11 Beta, I think you're right about the issue. I noticed it had two icons in the system tray for whatever reason. After closing one I didn't experience any more duplication issues.

**Comment by federico-terzi** [comment]
Sounds good, thank you. I'll try to make this more explicit in the upcoming version :)
