### ISSUE TITLE
Doesn't work in RStudio 

### ISSUE THREAD

**Issue by yu-soong** [federico-terzi/espanso#743]
Hi, it doesn't work in Rstudio, somehow: only the first three letters are shown. For instance: "Best wishes" only shows "Bes".

espanso: the latest one
OS: Macos BigSur 11.5.2 (MacBook Pro Apple Chip)
Rstudio version 1.4.1717

best,
Yu

**Comment by federico-terzi** [comment]
Hey @yu-soong,

I'm sorry you experienced this problem! Please see this thread: https://www.reddit.com/r/espanso/comments/n3wigg/snippets_only_partially_expand_in_rstudio/

Cheers :)
