### ISSUE TITLE
espanso custom packages can't be a private repo

### ISSUE THREAD

**Issue by brukberhane** [federico-terzi/espanso#744]
I recently realized that you can't open a private repository for a custom espanso package. Is there a reason and/or workaroudnd to that?

**Comment by federico-terzi** [comment]
Hey @brukberhane,

Thank you for the feedback! This is not currently supported, but it's coming in the next major version #594 
In the meanwhile, see #308

Cheers :)

**Comment by brukberhane** [comment]
Alright thanks!
