### ISSUE TITLE
Arguments not working

### ISSUE THREAD

**Issue by molitona** [federico-terzi/espanso#747]
Hi, I've tried to test args but they don't work (this code below doesn't work) when typing :greet/test/

> - trigger: ":greet"
>   replace: "Hey $0$, how are you?\nIt's been a while!"
>   passive_only: true

I use arch linux.

**Comment by federico-terzi** [comment]
Hey @molitona,

I'm sorry you experienced this problem! Did you add the following lines to your default.yml file?

```
enable_passive: true
passive_key: CTRL
```

You might also want to read the docs for more information: https://espanso.org/docs/passive-mode/

Keep in mind that passive mode is going away in the upcoming version (it will be superseded by Regex triggers), so try to avoid it if possible. In the meanwhile, you might also consider forms to accept custom arguments: https://espanso.org/docs/forms/

Cheers :)

**Comment by molitona** [comment]
yeah, i added

> enable_passive: true
> passive_key: CTRL

with no success.

But, i want not to have a box prompted to enter a value, is there any solution to pass args directly ?
Also, form not work, when i type that trigger it will be deleted and no prompt ! 

>  - trigger: ":greet"
>     form: |
>       Hey {{name}},
>       Happy Birthday!

**Comment by federico-terzi** [comment]
> But, i want not to have a box prompted to enter a value, is there any solution to pass args directly ?

I see, that use-case is solved using the upcoming regex triggers. I'll make sure to share some news once it's ready to be tried :)

> Also, form not work, when i type that trigger it will be deleted and no prompt !

Interesting, this seems like a bug. Probably you need to install modulo as well :) See: https://espanso.org/install/linux/#installing-modulo

Cheers :)
