### ISSUE TITLE
Multiple espanso instances are launched whenever the config changes (auto_restart).

### ISSUE THREAD

**Issue by joech4n** [federico-terzi/espanso#748]
Multiple espanso instances are launched whenever the config changes.

```
❯ espanso --version

espanso 0.7.3
```

**Comment by federico-terzi** [comment]
Hey @joech4n,

Thanks for reporting this issue! This is a known problem (see #548) which has been fixed in the upcoming version. I'm going to close the issue in favor of the other one :)

Cheers :)
