### ISSUE TITLE
Doc Typo: "br" not "bs"

### ISSUE THREAD

**Issue by epmills** [federico-terzi/espanso#75]
Found I believe a typo in the documentation but was not able immediately to find documentation source in github (did I miss it?).

The last sentence of the _Creating your own Match_ section should ready `:br` and not `:bs`, correct?

Echoing what others have said, very impressive concept with really nice documentation!

**Comment by federico-terzi** [comment]
Hi @epmills ,
Thank you very much for your help, that's definitely a typo. I will fix it asap.
