### ISSUE TITLE
Espanso stopped working in chrome browser - windows 10 

### ISSUE THREAD

**Issue by santiyounger** [federico-terzi/espanso#754]
Hey, have been using espanso for a long time in Linux and love it! Recently I got a windows 10 PC and the first thing I did was install espanso.

It was working perfectly until today. For some reason Espanso no longer works inside the Chrome Browser.

I had espanso installed with the windows installer, I reinstalled it several times. I even installed it through chocolatly with the command `choco install espanso`

There are no error messages, espanso work correctly across most of my computer, but it stopped working inside of Chrome.

I'm new to windows so I don't really know what might be causing this, I apprecaite any help. 

Feel free to let me know if I need to provide more info! thanks!

**Comment by federico-terzi** [comment]
Hey @santiyounger,

Thanks for reporting this issue! Could you please tell me your Chrome version?

Cheers :)

**Comment by santiyounger** [comment]
Thanks a lot man,

I'm using Chrome Version 93.0.4577.82 (Official Build) (64-bit) in windows 10

After writing this issue, I realized that  this problem comes and goes. right now I can't replicate it any more. Things are working alright now!

I don't want to take too much of your time.
 For now this problem seems like it solved itself.
 If I manage to replicate it and find the reason for the issue I'll re-open this issue, but for now I'll close it

As always super grateful for the amazing work you've done with espanso @federico-terzi it's by far one of my favorite projects, I use every day!

you rock! have a great day

**Comment by federico-terzi** [comment]
@santiyounger Thank you for the kind words!

All right, let me know if the problem happens again :)

**Comment by Lissy93** [comment]
I'm seeing this issue too, I'm using Brave Browser v 1.32.113, which is based on Chromium 96. Espanso is working perfectly in every app other than Chromium, no errors or anything, just none of my bindings have any effect. This issue started a few months ago.

I don't think it's an issue with Espanso per se, but rather something to do with the way that Chrome sandboxes processes. Although not entirely sure why this would be the case, or what the correct fix would be. But as a workaround, it does actually work perfectly if you run Espanso as administrator.

Also just want to add my thanks to you, @federico-terzi - Espanso is awesome, it's one of the apps that I couldn't imagine life without now. You've done a great job, keep it up! Hopefully after Christmas I can increase my sponsorship :)

**Comment by federico-terzi** [comment]
Hey @Lissy93,

Thank you for the kind words and the support!

> But as a workaround, it does actually work perfectly if you run Espanso as administrator.

This is very interesting, I've opened an issue to track this bug further https://github.com/federico-terzi/espanso/issues/894

Thanks for your help :)

**Comment by federico-terzi** [comment]
Hey @Lissy93,
I've followed up on #894, when you have the chance, could you please provide some more details? :) Thanks!
