### ISSUE TITLE
 Espanso enables/disables itself automatically many times

### ISSUE THREAD

**Issue by molitona** [federico-terzi/espanso#755]
Hi, I've noticed that espanso enable/disable itself automatically many times. 
I'm not pressing double tab by mistake.
What's the matter ?

> 20:57:25 [ INFO] espanso version 0.7.3
> 20:57:25 [ INFO] using config path: /home/user/.config/espanso
> 20:57:25 [ INFO] using package path: /home/ser/.local/share/espanso/packages
> 20:57:25 [ INFO] spawning worker process...
> 20:57:25 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/espanso.sock
> 20:57:25 [ INFO] initializing worker process...
> 20:57:25 [ INFO] Binded to IPC unix socket: /home/user/.local/share/espanso/worker.sock
> 20:57:26 [ INFO] watching for changes in path: /home/user/.config/espanso
> 20:57:26 [ INFO] Using modulo at "/usr/bin/modulo"
> 20:57:26 [ INFO] worker is running!
> 22:35:06 [ INFO] Toggled: espanso disabled
> 22:35:19 [ INFO] Toggled: espanso enabled
> 23:14:59 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:15:23 [ INFO] Toggled: espanso disabled
> 23:15:23 [ INFO] Toggled: espanso enabled
> 23:16:31 [ INFO] Toggled: espanso disabled
> 23:16:31 [ INFO] Toggled: espanso enabled
> 23:19:33 [ INFO] Toggled: espanso disabled
> 23:19:33 [ INFO] Toggled: espanso enabled
> 23:19:33 [ INFO] Toggled: espanso disabled
> 23:19:33 [ INFO] Toggled: espanso enabled
> 23:19:33 [ INFO] Toggled: espanso disabled
> 23:19:33 [ INFO] Toggled: espanso enabled
> 23:22:31 [ INFO] Toggled: espanso disabled

**Comment by federico-terzi** [comment]
Answered in https://github.com/federico-terzi/espanso/issues/751 :)
