### ISSUE TITLE
Replace pattern \n is expanded into a return keypress

### ISSUE THREAD

**Issue by rnoennig** [federico-terzi/espanso#760]
Hi,

I'd like to use a predefined block of text that gets inserted once the trigger is detected.
```yaml
- trigger: ":ext"
  replace: "this is\nmy block"
```

In my app it looks like athis:
"this is

my block" (exaggerated distance, since github has not concept of paragraphs)

My expected result would be:
"this is
my block" (No distance between the two lines)

What gets inserted however is semantically more something like "<p>this is</p><p>myblock</p>", since the yaml string newline character is expanded into a return keypress. In some applications the return key does not create a newline, but a new paragraph. Shift+return inserts a newline in some of those applications.

I've read #652 and know that you don't want to support arbitrary shortcuts, but I think providing a way to insert a shift+return press instead of a return press is a text expander problem.

One solution could be to create another block type like the Literal Block Scalar that treats \n more like a newline instead of a paragraph:
```yaml
- trigger: "include newlines"
  replace: <
            this is
            my block
```

What do you think? Is this maybe already possible?

**Comment by KyleSnodgrass** [comment]
Hello there. I also wanted to be able to create a newline in applications requiring shift+enter. I found the following works for me:

```
  # Formatting for Webex:
  - trigger: "qq "
    force_clipboard: true
    replace: |
               ```
               $|$
               ```
```

**Comment by federico-terzi** [comment]
Hey @rnoennig,

Thank you for the feedback! Until #556 is available, it's unlikely there would be a way to inject Shift+Enter instead of Enter.
That said, the solution proposed by @KyleSnodgrass is exactly what I would recommend! (using the `force_clipboard: true` param)

Cheers :)

**Comment by rnoennig** [comment]
> Hello there. I also wanted to be able to create a newline in applications requiring shift+enter. I found the following works for me:
> 
> ```
>   # Formatting for Webex:
>   - trigger: "qq "
>     force_clipboard: true
>     replace: |
>                ```
>                $|$
>                ```
> ```

Thanks for the info. Unfortunately this only inserts line breaks in some apps. In others it just inserts "``` I```" without any line breaks at all.

> Thank you for the feedback! Until #556 is available, it's unlikely there would be a way to inject Shift+Enter instead of Enter.
Yes, macro support would also resolve this issue.

**Comment by federico-terzi** [comment]
> Unfortunately this only inserts line breaks in some apps. In others it just inserts " I" without any line breaks at all.

Interesting... are you on Linux?

**Comment by rnoennig** [comment]
> > Unfortunately this only inserts line breaks in some apps. In others it just inserts " I" without any line breaks at all.
> 
> Interesting... are you on Linux?
Yes, I'm on Ubuntu 20.04.3

**Comment by federico-terzi** [comment]
@rnoennig I see, thank you. Usually, that is caused by espanso not using the "right" paste shortcut in those apps, so you might need to configure it accordingly if you want to use the Clipboard backend :)

If you want to do it, you will need to create an [app-specific configuration](https://espanso.org/docs/configuration/#application-specific-configurations), setting the `paste_shortcut` parameter to one of the following:

```

**Comment by rnoennig** [comment]
> @rnoennig I see, thank you. Usually, that is caused by espanso not using the "right" paste shortcut in those apps, so you might need to configure it accordingly if you want to use the Clipboard backend :)
> 
> If you want to do it, you will need to create an [app-specific configuration](https://espanso.org/docs/configuration/#application-specific-configurations), setting the `paste_shortcut` parameter to one of the following:
> 
> ```
>     CtrlV,
>     CtrlShiftV, 
>     ShiftInsert,
>     CtrlAltV,
>     MetaV,
> ```
> 
> Cheers :)

That worked perfectly, thank you!

This is what I used:
```yaml
filter_title: "MyApp"
paste_shortcut: "CtrlShiftV"
matches:
  - trigger: ":sig"
    force_clipboard: true
    replace: |
      this is
      my block
```

**Comment by federico-terzi** [comment]
Great! :)
