### ISSUE TITLE
Very slow on Win10

### ISSUE THREAD

**Issue by kasparpalgi** [federico-terzi/espanso#765]
3-4 seconds for longer texts & in chats sends multipart if multiline text. Sometimes partial.

**Comment by federico-terzi** [comment]
Hey @crewnew-git,

I'm sorry you experienced this problem! The new version should improve this aspect considerably, but in the meanwhile, you could try setting this option in your `default.yml` configuration:

```yaml
backend: Clipboard
```

Let me know if that helps

Cheers :)

**Comment by federico-terzi** [comment]
I think we can safely close this issue now, but feel free to reopen if you encounter any other problems or have some feedback! :)
