### ISSUE TITLE
Use German umlauts within `replace:"...."`

### ISSUE THREAD

**Issue by ghost** [federico-terzi/espanso#766]
Hello,

I'm struggling with some of my replacements in my `~/.config/espanso/default.yml` file e. g.:

`  - trigger: ":bg"`
`    replace: "--\nBeste Grüße\nFrank"`
The output I get is `^`

Which way I can use German umlauts (Ä, ä, Ö, ö, Ü, ü and ß). I'm using a QWERTZ keyboard and my OS (Arch Linux) is configured accordingly (DE).

Thanks for taking time to look into this issue.

**Comment by fr-an-kh** [comment]
Hello @federico-terzi,

Thanks for your reply! Tried your example with same result. For clarification I should have mentioned that I most of the time use my terminal and TUI applications e. g. neovim, neomutt and that issue only occurs within terminal based applications. Using GUI apps your as well as my example work like a charm.

Long story short - no, didn't help.

**Comment by federico-terzi** [comment]
I see! Thank you for trying

What terminal are you using?

**Comment by federico-terzi** [comment]
Interesting, that might be caused by an invalid "paste shortcut" sent by espanso. Could you please try to open a terminal and run `espanso detect`, then post the output here?

We might need to create an [app-specific config](https://espanso.org/docs/configuration/#application-specific-configurations) config for st

Cheers :)

**Comment by federico-terzi** [comment]
Thank you! Could you please try creating a file `$CONFIG/user/st.yml` with the following content (where $CONFIG is the espanso config directory)

```yaml
filter_class: "St"

paste_shortcut: ShiftInsert
```

Then try again with the match specifying `force_clipboard: true`:

```yaml
- trigger: ":bg"
  force_clipboard: true
  replace: "--\nBeste Grüße\nFrank"
```

Let me know if that helps :)

**Comment by fr-an-kh** [comment]
Thanks for your effort! This worked as expected \o/ fantastic \o/

You've made my day :-D

**Comment by fr-an-kh** [comment]
I'm by no means a coder but how about the way [texpander](https://github.com/leehblue/texpander) handles text expansions? There you have a bunch of simple text files which get triggered it's abbreviations.

Using texpander I didn't encounter the problem mentioned before. The
downside of texpander is, at least for me, that typing gets interrupted
by pressing a key combination to launch the script and select the wanted
expansion via rofi/dmenu.

Maybe this approach inspires you in some way?
