### ISSUE TITLE
Size of button on initial start

### ISSUE THREAD

**Issue by JeppeKlitgaard** [federico-terzi/espanso#777]
So excited for Espanso v2!

![image](https://user-images.githubusercontent.com/1814611/136703810-4e3fbce7-34bd-4748-809f-1b8037c64839.png)

This is a tiny flaw, but figure I would report it anyway. As you can see, the "Got it!" button is not sized properly (on Windows 10).

Can't wait to try out all the new features!

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard,

Thanks for reporting this issue! This definitely looks like a bug, we'll investigate :)

Cheers :)
