### ISSUE TITLE
Allow UTF8 character in Match

### ISSUE THREAD

**Issue by Kwelity** [federico-terzi/espanso#78]
When trying to add special character, the program can't load the config

`espanso log`

output:

```
15:33:49 [ERROR] thread 'daemon_background' panicked at 'byte index 1 is not a char boundary; it is inside '¦' (bytes 0..2) of `¦test`': src/libcore/str/mod.rs:2068
stack backtrace:
   0: <unknown>
...
  18: <unknown>
  19: start_thread
  20: clone

15:33:49 [ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"': src/libcore/result.rs:1084
stack backtrace:
   0: <unknown>
...
   8: <unknown>
   9: XRecordEnableContext
  10: <unknown>
...
  18: <unknown>
  19: __libc_start_main
  20: <unknown>
```

the config tested:

```
  - trigger: "¦test"
    replace: "coucou"
```

The character ¦ seems to be problematic due to its size.

My OS is linux, espanso was install from the aur package (version 0.2.3 slightly outdated but the change log doesn't mention my problem)

Why?

It would allow us to start a sequence with non common character, making it more difficult to clash with other program.

**Comment by federico-terzi** [comment]
Hi @Kwelity,
Thanks for pointing that out, it's definitely a bug.
I will investigate further
