### ISSUE TITLE
Port 'espanso match' subcommand to v2

### ISSUE THREAD

**Issue by napcok** [federico-terzi/espanso#780]
It is planned to port match subcommand to Espanso v2?
I was using `match list` and `match exec` in scripts with previous version.

Espanso v2 works very well here. Thanks for working on it :)
Best regards.

**Comment by federico-terzi** [comment]
Hey @napcok,

Thank you for the feedback! Yes, I'm planning to port it in the upcoming 2/3 weeks :)

I'll keep you posted, we are going to iterate a lot in the upcoming weeks

Cheers :)

**Comment by federico-terzi** [comment]
Hey,

I'm publishing both commands in the v2.0.5-alpha, you'll be able to use:

```
espanso match list
espanso match list --class "TextEdit" --json

# and

espanso match exec -t "your trigger"
```

Cheers :)
