### ISSUE TITLE
Espanso 2.0.1 alpha doesn't start automatically after reboot

### ISSUE THREAD

**Issue by Masacroso** [federico-terzi/espanso#783]
I've installed espanso 2.0.1 alpha following the installation steps for linux (however i didn't installed in the $HOME/opt folder, I used $HOME/Documents instead). I registered in the path (and indeed espanso is available from any terminal), and also I register the service with the command `espanso service register` (the documentation says `espanso register` but it didn't work).

However I need to start espanso after every reboot of the system. I have kubuntu 21.04.

P.D.: anyway I can fix this behavior making an script that start espanso automatically when boots.

**Comment by federico-terzi** [comment]
Hey @Masacroso,

Thanks for reporting this issue! There seems to be an issue with the Systemd entry, could you please reboot your system and then post the output of `espanso log` here? That would be very helpful!

Cheers :)

**Comment by Masacroso** [comment]
> Hey @Masacroso,
> 
> I think we might have solved the problem, when you have the chance please try with the new release (v2.0.2-alpha) which is going to be released in a few minutes. Thank you again for the help! Feel free to reopen the issue if the problem is not solved :)
> 
> Cheers :)

Now it works perfectly! Thanks!
