### ISSUE TITLE
Additional searchable terms for matches using search dialog

### ISSUE THREAD

**Issue by JeppeKlitgaard** [federico-terzi/espanso#789]
I think a really powerful feature would be to allow for additional searchable terms in the matches for use with the (fantastic) new search dialog.

This is particularly useful for emojis, where I often find that I forget exactly which words correspond to a given emoji. This would allow the users to use a premade `emojis` package much more easily.

```yaml
- "replace": "🥩"
  "triggers":
  - ":meat"
  "search_terms":
  - "steak"
  - "t-bone"
```

The search terms would only be considered when using the graphical search utility.

Something similar could be achieved using the existing `triggers` property, but one might simply want these terms only to be accessible using the search dialog such that the collection of triggers is not 'polluted'.

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard,

Thank you for the feedback! This seems like a very interesting use-case, as I struggle with aliases as well. I'll mark it as a feature request :)

Cheers :)

**Comment by JeppeKlitgaard** [comment]
If this does indeed get implemented, I would like to help implement an improved 'all-emoji' package for the hub.

I have been working a bit on a pet project that generates the appropriate YAML files for lots of triggers programmatically using `jsonnet` and `python`. This allows me to quickly and reliably change over `pre` and `post`-triggers as well as generate trigger/replacement pairs based on the nice alphabetical ordering of most parts of the unicode spec. Feel free to have a peek: https://github.com/JeppeKlitgaard/barista

There seems to be a nice dataset here that could be extended to cover the whole unicode emoji spec: https://gist.github.com/zats/35b2f5bbe5ae72a2efb7793098be10dd

**Comment by federico-terzi** [comment]
@JeppeKlitgaard Sounds good! Once this feature is ready, we can start working on it :)

**Comment by federico-terzi** [comment]
Coming in the next release :)

I've followed your suggestion, so your example should work correctly:

```yaml
- "replace": "🥩"
  "triggers":
  - ":meat"
  "search_terms":
  - "steak"
  - "t-bone"
```

Thanks for your help :)

**Comment by JeppeKlitgaard** [comment]
This looks amazing! I am sure it will be a very useful feature – I can't wait to play with it!
