### ISSUE TITLE
Add Systemd integration with espanso

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#80]

**Comment by Scrumplex** [comment]
I think this should be handled similarly to the macOS implementation. We could just copy a systemd-user unit file to the correct place (e.g. `$XDG_CONFIG_HOME/systemd/user/espanso.service`), if there is no espanso user unit installed on the system. When `espanso register` is called, the unit file can be created (if it does not exist) and enabled with `systemctl --user enable espanso.service`. `espanso unregister` on the other hand should just disabled the unit and delete the unit file again. 

NOTE: It is possible, that the espanso unit file exists outside of the user's home directory (for example when using the AUR package), which means we should use something like  `$ systemctl --user is-enabled espanso.service`, to check if
1. the unit exists (command returns exit code 1 if it does not exist)
2. the unit is enabled already (command prints either "enabled" or "disabled")

**Comment by federico-terzi** [comment]
Thanks as always for the great suggestions @Scrumplex! Yours is pretty much the solution I was thinking.
This weekend I will try to develop this feature following your tips, hoping to circumvent the previous X11 error I encountered.

Thanks :)

**Comment by Scrumplex** [comment]
While updating the AUR packages I noticed, that espanso creates it's own service files no matter if they already exist system wide or not. Looks like `systemctl --user is-enabled espanso` returns exit code 1 if it's disabled, too.

**Comment by federico-terzi** [comment]
Yes, you are right. If the service is disabled espanso re-adds its service file. 
Do you think this can have any unwanted consequences?

At this point, considering that espanso supports systemd out of the box, I think it's reasonable for the user to configure it automatically using `espanso register`.
On the other hand, if the user wants to customize the service file location this can be problematic.

I can't find a graceful way to handle both of these situations. Any suggestion?

**Comment by Scrumplex** [comment]
What about this:
Check if command returns 1
If it outputted "disabled" ask the user if it should add the service anyway (defaulting to no)
The rest stays the same.

This should definitely inform the user, that there already is a service file.

**Comment by federico-terzi** [comment]
All right, it's a great solution. I'm opening a new issue: #84
