### ISSUE TITLE
Snippet character doesn't display properly when expanded

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [federico-terzi/espanso#806]
## Version
espanso 2.0.3-alpha

## Steps to reproduce
1. Create a snippet (note the ending question mark is a Unicode character) and save the file base.yml.
```
  - trigger: "kjw"
    replace: "What is $|$？"
```
2. In notepad, type `kjw`, we get the expected result `What is ？`
3. In Windows Terminal, type `kjw`, the ending question mark has been changed to some kind of jumbled character. But I'm sure the font I set for Windows Terminal can display this question mark correctly. If I copy the question mark and paste to Windows Terminal, is display without any issues.

![char](https://user-images.githubusercontent.com/39968/137948328-b85f85a9-f8eb-47c4-b0ea-706ba743ba12.gif)

**Comment by JeppeKlitgaard** [comment]
Your question mark is some odd unicode question mark that isn't the standard one - it doesn't render because the Windows Terminal font doesn't support the character, I assume.

Your character on the left, actual question mark on the right: ？?

**Comment by JeppeKlitgaard** [comment]
Sounds like the encoding on your `yml` file might be wrong. Is it UTF-8?

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> @0x7FFFFFFFFFFFFFFF Interesting, I'll investigate
> 
> In the meanwhile, you might have some luck with the "force_clipboard" option:
> 
> ```
>   - trigger: "kjw"
>     force_clipboard: true
>     replace: "What is $|$？"
> ```
> 
> Cheers :)

I tried, after that change, it still works in notepad, but in Windows Terminal it prints out `^V`.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> Sounds like the encoding on your `yml` file could be wrong. Is it UTF-8?

Yes it's UTF-8 without BOM and uses Linux line ending LF. I tried Windows line ending CRLF but the behavior is the same.

**Comment by Masacroso** [comment]
Try top see if the following works

      - trigger: "kjw"
        replace: "What is ？"

so you see what is going on. Its possible that $ and | are doing something weird.
