### ISSUE TITLE
New line is always added after choosing a choice from List Box

### ISSUE THREAD

**Issue by GeorgeYaz** [federico-terzi/espanso#808]
Hi @federico-terzi,

Currently I'm using the list box to match a trigger with different possibilities to choose from and the thing is that every time I pick a choice a new line is added as well.

here is how the configuration looks like:
![listConfig](https://user-images.githubusercontent.com/82532794/138100135-aa5f9bcb-fb48-4370-a3c0-7330850887e1.JPG)

and when writing the trigger "espanso" the following form will appear
![Capture](https://user-images.githubusercontent.com/82532794/138100536-d3760bd5-3a1a-4fdc-9137-8046d299901d.JPG)

but for example when choosing the first choice the sentence "Hi there!" will be displayed and a new line is created so in case I want to continue on the same line I have to delete this new line and continue writing.

So, is there any possibility or configuration that can be done to prevent adding a new line and staying on the same one.

Thank you for taking the time

**Comment by federico-terzi** [comment]
Hey @GeorgeYaz,

I'm sorry you experienced this problem! This is probably happening due to the YAML multiline syntax you are using, see here: https://yaml-multiline.info/

Try to replace

```
form: |
  {{choices}}
```

with

```
form: "{{choices}}"
```

Cheers :)

Cheers :)

**Comment by webserviceXXL** [comment]
@federico-terzi Find this issue since I have the same problem. But your solution isn't working with the current verion. The configuration is saved and loaded successfully, but when using the trigger the following string is returned instead of the real replacement.

`[Espanso]: An error occurred during rendering, please examine the logs for more information.`

Log:
```21:13:40 [worker(26451)] [ERROR] could not resolve variable "choices"
21:13:40 [worker(26451)] [ERROR] error during rendering: rendering error

Caused by:
    missing variable: `choices` ```

**Comment by ivan-paleo** [comment]
@webserviceXXL It's because it should be with square brackets rather than curly braces:
```
form: "[[choices]]"
```
