### ISSUE TITLE
Add Portable version

### ISSUE THREAD

**Issue by linsui** [federico-terzi/espanso#81]
```
    -c, --config <FILE>
            Sets a custom config directory.
```

This doesn't work for me on windows, espanso still uses the default one. And maybe `-c, --config <DIRECTORY>` would be more clear?
Could you add a portable mode? For example, if there is a `portable` file in the same directory, espanso will use config files in the same directory, or, if there is a `portable` directory, espanso will put config files in it. Thanks anyway!

**Comment by federico-terzi** [comment]
Hi @linsui,
Thanks for your great suggestion. I was planning to remove that flag entirely from the next release, but I understand that a portable version could be useful. 
I'll add this feature to the roadmap as you suggested and I'll change the name of the issue to reflect this change.

Thanks :)
