### ISSUE TITLE
Create /usr/local/bin folder on macOS if it doesn't exist yet when adding espanso to the path

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#814]

**Comment by pocc** [comment]
When installing v2.0.5, there is weird behavior where espanso is symlinked to a temp directory (/var/private/...) that doesn't exist. /usr/local/bin/espanso points to this file. Symlinking /usr/local/bin/espanso with

    ln -s /Applications/Espanso.app/Contents/MacOS/espanso /usr/local/bin/espanso

fixes.

**Comment by federico-terzi** [comment]
Hey @pocc,

Thanks for reporting this issue! I've done a bit of research, and this seems to be due to a macOS security feature known as "App Translocation". [This article](https://www.synack.com/blog/untranslocating-apps/) talks about it in the end.
I've opened some tickets to handle these edge-cases: #845 #844 

Cheers :)
