### ISSUE TITLE
[Bug] ALT-Tabbing turns on and off Espanso

### ISSUE THREAD

**Issue by JeppeKlitgaard** [federico-terzi/espanso#815]
I couldn't figure out for the life of me why Espanso was disabled for me half of the time.

It turns out that ALT-Tabbing twice within ≈ 1 second is perceived as an "ALT ALT" by Espanso, which also happens to be the default trigger for toggling Espanso.

Perhaps the 'grace period' for ALT presses should also be ended when another non-ALT key is pressed (including other characters than just TAB)

**Comment by JeppeKlitgaard** [comment]
Unfortunately it does still happen occasionally for me during normal use.

Can you reproduce the behaviour by Alt-tabbing back and forth for a bit, @federico-terzi?

**Comment by federico-terzi** [comment]
@JeppeKlitgaard Thank you for reporting! I'll reopen the issue :) What OS are you using?

**Comment by JeppeKlitgaard** [comment]
Thank you for being so fantastic at support - the Espanso community is uniquely spoiled in that respect!

I am on Windows 10

**Comment by federico-terzi** [comment]
@JeppeKlitgaard Thanks! I'll investigate

**Comment by JeppeKlitgaard** [comment]
I just wanted to give an update (that is, this is not to be taken as rushing you!), as I have been doing a bit more math writing lately where I use my Espanso setup heavily, and unfortunately I am getting the turning off an on behaviour due to ALT-Tabbing still.

Is anyone able to reproduce this? I am on Windows 10, mostly US and DK keyboard layouts.

Maybe the RNFR tag should be removed as well, if others are able to reproduce.

As always, fantastic work on Espanso!

**Comment by federico-terzi** [comment]
Hey @JeppeKlitgaard, thanks for the update!

That's interesting, I still haven't found a reliable way to solve the problem. In the meanwhile, you might try switching the `toggle_key` to another one :) For example, I'm using `toggle_key: RIGHT_CTRL`, see: https://espanso.org/docs/configuration/#customizing-the-toggle-key

Cheers :)

**Comment by JeppeKlitgaard** [comment]
I have changed to use `RIGHT_ALT`, which works well so far. Thank you for the tip!

**Comment by federico-terzi** [comment]
Hey guys,

I'm closing this issue as now the `toggle_key` is disabled by default (as it was too confusing), so this issue became less problematic

Cheers :)
