### ISSUE TITLE
Possibility to define abbreviation mode

### ISSUE THREAD

**Issue by timorunge** [federico-terzi/espanso#82]
Hey @federico-terzi,

thanks a lot for espanso!
I'm currently in the migration process away from TextExpander.

Since I'm a lazy guy one of my typical uses cases is to do some "auto correct" for words that I'm misspelling regularly. The issue that I'm facing is that if I'd like to type "other" and have a correction for ***ther*** like

```
  - trigger: "ther"
    replace: "there"
```

it's replacing ***other*** to ***othere***. 

As a quick work around I've put white spaces around the trigger (and the replace) like

```
  - trigger: " ther "
    replace: " there "
```

which is OK but hard to maintain  in the long run. 

To solve this it would be nice to have the possibility to add something like an *abbreviation mode* and / or the possibility to define patterns (`RegExp`) after which the replacing is happening. 

Example: 

```
  - trigger: "ther"
    replace: "there"
    abbreviation: "(\s|\t)"
```

The non plus ultra would be if this can be defined on a package level (I've one package based on [misspell](https://github.com/client9/misspell) with *28047* triggers) and per trigger. 

WDYT?

**Comment by timorunge** [comment]
Hey @federico-terzi,

awesome. From a pure performance POV I've not been facing any problems so far. It's blazingly fast. I'll (auto) generate some packages in the next days which I'm happy to share. :)

**Comment by federico-terzi** [comment]
That's great to hear thanks!

**Comment by timorunge** [comment]
@federico-terzi you can use https://github.com/timorunge/espanso-misspell-en as a reference and for performance tests. :)

**Comment by federico-terzi** [comment]
@timorunge thank you. This is actually super useful :)

**Comment by federico-terzi** [comment]
Hi @timorunge,

I'm in the process of developing this feature. I built the first draft in the `feature-word-separators` branch, though I want to test it further in the next few days as it changes a few important mechanics of espanso.

I'll let you know once the feature has been deployed, I expect it to be in the next week release.

Thanks for your help :)

**Comment by timorunge** [comment]
Thank you @federico-terzi, as soon as there is a new release I will take a close look if everything is working as expected and OFC report issues. :)

**Comment by federico-terzi** [comment]
Of course! Thank you for your help :)

**Comment by timorunge** [comment]
@federico-terzi Thanks to v0.3.2 i've pushed the changes as well to https://github.com/timorunge/espanso-misspell-en. :)

**Comment by federico-terzi** [comment]
> @federico-terzi Thanks to v0.3.2 i've pushed the changes as well to https://github.com/timorunge/espanso-misspell-en. :)

That's great to hear! I used your library a lot lately to do all sort of tests :)

**Comment by timorunge** [comment]
> > @federico-terzi Thanks to v0.3.2 i've pushed the changes as well to https://github.com/timorunge/espanso-misspell-en. :)
> 
> That's great to hear! I used your library a lot lately to do all sort of tests :)

Feel free to add them to the hub! :)

**Comment by federico-terzi** [comment]
Sure thing! I will add it to the hub when I have a bit of time :)

**Comment by federico-terzi** [comment]
@timorunge took me a bit of time, but your packages are finally available in the hub! :)
https://hub.espanso.org/packages/mispell-en/

Thanks for your help

**Comment by timorunge** [comment]
@federico-terzi Awesome!
Some "bug": Internal links in the README are pointing no nowhere. The licence in https://hub.espanso.org/packages/mispell-en/ is pointing to https://hub.espanso.org/packages/mispell-en/LICENSE.

**Comment by federico-terzi** [comment]
@timorunge All right, I'll fix it asap :)

**Comment by federico-terzi** [comment]
@timorunge this should have been fixed now :)
