### ISSUE TITLE
Azerty keyboard

### ISSUE THREAD

**Issue by Gadgetroch** [federico-terzi/espanso#823]
Hi,

Shortcut for search bar doesn't work on azerty keyboard.

Thank's

**Comment by federico-terzi** [comment]
Hey @Gadgetroch,

I've tried with the default shortcut (ALT+Space) on Azerty (french) keyboard and it's working correctly for me. Did you customize the shortcut with the `search_shortcut` option?

Cheers :)

**Comment by Gadgetroch** [comment]
Hi,

I speak about lines
So shortcut like alt+1, alt+2 etc

Le dim. 31 oct. 2021 à 19:14, Federico Terzi ***@***.***> a
écrit :

**Comment by federico-terzi** [comment]
@Gadgetroch Thanks! I was able to reproduce. The next version (v2.0.5-alpha) will include a fix, and you'll be able to press ALT+Shift+1/9 to use the shortcut

Cheers :)

**Comment by Gadgetroch** [comment]
Nice !
Thanks :)

Le dim. 31 oct. 2021 à 20:22, Federico Terzi ***@***.***> a
écrit :

**Comment by federico-terzi** [comment]
Hey,

I'm publishing a fix in the upcoming v2.0.5-alpha release, thank you for the help!

Cheers :)

**Comment by Mehdi-YC** [comment]
i still have a problem in X11 I3wm
![image](https://github.com/espanso/espanso/assets/44881216/8d422667-b6b6-4cf3-be5d-968f2ac49e73)

here is the result i got 
i get in slack (flatpak) for example
3YQHIQ CHERIF ?ohq,ed ?qhdi qdd &é!&_!éàé"
