### ISSUE TITLE
Simple static match doesn't trigger in version 2.0.0-alpha

### ISSUE THREAD

**Issue by arabello** [federico-terzi/espanso#825]
While using version 2, sometimes matches do not trigger at all leaving the unexpanded text untouched. This happens rarely, but it blocks multiple successive triggers in a short period of time.

Below here the  `espanso log` output of interest:
```
09:09:40 [worker(792)] [WARN] injection delay has timed out, please release the modifier keys (SHIFT, CTRL, ALT, CMD) to trigger an expansion
09:09:42 [worker(792)] [WARN] detected outdated modifier records for Ctrl, releasing the state
```

The issue appeared while using Google Chrome, inside a webpage. I'll update this thread if I can find out more details on when it happens.

**Comment by arabello** [comment]
I found out that this issue is mainly related to the external [bluetooth keyboard](https://www.logitech.com/en-us/products/keyboards/k380-multi-device.html) I'm using, at least statistically (I wasn't able to reproduce it while using the Macbook integrated keyboard).

I guess bluetooth connectivity might play a role here.

**Comment by federico-terzi** [comment]
@arabello Interesting! Thank you for sharing, this might be definitely related

**Comment by federico-terzi** [comment]
Hey @arabello,

The next version 2.1.0-alpha will include a workaround that should mitigate this problem, thank you for the help!

Cheers :)
