### ISSUE TITLE
Search bar is not focusing automatically on Ubuntu/Gnome

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#829]
I've been testing espanso on a Ubuntu 20 + Gnome VM, and I've noticed it doesn't automatically focus the search bar
![search bar not focusing](https://user-images.githubusercontent.com/20475953/139322249-7389f0f1-892d-44d4-a434-363427b61273.gif)

**Comment by federico-terzi** [comment]
This doesn't seem to happen anymore, feel free to reopen if any of you encounter this again

**Comment by federico-terzi** [comment]
Reopening this one as other users reported it: https://github.com/federico-terzi/espanso/issues/852#issuecomment-967078183

**Comment by federico-terzi** [comment]
Might be helpful: https://forums.wxwidgets.org/viewtopic.php?t=46000

**Comment by pstuifzand** [comment]
@federico-terzi I ran espanso from the dev branch. This change for Ubuntu works for me. The searchbar is focussed automatically now.

**Comment by federico-terzi** [comment]
@pstuifzand Thanks for checking!
