### ISSUE TITLE
Taking Screenshots Toggles espanso

### ISSUE THREAD

**Issue by grantwforsythe** [federico-terzi/espanso#831]
## Overview

I use `Gyazo  (v 4.1.6)` for screen capture which I have bound to `PRT-SC`.

I noticed whenever I take a screenshot, espanso is toggled.

```bash
01:20:59 [ INFO] Toggled: espanso enabled     
02:11:07 [ INFO] Toggled: espanso disabled
02:12:07 [ INFO] Toggled: espanso enabled     
02:11:08 [ INFO] Toggled: espanso disabled  
02:12:07 [ INFO] Toggled: espanso enabled     
02:14:30 [ INFO] Toggled: espanso disabled    
```

**Comment by federico-terzi** [comment]
Hey @grantwforsythe,

Thanks for reporting this issue! Could you please tell me:
* Your operating system
* The Espanso's version you are using (you can find it by running `espanso --version` in a terminal)

In the meanwhile, you might mitigate the issue by changing the toggle key: https://espanso.org/docs/configuration/#customizing-the-toggle-key

Cheers :)

**Comment by grantwforsythe** [comment]
Hi @federico-terzi ,

My specs are below:
- `Windows 10 Pro (v 10.0.19043 Build 19043)`
- `espanso (v 0.7.3)`

I tried changing the toggle key but the issue still persists. However, disabling the toggle key entirely does mitigate the issue.

**Comment by federico-terzi** [comment]
@grantwforsythe Thank you! I'll investigate :)

**Comment by federico-terzi** [comment]
Hey,

The default `toggle_key` behavior has been deprecated in the new version #916, so this issue should be less relevant now. Thanks for the help!

Cheers :)
