### ISSUE TITLE
Nested Matches and forms

### ISSUE THREAD

**Issue by GeorgeYaz** [federico-terzi/espanso#838]
Hi @federico-terzi,

I'm trying to use the forms with nested matches as follow, after writing a trigger (**valve**) a list will appear and then after choosing one option from the list this option will trigger another form(**set valve**). I'm not sure if this is even possible. I tried to play around but unfortunately it didn't work.

Here is the yml configuration:
![github](https://user-images.githubusercontent.com/82532794/140026384-198e7d75-d5d0-4579-bda8-b494e350bb21.JPG)

I also tried to find a way to implement this in a nested matches as described in the documentation but still couldn't find one.

Is there anything I can do to make this work?

One last thing, I'm using windows 11 and espanso is working flawlessly, thank you very much for the great work!

**Comment by federico-terzi** [comment]
Hey @GeorgeYaz,

As far as I understand, you would like to conditionally trigger a match `set valve` or another `set valve feedback` based on the choice of a previous form, did I understand correctly?

Cheers :)

**Comment by GeorgeYaz** [comment]
Hi @federico-terzi,

it's exactly the way you mentioned it :)

**Comment by federico-terzi** [comment]
@GeorgeYaz I see! You can't do that with Espanso right now, but you might get similar behavior by using the match disambiguation feature of the alpha v2:

```yaml
  - trigger: "valve"
    form: "your form {{value}}"
  - trigger: "valve"
    form: "another form"
```

The key here is to use the same trigger for both, which will open the search bar to let you select the right one :)
(keep in mind that you need the v2 to use it)

Cheers :)
