### ISSUE TITLE
disabling or reconfiguring the UI toggle Combo Keys 

### ISSUE THREAD

**Issue by m0ll3art** [federico-terzi/espanso#841]
Hi 

first wanted to say it's amazing work you're doing and I enjoy using `espanso`

However, I would like to know if there is a way to reassign or disable the default UI toggle Combo ALT-SPC since already assigned locally? And if not is it possible to externalize this setting in the default.yml config file? 

thanks

**Comment by federico-terzi** [comment]
Hey @m0ll3art ,

Thanks for reporting this issue! The documentation is still lacking, I'm sorry about that, I'm working hard to get it ready for the new release :)

You can customize the search shortcuts by adding the following to your `$CONFIG/config/default.yml` file and change them as you like:

```yaml
search_trigger: "jkj"
search_shortcut: "ALT+SPACE"
```

The valid values are listed here: https://github.com/federico-terzi/espanso/blob/master/espanso-detect/src/hotkey/keys.rs#L221-L302
Though I haven't tested them all, some of them might be broken :)

Let me know if that helps

Cheers :)

**Comment by federico-terzi** [comment]
You can also disable them by using the value "OFF"

**Comment by m0ll3art** [comment]
Hi @federico-terzi 

many thanks for your prompt answer. Again really that you provide us with this tool. 

Cheers
