### ISSUE TITLE
Installing packages not working 

### ISSUE THREAD

**Issue by m0ll3art** [federico-terzi/espanso#842]
Hi 

I'm new to espanso and still testing and I was performing some basic tasks, such as installing some packages. I use the command `espanso install <package>`  but I always get the same error such as this one 

```
installing package: basic-emojis - version: latest
using package provider: espanso-hub
fetching package index...
unable to install package: unable to find package 'basic-emojis@latest' in the espanso hub
```

here for the `basic-emojis` as an example 

Do you expect special proxy settings? normal `npm` or `brew` commands are working as expected .. 

Working on a macOS BIg Sur 

thanks

**Comment by federico-terzi** [comment]
Hey @m0ll3art,

I'm sorry you experienced this problem! Unfortunately, packages are not working yet on the v2. We are working hard to bring the functionality back, but it will probably take a few weeks still :)

Cheers :)

**Comment by m0ll3art** [comment]
Hey @federico-terzi  

do not be, you do an amazing job, I was only wondering since I was behind the corporate firewall and not sure about the FW rules.. Thanks and I will keep to be posted on this one ;-) 
Cheers

**Comment by federico-terzi** [comment]
Hey,

Packages should be working now :) We are still working on the new Hub website, for now you should be able to see them on the new repository: https://github.com/espanso/hub

Cheers :)
