### ISSUE TITLE
Block the wizard and prompt the user to move the AppBundle if App Translocation is detected

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#844]
Currently, macOS ships with a security feature known as App Translocation which interferes with the way espanso creates the symlink alias (see https://github.com/federico-terzi/espanso/issues/814#issuecomment-960432346).

We will need to block the wizard and prompt the user to move the Espanso.app bundle inside the /Applications folder

This article talks about App Translocation: https://www.synack.com/blog/untranslocating-apps/

**Comment by pocc** [comment]
Thank you. This is likely why alpha has been occasionally nonresponsive on my mac. Some files might be in unexpected places.

**Comment by federico-terzi** [comment]
@pocc Thanks! That could be also caused by other issues, such as #825. The next time you see Espanso become unresponsive, could you please post the output of `espanso log` here? :)
