### ISSUE TITLE
Idea: Add tags or labels to triggers

### ISSUE THREAD

**Issue by tiktuk** [federico-terzi/espanso#854]
It could be useful to be able to add a `label`, `tag`, `category` and/or `description` to a trigger.

Especially for the new Search Bar to search in. So one could search for eg. `signature` and get all signatures.

Just and idea. Cheers!

**Comment by federico-terzi** [comment]
Hey @tiktuk,

Thank you for the feedback! This seems to be related to https://github.com/federico-terzi/espanso/issues/789.
I'm closing this one in favor of the other one, feel free to continue the discussion there!

Cheers :)

**Comment by tiktuk** [comment]
Ok, thanks :)
