### ISSUE TITLE
Form can't be submitted with Enter if active control is list

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#857]
Currently reported on Linux, might happen on other OSes as well

**Comment by MikhailTNY** [comment]
Just to clarify, is it possible the original report didn't specify if they tried using the arrow key to select an item first?

By default, it shows up like this: 

![image](https://user-images.githubusercontent.com/370953/141687799-147c60de-e866-4f4c-8d65-77c23d20cfa3.png)

The "focus" border does not mean the first item is selected, so you can hit enter but it is not going to be submit anything. 

My recommendation is disable the submit button if no object is selected and do not allow enter to dismiss the view if nothing is selected. We have `esc` for that.

**Comment by federico-terzi** [comment]
Hey @MikhailTNY,

Thank you for the feedback! Good point, I'll investigate :)

Cheers :)
