### ISSUE TITLE
Typing extended characters using Accent+letter on keyboard creates wrong outcome while espanso is active

### ISSUE THREAD

**Issue by intreeking** [federico-terzi/espanso#86]
When espanso is active and an accent or caron is typed using "accent + letter" method to write an extended character a doubled accent followed by the letter is typed. Happens anywhere in Windows 10 64 and in all languages/inputs that use this method. 
Example: ´´Uplně vs. Úplně; ˇˇCesko vs. Česko. 
This completeley prevents me from using espanso as I cannot type extended characters until exiting espanso. Other tools like Beeftext behave the same.
Can this be fixed?
Thanks.

**Comment by federico-terzi** [comment]
Hi @intreeking,
Thank you for your great feedback. This seems like a tricky problem, especially considering that also Beeftext has it.
espanso implements a very thin layer on top of the existing Windows Raw Input, so it could be a bug related to that API.

That's said I will take a look at it, to see if I can do something. I would need some more information:
* Which language are you using on Windows?
* Which Keyboard layout do you use?

Thanks

**Comment by intreeking** [comment]
Sure. I use the English version of W10 64 with a Czech language pack and keyboard. I think the OS display language has little to do with the issue, but that is just an assumption. I have seen other users report the same issue on the web for Greek input or French input/keyboard. I think the layer just executes something immediately while the windows input when typing an accent waits for the following character to type an accented character.
Happy to test stuff out for you.

**Comment by intreeking** [comment]
Also, I used to use PhraseExpress, which did not appear to have this issue.

**Comment by federico-terzi** [comment]
Thank you for your help, I'll investigate further using the tips you gave me. 

> I think the layer just executes something immediately while the windows input when typing an accent waits for the following character to type an accented character.

You're almost surely right, it's probably related to the order of the keys pressed.

I'll let you know once I have something to work on, thanks again

**Comment by federico-terzi** [comment]
Hi @intreeking,

I've looked into the issue and it turned out to be pretty easy to solve! 
It should be working correctly in the next release ( v0.3.2 ), probably happening this weekend.

Thanks for your help

**Comment by intreeking** [comment]
This sounds great! When released, I will share the love of your tool with my translator sturents in my online course.
Best wishes
