### ISSUE TITLE
Windows portable version link wrong on the website

### ISSUE THREAD

**Issue by victorwestmann** [federico-terzi/espanso#861]
On the website, on the link: https://espanso.org/install/

The Windows download, for the portable version, is pointing to 
https://github.com/federico-terzi/espanso/releases/download/v2.0.5-alpha/Espanso-Win-Portable-x86_64.exe
and this link is broken. :(

The correct link is:
https://github.com/federico-terzi/espanso/releases/download/v2.0.5-alpha/Espanso-Win-Portable-x86_64.zip

(final 3 letters of the link: zip).

Thank you for your work and for making it available for us! :)
Victor

**Comment by federico-terzi** [comment]
Hey @victorwestmann,

Thanks for reporting this issue! You are absolutely right, I've fixed the link :)

Cheers :)
