### ISSUE TITLE
Please add multiple trigger for same expanding option (replication)

### ISSUE THREAD

**Issue by yedhrab** [federico-terzi/espanso#863]
Can we give list of triggers for same replication

```yaml
 - trigger: ":option:", ":opt:"
    replace: "⌥"
```

**Comment by federico-terzi** [comment]
Hey @yedhrab,

Thank you for the feedback! You can do that by using the `triggers` option, see here: https://espanso.org/docs/matches/#multiple-triggers

Cheers :)

**Comment by yedhrab** [comment]
Oh, sorry for it. Thank you so much (:
