### ISSUE TITLE
Add a bug template to this repo

### ISSUE THREAD

**Issue by MikhailTNY** [federico-terzi/espanso#868]
Hi, 

I'd recommend adding a bug template here, to ask user which platform and which app version they're using to improve the bug submission, especially since we can't use labels here.

**Comment by federico-terzi** [comment]
Hey @MikhailTNY,

Thank you for the feedback! Good point, we should add it

Cheers :)

**Comment by federico-terzi** [comment]
I've added a couple of templates, thanks for suggesting!
