### ISSUE TITLE
Missing buttons on the migration view on W11

### ISSUE THREAD

**Issue by MikhailTNY** [federico-terzi/espanso#871]
Hi, 

On W11, I can't see the two buttons on the migration to perform the migration. 

![image](https://user-images.githubusercontent.com/689173/141654117-ce991759-e03f-494f-addf-c57b585a0804.png)

This is with the **v2.1.0-alpha**.

**Comment by federico-terzi** [comment]
Hey @MikhailTNY,

Thanks for reporting this issue! This definitely looks like a bug. Are you using display scaling? If so, at which setting?

Cheers :)

**Comment by MikhailTNY** [comment]
Yes, 150% with 4K 27” monitor.

**Comment by federico-terzi** [comment]
@MikhailTNY Makes sense, thanks!
