### ISSUE TITLE
Espanso paste 2 differents things in 2 different apps from the same trigger

### ISSUE THREAD

**Issue by hedonnn** [federico-terzi/espanso#876]
Version 2.0. on Windows 10

A replacement created with "|" in order to be copied as-is is copied exactly as intended in a desktop application (here OneNote) but only paste the last thing from the clipboard in Gmail (in browser, here Brave).

The bug persists wether backend: Clipboard is commented or not.

**Comment by federico-terzi** [comment]
Hey @DamienCasoni,

I'm sorry you experienced this problem! Could you please try adding the following line to you `config/default.yml` file and see if that helps? (increase the value as needed)

```yaml
pre_paste_delay: 500
```

If that works, we can then create an app-specific patch for brave

Cheers :)

**Comment by DamienCasoni** [comment]
It works! Thank you! I've been trying different values, the lowest which works for me is 400.

**Comment by federico-terzi** [comment]
@DamienCasoni Nice! I'm writing the relevant documentation in the upcoming days, but we might want to create a patch for it. Does this problem happen only in Brave?

**Comment by hedonnn** [comment]
@federico-terzi I haven't noticed it anywhere else so far.
