### ISSUE TITLE
Espanso showing Square Boxes instead of Fonts in Espanso Form

### ISSUE THREAD

**Issue by bsahane** [federico-terzi/espanso#877]
**Espanso showing Square Boxes instead of Fonts in Espanso Form**

Installed espanso on Fedora 35 using [documentation](https://espanso.org/docs/next/install/linux/)
``` bash
sudo snap install espanso --classic --channel=latest/edge
```
Everything working properly except "[Espanso From](https://espanso.org/docs/next/matches/forms/)" as it shows Square Boxes instead of Fonts

Code in base.yml config
``` yaml
  - trigger: ":greet"
    form: |
      Hey [[name]],
      Happy Birthday!
```
Output of `:greet`
![image](https://user-images.githubusercontent.com/3491929/142015475-61b85527-f473-48be-a880-ca93c95d4b8e.png)

Even Typed Text shown in Square Boxes
![image](https://user-images.githubusercontent.com/3491929/142016198-3f50adcc-e10f-42d6-85fd-4da1e134fa83.png)

But after click on button show correct output as
``` md
Hey Test,
Sample Test
Happy Birthday!
```
---
**Setup information**
- Operating System: `Fedora Linux 35 (Workstation Edition)`
- Espanso Version: `espanso 2.1.0-alpha`

**Comment by federico-terzi** [comment]
Hey @bsahane,

Thanks for reporting this issue! That's very interesting, could you please run the following commands and post the output here?

```
locale
localectl status
```

Cheers :)

**Comment by bsahane** [comment]
Hello @federico-terzi Thank you for response

Please find the output for your reference
```bash
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```bash
$ localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```

**Comment by federico-terzi** [comment]
@bsahane Thanks! That's _very_ interesting, given that the US locale should be the most widely supported one :) I'll investigate

**Comment by bsahane** [comment]
Thank You @federico-terzi please take your time..

**Comment by federico-terzi** [comment]
Hey @bsahane,

I've investigated a bit, and there seem to be some possible workarounds:

* https://askubuntu.com/questions/1103560/only-squares-instead-of-letters-and-numbers-are-displayed-in-my-calculator-and-o
* https://askubuntu.com/questions/843533/text-has-turned-to-boxes-in-ubuntu-16-04

When you have the chance, could you please check if those steps are helpful? :)

Cheers :)

**Comment by bsahane** [comment]
Hello @federico-terzi,
Thank you for the update, 
I tried both possible workarounds but It doesn't work for me

**Comment by federico-terzi** [comment]
@bsahane I see, thanks for trying! I'll keep investigating then :)

**Comment by bsahane** [comment]
Hello @federico-terzi,

I think square boxes showing instead of fonts due to snap package, I found this link

* https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/11

But not found any solution from here.

**Comment by federico-terzi** [comment]
@bsahane Thanks! Perhaps, this one might help? https://askubuntu.com/a/1228809

It seems to be related to a snap package

**Comment by bsahane** [comment]
Thank You @federico-terzi for your Troubleshooting and Help.

**Comment by federico-terzi** [comment]
@bsahane Awesome, thanks!

> Whenever possible, please build a standalone .rpm version for RPM-based Distros.

I'll see what we can do :) #596 

Cheers :)

**Comment by ddfonseca** [comment]
I'm just commenting that

rm -rf ~/.cache/fontconfig 
sudo fc-cache -r -v

works for me.

**Comment by ksad** [comment]
@ddfonseca thanks for the trick, it works well me
