### ISSUE TITLE
Usage of Multiple Profiles

### ISSUE THREAD

**Issue by yosamshiyam** [federico-terzi/espanso#879]
I actually got this idea from Karabiner-Elements, an app I use regularly on my mac.

My idea is this:  it would be nice if there was somehow the ability to have multiple profiles.  A case usage would be, let's say the language I'm typing in is Ancient Greek; and I prefer to have my shortcuts geared towards to the phonetics of the language.  Thus, let's suppose I was to type "θ" on my mac.  Theta, intuitively thus would be spelt with a "th".  But oridinarily, if I set "th" to be short-cutted, I'd run into immediate problems in typing the word...well....THE when I come back to writing in english! 

So it would be swell, if I had two profiles set up.  One for each language, with specific shortcuts geared towards each language or state that while ordinarily would overlap, don't because they're in two distinct profiles.

I realize this is a lot to code, but the thought came to be, so I decided to shoot it out!

**Comment by federico-terzi** [comment]
Hey @yosamshiyam,

Thank you for the feedback! This seems similar to https://github.com/federico-terzi/espanso/issues/462 and should be relatively feasible with the new v2 architecture.

I'm closing this one in favor of the other one, feel free to continue the discussion there!

Cheers :)
