### ISSUE TITLE
Espanso does not update clipboard properly.

### ISSUE THREAD

**Issue by ChristopherLittle51** [federico-terzi/espanso#885]
**Describe the bug**
After typing a trigger, the text is replaced with text from the clipboard instead of the match programmed for the trigger. This only applies when matches are pasted using the clipboard. There is a delay of up to 30 seconds before the clipboard content (not the correct match) is pasted. Clipman shows no change in the clipboard history. EDIT: After updating to the 5.15.2-2 Kernel, the clipboard is being updated, but it is still pasting the previous clipboard contents.

**To Reproduce**
1. Type trigger. 
2. Wait for up to 30 seconds.
3. Clipboard content is pasted.

**Expected behavior**
Correct match pasted instead of clipboard content.

**Logs**

> 09:28:51 [daemon(3176)] [INFO] reading configs from: "/home/cl/.config/espanso"
> 09:28:51 [daemon(3176)] [INFO] reading packages from: "/home/cl/.config/espanso/match/packages"
> 09:28:51 [daemon(3176)] [INFO] using runtime dir: "/home/cl/.cache/espanso"
> 09:28:51 [daemon(3176)] [INFO] watching for changes in path: "/home/cl/.config/espanso"
> 09:28:51 [daemon(3176)] [INFO] espanso version: 2.1.1-alpha
> 09:28:51 [daemon(3176)] [INFO] spawning the worker process...
> 09:28:51 [daemon(3176)] [INFO] binded to IPC unix socket: /home/cl/.cache/espanso/espansodaemonv2.sock
> 09:28:51 [worker(3184)] [INFO] reading configs from: "/home/cl/.config/espanso"
> 09:28:51 [worker(3184)] [INFO] reading packages from: "/home/cl/.config/espanso/match/packages"
> 09:28:51 [worker(3184)] [INFO] using runtime dir: "/home/cl/.cache/espanso"
> 09:28:51 [worker(3184)] [INFO] using X11AppInfoProvider
> 09:28:51 [worker(3184)] [INFO] binded to IPC unix socket: /home/cl/.cache/espanso/espansoworkerv2.sock
> 09:28:51 [worker(3184)] [INFO] using X11Source
> 09:28:51 [worker(3184)] [INFO] monitoring the status of the daemon process
> 09:28:51 [worker(3184)] [INFO] using X11Injector
> 09:28:51 [worker(3184)] [INFO] using X11Clipboard
> 

**Setup information**
- OS: Manjaro Linux XFCE 4.16 (Also experienced this same issue in Gnome 40 on Wayland, currently using X11)
> OS: Manjaro Linux x86_64 
> Host: MS-7C91 2.0 
> Kernel: 5.15.2-2-MANJARO 
> Uptime: 19 mins 
> Packages: 1172 (pacman) 
> Shell: bash 5.1.8 
> Resolution: 2560x1440, 2560x1080 
> DE: Xfce 4.16 
> WM: Xfwm4 
> WM Theme: Desert_Dark-main 
> Theme: Desert_Dark-main [GTK2/3] 
> Icons: Papirus-Adapta-Nokto-Maia [GTK2/3] 
> Terminal: xfce4-terminal 
> Terminal Font: Monospace 12 
> CPU: AMD Ryzen 5 3500 (6) @ 3.600GHz 
> GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
> Memory: 4823MiB / 32090MiB 

- Version: espanso 2.1.1-alpha (built from AUR espanso-git package)

**Comment by federico-terzi** [comment]
Hey @ChristopherLittle51,

Thanks for reporting this issue! A couple of questions:
* Does it happen on every application?
* Can you try following these instructions and see if that helps? https://github.com/federico-terzi/espanso/issues/876#issuecomment-969239204

Cheers :)

**Comment by ChristopherLittle51** [comment]
Thanks for replying.
It was happening in every app I've tried so far, but I sat down and tried a few others and I'm getting some weird results:

- In Firefox 94.0.2, it does not work on helpscout.net (My work email software) but it works just fine in this textbox on GitHub. It works in Pastebin, notes.cx and gmail/gsuite.
- In Mousepad, it did not work, and after repeated attempts at entering a trigger it crashed and started a coredump: [Pastebin](https://pastebin.com/b2BsgYkt)
- In Notepadqq it works fine. 
- In OnlyOffice it works fine.
- The built in "Notes" app in Manjaro, it doesn't work.

Adding that line to the default.yml file did not appear to change this behaviour for better or worse. Removing it again and reloading espanso retained the same behaviour.

Simple enough, it's basically only broken on a few websites. The problem being ofcourse that I do 95% of my work on this one website (helpscout.net). 

Thank you for your help. I will keep looking into this and seeing if I can track down anything that sticks out.

**Comment by federico-terzi** [comment]
@ChristopherLittle51 Thanks! In the next release (2.1.1-alpha) I'll ship an alternative clipboard backend, which might improve the situation :) Hopefully, that will help

**Comment by ChristopherLittle51** [comment]
I've uninstalled my previous AUR installation and switched to the 2.1.1-alpha AppImage, still experiencing the same issues as before. Is there another step I should take to enable the new backend?

**Comment by federico-terzi** [comment]
Hey @ChristopherLittle51,

I'm sorry about that! I completely forgot to point out the new option :) 
Make sure to have the `xclip` command installed (you can install it from most distros package managers), then add the following to your `$CONFIG/config/default.yml` file:

```
x11_use_xclip_backend: true
```

Let me know if that helps :)

**Comment by ChristopherLittle51** [comment]
Still no dice, unfortunately. Here's the relevant logs:

> 11:39:53 [daemon(10179)] [INFO] reading configs from: "/home/cl/.config/espanso"
11:39:53 [daemon(10179)] [INFO] reading packages from: "/home/cl/.config/espanso/match/packages"
11:39:53 [daemon(10179)] [INFO] using runtime dir: "/home/cl/.cache/espanso"
11:39:53 [daemon(10179)] [INFO] watching for changes in path: "/home/cl/.config/espanso"
11:39:53 [daemon(10179)] [INFO] espanso version: 2.1.1-alpha
11:39:53 [daemon(10179)] [INFO] spawning the worker process...
11:39:53 [daemon(10179)] [INFO] binded to IPC unix socket: /home/cl/.cache/espanso/espansodaemonv2.sock
11:39:53 [worker(10187)] [INFO] reading configs from: "/home/cl/.config/espanso"
11:39:53 [worker(10187)] [INFO] reading packages from: "/home/cl/.config/espanso/match/packages"
11:39:53 [worker(10187)] [INFO] using runtime dir: "/home/cl/.cache/espanso"
11:39:53 [worker(10187)] [INFO] binded to IPC unix socket: /home/cl/.cache/espanso/espansoworkerv2.sock
11:39:53 [worker(10187)] [INFO] monitoring the status of the daemon process
11:39:53 [worker(10187)] [INFO] using X11AppInfoProvider
11:39:53 [worker(10187)] [INFO] using X11Source
11:39:53 [worker(10187)] [INFO] using X11Injector
11:39:53 [worker(10187)] [INFO] using X11Clipboard
11:39:56 [worker(10187)] [ERROR] attempted to use XClipClipboard, but `xclip` command can't be called
11:39:56 [worker(10187)] [ERROR] text injector (clipboard) reported an error: attempted to use XClipClipboard, but `xclip` command can't be called

`Journalctl -xe` provides the same lines, but with a bit extra before "Using X11Injector": 
> Dec 03 11:47:27 <Hostname> Espanso.AppImage[11411]: X11 Reported an error, code: 10, request_code: 33, minor_code: 0
Dec 03 11:47:27 <Hostname> Espanso.AppImage[11411]: X11 Reported an error, code: 10, request_code: 33, minor_code: 0
Dec 03 11:47:27 <Hostname> Espanso.AppImage[11411]: X11 Reported an error, code: 10, request_code: 33, minor_code: 0
Dec 03 11:47:27 <Hostname> Espanso.AppImage[11411]: X11 Reported an error, code: 10, request_code: 33, minor_code: 0


I've uninstalled and reinstalled xclip from pacman several times, and even attempted to use the xclip-git package from the AUR. I've also tried rebooting and complete cold boots to no avail. I am able to call xclip from the command line no problem, like using `xclip -o` to paste highlighted text on screen.
Now, it's no longer working in the apps/sites it was working on previously. If I disable the option `x11_use_xclip_backend`, it begins working on the applications it was working on before, but still not on helpscout.net.

Please let me know if there's any other debugging steps I need to take. I have tried what I know to try so far.

**Comment by federico-terzi** [comment]
@ChristopherLittle51 Thank you! I've realized that I mistakenly called `xclipz` instead of `xclip` in the new backend, which caused Espanso to not find the command! I'm sorry about that :) https://github.com/federico-terzi/espanso/commit/74c5e5ae86521e27ed34dcd1f80d1e695a92a580

I've pushed a fix. When you have the chance, please update Espanso from the `espanso-git` AUR package and restart it with `espanso restart`.

Let me know if that helps (make sure to keep `x11_use_xclip_backend: true` to use the new backend)

Cheers :)

**Comment by ChristopherLittle51** [comment]
Thank you! Sorry, I was out of town all weekend and couldn't test, so just got to it today.
The clipboard is now working, matches are instantly inserted after typing the trigger. However, there's now a new problem: Newlines are now being folded instead of keeping the line breaks.

Example: 
```
matches:
  - trigger: "+test"
    replace: |
              Dashing through the snow,
            
              in a one horse open sleigh,
            
              o'er the fields we go,
            
              laughing all the way!
```
becomes:

Dashing through the snow, in a one horse open sleigh, o'er the fields we go, laughing all the way!

But only on the same websites/apps as before.

**Comment by federico-terzi** [comment]
@ChristopherLittle51 That's interesting... I'll investigate, thanks!

**Comment by federico-terzi** [comment]
Hey @ChristopherLittle51, when you have the chance, could you please try with the markdown option to see if that helps?

Something like:

```
matches:
  - trigger: "+test"
    markdown: |
              Dashing through the snow,
            
              in a one horse open sleigh,
            
              o'er the fields we go,
            
              laughing all the way!
```

Cheers :)

**Comment by ChristopherLittle51** [comment]
This is much closer to the intended output, however we are still missing line breaks. For example the above config results in the lines being on separate lines, but there is no space between them: 
```
Dashing through the snow,
in a one horse open sleigh,
o’er the fields we go,
laughing all the way!
```
When the intended effect is an empty line between each line:

``` 
Dashing through the snow,

in a one horse open sleigh,

o’er the fields we go,

laughing all the way!
```

It's more workable, for sure. Some stuff will have to be edited with the markdown-style line endings (space, space, return) otherwise it still comes out on one line.

I did just get a strange glitch when using it in this text box though. 
```
瀼䐾獡楨杮琠牨畯桧琠敨猠潮ⱷ⼼㹰ਊ瀼椾⁮⁡湯⁥潨獲⁥灯湥猠敬杩ⱨ⼼㹰ਊ瀼漾⌦㈸㜱攻⁲桴⁥楦汥獤眠⁥潧㰬瀯ਾ㰊㹰慬杵楨杮愠汬琠敨眠祡㰡瀯ਾ㰊牰㹥挼摯㹥†††††⼼潣敤㰾瀯敲>
```

For reference: I inserted the match config you posted above into a .yml in the match folder. (Mine is called freight.yml). I typed `+test` in Helpscout's message field and got the jingle bells lyrics, but typing `+test` in GitHub's reply field generated this gibberish.

I don't see anything out of line in espanso log or journalctl. 
Trying one of my other matches just generates a longer string of gibberish:
```
瀼吾慨歮礠畯映牯瀠潲楶楤杮琠楨⁳湩潦浲瑡潩Ⅾ䤠⌦㈸㜱氻⁬桳牡⁥瑩眠瑩⁨桴⁥敲瑳漠⁦祭琠慥⹭⼼㹰ਊ瀼䠾牥♥㠣ㄲ㬷⁳桷瑡琠⁯硥数瑣㰺瀯ਾ㰊㹰胢₢潙牵漠摲牥眠汩⁬敢楧⁮牰捯獥楳杮‮敗愠敲挠潬敳⁤湯眠敥敫摮⁳湡⁤潨楬慤獹㰮瀯ਾ㰊㹰胢₢癅牥⁹牯敤⁲楷汬朠⁯桴潲杵⁨⁡牰ⵥ桳灩楰杮挠敨正㰮瀯ਾ㰊㹰胢₢晁整⁲桴⁥档捥Ⱬ礠畯⁲牯敤⁲楷汬戠⁥楰正摥甠⁰祢琠敨猠楨灰湩⁧潣灭湡⹹⼼㹰ਊ瀼ꊀ传据⁥⁉敲散癩⁥牴捡楫杮椠普Ɐ䤠眠汩⁬灵慤整漠⁮䉥祡猠⁯桴瑡礠畯挠湡琠慲正礠畯⁲牯敤⹲⼼㹰ਊ瀼ꊀ夠畯挠湡甠敳琠敨猠楨灰湩⁧潣灭湡馀⁳敷獢瑩⁥潴琠慲正礠畯⁲牯敤⹲⼼㹰ਊ瀼嘾獩瑩礠畯⁲異捲慨敳栠獩潴祲琠⁯楶睥琠慲正湩⁧湩潦浲瑡潩⁮湯散甠摰瑡摥‬牯挠灯⁹湡⁤慰瑳⁥桴獩唠䱒椠瑮⁯潹牵戠潲獷牥㰺瀯ਾ㰊㹰瑨灴㩳⼯睷⹷扥祡挮浯洯批倯牵档獡䡥獩潴祲⼼㹰ਊ瀼䐾敵琠⁯桴⁥敭桴摯漠⁦敤楬敶祲‬䉥祡⌦㈸㜱猻琠慲正湩⁧敳癲捩⁥楷汬渠瑯眠牯⁫潦⁲桴獩猠楨浰湥⹴夠畯挠湡攠瑮牥琠敨琠慲正湩⁧畮扭牥漠⁮桴⁥牦楥桧⁴慣牲敩♲㠣ㄲ㬷⁳敷獢瑩⁥愨獬⁯慣汬摥琠敨倠佒丠浵敢⥲㰮瀯ਾ㰊㹰潙⁵慣⁮捳敨畤敬搠汥癩牥⁹獵湩⁧桴⁥慣牲敩♲㠣ㄲ㬷⁳慮敭愠摮琠慲正湩⁧畮扭牥‮敓牡档映牯琠敨挠牡楲牥⌦㈸㜱猻渠浡⁥桴瑡椠⁳楤灳慬敹⁤湯攠慂ⱹ愠摮礠畯眠汩⁬楦摮戠瑯⁨桴⁥慣牲敩♲㠣ㄲ㬷⁳敷獢瑩⁥湡⁤桰湯⁥畮扭牥㰮瀯ਾ㰊㹰汐慥敳搠⁯潮⁴敨楳慴整琠⁯潣瑮捡⁴敭椠⁦潹⁵慨敶愠祮焠敵瑳潩獮㰮瀯>
```

Weird.

**Comment by ChristopherLittle51** [comment]
I did find another issue that appears to be the same result:
https://github.com/symless/synergy-core/issues/316

Looks like pasting with styles here is causing characters to be mapped incorrectly.

**Comment by federico-terzi** [comment]
@ChristopherLittle51 That's interesting!

Perhaps, you can "force" additional newlines by using HTML with the `<br>` tag, such as:

```yaml
matches:
  - trigger: "+test"
    html: |
              Dashing through the snow, <br><br> 
              in a one horse open sleigh,  <br><br> 
              o'er the fields we go, <br><br>
              laughing all the way!
```

Let me know if that helps :)

> Now for everywhere the earlier code was working (notes.cx, github, gmail, trello) it's generating gibberish when using the markdown option. It's not generating gibberish on Helpscout.net or mousepad.

This is pretty strange... Unfortunately, I can't reproduce it on my machine. Please let me know if you find a reproducible way to trigger this behavior :)

**Comment by ChristopherLittle51** [comment]
I was unable to find a solution, and I've ended up switching to Debian Testing. Working great on Wayland so far. I am thinking there were issues with my Manjaro install as I began experiencing other issues later on. 

Thanks for all your help!

**Comment by JohnFinn** [comment]
Having same issue on wayland
```
01:45:33 [daemon(52695)] [INFO] reading configs from: "/home/jouni/.config/espanso"
01:45:33 [daemon(52695)] [INFO] reading packages from: "/home/jouni/.config/espanso/match/packages"
01:45:33 [daemon(52695)] [INFO] using runtime dir: "/home/jouni/.cache/espanso"
01:45:33 [daemon(52695)] [INFO] system info: NixOS v23.11 - kernel: 6.1.84
01:45:33 [daemon(52695)] [WARN] keyboard layout watcher couldn't determine active layout.
01:45:33 [daemon(52695)] [INFO] espanso version: 2.2.1
01:45:33 [daemon(52695)] [INFO] watching for changes in path: "/home/jouni/.config/espanso"
01:45:33 [daemon(52695)] [INFO] spawning the worker process...
01:45:33 [daemon(52695)] [INFO] binded to IPC unix socket: /home/jouni/.cache/espanso/espansodaemonv2.sock
01:45:33 [worker(52701)] [INFO] reading configs from: "/home/jouni/.config/espanso"
01:45:33 [worker(52701)] [INFO] reading packages from: "/home/jouni/.config/espanso/match/packages"
01:45:33 [worker(52701)] [INFO] using runtime dir: "/home/jouni/.cache/espanso"
01:45:33 [worker(52701)] [INFO] system info: NixOS v23.11 - kernel: 6.1.84
01:45:33 [worker(52701)] [INFO] binded to IPC unix socket: /home/jouni/.cache/espanso/espansoworkerv2.sock
01:45:33 [worker(52701)] [INFO] using WaylandAppInfoProvider
01:45:33 [worker(52701)] [INFO] detection module will use this keyboard layout: [R=, M=, L=us, V=, O=]
01:45:33 [worker(52701)] [INFO] monitoring the status of the daemon process
01:45:33 [worker(52701)] [INFO] using EVDEVSource
01:45:33 [worker(52701)] [INFO] Querying modifier status...
01:45:33 [worker(52701)] [INFO] inject module will use this keyboard layout: [R=, M=, L=us, V=, O=]
01:45:33 [worker(52701)] [INFO] using EVDEVInjector
01:45:33 [worker(52701)] [INFO] using WaylandFallbackClipboard
```
on alacritty clipboard content is pasted, and in chrome the correctly expanded text
