### ISSUE TITLE
Doesn't work in web browser password field.

### ISSUE THREAD

**Issue by singlexyz** [federico-terzi/espanso#889]
Password input for webpage， the trigger doesn't replace.

Is there a way to make it works even when the password is entered? 

<img width="365" alt="图片" src="https://user-images.githubusercontent.com/4456413/143686048-8f1f68dc-0920-47ca-b064-d2dc91475332.png">

**Comment by federico-terzi** [comment]
Hey @singlexyz,

Thanks for reporting this issue! Are you on macOS?

Cheers :)

**Comment by singlexyz** [comment]
> Hey @singlexyz,
> 
> Thanks for reporting this issue! Are you on macOS?
> 
> Cheers :)

Yes, It's macOS Monterey 12.01. Test on all browsers.

**Comment by federico-terzi** [comment]
@singlexyz Nice! Thank you, makes sense.

MacOS has a security feature called "SecureInput" that prevents regular expansions from working inside password fields. So unfortunately, regular expansions will never work inside password fields. That said:

* Once https://github.com/federico-terzi/espanso/issues/383 is implemented, you'll be able to use a keyboard shortcut to trigger an expansion inside a password field
* If you use the new v2, you can also use the search bar to inject the text inside the password field. You first need to open it with ALT+SPACE and then select the desired snippet

Cheers :)

**Comment by singlexyz** [comment]
> @singlexyz Nice! Thank you, makes sense.
> 
> MacOS has a security feature called "SecureInput" that prevents regular expansions from working inside password fields. So unfortunately, regular expansions will never work inside password fields. That said:
> 
>     * Once [Way to run a match using a keyboard shortcut #383](https://github.com/federico-terzi/espanso/issues/383) is implemented, you'll be able to use a keyboard shortcut to trigger an expansion inside a password field
> 
>     * If you use the new v2, you can also use the search bar to inject the text inside the password field. You first need to open it with ALT+SPACE and then select the desired snippet
> 
> 
> Cheers :)

Ah, I see. and SecureInput looks can't disabled.
And I dynamically changed the password filed to text filed, it still didn't work.
Then I make a script, when the password field focus:
Create a temporary text field so that espanso can be used in it, 
and then synchronize to the password field.
This can be applied to most web pages, haha.

https://gist.github.com/singlexyz/249fa242135fda51a509e8411c1984cd

![ezgif-2-1f18d2b6c11a](https://user-images.githubusercontent.com/4456413/144657444-885fc8fe-8529-4b84-b55c-16dcd0b01dea.gif)

**Comment by federico-terzi** [comment]
@singlexyz That's really interesting! Thanks for sharing :)
