### ISSUE TITLE
Cannot change config directory

### ISSUE THREAD

**Issue by Wittionary** [federico-terzi/espanso#891]
**Describe the bug**
I attempt to change the config directory via CLI. The help text is returned and the config path is not updated.

**To Reproduce**
I've tried all of the following in an administrative pwsh prompt.
````powershell
espanso.cmd -v --config_dir C:\Users\myusername\Dropbox\Apps\espanso
espanso.cmd --config_dir C:\Users\myusername\Dropbox\Apps\espanso
espanso.cmd --config_dir C:\Users\myusername\Dropbox\Apps\espanso -v
espanso.cmd --config_dir "C:\Users\myusername\Dropbox\Apps\espanso"
espanso.cmd --config_dir "C:\\Users\\myusername\\Dropbox\\Apps\\espanso"
````

**Expected behavior**
A message notifying me the config path had been updated and a notification saying the config had been reloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1906737/143804731-c94987c7-a76f-4e78-a3a1-41b64e4b0a3d.png)

**Logs**
````pwsh
21:15:56 [daemon(1804)] [INFO] reading configs from: "C:\\Users\\myusername\\AppData\\Roaming\\espanso"
21:15:56 [daemon(1804)] [INFO] reading packages from: "C:\\Users\\myusername\\AppData\\Roaming\\espanso\\match\\packages"
21:15:56 [daemon(1804)] [INFO] using runtime dir: "C:\\Users\\myusername\\AppData\\Local\\espanso"
21:15:56 [daemon(1804)] [INFO] watching for changes in path: "C:\\Users\\myusername\\AppData\\Roaming\\espanso"
21:15:56 [daemon(1804)] [INFO] espanso version: 2.1.0-alpha
21:15:56 [daemon(1804)] [INFO] spawning the worker process...
21:15:56 [daemon(1804)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
21:15:56 [worker(13980)] [INFO] reading configs from: "C:\\Users\\myusername\\AppData\\Roaming\\espanso"
21:15:56 [worker(13980)] [INFO] reading packages from: "C:\\Users\\myusername\\AppData\\Roaming\\espanso\\match\\packages"
21:15:56 [worker(13980)] [INFO] using runtime dir: "C:\\Users\\myusername\\AppData\\Local\\espanso"
21:15:56 [worker(13980)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
21:15:56 [worker(13980)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
21:15:56 [worker(13980)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
21:15:56 [worker(13980)] [INFO] monitoring the status of the daemon process
21:15:56 [worker(13980)] [INFO] using Win32AppInfoProvider
21:15:56 [worker(13980)] [INFO] using Win32Source
21:15:56 [worker(13980)] [INFO] using Win32Injector
21:15:56 [worker(13980)] [INFO] using Win32Clipboard
````

**Setup information**
- OS: What OS are you using?
- Win11 Version 21H2
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)
- 2.1.0-alpha

**Comment by federico-terzi** [comment]
Hey @Wittionary,

I'm sorry you experienced this problem! The `--config_dir` command line option is used to override the config directory for the current run, it's not a way to permanently change the directory :)

If you want to do so, your best bet is to define a `ESPANSO_CONFIG_DIR` environment variable with your desired path (like `C:\Users\user\Documents\espanso`), and then restart your PR/espanso.

Let me know if that helps

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions!
Cheers :)
