### ISSUE TITLE
"Why is espanso not working?" link is broken

### ISSUE THREAD

**Issue by kud** [federico-terzi/espanso#892]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/655838/144431998-150ad5b6-bd8d-4aac-9a20-038d53acfb07.png">

**Comment by federico-terzi** [comment]
Hey @kud,

Thanks for reporting this issue! You are absolutely right, I forgot to update the link and create the appropriate documentation page! I'll add it to the roadmap

Cheers :)

**Comment by kud** [comment]
Thank you 😊

**Comment by federico-terzi** [comment]
Hey,

The next version 2.1.3-alpha will include a fix for this problem and will link to [this new page](https://espanso.org/docs/next/troubleshooting/secure-input/), thank you for the help! :)

Cheers :)

**Comment by kud** [comment]
Thanks!
