### ISSUE TITLE
Espanso doesn't work on Brave + Windows 10

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#894]
As reported by @Lissy93, I'm opening a separate discussion to investigate this further :)

I'm seeing this issue too, I'm using Brave Browser v 1.32.113, which is based on Chromium 96. Espanso is working perfectly in every app other than Chromium, no errors or anything, just none of my bindings have any effect. This issue started a few months ago.

I don't think it's an issue with Espanso per se, but rather something to do with the way that Chrome sandboxes processes. Although not entirely sure why this would be the case, or what the correct fix would be. But as a workaround, it does actually work perfectly if you run Espanso as administrator.

**Comment by federico-terzi** [comment]
Hey @Lizzy93,

I've been testing Espanso with Brave (same version) and it seems to work fine for me. Reading online I've stumbled upon this Reddit thread: https://www.reddit.com/r/productivity/comments/ac8ahi/textexpander_not_working_with_chrome_browser/

Nothing too useful, but it got me thinking. Are you running some software related to security (antivirus) or something related to keyboard (like a debouncer)?

Thanks for your help :)

**Comment by Lissy93** [comment]
Heya, so sorry for the late response, totally forgot to come back to this

I did try to figure out if it could be something else running, but without success. That said, the issue now seems to come and go, and is quite temperamental. I think it's most likely not an issue with Espanso, but some conflict or privacy setting somewhere. So unless anyone others are experiencing the same thing, it's probably worth closing the ticket

Thank you again for all your work on Espanso, it's an awesome project, and really neatly implemented. And thank you for your help with this issue, really appreciate it :)

**Comment by JeppeKlitgaard** [comment]
I am running Brave on Windows 10 and have not experienced any problems with Espanso alpha so far, though I don't often use expansions that often in the browser.

**Comment by federico-terzi** [comment]
Thanks guys! I'm closing the issue for now, but feel free to reopen it if you discover something else that could help us debug the issue :)

Cheers :)
