### ISSUE TITLE
100 Character Limit On Linux Wayland?

### ISSUE THREAD

**Issue by y20k** [federico-terzi/espanso#895]
**Describe the bug**
Espanso seems to have a character limit set to 100 characters on Linux / Wayland

**To Reproduce**
1. create two new entries in base.yml
```
  - trigger: ":100"
    replace: "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"

  - trigger: ":101"
    replace: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901"

```
2. compare the outcome. 
`:100` gets expanded correctly
`:101` produces a short flicker on screen, the string ":101" disappears, nothing gets exanped

**Expected behavior**
There should be no character limit. 
Or the limit should be at ... say 1000 characters.

**Setup information**
- OS: Fedora Linux 35 (Workstation Edition) - Wayland
- Version: v2.1.0-alpha

**Comment by federico-terzi** [comment]
Hey @y20k,

I'm sorry you experienced this problem!

> Espanso seems to have a character limit set to 100 characters on Linux / Wayland

After 100 characters, Espanso switches to the "clipboard mode", which is faster than regular injection but relies on a different mechanism. For some reason, it seems that the clipboard backend is not working on your machine.

Could you please try adding the following line to your `$CONFIG/config/default.yml` file and see if that helps?

```yaml
paste_shortcut: "SHIFT+INSERT"
```

You can also force Espanso to avoid the "clipboard mode" switch entirely by adding the following to your `$CONFIG/config/default.yml` file:

```yaml
clipboard_threshold: 10000
```

but I would personally advise against it if possible, as it's needed when you want to inject special characters (such as emojis) and images...

Cheers :)

**Comment by y20k** [comment]
Good evening @federico-terzi 

Thank you.

```
paste_shortcut: "SHIFT+INSERT"
```

solved the issue. 

Please let me know, if I can be of further assistance.

:beers:

**Comment by federico-terzi** [comment]
@y20k Nice! I'll make sure to set `SHIFT+INSERT` as the default shortcut on Wayland then :)
