### ISSUE TITLE
Add the M1-friendly version of Espanso to Homebrew

### ISSUE THREAD

**Issue by SquareBottle** [federico-terzi/espanso#897]
**Is your feature request related to a problem? Please describe.**
I have a strong preference for using package managers whenever possible, and I know I'm not alone! So, it's unfortunate that Homebrew is no longer supported.

**Describe the solution you'd like**
Resume putting new versions of Espanso on Homebrew, please!

**Describe alternatives you've considered**
Installing "the normal way" is an option, but loses the benefits of package management. Also, other package managers exist for the mac platform, but Homebrew is the most popular by a wide margin.

**Comment by federico-terzi** [comment]
Hey,

Thank you for the feedback! I'll investigate the best way to bring Espanso v2 there, we'll probably need homebrew cask for this

Cheers :)

**Comment by federico-terzi** [comment]
This should be good to go now :) More info here: https://espanso.org/docs/next/install/mac/#install-using-homebrew
