### ISSUE TITLE
Block the install if newer espanso is installed

### ISSUE THREAD

**Issue by MikhailTNY** [federico-terzi/espanso#898]
**Describe the bug**
^ as the title said, do not allow 0.x version install over the 2.x versions. Force the user to uninstall 2.x first. 

**To Reproduce**
1. Install the latest 2.x alpha 
2. Spend a lot of time migrating the stuff
3. Install 0.7.3 because you forgot you were using 2.x alpha and all of the previous files were replaced

**Expected behavior**
I expected the installer to check that it is not going to overwrite 2.x install by accident. 

**Setup information**
- OS: Windows 11
- Version: espanso 2.1.1-alpha

**Comment by federico-terzi** [comment]
Hey @MikhailTNY,

I'm sorry you experienced this problem! Unfortunately, I don't think we'll be able to integrate a new check with the old 0.x version, as that release is mostly in maintenance mode now. Given the limited resources we have right now, I'd rather prefer improving the v2 than the v0.x, as the former will become the standard in early 2022. I hope you'll understand :)

Cheers :)
