### ISSUE TITLE
backend clipboard not working in termite/xterm/uxterm

### ISSUE THREAD

**Issue by cambid** [federico-terzi/espanso#90]
The default backend (under linux) clipboard doesn't work in the following terminals:
* termite
* uxterm
* xterm

After entering the trigger it deletes the trigger but doesn't input the replace text

The same configuration is working successfully under gnome-terminal.

**Comment by federico-terzi** [comment]
Hi @cambid,
Thanks for your feedback, I'll need to adjust the filters for those terminals.

It would be a great help if you could execute this commands and post the results:

Open a terminal and leave the `espanso detect` command running, then focus a window of each of these terminals and paste the results here.

Let me know if you need more information, thanks

**Comment by cambid** [comment]
Hi @federico-terzi 

Here are the detected informations of the problematic terminals:

```
Detected change, current window has properties:
==> Title: ''
==> Class: 'Termite'
==> Executable: '/usr/bin/termite'

Detected change, current window has properties:
==> Title: ''
==> Class: 'XTerm'
==> Executable: ''

Detected change, current window has properties:
==> Title: 'uxterm'
==> Class: 'UXTerm'
==> Executable: '/usr/bin/xterm'
```

**Comment by dlbradford** [comment]
Hi @federico-terzi,
I am experiencing what seems to be the same issue under KDE > konsole:
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'dave : bash — Konsole'
==> Class: 'konsole'
==> Executable: '/usr/bin/konsole'

Detected change, current window has properties:
==> Title: 'dave : espanso — Konsole'
==> Class: 'konsole'
==> Executable: '/usr/bin/konsole'

Detected change, current window has properties:
==> Title: 'dave : bash — Konsole'
==> Class: 'konsole'
==> Executable: '/usr/bin/konsole'

Detected change, current window has properties:
==> Title: 'dave : espanso — Konsole'
==> Class: 'konsole'
==> Executable: '/usr/bin/konsole'

**Comment by federico-terzi** [comment]
All right, thank you for your help @cambid and @dlbradford.
I will update espanso to support these terminals in the next release, that should be rolled out this weekend.

Thanks

**Comment by federico-terzi** [comment]
Hi guys,

I'm currently rolling out version 0.3.1 that should fix these problems. I didn't have much time to test it on every terminal. Let me know if you still experience any issues.

Thanks

**Comment by dlbradford** [comment]
Hi, Federico,
Using Pop!_OS 19.04, tested:
Xterm(330) works great.
konsole 19.04.3 works great.

Thank you so much for the quick turn around on this!

**Comment by federico-terzi** [comment]
@dlbradford You're welcome! And thank you for helping me making espanso better
