### ISSUE TITLE
Search Box is triggered when typing j-k-j

### ISSUE THREAD

**Issue by malwikl** [federico-terzi/espanso#903]
**Describe the bug**
When I type j-k-j  the search box opens
(without the -, but guess what, I cannot type it :-))

**To Reproduce**
1. Type j-k-j anywhere

**Screenshots**

![2021-12-08_13-12-27](https://user-images.githubusercontent.com/4599729/145206624-3c2d0f70-e795-465f-807d-374c2dcaa592.gif)

**Logs**
If12:56:22 [worker(15489)] [WARN] detected inconsistent modifier state for keys [(Control, 59), (Shift, 56)], sending compensating events...
13:06:39 [worker(15489)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...
13:08:07 [worker(15489)] [WARN] detected inconsistent modifier state for keys [(Meta, 55)], sending compensating events...

**Setup information**
- OS: MacOS 12.0.1
- Version: espanso 2.1.1-alpha

**Comment by federico-terzi** [comment]
Hey @malwikl,

I'm sorry you experienced this problem! This is expected, but you can disable this behavior by adding the following to your `$CONFIG/config/default.yml` file:

```yaml
search_trigger: off
```

The documentation is still lacking, but I'm working hard to bring it up to speed :)

Cheers :)
