### ISSUE TITLE
Search bar not working on Ubuntu, Pop!_OS 21.04. Espanso works correctly

### ISSUE THREAD

**Issue by jegornagel** [federico-terzi/espanso#907]
**Describe the bug**
The Espanso works correctly but Search bar doesn't appear when pressing Alt+Space. Modulo​ is installed. 

**Expected behavior**
When pressing ALT+Space the Search bar appears.

**Logs**
Nothing interesting here but:
```
16:57:14 [ INFO] espanso version 0.7.3
16:57:14 [ INFO] using config path: /home/nz/.config/espanso
16:57:14 [ INFO] using package path: /home/nz/.local/share/espanso/packages
16:57:14 [ INFO] spawning worker process...
16:57:14 [ INFO] Binded to IPC unix socket: /home/nz/.local/share/espanso/espanso.sock
16:57:14 [ INFO] initializing worker process...
16:57:14 [ INFO] Binded to IPC unix socket: /home/nz/.local/share/espanso/worker.sock
16:57:14 [ INFO] worker is running!
16:57:14 [ INFO] watching for changes in path: /home/nz/.config/espanso

```

**Setup information**
- OS: Pop!_OS 21.04.
- Version: 0.7.3 installed with .deb package https://espanso.org/docs/install/linux#installing-on-ubuntu--debian

**Comment by federico-terzi** [comment]
Hey @jegornagel,

I'm sorry you experienced this problem! If you want to use the search bar, you'll need to install version 2 :) See: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)
