### ISSUE TITLE
espanso detect doesn't see changes on Mac OS

### ISSUE THREAD

**Issue by adam-edison** [federico-terzi/espanso#91]
**Steps:**

Run

```bash
espanso detect
```

Notice the following output

```bash
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

Detected change, current window has properties:
==> Title: 'com.apple.Terminal'
==> Class: 'com.apple.Terminal'
==> Executable: '/Applications/Utilities/Terminal.app'
```

**Notes:**

Switch to many windows, like Slack or Notes. Whether or not you return focus to the Terminal, the output of `espanso detect` does not change. Typing (or not) in thes windows also does not cause the output to change.

**Environment:**

MacOS Mojave 10.14.6
espanso 0.3.0

**Comment by federico-terzi** [comment]
Hi @adam-edison,
Thank you for your feedback, this is strange indeed. Does it happen with every app?
Could you please post here the output of `espanso log`?

Regards

**Comment by adam-edison** [comment]
I'm noticing the `espanso restart` command doesn't work either. It somehow still has the previous default.yml cached. Due to both of those issues it makes the application unusable, and I've had to uninstall. 

At this point I don't think I have time to invest in this issue . Thanks for following up, though.

**Comment by federico-terzi** [comment]
That's strange indeed, I'm sorry you experienced those problems. I will reopen this issue to investigate further, though I won't ask you to help in the process as I understand you are busy.
You may want to consider unfollowing this issue to stop receiving notifications.

Thanks

**Comment by nikolai-cc** [comment]
On my mac the `detect` command doesn't seem to be working either. The `restart` command loads the new `default.yml` without any problems though.

This is the output of `espanso log` just after an `espanso restart`, `espanso detect`, and switching from terminal to safari, sublime text and back to the terminal. Output of `espanso detect` remains unchanged on terminal information:

```12:05:05 [ INFO] espanso version 0.3.1
12:05:05 [ INFO] using config path: /Users/nikolai/Library/Preferences/espanso
12:05:05 [ INFO] using package path: /Users/nikolai/Library/Application Support/espanso/packages
12:05:05 [ INFO] starting daemon...
12:05:05 [ INFO] Status icon already initialized, skipping.
12:05:05 [ INFO] Initializing EspansoNotifyHelper in /Users/nikolai/Library/Application Support/espanso
12:05:05 [ INFO] EspansoNotifyHelper already initialized, skipping.
12:05:05 [ INFO] Binded to IPC unix socket: /Users/nikolai/Library/Application Support/espanso/espanso.sock
12:05:05 [ INFO] espanso is running!```

Let me know if you need any more information!

**Comment by nikolai-cc** [comment]
One more thing, the filters **do** seem to work as intended.
added a file `test.yml` in the `espanso/user` folder with

```
filter_title: "Safari"

matches:
  - trigger: ";test"
    replace: "this works!"
```

It replaces `;test` with `this works!` in safari, but not terminal.

**Comment by timorunge** [comment]
@nikolai-cc I had the same problem with [alacritty](https://github.com/jwilm/alacritty). 

Changing the Backend to `Clipboard` was doing the trick for me (`~/Library/Preferences/espanso/user/io.alacritty.yml`). 

```
filter_title: "io.alacritty"

backend: "Clipboard"
```

**Comment by federico-terzi** [comment]
Hi @nikolai-cc,

Yesterday I released a fix for the `espanso detect` bug that was affecting macos users. It should be rolled out in the next release ( probably this weekend ).

Thanks for your feedback

**Comment by federico-terzi** [comment]
> @nikolai-cc I had the same problem with [alacritty](https://github.com/jwilm/alacritty).
> 
> Changing the Backend to `Clipboard` was doing the trick for me (`~/Library/Preferences/espanso/user/io.alacritty.yml`).
> 
> ```
> filter_title: "io.alacritty"
> 
> backend: "Clipboard"
> ```

Hi @timorunge, did you have this problem on Linux or MacOS? Thanks

**Comment by federico-terzi** [comment]
> @federico-terzi on MacOS.

All right thanks. So in your case espanso didn't work with alacritty by default, am I right? Because it could be worth it to open an issue if that's the case.

**Comment by timorunge** [comment]
> All right thanks. So in your case espanso didn't work with alacritty by default, am I right? Because it could be worth it to open an issue if that's the case.

That's correct. The Clipboard solution was sufficient for now. I'll create a new - more generic - ticket since I'm facing some other issues after reloading espanso.

**Comment by timorunge** [comment]
@federico-terzi: Quick heads up regarding `io.alacritty`: The problem is present on macOS 10.14 and sortable via the `Clipboard` backend. While on MacOS 10.15 it's vise versa.

**Comment by federico-terzi** [comment]
@timorunge all right, I expected some problems with the Catalina update. I'll need to find a way to test it on the new OS version. I'll wait for your issue now.
Thanks
