### ISSUE TITLE
Snap package requires the dependencies mentioned under "Manual installation"

### ISSUE THREAD

**Issue by iverik-no** [federico-terzi/espanso#913]
Installing Espanso via Snap. Apparently xclip and notify-send isn´t provided with the Snap. Since the only mention of extra dependencies is under "Manual installation", one is led to believe that this is the only circumstance where the dependencies are needed to be installed manually.

`libxtst6 libxdo3 xclip libnotify-bin`

As it turns out, I needed to install them after installing the Snap version to get it to run.
I would suggest to either have them included in the Snap (if that´s an option), or to update the docs to say that they need to be installed after installing the Snap :)

Output from terminal: 

```
USER@PC:~/Downloads$ sudo snap install espanso --classic
[sudo] password for USER:
2021-12-23T12:52:10+01:00 INFO Waiting for automatic snapd restart...
espanso 0.7.3 from Federico Terzi (federicoterzi) installed
USER@PC:~/Downloads$ espanso start
Error: 'notify-send' command is needed for espanso to work correctly, please install it.
Error: 'xclip' command is needed for espanso to work correctly, please install it.

Pre-check was not successful, espanso could not be started.
```

**To Reproduce**
1. Install espanso via Snap on a fresh distro install.
2. espanso start
3. Message in terminal, as provided above.

**Expected behavior**
Espanso should start, without missing dependencies.
Or there should be a clear explanation that the dependencies (libxtst6 libxdo3 xclip libnotify-bin) must be installed manually for the Snap too, not just under "Manual install".

**Setup information**
- OS: Kubuntu 21.10 with Backports (X11).
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @iverik-no,

Thanks for reporting this issue! This problem should have been fixed in the new version (v2), which is going to become stable soon. Therefore, I think it's safe to close this issue for now. 

Feel free to reopen if you have any concerns or you experience any problem with the new version :)

Cheers :)
