### ISSUE TITLE
Espanso is not configured to auto-start with Windows

### ISSUE THREAD

**Issue by MikhailTNY** [federico-terzi/espanso#918]
**Is your feature request related to a problem? Please describe.**
For some reason, I had to manually start Espanso every time I boot up Windows. I don't recall having to do this in the previous version. 

I checked my task manager, Espanso is not on the list. 

**Describe the solution you'd like**
I recommend adding Espanso to the startup list during the installation process. 

**Additional context**

Should add this to `status` command to confirm if it has been registered to start or not. 

This is on Windows 11.

**Comment by federico-terzi** [comment]
Hey @MikhailTNY,

I'm sorry you experienced this problem!

Could you please try running this command in the terminal and see if that helps?

```
espanso service register
```

Cheers :)

**Comment by MikhailTNY** [comment]
Hi @federico-terzi, 

That did work for me. Note that this wasn't mentioned in the expanso output ( _service       Register and manage 'espanso' as a system service_), I typed `espanso.cmd service` and nothing happened. I'd recommend updating that to show the extra commands or remove the need for `register`. 

Thanks!

**Comment by federico-terzi** [comment]
@MikhailTNY Makes sense, thanks!

I've opened an issue for that: https://github.com/federico-terzi/espanso/issues/920

Cheers :)
