### ISSUE TITLE
"Install for all users" - espanso installer

### ISSUE THREAD

**Issue by grenudi** [federico-terzi/espanso#919]
**Is your feature request related to a problem? Please describe.**
- At work, we have multiple accounts, and one admin account.   
Espanso works only on admin account, and I can't figure out a way to install it for all users.   
I can't even run it for a non admin user, using admin password. (portable version - same thing)  
  
**Describe the solution you'd like**  
- Option to install espanso for all users, like many other installers do (though I don't know how it's done)

**Describe alternatives you've considered**
- I'm using admin account atm. Couldn't find any better solution.

**Additional context**
- there is an error about failure to launch a daemon when I launch espansod.exe from admin on non admin account (I can attach screenshots and log later)

**Comment by federico-terzi** [comment]
Hey @grenudi,

Thanks for reporting this issue! That's interesting, I was going to suggest portable mode but it seems you already tried that.

I'm particularly curious about one thing: when you have the chance, could you please try running portable mode inside a non-admin user and then post the output here? I'm wondering if there could be some other software interfering with Espanso with non-admin users...

Cheers :)

**Comment by grenudi** [comment]
Hello @federico-terzi 
It's working after I've changed path for `espansod.exe` to absolute in `START_ESPANSO.bat` 
like so:
`start C:\Users\XXX\Desktop\espanso-portable\espansod.exe launcher`
and I launch  `START_ESPANSO.bat` as Admin with no issues now. 

Thank you for you time. Have a good day!

**Comment by federico-terzi** [comment]
@grenudi Glad you got that sorted out :)
