### ISSUE TITLE
Feature request to position cursor after replacement

### ISSUE THREAD

**Issue by cambid** [federico-terzi/espanso#92]
aText on Mac has a great feature to position the cursor in the replacement string after the replacement. 

Here is a screenshot of the configuration: 
[https://www.trankynam.com/atext/screenshots/main_window_variables.png](url)

Can you create this feature in espanso?

**Comment by federico-terzi** [comment]
Hi @cambid,

I wanted to add that feature as well. I'll try to implement an experimental version in the next release, so we can test it further.

Thanks for your help

**Comment by toddatctera** [comment]
In case @cambid or anyone else searching Issues for how to set the cursor position like I did, it's in the docs:
https://espanso.org/docs/matches/#cursor-hints

> Starting from version 0.3.2, espanso supports cursor hints, a way to control the position of the cursor after the expansion.
> 
> Using them is very simple, just insert $|$ where you want the cursor to be positioned, in this case:

**Comment by ibehnam** [comment]
Is it possible to have multiple cursors? Like a differential: `\pa` → `∂$|{1}$/$|{2}$` which generates things like ∂f/∂x?

**Comment by vinn2010** [comment]
Updated link for anyone who searches --> https://espanso.org/docs/matches/basics/#cursor-hints
