### ISSUE TITLE
Default Search Trigger Collides with Vim Navigation

### ISSUE THREAD

**Issue by dbready** [federico-terzi/espanso#925]
First of all, this package is great, and I love it.

Recently tried a newer version and stumbled upon the Search box - neat functionality (although I am probably not going to use it myself). However, the default search_trigger `jkj` is easily hit by programs that use "Vim navigation bindings" (`hjkl` instead of arrow keys). I encountered this inside a Jupyter Notebook and later NeoVim itself.

Any chance the default trigger could be changed? Defaults are hard, but I wanted to make the case before the 2.0 release. Possible I am just a madman that mashes the keys when navigating text, but that particular combo is unusable for people using these kinds of programs and I had to search the issues to find documentation (#828) on how to adjust the configuration.

**Comment by federico-terzi** [comment]
Hey @dbready,

Thank you for the feedback! Being a VIM user myself, I definitely noticed this issue as well...
The original rationale was to use some keys close to the keyboard home row to make it convenient, but `jkj` was likely not a great choice due to the VIM conflicts.
Do you have any suggestions on what could be a good default, if any?

Cheers :)

**Comment by dbready** [comment]
No real suggestions from my end. I lean more towards something that requires a meta-character (eg default search_shortcut is `ALT+SPACE`) for an action that evokes a global pop-up. Anything less deliberate strikes me as prone to surprise.

**Comment by federico-terzi** [comment]
@dbready Good point! In the next version, the `search_trigger` will be disabled by default to avoid confusion. Users will be able to explicitly re-enable it by adding the `search_trigger: "jkj"` option to their `$CONFIG/config/default.yml` file.

Thanks for your help!
