### ISSUE TITLE
Search bar default

### ISSUE THREAD

**Issue by DaWolfi** [federico-terzi/espanso#928]
Hi,
sometimes it would be nice if the part of the trigger you've already entered is set as default value in the search bar, and you don't have to restart typing the whole trigger.
I'm sure not everybody wants/needs this feature, so a parameter in the global config could be useful in this case. (search_bar_default: no = actual behaviour)

**Comment by federico-terzi** [comment]
Hey @DaWolfi,

Thank you for the feedback! Just to make sure I understand correctly, are you suggesting adding a configuration option to "prepopulate" the search bar input?

Cheers :)

**Comment by DaWolfi** [comment]
Yes! Is it possible to copy the trigger buffer to the input field, and place the cursor at the end of the string? Then you could immediately expand or reduce the string from this point.
Cheers!

**Comment by federico-terzi** [comment]
@DaWolfi Thanks! Unfortunately, I still don't understand what you mean exactly, I'm sorry about that! Could you please share a more detailed example of your planned usage?

In particular, I don't really understand what you mean by "the trigger yoùve already entered":

> sometimes it would be nice if the part of the trigger you've already entered is set as default value in the search bar

Cheers :)

**Comment by DaWolfi** [comment]
no probem! let's say you have these matches definied:

matches:
  - triggers:
    - "**:foo**bar"
    - ":notfound1"
    - ":greet3"
    replace: "first example"
  - triggers: [**:foo**obaar, :notfound2]
    replace: "second example"
  - triggers:
      - "**:foo**babafoobar"
      - ":greet2"
      - ":notfound3"
    replace: "third example"  

as you can see we have three trigger strings starting with "**:foo**"
when you start typing **:foo** and open the search bar at this point, it should look like this:

![20220110-201818](https://user-images.githubusercontent.com/26442759/148825951-a11e4236-de96-4bd9-934f-f8a6168dc0fa.png)

**Comment by federico-terzi** [comment]
Hey @DaWolfi,

Thanks for clarifying! I see that you mean, unfortunately that would be rather difficult to accomplish with the current architecture. That said, you might be able to use "match disambiguation" for a similar result:

If you declare multiple matches with the same trigger, Espanso will automatically open the search bar to let you choose between them. For example, if you define these matches: 

```yaml
matches:
  - triggers:
    - ":foo"
    - ":notfound1"
    - ":greet3"
    replace: "first example"
  - triggers: [":foo", ":notfound2"]
    replace: "second example"
```

and then type `:foo`, Espanso will let you choose between them. So as long as there is a common trigger, you will get a similar behavior to what you described :)

You might need to wait for the next version for things to stabilize though, as https://github.com/federico-terzi/espanso/issues/796 will ship in the next release :)

Cheers :)

**Comment by DaWolfi** [comment]
Hi @federico-terzi,
thanks for the investigation and your explanations, your solution will do for now :)
