### ISSUE TITLE
Error when running espanso on Windows 8 due to SetThreadDpiAwarenessContext

### ISSUE THREAD

**Issue by federico-terzi** [federico-terzi/espanso#93]
![image001](https://user-images.githubusercontent.com/20475953/67139267-87217b00-f24e-11e9-9c07-1678ebaf0c78.png)

**Comment by federico-terzi** [comment]
I could probably fix this issue using this method: https://stackoverflow.com/questions/52690147/check-if-winapi-function-is-available

**Comment by federico-terzi** [comment]
Turns out Windows 8 support is more complicated than expected.
This particular error can be solved relatively easy with something like: 
```c++
typedef void (WINAPI *STDAC)(DPI_AWARENESS_CONTEXT);

// Make the notification capable of handling different screen definitions ( available only from Windows 10 )
// Call it only if the operating system supports it.
SYSTEM_INFO si;
ZeroMemory(&si, sizeof(SYSTEM_INFO));
STDAC setThreadDpiAwarenessContextPointer = (STDAC) GetProcAddress(
        GetModuleHandle(TEXT("User32.dll")),
        "SetThreadDpiAwarenessContext");
if(setThreadDpiAwarenessContextPointer != NULL){
    setThreadDpiAwarenessContextPointer(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE);
}
```

But even after solving this exception, espanso is not working at all. It seems like the application is not receiving WM_INPUT messages from the OS.

At the moment, supporting older versions of Windows is difficult for me, so unless someone experienced with WinAPI is willing to help me with this issue, I don't think it will be solved anytime soon.

**Comment by federico-terzi** [comment]
I'm closing the issue, as I don't plan to support Windows 8 in the future

**Comment by earthbound19** [comment]
I get this error when the program runs on Windows 7, but it mentions USER32.dll (not the .exe file name). I'm guessing it would not work on any version of Windows.

Too bad, I love the program. I'm enjoying use of it on a Mac, thank you!

**Comment by federico-terzi** [comment]
Hey @earthbound19,
I'm really sorry about that, but supporting older versions of Windows has been tried many times in the past and it's too difficult for a single developer :)
