### ISSUE TITLE
Can't open the Search Bar with Alt+Space on Windows.

### ISSUE THREAD

**Issue by ahmedfarrag17** [federico-terzi/espanso#935]
I still don't know how to show the Search Bar. I try Alt+Space and nothing happens! I thought it was a problem with my Italian Keyboard Layout. I put it in English and still doesn't work! how to fix that?
I have Espanso Enabled.

**Comment by federico-terzi** [comment]
Hey,

Are you using the v2? :) https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by federico-terzi** [comment]
Hey,
I'm going to close this issue as it's been a while since the last follow up.
Let me know if you have other questions.
Cheers :)
