### ISSUE TITLE
multi-line expansions don't work in chat.google.com

### ISSUE THREAD

**Issue by thomasvs** [federico-terzi/espanso#936]
**Describe the bug**
A clear and concise description of what the bug is

I have colon address set to type my address in three lines with the \n character.
This worked everywhere so far.

Today, in chat.google.com, it only pastes the first line (name)

**To Reproduce**
1. Go to chat.google.com
2. start a chat with someone
3. type colon address

**Expected behavior**

It should type 3 lines of address for me.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: What OS are you using?
- Version: which version of Espanso are you running? (you can find out by running `espanso --version` inside a terminal)

**Comment by federico-terzi** [comment]
Hey @thomasvs,

I'm sorry you experienced this problem! Could you please try the `force_clipboard` option and see if that helps? Such as

```yaml
  - trigger: ":sig"
    force_clipboard: true
    replace: "Best Regards\nFederico"
```

Cheers :)

**Comment by thomasvs** [comment]
Thanks, that works for this case!

Is the suggestion to add this for any multi-line expansion? I assume it's not the default, and that there might be drawbacks to using it?

It seems like this ought to be more of a global setting than a per-expansion setting?

**Comment by federico-terzi** [comment]
@thomasvs Nice! Glad you got it working

> Is the suggestion to add this for any multi-line expansion?

It depends, in general, I would only advise using it if you are experiencing this problem

>  I assume it's not the default, and that there might be drawbacks to using it?

Yes, the drawback is that it uses the clipboard to perform the expansion. Therefore, there might be cases in which the previous clipboard content is lost (for example, when you have images in the clipboard).
For that reason, I usually suggest to use the Clipboard option only when necessary.

> It seems like this ought to be more of a global setting than a per-expansion setting?

You can also enable it globally by adding the following line to your `default.yml` file:

```
backend: Clipboard
```

Cheers :)
