### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by mwaitzman** [federico-terzi/espanso#939]
What's the current (and planned) state of using Espanso on Android?

**Comment by federico-terzi** [comment]
Hey @mwaitzman,

Thanks for your interest! At the moment, the Android version is only a long-term vision, as there are other more important features we'll need to tackle first (GUI, Macros, and a few others). It's unlikely for the Android version to come before 2023

I'll make sure to update the issue when something new happens in this area!

Cheers :)
