### ISSUE TITLE
Ability to have description next to form choice box / list box

### ISSUE THREAD

**Issue by dodalovic** [federico-terzi/espanso#943]
Hi, 
thanks for the life-saving tool, first of all!

I was thinking of creating a target like `:id`:

which would present me with a list of vairous ids I use in my life, but having description next to each item, so that I can easily recognize it:

So, left to `first choice, second choice`:
![image](https://user-images.githubusercontent.com/6358061/149530028-f53725b3-9312-4a3e-8d90-4c9134816a9e.png)

I'd like to have their semantics, so that I can choose the proper one. 

Does this make any sense to you?

Like:

Tax number: `xxxxxxxx`
Insurance number: `yyyyyyyy`
....

**Comment by federico-terzi** [comment]
Hey @dodalovic,

Thank you for the feedback! If you are using the new v2 (see https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339), you can use two features to obtain a similar behavior:

* [Match disambiguation](https://espanso.org/docs/next/matches/basics/#match-disambiguation) combined with [Search Labels](https://espanso.org/docs/next/matches/basics/#search-labels)
* Or the [Choice Extension](https://espanso.org/docs/next/matches/extensions/#choice-extension), using the [explicit ID mode](https://espanso.org/docs/next/matches/extensions/#advanced-use-with-ids).

Hope that helps!

Cheers :)
