### ISSUE TITLE
Ctrl + enter not choosing the choice item (forms)

### ISSUE THREAD

**Issue by dodalovic** [federico-terzi/espanso#947]
espanso 0.7.3

Pop os 21.10

**Comment by federico-terzi** [comment]
Hey @dodalovic,

I'm sorry you experienced this problem! I think this problem might have been solved in the new v2 release, when you have the chance could you please try upgrading and see if that helps? :) See: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)
