### ISSUE TITLE
Add options to disable Status Icon and Notifications

### ISSUE THREAD

**Issue by timorunge** [federico-terzi/espanso#95]
It would be nice if espanso would give - in the configuration file - the possibility to hide the menu item.

**Comment by federico-terzi** [comment]
Hi @timorunge,
That could definitely be a good option. Do you mean the status bar icon?

**Comment by timorunge** [comment]
@federico-terzi: Yes. Meaning to have a complete "silent" application (everyone is filling the status bars, docks, ...).

**Comment by federico-terzi** [comment]
All right! I'll rename the issue to make it clearer

**Comment by JPUnD** [comment]
I would also like to have this be to be a optional feature that you can turn on or off, having a notification by espanso every time i start my machine (linux) is kind of unnecessary

**Comment by federico-terzi** [comment]
Hey guys,

I'm shipping version 0.5.5 which includes this feature. Just add the following lines to your `default.yml` configuration:

```yaml
show_icon: false            # Disable the status icon
show_notifications: false   # Disable the notifications
```

Cheers :)
