### ISSUE TITLE
The new version 2.x is slower than the previous ones

### ISSUE THREAD

**Issue by kud** [federico-terzi/espanso#951]
With the previous versions, it was like immediate. Now with the new version - which is really less buggy by the way, thanks for that - it's not immediate anymore. Is there any reason of that?

https://user-images.githubusercontent.com/655838/150117331-99de5ef8-61a4-4ec5-a5f3-0aaa4eda1490.mp4

OS: macOS 10.15.4 (19E287)

**Comment by federico-terzi** [comment]
Hey @kud,

Thanks for reporting this issue! Are you pressing any modifier (Shift, Ctrl, Alt, etc) while typing the trigger?
Because Espanso v2 now waits until you release them :) See: https://github.com/federico-terzi/espanso/issues/940#issuecomment-1013749630

Cheers :)

**Comment by kud** [comment]
Oh you're perfectly right!

I do this combo: "=" + "⇧ + <" and indeed, it does the job when I release the ⇧ touch.

Thank you! 😊
