### ISSUE TITLE
Question regarding trigger replacements.

### ISSUE THREAD

**Issue by rafamerlin** [federico-terzi/espanso#955]
Hey, I'm moving from AutoHotKey hotstrings to espanso matches as I've moved from windows to mac os.

There are some different behaviours for me that I'm unsure if are just the way it's meant to work of if this is something configurable.

In AHK if I have a trigger like `gs` to replace it with `git status` it will still let me type `gsa` and won't replace anything. Also in situations where I'm writing something like `greetings` it won't do anything.

In espanso, even if I try to increase the `inject_delay` option quite a bit I'm still getting the same result, which is, if I want to type `gsa` I get `ggit status` instead. And if I try to type `greetings` I get `greetinggit status`

Is there a config I can use to have the behavior I'd get with AHK where these wouldn't get replaced at all?

**Comment by federico-terzi** [comment]
Hey @rafamerlin,

I'm sorry you experienced this problem! You probably need [Word triggers](https://espanso.org/docs/matches/#word-triggers).

Also, I'd suggest upgrading to the v2 as the word triggers support has been improved significantly: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by rafamerlin** [comment]
Thanks a lot for the quick response. I'll give it a look :)
