### ISSUE TITLE
Disable "unable to detect layout" warning on Wayland

### ISSUE THREAD

**Issue by Schlaefer** [federico-terzi/espanso#961]
**Is your feature request related to a problem? Please describe.**

Currently espanso emits: *[WARN] unable to determine the currently active layout, you might need to explicitly specify the layout in the config for espanso to work correctly.* into the system log.

This happens every second and makes the log crowded and hard to read.

**Describe the solution you'd like**

Emit the message once on application start/configuration change but suppress it until layout detection is implemented and could actually fail.

**Comment by federico-terzi** [comment]
Hey @Schlaefer,

Thanks for reporting this issue! Indeed, we should limit the number of warnings. I'll investigate

Cheers :)
