### ISSUE TITLE
Multiline replacement in Vim/Neovim

### ISSUE THREAD

**Issue by y-mx-b** [federico-terzi/espanso#962]
**Describe the bug**
Multiline replacement in Vim/Neovim is not working properly. Replacement result becomes garbled, with newlines inserted at unexpected locations.

**To Reproduce**
1. Open Vim/Neovim
2. Attempt multiline replacement

**Expected behavior**
Appropriate multiline text to replace the trigger.

**Screenshots**
Trigger Definition:
![Screen Shot 2022-01-25 at 4 45 07 PM](https://user-images.githubusercontent.com/48655352/150933436-c0a73c19-08d8-4f07-9f64-86e0465eaf2f.png)
Use inside Neovim:
![Screen Shot 2022-01-25 at 4 44 48 PM](https://user-images.githubusercontent.com/48655352/150933454-d34d5afc-2f25-4220-a3c6-857cf6cfcefa.png)

**Setup information**
- OS: macOS Monterey 12.1
- Version: 0.7.3

**Comment by federico-terzi** [comment]
Hey @y-mx-b,

I'm sorry you experienced this problem! Perhaps the `force_clipboard: true` option might help in this case, like:

```yaml
  - trigger: ":sig"
    force_clipboard: true
    replace: |
      Best Regards
      Federico
```

Cheers :)

**Comment by y-mx-b** [comment]
I had no clue that was an option, it worked perfectly! Thank you so much! It even fixes the problem I had with indentation.
