### ISSUE TITLE
Be able to remap the Alt+Space key binding

### ISSUE THREAD

**Issue by Nagidal** [federico-terzi/espanso#963]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I cannot remap Espanso's `Alt+Space` to another keyboard shortcut. 

**Describe the solution you'd like**
Be able to remap Espanso's `Alt+Space` to another keyboard shortcut

**Alternatives**
* Option to disable Espanso's search bar altogether.
* When Espanso is disabled, which can be done with a definable keyboard shortcut, it should unmap the Alt-Space and no longer react to it until it is enabled again.

**Additional context**
`Alt+Space` is a very basic Windows shortcut which accesses the Window menu. I use it regularly to maximize a window: `Alt+Space, x` or to restore windows: `Alt+Space, r`

**Comment by federico-terzi** [comment]
Hey @Nagidal,

I'm sorry you experienced this problem! You can remap the shortcut following these instructions: https://espanso.org/docs/next/configuration/options/#customizing-the-search-shortcut

Cheers :)
