### ISSUE TITLE
Old Rust chronotope link in documentation (v0.3.1 -> latest)

### ISSUE THREAD

**Issue by dharrison27** [federico-terzi/espanso#967]
**Describe the bug**
Not really a bug, more of a documentation update thing.

**To Reproduce**
n/a

**Expected behavior**
[up to date chronotope link](https://docs.rs/chrono/latest/chrono/format/strftime/index.html) needed within documentation [[documentation>Matches>Date Extension](https://espanso.org/docs/matches/#date-extension)], unless espanso purposefully [only utilizes v0.3.1](https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html)

**Screenshots**
n/a

**Logs**
n/a

**Setup information**
n/a

**Misc**
For clarity, full links used above, pasted:

> old
> https://docs.rs/chrono/0.3.1/chrono/format/strftime/index.html
> 
> latest
> https://docs.rs/chrono/latest/chrono/format/strftime/index.html
> 
> Location of old link
> https://espanso.org/docs/matches/#date-extension

**Comment by federico-terzi** [comment]
@dharrison27 Good point, thanks!

**Comment by federico-terzi** [comment]
The new docs bundle the formatting options directly, so we can close this issue, thanks! :)
