### ISSUE TITLE
Search window (ALT + Space) starts without a cursor inside the window

### ISSUE THREAD

**Issue by patrykpalej** [federico-terzi/espanso#969]
**Describe the bug**
It's a minor one but still annoys a little bit and I think it could be fixed. When hitting ALT + Space (Linux here) the window is not ready to type, but I need to click it with my mouse first. Maybe I'm just doing something wrong, but cannot find any way to do it properly

**To Reproduce**
1. Click ALT + Space
2. Start typing - you cannot because the cursor is not inside the newly opened window
3. Click on the window
4. Only now you can type

**Expected behavior**
A pop-up window should be ready to type (I think so).

**Setup information**
- Ubuntu 20.04
- espanso 2.1.3-alpha

**Comment by federico-terzi** [comment]
Hey @patrykpalej,

I'm sorry you experienced this problem! This is a known issue, see #829 , we are working to solve it :)

Cheers :)
