### ISSUE TITLE
Access denied error while installing using a custom path (Windows)

### ISSUE THREAD

**Issue by arabello** [federico-terzi/espanso#97]
Hi,
I'm getting an error that aborts the installing process on Windows when using a _custom_ path. Instead, with the _default_ path, it completes successfully. 

![Capture](https://user-images.githubusercontent.com/16003164/67329001-89b7f500-f51a-11e9-937d-50f7ae6fa3cf.PNG)

It seems that the installer should ask for write permission.

**Comment by federico-terzi** [comment]
Hi @arabello,

Thank you very much for your feedback, I'll take a look in the next few days and I'll get back to you.

Thanks for your help

**Comment by federico-terzi** [comment]
Unfortunately, I couldn't find a reasonable solution to this problem. Most of the alternatives either lacked correct support or gave the same results. For this reason, I'm closing the issue as wontfix.

Thanks for your help
