### ISSUE TITLE
Drop-down menu in forms

### ISSUE THREAD

**Issue by couleurm** [federico-terzi/espanso#971]
**Is your feature request related to a problem? Please describe.**
To choose my encoding settings/video filters with ffmpeg

**Describe the solution you'd like**
Whatever you select ends up being typed

**Describe alternatives you've considered**
Making espanso triggers for each encoding setting

**Additional context**
Also make it so whatever key you press with select the option which has it as it's first letter, it's terribly phrased if you don't get my point just right click any file and press some keys
![image](https://user-images.githubusercontent.com/82747632/151884408-3a9faa1b-7b4b-46c0-841f-ad164589fe62.png)

**Comment by federico-terzi** [comment]
Hey @couleurm,

Thank you for the feedback! Have you already considered:
* The [search bar](https://espanso.org/docs/next/get-started/#search-bar)
* Or the [choice extension](https://espanso.org/docs/next/matches/extensions/#choice-extension)
* Or the [Form's choice box](https://espanso.org/docs/next/matches/forms/#choice-box)

In case those don't solve your problem, feel free to reopen the issue!

Cheers :)
