### ISSUE TITLE
Tab never selects the submit button

### ISSUE THREAD

**Issue by chadhs** [federico-terzi/espanso#977]
**Describe the bug**
On macOS Monterey I can tab between form input fields, but tab never selects the submit button.

**To Reproduce**
1. create any form
2. activate the shortcut
3. keep pressing tab

**Expected behavior**
Pressing tab should highlight the "submit" button after cycling through all other selectable fields.

**Screenshots**
[screen recording](https://user-images.githubusercontent.com/1085679/152548999-80cfb11a-2212-46cd-8eb9-73052b1e15bd.mov)

**Logs**
No error logs.

**Setup information**
- OS: macOS Monterey 12.1 (21C52)
- Version: espanso 0.7.3

**Comment by chadhs** [comment]
I did see you can use ^↩, but this seems like a regression.  If I am wrong, I can close this or maybe change to a feature request.

**Comment by chadhs** [comment]
I did try this on macOS 11 BigSur with Espanso 0.7.3 and tab cycles just fine to the the submit key.

**Comment by federico-terzi** [comment]
Hey @chadhs,

I'm sorry you experienced this problem! Have you tried with this process? https://espanso.org/docs/forms/#macos-remarks

Cheers :)

**Comment by chadhs** [comment]
@federico-terzi you are correct!  how on earth did I miss that setup step on my new Mac.  my apologies for not catching this.

**Comment by reagle** [comment]
The link to the espanso docs is now 404, and even the current docs have instructions that no longer apply. Is this what we need to enable to navigate forms by keyboard? https://support.apple.com/guide/mac-help/navigate-your-mac-using-full-keyboard-access-mchlc06d1059/13.0/mac/13.0
