### ISSUE TITLE
Status icon is not HiDPI-ready

### ISSUE THREAD

**Issue by kkga** [federico-terzi/espanso#98]
The icon is blurry on a hi-dpi screen.

<img src="https://user-images.githubusercontent.com/1460122/67393282-bf0c2380-f5aa-11e9-8a39-5ae9b3a85e5b.png">

**Comment by federico-terzi** [comment]
Hi @kkga,

Thanks for your feedback, I'll take a look. I don't have access to a Mac with a retina screen, so it could take a few trial and error.

Thanks for your help

**Comment by timorunge** [comment]
@federico-terzi 1a3e2c7 will not fix this. It looks like the following:

<img width="541" alt="Screenshot 2019-10-24 at 16 58 09" src="https://user-images.githubusercontent.com/1560363/67498386-a3268180-f67f-11e9-904e-e4c2988f3e43.png">

I've been playing around with a solution and came up with the following:

Before:
<img width="541" alt="Screenshot 2019-10-24 at 16 32 31" src="https://user-images.githubusercontent.com/1560363/67497130-d10ac680-f67d-11e9-9e80-cb8a57f800cd.png">

After:
<img width="541" alt="Screenshot 2019-10-24 at 16 32 45" src="https://user-images.githubusercontent.com/1560363/67497152-de27b580-f67d-11e9-89fe-cbc7c1791066.png">

My problem is that the boarders are not "perfect". 

To create an high res item for MacOS:

- Create an Image with the dimensions of 88x88px and a resolution of 350 pixels per inch
- Position the "e":
   - 8px from the top
   - 6px from the bottom
   - 12px from the left
   - 16px from the right

**Comment by federico-terzi** [comment]
Hi @timorunge,

Thank you very much for your help, I definitely need it! Could you provide me the image you used in the third example?
I don't have a retina display so I cannot test this effectively.

Thanks

**Comment by timorunge** [comment]
@federico-terzi: Sure, I can share the same. But like I said: The boarders are not as good as they should be (I took [this file](https://github.com/federico-terzi/espanso/blob/master/other/EspansoNotifyHelper/EspansoNotifyHelper/Assets.xcassets/AppIcon.appiconset/icongreen-256.png) as a source). 

I'm happy to create a final PNG for you if you have some PDF or SVG image to work with.

Image: 
![icon](https://user-images.githubusercontent.com/1560363/67510372-1c7c9f00-f695-11e9-8b26-00cf90ceb264.png)

**Comment by federico-terzi** [comment]
> I'm happy to create a final PNG for you if you have some PDF or SVG image to work with.

@timorunge that would be a great help! Here's the SVG file: https://drive.google.com/file/d/1T_TdF2rZYAeLsRoJJ4_ZyRaKR-uuq6JV/view?usp=drivesdk

Let me know if you need something else to create the icon. Thanks

**Comment by timorunge** [comment]
@federico-terzi: See #100.

**Comment by timorunge** [comment]
@federico-terzi the status bar icon which should be in `v0.3.2` is not automatically applied by an update. `icon.png` in `~/Library/Application Support/espanso` is still the low res one.

**Comment by federico-terzi** [comment]
Hi @timorunge, you are totally right. I forgot to mention that existing espanso users on macOS should delete the  `~/Library/Application Support/espanso/icon.png` file and then restart espanso.

Thanks for your help
