### ISSUE TITLE
Error for Multiple Triggers

### ISSUE THREAD

**Issue by ReaderGuy42** [federico-terzi/espanso#980]
**Describe the bug**
I'm trying to setup multiple triggers so that if I accidentally hit `#` instead of `'` it corrects it. But if I simply have the trigger `#s` I can't write hashtags that start with s because it'll correct it to an apostrophe then. So I tried this:

`  - trigger: ["a#s", "b#s", "c#s", "d#s", "e#s", "f#s", "g#s", "h#s", "i#s", "j#s", "k#s", "l#s", "m#s", "n#s", "o#s", "p#s", "q#s", "r#s", "s#s", "t#s", "u#s", "v#s", "w#s", "x#s", "y#s", "z#s"]
    replace: "'s"
`
But now upon saving I get the error:
``` 
Error parsing YAML file '/home/ReaderGuy42/.config/espanso/default.yml', invalid syntax: matches[10].trigger: invalid type: sequence, expected a string at line 53 column 14
```

**To Reproduce**
1. Attempt multiple triggers
2. save
3. see error

**Logs**
Can't run log because of the error (see above)

**Setup information**
- OS: Linux Mint
- Version: 0.7.3

Thanks :)

**Comment by ReaderGuy42** [comment]
I just saw the thing about the extra "s" at the end of triggers instead of trigger. Sorry!

**Comment by ReaderGuy42** [comment]
Now I noticed that this will cut off the letter before the # (D'uh? that was stupid). Any ideas on how I could solve this without having 26 triggers, one per letter?

**Comment by federico-terzi** [comment]
Hey @ReaderGuy42,

Thank you for the feedback! Unfortunately, there is currently no way to do that without defining 26 triggers. If you upgrade to v2 (see [1]), you'll get pretty close with [Regex triggers](https://espanso.org/docs/next/matches/regex-triggers/#basics), but you would still lose the letter before `#`.
Once #556 is implemented, you should be able to solve the problem elegantly, but it's not ready yet :)

[1]: https://github.com/federico-terzi/espanso/issues/594#issuecomment-939329339

Cheers :)

**Comment by ReaderGuy42** [comment]
I figured it out! I added a space after the s so "#s " because the apostrophe s where I accidentally type a # instead ends after the s. For hashtags I continue typing after the s instead, so that solves this problem :) Thanks!
