### ISSUE TITLE
Impossible to add a "$" in a form

### ISSUE THREAD

**Issue by Elaws** [federico-terzi/espanso#985]
Hello,

I get weird behavior when trying to add `$` inside a form :

```
matches:
  - trigger: "\\shortcut"
     form: $\name\{{{value}}\}$
```

It works perfectly fine without the `$`. Any idea how to fix this ?

Thanks !

**Comment by Elaws** [comment]
@federico-terzi : Thanks a lot for your quick reply ! I've upgraded to latest alpha, the search bar (and especially with "label" feature) is awesome !

Also, my bad because you made me realize I just had a conflict between the `$` I was trying to add through Espanso, and my app that had `$` autoclose !

So I've not tested again on 0.7.3 (would need to uninstall v2), but maybe it was working perfectly fine there.

**Comment by federico-terzi** [comment]
@Elaws Awsome, glad you got it working :)
