### ISSUE TITLE
How to auto add a space after trigger? 

### ISSUE THREAD

**Issue by woshichuanqilz** [federico-terzi/espanso#987]
I want the expanded word auto add a space after triggered. 

I try the option word and set it like this: 

```
  - trigger: ";ck"
    replace: check
    word: true
```

But it need press space to trigger the replace. 

I want the original trigger mode (with out space pressed) but auto add a space, how to make it

**Comment by ReaderGuy42** [comment]
So, if I'm understanding that correctly, you'd like the result to be "check " with a space after the word?
If so, you can put quotation marks around the word and then put in a space before the second one, so it'd look like this:

  - trigger: ";ck"
    replace: "check "
    word: true
Does that help?

**Comment by federico-terzi** [comment]
Hey @woshichuanqilz,

As @ReaderGuy42 said, you should probably drop the `word` option and add the trailing space on the replace:

```yaml
  - trigger: ";ck"
    replace: "check "
```

Cheers :)
