### ISSUE TITLE
[Wayland] New triggers don't work

### ISSUE THREAD

**Issue by Vistaus** [federico-terzi/espanso#989]
**Describe the bug**
I used to be able to add new triggers to the config file and have them work, but since a few weeks, Espanso only reads triggers that have been in there for a long time. I assume this is some sort of bug in the Wayland version of Espanso, as the triggers that do still work are from the X11 version that I used to use.

**Setup information**
- OS: Void Linux
- DE: KDE Plasma 5.24
- Version: 2.1.4-beta from latest git (dev branch)

**Comment by federico-terzi** [comment]
Hey @Vistaus,

I'm sorry you experienced this problem! 

> Espanso only reads triggers that have been in there for a long time

This is very strange, I'd say there could be two possible causes:
* There are syntax errors in some of the new config files (strange, because you should be seeing a troubleshooting window show up in that case)
* The "new" configurations are excluded for some reasons (perhaps, an app-specific configuration?)

Could you please try typing `#acfg#` and posting the output here? That should tell us which configurations are currently loaded :)
Also, if you can post the logs that would be a great help!

Cheers :)

**Comment by Vistaus** [comment]
Hey, Federico! Thanks for responding! 🙂

Of course I did check for syntax errors, but there aren't any.

#acfg# doesn't output anything. The configuration is definetely loaded, though.

**Comment by federico-terzi** [comment]
@Vistaus Thanks!

> #acfg# doesn't output anything.

That's interesting... You should see a window appear with some debugging info. Could you please post the output of `espanso log` here?

Also, could try typing `#pacfg#` inside a text application and posting the output here? that should paste some debugging info

Cheers :)

**Comment by Vistaus** [comment]
Here's the output of espanso log:

```
~ espanso log
13:41:15 [daemon(6312)] [INFO] reading configs from: "/home/thefish/.config/espanso"
13:41:15 [daemon(6312)] [INFO] reading packages from: "/home/thefish/.config/espanso/match/packages"
13:41:15 [daemon(6312)] [INFO] using runtime dir: "/home/thefish/.local/share/espanso"
13:41:15 [daemon(6312)] [WARN] keyboard layout watcher couldn't determine active layout.
13:41:15 [daemon(6312)] [INFO] watching for changes in path: "/home/thefish/.config/espanso"
13:41:15 [daemon(6312)] [INFO] espanso version: 2.1.4-beta
13:41:15 [daemon(6312)] [INFO] spawning the worker process...
13:41:15 [daemon(6312)] [INFO] binded to IPC unix socket: /home/thefish/.local/share/espanso/espansodaemonv2.sock
13:41:15 [worker(6318)] [INFO] reading configs from: "/home/thefish/.config/espanso"
13:41:15 [worker(6318)] [INFO] reading packages from: "/home/thefish/.config/espanso/match/packages"
13:41:15 [worker(6318)] [INFO] using runtime dir: "/home/thefish/.local/share/espanso"
13:41:15 [worker(6318)] [INFO] binded to IPC unix socket: /home/thefish/.local/share/espanso/espansoworkerv2.sock
13:41:15 [worker(6318)] [INFO] using WaylandAppInfoProvider
13:41:15 [worker(6318)] [INFO] monitoring the status of the daemon process
13:41:15 [worker(6318)] [INFO] detection module will use this keyboard layout: [R=evdev, M=pc86, L=us, V=dvorak-intl, O=terminate:ctrl_alt_bksp]
13:41:15 [worker(6318)] [INFO] using EVDEVSource
13:41:15 [worker(6318)] [INFO] Querying modifier status...
13:41:15 [worker(6318)] [INFO] inject module will use this keyboard layout: [R=evdev, M=pc86, L=us, V=dvorak-intl, O=terminate:ctrl_alt_bksp]
13:41:15 [worker(6318)] [INFO] using EVDEVInjector
13:41:15 [worker(6318)] [INFO] using WaylandFallbackClipboard
~ 
```

Also, acfg did work now. I don't know why it failed last time, but it worked now!

```
[espanso config: "/home/thefish/.config/espanso/config/default.yml"]

backend: Clipboard
enable: true
paste_shortcut: Some("SHIFT+INSERT")
inject_delay: None
key_delay: None
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: None
auto_restart: true
restore_clipboard_delay: 300 
backspace_limit: 5
search_trigger: None
search_shortcut: Some("ALT+SPACE")
keyboard_layout: Some(RMLVOConfig { rules: Some("evdev"), model: Some("pc86"), layout: Some("us"), variant: Some("dvorak-intl"), options: Some("terminate:ctrl_alt_bksp") })

show_icon: true
show_notifications: true
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "/home/thefish/.config/espanso/match/packages/arrows/package.yml",
    "/home/thefish/.config/espanso/match/espanso-package-foreign-thanks/foreign-thanks/1.0.0/package.yml",
    "/home/thefish/.config/espanso/match/packages/basic-emojis/package.yml",
    "/home/thefish/.config/espanso/match/packages/all-emojis/package.yml",
    "/home/thefish/.config/espanso/match/packages/ip/package.yml",
    "/home/thefish/.config/espanso/match/espanso-package-date-utilities/date-utilities/1.0.0/package.yml",
    "/home/thefish/.config/espanso/match/base.yml",
]
```

**Comment by federico-terzi** [comment]
@Vistaus Thanks! Are these the match files you expected or did Espanso miss some of them?

```
match_paths: [
    "/home/thefish/.config/espanso/match/packages/arrows/package.yml",
    "/home/thefish/.config/espanso/match/espanso-package-foreign-thanks/foreign-thanks/1.0.0/package.yml",
    "/home/thefish/.config/espanso/match/packages/basic-emojis/package.yml",
    "/home/thefish/.config/espanso/match/packages/all-emojis/package.yml",
    "/home/thefish/.config/espanso/match/packages/ip/package.yml",
    "/home/thefish/.config/espanso/match/espanso-package-date-utilities/date-utilities/1.0.0/package.yml",
    "/home/thefish/.config/espanso/match/base.yml",
]
```

I'm also curious, perhaps Espanso is not detecting triggers containing some specific special characters?

**Comment by Vistaus** [comment]
Those are the correct match files.

But I found the root of the problem now. Foolish me hadn't been paying enough attention. I was still editing the old config file rather than the new one in /home/thefish/.config/espanso/match/base.yml
I added new triggers to the correct file and now they are working again! 🙂

I'm very sorry for this mistake. Thank you so much for helping me, though! 🙂

**Comment by federico-terzi** [comment]
@Vistaus No worries! Glad we figured this out :)
