### ISSUE TITLE
App Specific configs don't work with I3WM on arch

### ISSUE THREAD

**Issue by KamilKleina** [federico-terzi/espanso#990]
**Describe the bug**
App specific configs don't work with i3wm on arch. Espanso doesn't detect properly that active window is the one specified in config.

**To Reproduce**
1. Create a folder config inside $CONFIG > name a file for example "firefox.yml"
inside file provide below two lines:
`filter_class: "firefox"   
enable: false`

tried the same for visual studio, also tried using titile over class.

**Expected behavior**
Espanso should stop working in specified program

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**Logs**
If possible, run `espanso log` in a terminal after the bug has occurred, then post the output here so that we can better diagnose the problem

**Setup information**
- OS: Arch Linux with 5.16.10-zen-1-1-zen 
- Version: 2.1.3.-alpha

**Comment by federico-terzi** [comment]
Hey @KamilKleina,

I'm sorry you experienced this problem! Could you please type the following while using Firefox and copy the output here?

```
#detect#
```

Cheers :)

**Comment by KamilKleina** [comment]
Hey man,
that's how I got my info what to put in my “class” section, and also I tried to use xprop too, and they got both generate same results:
Here is a log from `#detect#`
`title: 'App Specific configs don't work with I3WM on arch · Issue #990 · federico-terzi/espanso — Mozilla Firefox'
exec: ''
class: 'firefox'`

**Comment by federico-terzi** [comment]
@KamilKleina Thanks!

Just to make sure the steps are correct, did you create `firefox.yml` file inside `$CONFIG/config/firefox.yml` with the following content? (please double check the path and extension)

```yaml
filter_class: "firefox"
enable: false
```

Cheers :)

**Comment by KamilKleina** [comment]
`cat ~/.config/espanso/config/firefox.yml `
`filter_class: "firefox"
enable: false`

**Comment by federico-terzi** [comment]
@KamilKleina Thanks! That's very interesting, things should be working with that configuration...

Could you please type `#acfg#` inside Firefox and post the output here? That will give us a lot of debugging information we can use to figure this out :)

**Comment by KamilKleina** [comment]
`[espanso config: "default"]

backend: Auto
enable: true
paste_shortcut: None
inject_delay: None
key_delay: None
apply_patch: true
word_separators: [" ", ",", ".", "?", "!", "\r", "\n", "\u{16}"]

preserve_clipboard: true
clipboard_threshold: 100
disable_x11_fast_inject: false
pre_paste_delay: 100
paste_shortcut_event_delay: 10
toggle_key: Some(RightCtrl)
auto_restart: true
restore_clipboard_delay: 300 
backspace_limit: 3
search_trigger: Some("jkj")
search_shortcut: Some("ALT+SHIFT+SPACE")
keyboard_layout: None

show_icon: true
show_notifications: false
secure_input_notification: true

x11_use_xclip_backend: false
win32_exclude_orphan_events: true
win32_keyboard_layout_cache_interval: 2000

match_paths: [
    "default",
]
`

While we are at this can you tell me also how I can disable that JKJ shortcut? it's really annoying while using VIM
I got inside my default.yml:
```search_shortcut: ALT+SHIFT+SPACE```

**Comment by federico-terzi** [comment]
Hey @KamilKleina,

That's interesting, the match_paths seems off. Could you please post the output of `espanso log` here?

> While we are at this can you tell me also how I can disable that JKJ shortcut? it's really annoying while using VIM

You should either add `search_trigger: off` or upgrade to the latest version (that shortcut has been now disabled by default because it caused much confusion :)

**Comment by KamilKleina** [comment]
espanso log
10:37:39 [daemon(3302)] [INFO] reading configs from: "/home/kamil/.config/espanso"
10:37:39 [daemon(3302)] [INFO] reading packages from: "/home/kamil/.config/espanso/match/packages"
10:37:39 [daemon(3302)] [INFO] using runtime dir: "/home/kamil/.cache/espanso"
10:37:39 [daemon(3302)] [INFO] watching for changes in path: "/home/kamil/.config/espanso"
10:37:39 [daemon(3302)] [INFO] espanso version: 2.1.3-alpha
10:37:39 [daemon(3302)] [INFO] spawning the worker process...
10:37:39 [daemon(3302)] [INFO] binded to IPC unix socket: /home/kamil/.cache/espanso/espansodaemonv2.sock
10:37:39 [worker(3310)] [INFO] reading configs from: "/home/kamil/.config/espanso"
10:37:39 [worker(3310)] [INFO] reading packages from: "/home/kamil/.config/espanso/match/packages"
10:37:39 [worker(3310)] [INFO] using runtime dir: "/home/kamil/.cache/espanso"
10:37:39 [worker(3310)] [WARN] espanso is reading the configuration using compatibility mode, thus some features might not be available
10:37:39 [worker(3310)] [WARN] you can migrate to the new configuration format by running 'espanso migrate' in a terminal
10:37:39 [worker(3310)] [INFO] using X11AppInfoProvider
10:37:39 [worker(3310)] [INFO] binded to IPC unix socket: /home/kamil/.cache/espanso/espansoworkerv2.sock
10:37:39 [worker(3310)] [INFO] using X11Source
10:37:39 [worker(3310)] [INFO] monitoring the status of the daemon process
10:37:39 [worker(3310)] [INFO] using X11Injector
10:37:39 [worker(3310)] [INFO] using X11Clipboard

logs, and thank you for the help with shortcut
