### ISSUE TITLE
[wayland] Espanso does not replace text. Detect outputs an error.

### ISSUE THREAD

**Issue by gabe9** [federico-terzi/espanso#997]
First time user, installed espanso according to instructions. Did it twice, as first troubleshooting step.

All messages are OK but no replacement occurs.

Steps:

espanso start
Daemon started correctly!

espanso log
19:52:18 [ INFO] espanso version 0.7.3
19:52:18 [ INFO] using config path: /home/gabe/.config/espanso
19:52:18 [ INFO] using package path: /home/gabe/.local/share/espanso/packages
19:52:18 [ INFO] spawning worker process...
19:52:18 [ INFO] Binded to IPC unix socket: /home/gabe/.local/share/espanso/espanso.sock
19:52:18 [ INFO] initializing worker process...
19:52:18 [ INFO] Binded to IPC unix socket: /home/gabe/.local/share/espanso/worker.sock
19:52:18 [ INFO] Using modulo at "/usr/bin/modulo"
19:52:18 [ INFO] worker is running!
19:52:19 [ INFO] watching for changes in path: /home/gabe/.config/espanso

Typing :espanso on a text editor does nothing.

Trying to see if I could solve the issue, tried.
 
espanso detect
Listening for changes, now focus the window you want to analyze.
You can terminate with CTRL+C

XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
... repeats until terminated

While espanso detect is running, I select gedit and type the tigers.
:espanso    :date    Nothing happens

espanso detect does not changes the error message.

Not sure what else to do. Any sugestions?

OS: Manjaro Linux
Linux machinea 5.15.21-1-MANJARO
wayland 1.20.0-1
gnome 41.3
espanso 0.7.3

**Comment by rickykresslein** [comment]
espanso 0.7.3 doesn't work with Wayland. You need to build the alpha version. You can find the instructions here: [](https://espanso.org/docs/next/install/linux/#install-on-wayland)

**Comment by federico-terzi** [comment]
Hey @gabe9,

I'm sorry you experienced this problem! As @rickykresslein pointed out (thanks!), you'll need to upgrade to the v2 for Wayland to work

Cheers :)
